- .pylintrc
- .vscode/settings.json
- README.md
First iteration agreed for folder structure.
@odeimaiz please take over and add js linters and web-client structure. thx!
> First iteration on folder structure

- Makefile
- services/director/producer.py
- services/web-client/source/class/qxapp/components/workbench/SettingsView.js
- services/web-client/source/class/qxapp/components/workbench/Workbench.js
- services/web-server/async_sio.py
Looks like there is a problem in the backend.
Modeler and Jupyter services are not started
> web-client and web-server ready for starting jupyter

- package.json
- services/director/producer.py
- services/director/registry_proxy.py
- services/web-client/source/class/qxapp/components/workbench/SettingsView.js
- services/web-client/source/class/qxapp/components/workbench/Workbench.js
- only create an internal network if an interactive service is made of more than 1 docker container
- fixed some project dependencies
- automatically set the right url in the client side when opening the viewer (osparc01 was hard-coded till now)
> small fixes

- .vscode-template/settings.json
... we should instruct the .vcode editor todo that too.
> since we are using 2 space indentation

- services/web/client/source/class/qxapp/desktop/PrjEditor.js
simpler is better (and smoother)
> animation fix 3

- services/web/client/package.json
- services/web/client/scripts/install-contrib.sh
* links for font contribs are not necessary anymore
> * qxcompiler 0.2.13 is out

- packages/simcore-sdk/src/simcore_sdk/nodeports/_item.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/filemanager.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/serialization.py
- packages/simcore-sdk/tests/nodeports/test_item.py
- services/dy-2Dgraph/use-cases/cc/cc-oned/cc_config-oned.json
- services/dy-2Dgraph/use-cases/cc/cc-single-cell/cc_single_cell.json
- services/dy-2Dgraph/use-cases/cc/cc-twod/cc_config-twod.json
- able to create data item from item keys even if there is no timestamp
- able to create data item even if there much more keys than needed
- able to create data item even if there are nested objects (sic)
- adapted test configurations to reflect this
> Fix connecting

- .gitignore
- Makefile
- services/docker-compose.swarm.yml.template
- services/web/server/src/server.py
fixes issue with docker-compose overrides and a problem with multiple subscriptions to pub/sub
> Swarm hotfix

- Makefile
- services/docker-compose.swarm.yml.template
- services/sidecar/Dockerfile
- services/sidecar/requirements.txt
- services/sidecar/src/sidecar/sidecar.py
- services/web/server/requirements/common.txt
- services/web/server/src/comp_backend_subscribe.py
Should clean connection automatically and make the server more stable
> Amqp hotfix

- services/web/client/source/class/qxapp/components/login/Form.js
- services/web/client/source/class/qxapp/dev/fake/Data.js
Fixes issues @mguidon in last PR#106
> Fixes typos in client after bad merge

- Makefile
- packages/s3wrapper/src/s3wrapper/s3_client.py
- packages/s3wrapper/tests/test_minio.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/_item.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/_itemslist.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/config.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/dbmanager.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/filemanager.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/nodeports.py
- packages/simcore-sdk/src/simcore_sdk/nodeports/serialization.py
- packages/simcore-sdk/tests/conftest.py
- packages/simcore-sdk/tests/nodeports/test_item.py
- services/director/source/producer.py
- services/director/source/registry_proxy.py
- services/docker-compose.deploy.devel.yml
- services/dy-2Dgraph/use-cases/cc/develdbs3init.py
- services/dy-2Dgraph/use-cases/kember/develdbs3init.py
- services/dy-modeling/Makefile
- services/dy-modeling/client/Dockerfile
- services/dy-modeling/docker-compose.devel.yml
- services/dy-modeling/docker-compose.yml
- services/dy-modeling/server/Dockerfile
- services/sidecar/src/sidecar/sidecar.py
- services/sidecar/src/sidecar/sidecar_utils.py
---
name: Modeler available again
about: The modeler services do not display the needed docker labels to be available in OSparc. It is needed for demos.
---
**@pcrespov @odeimaiz **
> Modeler available again

- services/dy-3dvis/simcoreparaviewweb/Dockerfile
- services/dy-3dvis/simcoreparaviewweb/config/apache.conf
fixes visualizer version to 3.1.6 instead of 3.1.9 which broke function signature in paraview
connects #27 
> fixes for 3d rebranding

- services/dy-3dvis/simcoreparaviewweb/src/input-retriever.py
> added unziping procedure if file is a zip file

- services/dy-modeling/client/compile.json
- services/dy-modeling/client/source/class/qxapp/Application.js
- services/dy-modeling/client/source/class/qxapp/component/ThreeView.js
- services/dy-modeling/client/source/class/qxapp/modeler/BoxCreator.js
- services/dy-modeling/client/source/class/qxapp/modeler/CylinderCreator.js
- services/dy-modeling/client/source/class/qxapp/modeler/DodecahedronCreator.js
- services/dy-modeling/client/source/class/qxapp/modeler/SphereCreator.js
- services/dy-modeling/client/source/class/qxapp/modeler/SphereCreatorS4L.js
- services/dy-modeling/client/source/class/qxapp/modeler/SplineCreator.js
- services/dy-modeling/client/source/class/qxapp/modeler/SplineCreatorS4L.js
connects #288
Feature:
* Create cylinder fixed. It's not optimal, but does the trick for the demo
Bonus:
* isModeler (show modeling tools) and isDebug (show file menu) are set in compiler.json
> Fix cylinder in modeler

- api/specs/shared/schemas/node-output-list-icon-api-v0.0.1.yaml
added node-output-list-icon-api-v0.0.1.yaml that is used by Neuroman
> node-output-list-icon-api-v0.0.1.yaml added

- services/web/client/source/class/qxapp/wrappers/WebSocket.js
make the websocket connection work on osparc.io
> make websocket connection 'portable'

- services/web/client/source/class/qxapp/data/model/NodeModel.js
- services/web/client/source/class/qxapp/desktop/PrjEditor.js
- use version 2.7.0
connects #308 
> neuroman uses latest modeler version

- services/docker-compose.yml
> Fix missing env variable

- services/dy-jupyter/Dockerfile
- services/dy-jupyter/Makefile
- services/dy-jupyter/docker-compose.yml
- services/web/server/src/simcore_service_webserver/reverse_proxy/handlers/jupyter.py
> Add r notebook

- services/web/client/source/class/qxapp/Application.js
With this users will be presented a dialog prior to navigating away from the page.
For security reasons, it is not possible to style or influence this dialog in any way.
connects to #288 
> prevent page unload

- Makefile
- services/dy-2Dgraph/use-cases/Makefile
- services/web/client/source/class/qxapp/data/model/NodeModel.js
- services/web/client/source/class/qxapp/desktop/PrjEditor.js
- services/web/server/src/simcore_service_webserver/data/fake-template-projects.json
> Make osparc great again

- services/web/client/.dockerignore
- services/web/client/Dockerfile
> bug: missing contrib.json for release build process

- services/storage/Dockerfile
- services/web/server/src/simcore_service_webserver/computation_api.py
- services/web/server/src/simcore_service_webserver/director/config.py
fixes #528, fixes #529 (well maybe)
> Fix webserver not getting services + maybe storage not working

- services/dy-modeling/client/contrib.json
- services/web/client/contrib.json
improve the alignment of labels and form fields
connects to #228 
> update to latest theme release

- .travis.yml
fix the deployment of the generated API documentation
> another try with deployment

- ops/travis/helpers/test_for_changes
- ops/travis/unit-testing/frontend
- services/web/server/src/simcore_service_webserver/statics.py
- Extends PR #609
- Fixes pylint false positive detected in [build](https://travis-ci.org/ITISFoundation/osparc-simcore/jobs/499885597#L1926). See details next to code.
> Fixes pylint false positive

- api/specs/shared/schemas/node-meta-v0.0.1.json
fixes jsonschema for fileToKeyMap entry for the case where a key contains capital letters.
fixes #642
> use same schema for filekeymap as for original key 

- services/dy-raw-graphs/Dockerfile
- services/dy-raw-graphs/Makefile
- services/dy-raw-graphs/docker-compose.devel.yml
- services/dy-raw-graphs/docker-compose.yml
> Table View service

- services/dy-raw-graphs/Dockerfile
Force bower installation not to make any questions (d3-legend asks for versions). [Related commits](https://github.com/ITISFoundation/raw/commits/master-osparc)
> Make bower installation silent

- services/director/Dockerfile
- services/director/src/simcore_service_director/config.py
- services/docker-compose.devel.yml
fixes #660 by mounting services/api in devel mode and defining the location of the node schema.
director will be refactored soon to cope with cookiecutter-simcore-pyservice.
> fixed director in devel mode

- services/web/client/source/class/qxapp/component/workbench/servicesCatalogue/ServicesCatalogue.js
- services/web/client/source/class/qxapp/desktop/ControlsBar.js
Pops up a window displaying the Service Info from Services Catalogue
closes #680
> Provide Service Info from Services Catalogue

- services/web/client/source/class/qxapp/component/widget/NodePorts.js
- services/web/client/source/class/qxapp/desktop/PanelView.js
- services/web/client/source/class/qxapp/theme/Appearance.js
- services/web/client/source/class/qxapp/theme/Color.js
- services/web/client/source/class/qxapp/theme/Decoration.js
* Removes borders from PanelView content containers. This is used in both sidebars, right (tree, awesome and logger view) and left (node inputs/ports).
* Changes background for input/ports on left sidebar.
connects to #668 
> Removed borders from PanelView content.

- services/web/client/source/class/qxapp/component/widget/NodesTree.js
- services/web/client/source/class/qxapp/component/workbench/WorkbenchUI.js
- services/web/client/source/class/qxapp/data/Store.js
- services/web/client/source/class/qxapp/data/model/Node.js
- services/web/client/source/class/qxapp/data/model/Workbench.js
- services/web/client/source/class/qxapp/desktop/LayoutManager.js
- services/web/client/source/class/qxapp/desktop/NavigationBar.js
- services/web/client/source/class/qxapp/desktop/PrjEditor.js
- services/web/client/source/class/qxapp/test/data/model/Workbench.js
- services/web/server/src/simcore_service_webserver/data/fake-template-projects.json
- services/web/server/src/simcore_service_webserver/data/fake-user-projects.json
Fixes some bugs:
Bonus:
closes #702, #703, #706
> Fixes some Frontend bugs

- .github/ISSUE_TEMPLATE/tester_report.md
- services/web/client/source/class/qxapp/About.js
- services/web/client/source/class/qxapp/component/widget/NewGHIssue.js
- services/web/client/source/class/qxapp/component/widget/inputs/NodeOutputLabel.js
- services/web/client/source/class/qxapp/desktop/NavigationBar.js
- services/web/client/source/class/qxapp/desktop/ServiceBrowserListItem.js
- services/web/client/source/class/qxapp/desktop/preferences/pages/BasePage.js
- services/web/client/source/class/qxapp/ui/basic/Label.js
- services/web/client/source/class/qxapp/utils/LibVersions.js
- services/web/client/source/class/qxapp/utils/Utils.js
- services/web/client/source/class/qxapp/wrapper/Plotly.js
Opens a new tab pointing to Github New Issue website.
It adds automatically the "tester_review" tag and also the environment prettified information (both via url).
connected #695
> Create New Github Issue from Frontend

- .travis.yml
- ops/travis/unit-testing/frontend
- package.json
- services/web/client/Manifest.json
- services/web/client/compile.json
- services/web/client/contrib.json
- services/web/client/package-lock.json
- services/web/client/package.json
Bring qooxdoo compile, qooxdoo-sdk and contribs to the latest version
```
npm cache clean --force
npm update
npx qx contrib update
npx qx contrib upgrade
npx qx contrib list
```
> upgrade to the latest qooxdoo and contribs

- services/web/server/src/simcore_service_webserver/data/fake-template-projects.isan.json
- services/web/server/src/simcore_service_webserver/data/fake-template-projects.isan.old.json
> Fix ISAN templates

- services/web/server/src/simcore_service_webserver/application_config.py
- services/web/server/src/simcore_service_webserver/config/host-dev-config.yaml
- services/web/server/src/simcore_service_webserver/config/server-defaults.yaml
- services/web/server/src/simcore_service_webserver/config/server-docker-dev.yaml
- services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml
- services/web/server/src/simcore_service_webserver/config/server-template.yaml
- services/web/server/src/simcore_service_webserver/studies_access.py
- services/web/server/tests/unit/with_postgres/config.yaml
- services/web/server/tests/unit/with_postgres/test_access_to_studies.py
replica of PR #846 (already merged in staging) to master
> Hotfix/config studies -> master

- services/web/client/source/class/qxapp/component/message/FlashMessenger.js
- services/web/client/source/class/qxapp/component/workbench/WorkbenchUI.js
- services/web/client/source/class/qxapp/test/utils/Utils.js
- services/web/client/source/class/qxapp/utils/Utils.js
> Fix service version sorting

- services/web/client/source/class/qxapp/component/widget/logger/LoggerView.js
- services/web/client/source/class/qxapp/desktop/StudyEditor.js
Makes Node-context logger optional
closes #862
> Make Node-context logger optional

- services/storage/Dockerfile
- services/storage/requirements/_base.in
- services/storage/requirements/_base.txt
- services/storage/requirements/_test.txt
- services/storage/requirements/python-with-pandas_89f709.txt
Speeds up storage build by using [python-with-pandas](https://github.com/ITISFoundation/dockerfiles/blob/89f70938b66c0e4c1966c9a62da7a6dc89778f45/python-with-pandas/3.6-alpine) as base image
> Adds base image with pandas

- services/storage/src/simcore_service_storage/datcore.py
Fix parsing of 's3' data within a collection.
> Fix parsing of collections of collections

- services/web/server/src/simcore_service_webserver/studies_access.py
Fixes study links for parameterized template studies
login
http://master.osparc.io/study/154fb4ad-4913-478f-af04-19725db901a7?stimulation_period_secs=1200
http://master.osparc.io/study/154fb4ad-4913-478f-af04-19725db901a7?stimulation_period_secs=600
> uuid of new project composed by template, user and parametrization

- services/storage/src/simcore_service_storage/data/docker-dev-config.yaml
- services/storage/src/simcore_service_storage/data/docker-prod-config.yaml
- services/storage/src/simcore_service_storage/data/host-dev-config.yaml
- services/storage/src/simcore_service_storage/dsm.py
- services/storage/tests/conftest.py
- services/storage/tests/test_dsm.py
- services/storage/tests/test_rest.py
Bug in logic if projects db was emtpy for a user.
> Fix file listing in corner case

- packages/s3wrapper/src/s3wrapper/s3_client.py
- services/docker-compose.yml
- services/storage/src/simcore_service_storage/dsm.py
On staging/production, mino is using ssl.
> SSL fix for aiobotocore in s3

- packages/s3wrapper/src/s3wrapper/s3_client.py
- services/docker-compose.yml
- services/storage/src/simcore_service_storage/dsm.py
Hotfix for talking to s3 with https protocol
> Fix endpoint of s3 in production (#943)

- services/sidecar/src/sidecar/core.py
Fix issue of apparently hanging computational services hanging up the message system
> Add context manager for long standing connections

- packages/s3wrapper/src/s3wrapper/s3_client.py
- services/docker-compose.yml
- services/sidecar/src/sidecar/core.py
- services/storage/src/simcore_service_storage/dsm.py
- services/web/client/source/class/qxapp/component/widget/logger/LoggerView.js
- services/web/client/source/class/qxapp/desktop/StudyEditor.js
- services/web/client/source/class/qxapp/file/FilesTreePopulator.js
- Fix endpoint of s3 in production (#943)
- Fix simcore.s3 tree loading issue (#947)
- Add context manager for long standing connections (#949)
> Merge to staging

- services/storage/src/simcore_service_storage/dsm.py
- services/storage/tests/test_dsm.py
Fix issue when deep copying projects that contain links to datcore
> Filename was missing

- .env-devel
- Makefile
- api/specs/webserver/v0/components/schemas/project-v0.0.1-converted.yaml
- api/specs/webserver/v0/components/schemas/project-v0.0.1.json
- services/web/client/source/class/qxapp/component/service/NodeStatus.js
- services/web/client/source/class/qxapp/component/widget/inputs/NodeOutputTreeItem.js
- services/web/client/source/class/qxapp/component/widget/logger/LoggerView.js
- services/web/client/source/class/qxapp/desktop/StudyEditor.js
- services/web/client/source/class/qxapp/file/FilePicker.js
- services/web/server/src/simcore_service_webserver/application_config.py
- services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml
- Hotfix storage fix deep copy path (#979)
- Fix bugs (#980)
- Configuration switch to enable/disable study access (#981)
> Freeze to merge staging

- .vscode-template/launch.json
- .vscode-template/pytest.ini
- services/maintenance/Dockerfile
- services/maintenance/requirements.txt
- services/web/server/src/simcore_service_webserver/computation_api.py
- services/web/server/src/simcore_service_webserver/projects/projects_db.py
- services/web/server/src/simcore_service_webserver/projects/projects_handlers.py
- services/web/server/src/simcore_service_webserver/projects/projects_utils.py
- services/web/server/src/simcore_service_webserver/studies_access.py
Unnecessary updates of the pipeline db due to project updates would stop execution of pipeline.
- FIX: Updates pipeline ONLY when project's DAG topology has changed
- FIX: right access to maintenance service
- NEW for dev: adds .vscode-template/launch.json template to remote debugging of webserver and storage services
> Fix/updated pipeline (#983)

- services/web/server/src/simcore_service_webserver/config/server-docker-dev.yaml
- services/web/server/src/simcore_service_webserver/security_roles.py
- services/web/server/tests/unit/with_postgres/test_projects.py
- services/web/server/tests/unit/with_postgres/test_storage.py
Anonymous users did not have access to:
- Update pipeline
- Files
> ISAN: Anonymous users need to have access to their files and update-pipeline

- services/docker-compose.yml
the maintenance service must have different port on staging and production
> maintenance port shall be dynamically assigned by the swarm

- api/specs/webserver/v0/components/schemas/project-v0.0.1-converted.yaml
- api/specs/webserver/v0/components/schemas/project-v0.0.1.json
> Fix missing property in workbench schema

- services/storage/docker/boot.sh
- services/storage/src/simcore_service_storage/dsm.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
- services/web/server/src/simcore_service_webserver/projects/projects_utils.py
- services/web/server/src/simcore_service_webserver/studies_access.py
> Fix deep copy if anonymous user

- Makefile
> Fixed make tag

- services/docker-compose.yml
- services/rabbit/README.md
- services/rabbit/enabled_plugins
> Update rabbitmq and enable monitoring endpoint

- .github/CODEOWNERS
- ci/travis/build/test-images
typos in paths and changed 'ci' ownership
> Fixes path in ci/travis/build/test-images

- services/web/client/source/class/osparc/Application.js
- services/web/client/source/class/osparc/store/Store.js
* Adds an invalidate method instide ``osparc.store.Store``
* Uses that method to invalidate the entire cache when the login page shows up.
Closes #1144
> solution for #1144

- services/web/server/src/simcore_service_webserver/sockets_handlers.py
- services/web/server/tests/integration/fixtures/celery_service.py
- services/web/server/tests/integration/fixtures/docker_compose.py
* Minor cleanup
* Enabled logging and disabled cors in websockets
> Hotfix Fix/websocket conn (#1185)

- services/web/client/source/class/osparc/file/FilePicker.js
> Improve  FilePicker UX

- services/sidecar/src/sidecar/__init__.py
- services/sidecar/src/sidecar/celery_log_setup.py
- services/sidecar/src/sidecar/config.py
- services/sidecar/src/sidecar/tasks.py
Removes hard-coded log levels
inits logging config upon import
Fixes issue in sidecar discovered by e2e
> Fixes getattr key errors in sidecar

- services/sidecar/src/sidecar/_deprecated.py
- services/sidecar/src/sidecar/core.py
Reduces logs of sidecar adjusting it to the loglevel defined in the environ
> Sets sidecar log-level to environ

- README.md
- docs/staging-instructions.md
- scripts/url-encoder.sh
- Document how the staging process is done
- adds a pure bash script to encode URLs
> Document staging

- services/web/client/source/class/osparc/desktop/NavigationBar.js
- services/web/client/source/class/osparc/desktop/StudyBrowser.js
- services/web/client/source/class/osparc/theme/Appearance.js
- services/web/client/source/class/osparc/ui/window/Dialog.js
* Show a dialog informing the user that he needs to have a logged-in account in GitHub in order to create issues for the platform.
* Created a convenient widget to show this kind of messages.
* using the newly created window for study delete confirmation.
#1148 
Test the issue creation link in the navigation bar.
> GitHub 404 when creating issue

- services/web/server/src/simcore_service_webserver/resource_manager/registry.py
- services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py
- services/web/server/tests/unit/with_dbs/test_projects.py
- services/web/server/tests/unit/with_dbs/test_redis_registry.py
- adds more tests
- fixes issue where opening 2 tabs with the same logged in user would return the same active project thus not taking in acount the client_session_id (tab unique identifier)
- added some documentation
> Fix get active project

- services/web/server/src/simcore_service_webserver/resource_manager/registry.py
- services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py
- services/web/server/tests/unit/with_dbs/test_resource_manager.py
- fix issue: any user with user_id below the one from puppeteer was being logged out when pupetteer logs out.
> fixed pattern matching

- services/storage/src/simcore_service_storage/db_tokens.py
- services/web/server/src/simcore_service_webserver/users_handlers.py
Hot fixes #1229 onto staging branch
> hot fix1229: fails db query

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- api/specs/common/schemas/Makefile
- services/director/src/simcore_service_director/api/Makefile
- services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json
- services/storage/src/simcore_service_storage/api/Makefile
- services/storage/src/simcore_service_storage/api/v0/openapi.yaml
- services/storage/src/simcore_service_storage/api/v0/schemas/project-v0.0.1.json
- services/web/server/src/simcore_service_webserver/api/Makefile
- services/web/server/src/simcore_service_webserver/api/v0/schemas/project-v0.0.1.json
Fixes sync of schemas and openapi specs
> [bug fix] sync api schemas

- services/web/client/source/class/osparc/file/FilePicker.js
- services/web/client/source/class/osparc/file/FilesAdd.js
path and dataset can't be accessed from File type of object
> [bug fix] Python UX fix2

- ci/helpers/dockerhub_login
- fixes current issue CI cannot build master
> fix CI in upstream/master

- services/web/client/source/class/osparc/component/widget/NodeInput.js
- services/web/client/source/class/osparc/component/workbench/NodeUI.js
- services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js
- services/web/client/source/class/osparc/desktop/ControlsBar.js
- services/web/client/source/class/osparc/store/Store.js
- services/web/client/source/class/osparc/theme/Appearance.js
- services/web/client/source/class/osparc/theme/Color.js
* Simplify node selection in the workbench
* No tri-state
* Selected/unselected have easier to differentiate colors (shades of gray :smile: )
* desktop-os-like selection behavior
* clicking on a node without control key selects only that node
* with control key unselects it, respecting previous selection
* now using ``Appearance`` class
* Aligning control buttons to the right
> Some fixes

- tests/e2e/utils/utils.js
> Appends more information in e2e's test screenshots

- .coveragerc
- .github/workflows/ci-testing-deploy-pr.yml
- .github/workflows/ci-testing-deploy.yml
- ci/github/integration-testing/simcore-sdk
- ci/github/integration-testing/webserver
- ci/github/unit-testing/api
- ci/github/unit-testing/director
- ci/github/unit-testing/service-library
- ci/github/unit-testing/sidecar
- ci/github/unit-testing/simcore-sdk
- ci/github/unit-testing/storage
- ci/github/unit-testing/webserver
- ci/travis/integration-testing/simcore-sdk
- ci/travis/integration-testing/webserver
- ci/travis/unit-testing/api
- ci/travis/unit-testing/director
- ci/travis/unit-testing/service-library
- ci/travis/unit-testing/sidecar
- ci/travis/unit-testing/simcore-sdk
- ci/travis/unit-testing/storage
- ci/travis/unit-testing/webserver
- services/web/server/src/simcore_service_webserver/computation_subscribe.py
- services/web/server/tests/integration/computation/test_rabbit.py
- services/web/server/tests/integration/fixtures/docker_swarm.py
> Increase timeout for test

- Makefile
- requirements.txt
- services/web/server/src/simcore_service_webserver/application.py
- services/web/server/src/simcore_service_webserver/projects/projects_db.py
- services/web/server/src/simcore_service_webserver/projects/projects_handlers.py
Fixes block in database when opening a study that contained a lot of dynamic services
- Removes nested connections 
- avoids nested async for loops due to issues in aiopg
- **Makefile** :  improves clean target
closes #1300 
- In browser, open Developer tools > Network > and monitor XHR requests
- Create study
- Add lots of dynamic services (e.g. jupyters)
- Requests shall not be waiting
> [bug] Fixes database blockage upon many requests on projects interface

- api/specs/common/schemas/node-meta-v0.0.1.json
- adds the integration-version label to the node schema
> add integration-version in node schema

- tests/e2e/tutorials/tutorialBase.js
get studyData after accessing a template via link (needed in portal-e2e)
> openStudyLink

- tests/e2e/tutorials/tutorialBase.js
This PR increases openStudy timeout
> Increase openStudy timeout

- .pylintrc
- packages/postgres-database/src/simcore_postgres_database/cli.py
- packages/pytest-simcore/src/pytest_simcore/minio_service.py
- packages/pytest-simcore/src/pytest_simcore/simcore_storage_service.py
- packages/pytest-simcore/src/pytest_simcore/traefik_service.py
- packages/service-library/tests/with_postgres/test_aiopg_utils.py
- services/api-gateway/src/simcore_service_api_gateway/auth.py
- services/api-gateway/src/simcore_service_api_gateway/utils/helpers.py
- services/director/src/simcore_service_director/producer.py
- services/sidecar/src/simcore_service_sidecar/executor.py
- services/sidecar/tests/integration/test_sidecar.py
- services/web/server/src/simcore_service_webserver/projects/projects_handlers.py
- services/web/server/tests/unit/with_dbs/test_redis_registry.py
pylint section in CI installs pylint ~2.0 and the latter has updated from 2.4 to 2.5. 
It is more sensitive and this PR fixes some linter issues.
Replaced RE ``f"([^\{\}"]+)"`` by `"$1"` in all ``*.py``
> Fixes f-string-without-interpolation linter error

- services/sidecar/src/simcore_service_sidecar/executor.py
fix missing change of filename from the sidecar with regard to service version 1.0.0
input.json -> inputs.json
output.json -> outputs.json
> in case of service integration 1.0.0 use inputs.json and outputs.json

- services/web/client/source/class/osparc/dashboard/StudyBrowser.js
The importance of parentheses.
> Fix thumbnails

- packages/service-library/src/servicelib/utils.py
- services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py
- services/web/server/src/simcore_service_webserver/security_api.py
- services/web/server/src/simcore_service_webserver/studies_access.py
- services/web/server/src/simcore_service_webserver/templates/error-page.html
- services/web/server/src/simcore_service_webserver/users_api.py
- services/web/server/src/simcore_service_webserver/utils.py
- services/web/server/tests/unit/with_dbs/test_access_to_studies.py
Hotfix for bug #1570 on staging. 
Cherry-pick and adapts PR #1572 from master.
After this PR is resolved:
1. will merge into master
2. test feature life
3. tag this head and release to production
#1570
```cmd
pytest tests/unit/with_dbs/test_access_to_studies.py
```
> Hot fix for #1570 in staging

- services/storage/src/simcore_service_storage/dsm.py
Fixes error while copying data in storage service. 
Manually tested in development.
> Hotfix copy in storage service

- services/web/server/src/simcore_service_webserver/config/server-docker-dev.yaml
- services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml
- tests/e2e/tutorials/mattward.js
- tests/e2e/tutorials/sleepers.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
> Platform stability: 

- .github/workflows/ci-release.yml
fix typo in github action workflow for release deployment
> Hotfix: typo in github actions workflow

- tests/e2e/tutorials/jupyters.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/utils.js
In order to make sure that the very basic functionalities work, this PR starts a template the contains:
- File Picker
- Jupyter Notebook
- Jupyter Lab
Workflow:
- The FilePicker points to a file that contains one number
- The Jupyter Notebook:
- Reads the number in the input file
- This number is powered
- The power is written in the first output file
- Retrieve is called
- We check if the output file was properly pushed
- The Jupyter Lab:
- Reads the number in the input file
- This number is square rooted
- The square is written in the first output file
- TODO: Jupyter Lab is able to push output files
ITISFoundation/osparc-issues#273
> e2e: JupyterNB + JupyterLab

- packages/simcore-sdk/src/simcore_sdk/node_ports/dbmanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports/exceptions.py
- services/sidecar/src/simcore_service_sidecar/celery_configurator.py
- services/sidecar/src/simcore_service_sidecar/executor.py
While recovering node port information from the database, the case in which the is missing was never handled. The PR addresses the issue.
Messages on failures will also be sent to the UI for easier debugging in the future.
`DatabaseError`was not caught and caused an exception if the pipeline was missing.
`DockerError` was never caught. When pulling an image (if the docker registry is not responding) an exception is raised and never handled.
> Fixes some error with the services

- services/api-server/requirements/_base.txt
- services/api-server/requirements/_test.txt
- services/api-server/src/simcore_service_api_server/core/openapi.py
Fixes vulnerabilities on api-server dependencies
> Upgrades api-server dependencies

- services/sidecar/src/simcore_service_sidecar/utils.py
- closes aiodocker connection gracefully
- prints more info during the is_gpu_node check
- prints the reason why the GPU mode was not found
> adds more information when checking if node has gpu support

- services/director/src/simcore_service_director/producer.py
fixes wrong appending of array
> bugfix: setup of mounts

- services/web/client/source/class/osparc/desktop/NavigationBar.js
> URL hardcoded

- services/director/tests/fixtures/fake_services.py
- services/sidecar/src/simcore_service_sidecar/executor.py
- services/sidecar/src/simcore_service_sidecar/utils.py
- services/sidecar/tests/integration/test_sidecar.py
make use of aiodocker context manager to properly close the underlying aiohttp client connection
> fix failing to close aiodocker connection

- .github/workflows/ci-testing-deploy.yml
- ci/deploy/dockerhub-test-images.bash
- ci/github/helpers/setup_docker_buildx.bash
- ci/github/helpers/setup_docker_compose.bash
- ci/github/helpers/setup_docker_experimental.bash
- requirements.txt
> update docker-compose to 1.26.2

- tests/e2e/docker/Dockerfile
- tests/e2e/docker/Makefile
- tests/e2e/docker/README.md
- adds Dockerfile/Makefile/Readme to create the puppeteer image that is used in the gitlab runners
> The puppeteer image with node 14

- services/catalog/src/simcore_service_catalog/api/routes/services.py
- services/catalog/src/simcore_service_catalog/core/background_tasks.py
- services/catalog/src/simcore_service_catalog/core/settings.py
- services/catalog/src/simcore_service_catalog/db/repositories/services.py
- services/catalog/tests/unit/test_openapi_specs.py
- services/web/server/src/simcore_service_webserver/catalog.py
- services/web/server/src/simcore_service_webserver/projects/projects_handlers.py
- services/web/server/tests/integration/test_project_workflow.py
- services/web/server/tests/unit/with_dbs/fast/test_access_to_studies.py
- services/web/server/tests/unit/with_dbs/slow/test_projects.py
- Fixes missing default product in catalog background task
- Minor cleanup
> BugFix: Fix/catalog model

- docs/releasing-workflow-instructions.md
- services/catalog/src/simcore_service_catalog/services/director.py
- Fixes typo that produced exception in a catch
- Doc update
> Minor fix catalog exception exception and doc

- tests/e2e/portal/2D_Plot.js
- tests/e2e/portal/3D_Anatomical.js
- tests/e2e/portal/3D_EM.js
- tests/e2e/portal/Bornstein.js
- tests/e2e/portal/CC_Human.js
- tests/e2e/portal/CC_Rabbit.js
- tests/e2e/portal/Mattward.js
- tests/e2e/portal/opencor.js
- tests/e2e/tutorials/jupyters.js
- tests/e2e/tutorials/mattward.js
- tests/e2e/tutorials/sleepers.js
- tests/e2e/tutorials/tutorialBase.js
In order to get more visual feedback from the portal-2-end testing, this PR makes it take screenshots every two seconds.
> screenshots every 2 seconds for p2e

- tests/e2e/portal/2D_Plot.js
- tests/e2e/portal/3D_Anatomical.js
- tests/e2e/portal/3D_EM.js
- tests/e2e/portal/Bornstein.js
- tests/e2e/portal/CC_Human.js
- tests/e2e/portal/CC_Rabbit.js
- tests/e2e/portal/Mattward.js
- tests/e2e/portal/opencor.js
- tests/e2e/tutorials/jupyters.js
- tests/e2e/tutorials/mattward.js
- tests/e2e/tutorials/sleepers.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/utils.js
This PR adds the template name to the screenshots
> Minor e2e: prefix Template name to Screenshots

- tests/e2e/docker/Dockerfile
- tests/e2e/docker/Makefile
Updates container used in e2e CI
> adds jq and curl in puppeteer's image for e2e/p2e CI

- tests/e2e/utils/utils.js
reduce size of screenshots in e2e
> set jpg quality to 15%

- tests/e2e/tutorials/sim4life.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
- tests/e2e/utils/responsesQueue.js
Adds an e2e test to check that the latest sim4life service (available to puppeteer) starts gracefully.
> e2e: sim4life

- tests/e2e/tutorials/tutorialBase.js
This PR fixes the issue we currently have when we need to wait for multiple services to be started. It also makes the "State of the thing" chat more quiet.
> e2e: fix jupyters

- services/web/server/src/simcore_service_webserver/computation_api.py
If a node (computational service) was deleted from the workbench, the pipeline would not start.
> Fixes modified pipelines not starting

- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/responsesQueue.js
- tests/e2e/utils/utils.js
This PR fixes, again..., the waitForServices function used in the e2e testing.
> fixed waitForServices

- tests/e2e/tutorials/tutorialBase.js
> Fix e2e portal testing

- services/web/client/source/class/osparc/dashboard/ExploreBrowser.js
Fixes the bug where the service submission form wasn't loading correctly.
> [bugfix] New service submission form

- services/web/client/compile.json
- services/web/client/source/class/osparc/Application.js
- services/web/client/source/resource/dev/classifiers.json
- services/web/client/source/resource/osparc/ti-solutions.svg
- tests/swarm-deploy/test_swarm_runs.py
> TI Treatment Planning

- services/web/client/source/class/osparc/dashboard/ExploreBrowser.js
- services/web/client/source/resource/form/service.json
Small corrections for the service submission form as requested by @KZzizzle
> Corrections for service submission form

- .github/workflows/ci-testing-deploy.yml
- ci/github/integration-testing/sidecar.bash
- ci/github/integration-testing/simcore-sdk.bash
- ci/github/system-testing/environment-setup.bash
- ci/github/system-testing/swarm-deploy.bash
- services/web/server/src/simcore_service_webserver/projects/projects_utils.py
- services/web/server/tests/unit/with_dbs/fast/test_access_to_studies.py
- services/web/server/tests/unit/with_dbs/slow/test_projects.py
fixes [#360](https://github.com/ITISFoundation/osparc-issues/issues/360)
> replace uuid in the ui section as well

- services/web/server/tests/unit/with_dbs/docker-compose-devel.yml
- services/web/server/tests/unit/with_dbs/docker-compose.yml
> fix unit test that checks all images are the same

- packages/models-library/requirements/_test.txt
- packages/postgres-database/requirements/_migration.txt
- packages/postgres-database/requirements/_test.txt
- packages/s3wrapper/requirements/_base.txt
- packages/s3wrapper/requirements/_test.txt
- packages/service-library/requirements/_test.txt
- packages/simcore-sdk/requirements/_base.txt
- packages/simcore-sdk/requirements/_test.txt
- scripts/requirements/Makefile
- services/api-server/requirements/_base.txt
- services/api-server/requirements/_test.txt
- services/catalog/requirements/_base.txt
- services/catalog/requirements/_test.txt
- services/director-v2/requirements/_test.txt
- services/director/requirements/_base.txt
- services/director/requirements/_test.txt
- services/sidecar/requirements/_base.txt
- services/sidecar/requirements/_packages.txt
- services/sidecar/requirements/_test.txt
- services/storage/requirements/_base.txt
- services/storage/requirements/_test.txt
- services/web/server/requirements/_base.txt
- services/web/server/requirements/_test.txt
- tests/environment-setup/requirements/requirements.txt
- tests/swarm-deploy/requirements/requirements.txt
Weekly upgrade of dependencies. Decided to do a separate PR for **aiohttp** upgrade (see #1911 ) since it is more critical [last upgrade](https://github.com/ITISFoundation/osparc-simcore/pull/1896) , they fixed an issue with yarl]
- **urllib3** from 1.25.10 to 1.25.11 
- **cryptography>3.2**. Upgrades security vulnerability <img width="959" alt="Screen Shot 2020-10-28 at 19 27 03" src="https://user-images.githubusercontent.com/32402063/97480350-90f6b780-1953-11eb-80d5-49380e933cd6.png">
- Upgrades all **packages used for testing** (e.g. tooling like pytest and other extras used in fixtures ONLY for test purposes). 
- Includes services in upgrade recipe
> Maintenance: upgrades reqs week 44

- services/docker-compose.yml
bad configuration that forces the sidecars to start in CPU mode
> bugfix - wrong configuration of sidecars

- tests/e2e/README.md
- tests/e2e/portal/2D_Plot.js
- tests/e2e/portal/3D_Anatomical.js
- tests/e2e/portal/3D_EM.js
- tests/e2e/portal/Bornstein.js
- tests/e2e/portal/CC_Human.js
- tests/e2e/portal/CC_Rabbit.js
- tests/e2e/portal/Mattward.js
- tests/e2e/portal/opencor.js
- tests/e2e/tests/startupCalls.test.js
- tests/e2e/tutorials/sleepers.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
- tests/e2e/utils/startPuppe.js
- tests/e2e/utils/utils.js
e2e: after pressing the Run button, instead of waiting a fixed amount of time, ask what the state of the study is and stop waiting if it's SUCCESS or FAILED. The previous waiting period is now used as a timeout.
> e2e: don't wait, ask

- services/web/client/source/class/osparc/dashboard/ExploreBrowser.js
- services/web/client/source/class/osparc/desktop/ControlsBar.js
- services/web/client/source/class/osparc/ui/mixin/FetchButton.js
* Adds response status message to flash error message (for wrong file type, for example)
* Bonus: Fixes bug with FetchButton
closes #1942
> [bugfix] filetype error message

- .github/workflows/ci-testing-deploy.yml
should fix the code-climate issue in master CI build
> fix issues with PR#1877

- packages/models-library/src/models_library/project_nodes.py
- services/director-v2/src/simcore_service_director_v2/core/events.py
- services/director-v2/src/simcore_service_director_v2/core/settings.py
> final issues in deployment

- packages/models-library/src/models_library/projects.py
- services/README.md
- services/director-v2/src/simcore_service_director_v2/api/errors/http_error.py
- services/director-v2/src/simcore_service_director_v2/api/errors/validation_error.py
- services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
- services/director-v2/src/simcore_service_director_v2/core/application.py
- services/docker-compose.yml
- services/web/server/src/simcore_service_webserver/director_v2.py
- services/web/server/src/simcore_service_webserver/studies_dispatcher/_core.py
- services/web/server/src/simcore_service_webserver/studies_dispatcher/_projects.py
- services/web/server/src/simcore_service_webserver/studies_dispatcher/handlers_redirects.py
- services/web/server/tests/sandbox/studies_links.md
- services/web/server/tests/unit/with_dbs/fast/test_studies_dispatcher_routes.py
- adds exception handler in director-v2: will convert any validation or concrete exception into formatted json responses. Before unhandled errors were responded as text and clients converting to ``client.json()`` would raise exceptions
- cleans up director client in web-server
- Fixes logs in directorv2
- Adds more connections to pg client pool in directorv2
- Increased coverage of studies_dispatcher testing (see all ``test_studies_dispatcher_...``
- some missing comments from PR's review by @GitHK  nad @sanderegg 
```cmd
make devenv
make test-dev-unit
```
> Various fixes on backend services after changes to pydantic  models

- services/web/client/source/class/osparc/desktop/WorkbenchView.js
the value sent is again Data instead of data...
> the data sent is inside the Data key

- services/web/client/source/class/osparc/viewer/MainPage.js
- services/web/client/source/class/osparc/viewer/NodeViewer.js
> Fix Guest viewers

- .env-devel
- services/web/client/source/class/osparc/viewer/NodeViewer.js
- services/web/server/src/simcore_service_webserver/studies_dispatcher/_core.py
- services/web/server/tests/unit/with_dbs/fast/test_studies_dispatcher_routes.py
> Dynamic dataset viewer

- services/web/client/source/class/osparc/component/node/BaseNodeView.js
- services/web/client/source/class/osparc/component/node/FilePickerNodeView.js
- services/web/client/source/class/osparc/component/node/GroupNodeView.js
- services/web/client/source/class/osparc/component/node/NodeView.js
- services/web/client/source/class/osparc/data/model/Node.js
- services/web/client/source/class/osparc/viewer/NodeViewer.js
related to https://github.com/ITISFoundation/osparc-issues/issues/368
> UI/UX: Node View header

- services/catalog/src/simcore_service_catalog/services/director.py
- services/web/client/source/class/osparc/dashboard/StudyBrowser.js
- services/web/client/source/class/osparc/data/model/Study.js
- services/web/client/source/class/osparc/desktop/MainPage.js
- services/web/client/source/class/osparc/desktop/StudyEditor.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
- tests/e2e/utils/responsesQueue.js
- tests/e2e/utils/utils.js
> Fix lock issue: "close" study after reloadUserStudies

- packages/models-library/src/models_library/projects_nodes.py
- packages/models-library/tests/test_project_nodes.py
- packages/simcore-sdk/requirements/_base.in
- packages/simcore-sdk/requirements/_base.txt
- packages/simcore-sdk/requirements/_test.txt
- packages/simcore-sdk/requirements/_tools.txt
- requirements/constraints.txt
- tests/swarm-deploy/requirements/requirements.in
- tests/swarm-deploy/requirements/requirements.txt
- Fixes missing argument in validators that stops model validation from working
- Increases test coverage of this CRITICAL module
- **EXTRA** fixes minio breaking changes. simcore-sdk and system-testings were not freezing reqs!
```cmd
make devenv
cd packages/models-library
make install-dev tests
```
> Fixes missing argument in Node validator class methods and minio dependency

- Makefile
> set s3 endpoint based on wsl2 ip address

- services/web/client/source/class/osparc/data/Resources.js
- services/web/client/source/class/osparc/store/Store.js
This PR fixes the bug introduced 2h ago
> BUG FIX: Classifiers might me empty

- services/web/server/src/simcore_service_webserver/groups_classifiers.py
- A good classic last minute FIX for the static bundle classifiers! :-)
Follows up on PR #2045
> BugFix: bundle classifiers

- services/director-v2/src/simcore_service_director_v2/utils/dags.py
When the minimal dependencies graph is created the director-v2 was checking the wrong part of the dict object.
This is now fixed and the following gif now works correctly:
fixes #2069 
see gif
> bugfix: correctly test dependencies

- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
The data returned by the director is a list of requirements not a single value.
> bugfix: gpu computational service not scheduled correctly

- Makefile
- docs/releasing-workflow-instructions.md
> spit out the logs as well as a list

- tests/e2e/portal/Kember.js
> Fix Kember test

- services/web/client/source/class/osparc/Application.js
- services/web/client/source/class/osparc/CookiePolicy.js
- services/web/client/source/class/osparc/utils/Utils.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
Pop up a window with the Cookie Policy message. Since cookies are required only "Accept" option is provided.
> Cookie Policy pop up message

- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
- director-v2 now upserts in comp_tasks table instead of deleting and re-inserting the tasks, so that the tasks remain stable.
fixes #2125
> really upsert in comp_task

- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
Problem:
The file-picker gets created --> the director-v2 inserts that new task in the comp_tasks table. When a file is then selected in the file-picker --> the director-v2 updates the task excluding the outputs (because that is a wanted behavior for dynamic/computational services)
- the upsert in the director-v2 must force the update of the comp_tasks table in case the node is a frontend service such as the file-picker.
> bugfix: frontend services outputs do not get transferred to the comp services

- services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py
e2e testing was constantly failing because services were taking very long to start. The reason was that the images were not in the hosts, then pulling was taking longer than usual for service to start and the test timed-out. The GC would jump in, and kill all running interactive services including those still pulling their images. Next round of e2e testing would have exactly the same problem ... 
In this PR, the GC will delay stopping the service until it did not finish pulling.
> enh: GC shall not stop service if still pulling image

- services/web/client/source/class/osparc/component/widget/logger/LoggerView.js
- tests/e2e/tutorials/isolve-gpu.js
- tests/e2e/tutorials/isolve-mpi.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
- tests/e2e/utils/utils.js
This PR adds an isolve-mpi test, which after running checks if ```Running MPI version 3.1 on 2 processes``` log was printed.
> e2e: Add MPI test

- services/catalog/src/simcore_service_catalog/core/background_tasks.py
Exception raised while handling another exception. There is a service metadata wrong but cannot see which one is .
> Fixes KeyError in exception handler

- services/web/client/source/class/osparc/component/node/BaseNodeView.js
- services/web/client/source/class/osparc/data/model/Node.js
- File Picker's and Dynamic's output are always up-to-date
> File Picker's and Dynamic's modified status

- services/director-v2/src/simcore_service_director_v2/models/domains/comp_tasks.py
- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
- services/director-v2/src/simcore_service_director_v2/utils/dags.py
- services/director-v2/src/simcore_service_director_v2/utils/logging_utils.py
- services/director-v2/tests/conftest.py
- services/director-v2/tests/unit/test_comp_tasks_model.py
- services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py
> Director-v2 Multi fixes

- tests/e2e/tutorials/jupyters.js
> check for notebook iframe since jupyter lab starts faster

- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/startPuppe.js
- tests/e2e/utils/utils.js
> wait for service connection

- services/web/server/src/simcore_service_webserver/groups_classifiers.py
- services/web/server/tests/unit/with_dbs/fast/test_groups_classifiers.py
Some fixes from issue observed in staging e2e:
- FIX: Classifiers validation 
```cmd
make devenv
pytest -vv tests/unit/with_dbs/fast/test_groups_classifiers.py
```
> BugFix: Fixes error parsing classifiers from database

- tests/e2e/tutorials/jupyters.js
- tests/e2e/utils/utils.js
> E2e wait for notebook3

- services/web/server/src/simcore_service_webserver/projects/projects_db.py
When dealing with tags templates were not included while adding and removing them.
closes https://github.com/ITISFoundation/osparc-issues/issues/392
> adding and removing tags from templates is now possible

- services/web/server/src/simcore_service_webserver/projects/projects_db.py
- services/web/server/tests/unit/with_dbs/slow/test_projects.py
until storage is fixed, listing shared studies is disallowed
> Disallow listing shared projects

- services/docker-compose.yml
sets healthcheck interval time to 2seconds
sets healtcheck timeout to 1s
sets traefik logs to WARNING level
> missing changes

- packages/service-library/src/servicelib/logging_utils.py
- services/api-server/Dockerfile
- services/api-server/requirements/_base.in
- services/api-server/requirements/_base.txt
- services/api-server/requirements/_test.txt
- services/api-server/requirements/_tools.txt
- services/api-server/requirements/ci.txt
- services/api-server/requirements/dev.txt
- services/api-server/requirements/prod.txt
- services/api-server/setup.py
- services/api-server/src/simcore_service_api_server/api/dependencies/database.py
- services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py
- services/api-server/src/simcore_service_api_server/core/application.py
- services/api-server/src/simcore_service_api_server/models/schemas/files.py
- services/api-server/src/simcore_service_api_server/utils/solver_job_outputs.py
- services/docker-compose.devel.yml
> api: get outputs out of solver node

- services/web/server/src/simcore_service_webserver/projects/projects_db.py
Already in release v1.8.1
- typo in the python imports
> Hotfix v1.8.x: imported wrong ValidationError 

- docs/releasing-workflow-instructions.md
> Update hotfix docs

- packages/service-library/requirements/_base.txt
- packages/service-library/src/servicelib/aiopg_utils.py
- services/api-server/requirements/_base.txt
- services/catalog/requirements/_base.txt
- services/catalog/requirements/_test.txt
- services/director-v2/requirements/_base.txt
- services/sidecar/requirements/_base.txt
- services/sidecar/requirements/_packages.txt
- services/sidecar/requirements/_test.txt
- services/storage/requirements/_base.txt
- services/storage/src/simcore_service_storage/dsm.py
- services/web/server/requirements/_base.txt
upgrade aiopg to 1.2.1 --> should fix issue where connection is not released while in a transaction
> Bugfix: Storage cannot release connection

- services/api-server/src/simcore_service_api_server/api/routes/health.py
- services/api-server/src/simcore_service_api_server/modules/director_v2.py
- services/api-server/src/simcore_service_api_server/utils/client_base.py
- tests/public-api/conftest.py
- tests/public-api/examples/.env-devel
- tests/public-api/examples/.gitignore
- tests/public-api/examples/Makefile
- tests/public-api/examples/opencor.py
- tests/public-api/examples/sleeper.py
- tests/public-api/test_solvers_jobs_api.py
NOTE: fixing download output files will be addressed in a separate PR
Fixes on #1865
> bugfix: Fixes 'Name or service not known' error in API

- services/docker-compose.yml
- tests/public-api/examples/opencor.py
- fixes docker-compose: ``shm_size`` options is not supported in swarm and portainer failed to deploy
- adds API example
>  🏗️ Fix/docker compose for portainer

- services/web/client/source/class/osparc/dashboard/ExploreBrowser.js
- services/web/client/source/class/osparc/dashboard/ResourceBrowserBase.js
- services/web/client/source/class/osparc/dashboard/StudyBrowser.js
- services/web/client/source/class/osparc/dashboard/StudyBrowserButtonLoadMore.js
- services/web/client/source/class/osparc/data/Resources.js
- services/web/client/source/class/osparc/desktop/MainPage.js
This PR implements the paginated templates calls in the frontend.
For demo purposes, we call 5 by 5:
Related to platform scalability https://github.com/ITISFoundation/osparc-issues/issues/428
> Templates pagination

- services/web/client/source/class/osparc/theme/ColorDark.js
- services/web/client/source/class/osparc/utils/Utils.js
This PR increases the contrast of the scroll bars in dark mode.
Before:
After:
Before:
After:
closes https://github.com/ITISFoundation/osparc-issues/issues/391
> Scroll bars: Increase contrast

- scripts/maintenance/clean_projects_of_user.py
the script for cleaning studies was not using the new awesome pagination feature. now it 's the case and will clean more than 20 studies.
> project cleaner script compatible with project pagination

- services/catalog/src/simcore_service_catalog/api/dependencies/database.py
- services/catalog/src/simcore_service_catalog/api/routes/services.py
- services/catalog/src/simcore_service_catalog/core/application.py
- services/catalog/src/simcore_service_catalog/core/events.py
- services/catalog/src/simcore_service_catalog/db/repositories/groups.py
- services/catalog/src/simcore_service_catalog/db/repositories/services.py
- services/docker-compose-ops.yml
- services/docker-compose.yml
gained a few 100ms in the operation, hopefully might help in the 20 users access osparc from the CI case
> Optimize catalog services endpoint

- tests/e2e/docker/Dockerfile
- tests/performance/Dockerfile
- tests/performance/Makefile
- tests/performance/docker-compose.yml
pin locust version and pushes it to dockerhub so it is accessible from p2p test
> 🏗️ Maintenance/set locust image

- requirements/constraints.txt
- services/api-server/requirements/_base.txt
- services/catalog/requirements/_base.txt
- services/director-v2/requirements/_base.txt
- services/dynamic-sidecar/requirements/_base.txt
- services/sidecar/requirements/_base.txt
- services/sidecar/requirements/_packages.txt
- services/sidecar/requirements/_test.txt
- services/storage/requirements/_base.txt
- services/web/server/requirements/_base.txt
Upgrades due to vulnerabilities:
- pydantic>=1.8.2 GHSA-5jqp-qgf6-3pvh
> 🏗️ maintenance: vulnerability updates

- .github/workflows/ci-testing-deploy.yml
- scripts/maintenance/clean_projects_of_user.py
- services/storage/src/simcore_service_storage/db.py
- services/web/server/src/simcore_service_webserver/db.py
- services/web/server/src/simcore_service_webserver/resource_manager/redis.py
- FIX: Replaces ``tenacity.Retrying`` by non-blocking ``AsyncRetrying`` in async calls (thx to @GitHK )
```log
15.022 instrumented  servicelib/monitor_slow_callbacks.py:23
└─ 15.022 _run  asyncio/events.py:143
└─ 15.022 _run_app  aiohttp/web.py:279
└─ 15.022 setup  aiohttp/web_runner.py:221
└─ 15.022 _make_server  aiohttp/web_runner.py:327
└─ 15.022 startup  aiohttp/web_app.py:384
└─ 15.022 send  aiohttp/signals.py:26
└─ 15.022 _on_startup  aiohttp/web_app.py:492
└─ 15.022 pg_engines  simcore_service_webserver/db.py:82
└─ 15.022 _create_pg_engine  simcore_service_webserver/db.py:69
└─ 15.022 __iter__  tenacity/__init__.py:395
└─ 15.022 sleep  tenacity/nap.py:22
└─ 15.022 sleep  ../../<built-in>:0 -
```
- FIX: extends timeout in ``scripts/maintenance/clean_projects_of_user.py``
- CHANGED: …
> Fixes slow calls

- tests/performance/locust_files/platform_ping_test.py
> performance testing: fix script typos

- Makefile
- ci/build/test-images.bash
- ci/deploy/dockerhub-test-images.bash
- ci/github/integration-testing/director-v2.bash
- ci/github/integration-testing/sidecar.bash
- ci/github/integration-testing/simcore-sdk.bash
- ci/github/integration-testing/webserver.bash
- ci/github/system-testing/e2e.bash
- ci/github/system-testing/public-api.bash
- ci/github/system-testing/swarm-deploy.bash
- ci/travis/integration-testing/director-v2.bash
- ci/travis/integration-testing/sidecar.bash
- ci/travis/integration-testing/simcore-sdk.bash
- ci/travis/integration-testing/webserver.bash
- ci/travis/system-testing/swarm-deploy.bash
- scripts/common-service.Makefile
- services/api-server/Dockerfile
- services/catalog/Dockerfile
- services/director-v2/Dockerfile
- services/director/Dockerfile
- services/docker-compose-build.yml
- services/dynamic-sidecar/Dockerfile
- services/sidecar/Dockerfile
- services/storage/Dockerfile
- services/web/Dockerfile
- services/web/client/Makefile
- tests/e2e/Makefile
- tests/e2e/docker/Makefile
- tests/e2e/docker/README.md
> 🏗️Maintenance: remove all cache docker images

- packages/service-library/src/servicelib/monitoring.py
- services/director-v2/requirements/_base.in
- services/director-v2/src/simcore_service_director_v2/modules/scheduler.py
- services/web/server/src/simcore_service_webserver/storage_handlers.py
- increase timeout when calling synchronisation from webserver
- fixes error in monitoring middleware (asyncio.CancelledError inherites BaseException)
- fixes #2422
>   🐛 Bugfix/clean storage issue

- services/web/client/source/class/osparc/About.js
- services/web/client/source/class/osparc/utils/LibVersions.js
- services/web/server/src/simcore_service_webserver/statics_settings.py
Lists the libs/tools used in the backend. For now, the list is hardcoded in the backend.
> List backend libs/tools

- tests/swarm-deploy/conftest.py
- tests/swarm-deploy/test_service_restart.py
- tests/swarm-deploy/test_swarm_runs.py
> use fixture to check that stack is deployed before testing

- Makefile
- services/director-v2/.env-devel
- services/director-v2/openapi.json
- services/director-v2/src/simcore_service_director_v2/api/dependencies/dynamic_services.py
- services/director-v2/src/simcore_service_director_v2/models/schemas/dynamic_services/service.py
- services/director-v2/src/simcore_service_director_v2/models/schemas/services.py
- services/director-v2/src/simcore_service_director_v2/modules/director_v0.py
- services/director-v2/tests/unit/test_models_dynamic_services.py
- services/docker-compose-deploy.yml
- services/docker-compose.pull.yml
> 🐛Fix dynamic-sidecar integration issues

- Makefile
- ci/deploy/dockerhub-deploy.bash
> 🐛 moving BUILD_TARGET

- services/docker-compose-deploy.yml
`static-webserver` was missing from` docker-compose-deploy.yaml` making push to GitHub to fail.
> 🐛 added missing service to push

- services/director-v2/src/simcore_service_director_v2/core/settings.py
- services/docker-compose.yml
> upgrade traefik to 2.4.13

- scripts/metrics/Makefile
- scripts/metrics/compute_list_of_images_in_registry.py
- scripts/metrics/requirements.txt
This script allows to generate a markdown file containing all the services that were added to a docker registry in a date range.
```bash
cd scripts/metrics
make
./compute_list_of_images_in_registry.py --help # follow the indications
```
> ✨ added script to generate metrics about additional services

- services/web/server/src/simcore_service_webserver/projects/projects_utils.py
> 🐛 project slideshow entries correctly replaced

- services/web/server/tests/unit/with_dbs/11/test_snapshots_api_handlers.py
> 🐛 Fix webserver 11 unittest

- services/web/server/tests/unit/with_dbs/11/test_snapshots_api_handlers.py
> 🐛 Fix unit test in webserver 11 (2 and final)

- packages/models-library/src/models_library/basic_types.py
- packages/models-library/src/models_library/projects_nodes.py
- packages/models-library/src/models_library/service_settings_labels.py
- packages/models-library/src/models_library/utils/database_models_factory.py
- packages/models-library/src/models_library/utils/misc.py
- packages/models-library/tests/test_projects.py
- packages/models-library/tests/test_service_settings_labels.py
- packages/models-library/tests/test_utils_database_models_factory.py
- packages/models-library/tests/test_utils_misc.py
- packages/pytest-simcore/src/pytest_simcore/helpers/rawdata_fakers.py
- services/director-v2/src/simcore_service_director_v2/models/schemas/dynamic_services/scheduler.py
- services/web/server/src/simcore_service_webserver/diagnostics_config.py
- services/web/server/tests/unit/isolated/test_snapshots_models.py
Some experimental ⚗️  tooling (currently only used in tests but intended to be used in production code when it reaches maturity)
- **```create_pydantic_model_from_sa_table ```**: class factory to create pydantic model classes out of sqlalchemy (sa) tables. 
- Rationale: an easy way to build pydantic models using information already defined in the sqlalchemy tables 
- **tests**: builds pydantic model classes from all sa tables in ``simcore_postgres_database.models``
- pydantic model example extractor
- Rationale: extracting examples from pydantic models 
- **tests** example extraction and model creation (via ``parse_obj``) against all models in ``models_library``
```command
make devenv
cd packages/models_library
make tests
```
> ⚗️  pydantic model classes factory and other utils

- services/director-v2/src/simcore_service_director_v2/core/errors.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/background_task.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/celery_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
- services/director-v2/tests/unit/conftest.py
- services/director-v2/tests/unit/test_modules_dask_client.py
- services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py
- Prevent the director-v2 from starting before the dask-scheduler dependency is up and running (previously was stopping after 20 attemps and continuining to start without complaining) --> This will fix the issue when deploying.
- 1st draft of handling Dask-scheduler disconnections:
- Dask-scheduler fails or is restarted for some reason (--> the client in the director does not expose a method to get an event in case of disconnection)
- the next time the director-v2 computational scheduler checks it will detect that the dask-scheduler is disconnected
- director-v2 will stop scheduling tasks and set them back to PUBLISHED, 
- and director-v2 will attempt to re-connect to the scheduler every 5-10 seconds until it succeed
- NOTHING can be scheduled until the dask-scheduler is re-connected. …
> ♻️ Ensure director-v2 waits on dask-scheduler, 1st draft on handling scheduler restarts

- services/web/client/source/class/osparc/Application.js
Bug found thanks to the p2e.
Do not invalidate currentStudyId from cache.
> Bugfix: Do not invalidate currentStudyId from cache

- services/web/server/src/simcore_service_webserver/snapshots_api_handlers.py
this should fix the problem with Mixed content when deployed on a platform behind Traefik
> if available get the scheme of the X-Forwarded-Proto header

- services/web/client/source/class/osparc/component/service/ServiceButtonSmall.js
- services/web/client/source/class/osparc/dashboard/CardBase.js
- services/web/client/source/class/osparc/ui/tree/CheckboxTreeItem.js
- services/web/client/source/class/osparc/ui/tree/MHintInTree.js
It fixes the Service Catalog filtering bug
Bonus:
> bugfix: Catalog filter

- services/web/client/source/class/osparc/component/service/ServiceButtonSmall.js
- services/web/client/source/class/osparc/component/workbench/NodeUI.js
- services/web/client/source/class/osparc/component/workbench/ServiceCatalog.js
- services/web/client/source/class/osparc/data/model/Node.js
- services/web/client/source/class/osparc/utils/Services.js
Fixes the type/tag filter in the Service Catalog
> Fix Service Catalog tags filter

- services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js
- services/web/client/source/class/osparc/desktop/StudyEditor.js
Middle mouse button enables panning:
> Workbench improvements: Pan

- services/director-v2/tests/unit/with_swarm/test_routes_dynamic_services.py
> 🐛 fix unit test for service version issue

- packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker.py
- packages/pytest-simcore/src/pytest_simcore/simcore_services.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_client.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/ports_mapping.py
- packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py
- services/dask-sidecar/Dockerfile
- services/dask-sidecar/docker/boot.sh
- services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
- services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py
- services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
- services/director-v2/src/simcore_service_director_v2/utils/dask.py
- services/director-v2/tests/unit/_helpers.py
- services/director-v2/tests/unit/conftest.py
- services/director-v2/tests/unit/test_modules_dask_client.py
- services/director-v2/tests/unit/with_dbs/conftest.py
- services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py
- services/director-v2/tests/unit/with_dbs/test_utils_dask.py
- services/docker-compose.yml
- services/dynamic-sidecar/Dockerfile
- services/storage/src/simcore_service_storage/dsm.py
- fix issue when downloading/uploading a file if the progress values are not set as they should
- set hostname for dask-sidecar so it's easy to identify
- give more information when the service fails
> 🐛 Dask scheduler: Fix issue when value and/or size is not set in file download progress

- services/dask-sidecar/docker/boot.sh
- adds time/date to ensure name uniqueness
> add the time and date to ensure uniqueness

- services/api-server/src/simcore_service_api_server/core/application.py
- services/api-server/src/simcore_service_api_server/core/settings.py
- services/datcore-adapter/src/simcore_service_datcore_adapter/core/application.py
- services/datcore-adapter/src/simcore_service_datcore_adapter/utils/requests_decorators.py
- services/datcore-adapter/tests/unit/conftest.py
- services/director-v2/src/simcore_service_director_v2/core/application.py
- services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py
- services/director-v2/tests/conftest.py
- services/director-v2/tests/integration/01/test_computation_api.py
- services/director-v2/tests/unit/test_modules_director_v0.py
- services/director-v2/tests/unit/with_swarm/test_routes_dynamic_services.py
- services/web/server/src/simcore_service_webserver/computation_subscribe.py
- services/web/server/tests/integration/02/test_rabbit.py
Activate API calls tracing in:
> ✨activate tracing in all fastapi apps

- services/web/client/source/class/osparc/component/metadata/ServicesInStudy.js
- services/web/client/source/class/osparc/component/node/BaseNodeView.js
- services/web/client/source/class/osparc/component/node/FilePickerNodeView.js
- services/web/client/source/class/osparc/component/node/NodeView.js
- services/web/client/source/class/osparc/component/workbench/NodeUI.js
- services/web/client/source/class/osparc/component/workbench/ServiceCatalog.js
- services/web/client/source/class/osparc/data/model/Node.js
- services/web/client/source/class/osparc/desktop/SlideshowToolbar.js
- services/web/client/source/class/osparc/desktop/SlideshowView.js
- services/web/client/source/class/osparc/desktop/StudyEditor.js
- services/web/client/source/class/osparc/desktop/WorkbenchPanel.js
- services/web/client/source/class/osparc/desktop/WorkbenchToolbar.js
- services/web/client/source/class/osparc/desktop/WorkbenchView.js
- services/web/client/source/class/osparc/file/FileDownloadLink.js
- services/web/client/source/class/osparc/file/FilePicker.js
- services/web/client/source/class/osparc/navigation/BreadcrumbNavigation.js
- services/web/client/source/class/osparc/navigation/BreadcrumbSplitter.js
- services/web/client/source/class/osparc/navigation/BreadcrumbsSlideshow.js
- services/web/client/source/class/osparc/ui/basic/NodeStatusUI.js
- services/web/client/source/class/osparc/ui/hint/InfoHint.js
- services/web/client/source/class/osparc/utils/StatusUI.js
- tests/e2e/tutorials/tutorialBase.js
> App Mode review

- services/docker-compose.yml
In Traefik language, a Path(`/study`) means that a path with EXACTLY /study will be redirected, a PathPrefix(`/study/`) means that anything building on top of /study/blahblahb/afdjhksdj will be redirected.
This PR ensures only minimal redirections are set.
Also it fixes the missing redirection to /view for the webserver.
> ♻️ set traefik rules to the minimal that allows entrypoints to go through

- packages/dask-task-models-library/requirements/_base.txt
- services/dask-sidecar/docker/boot.sh
- services/dask-sidecar/requirements/_base.in
- services/dask-sidecar/requirements/_base.txt
- services/dask-sidecar/requirements/_dask-complete.txt
- services/dask-sidecar/requirements/_dask-distributed.txt
- services/dask-sidecar/requirements/_packages.txt
- services/director-v2/requirements/_base.txt
> ✨ Dask scheduler to allow the dask-gateway to control it

- services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
This PR explicitely asks the dask-gateway-based clusters to go in "adaptive" mode, e.g. create/remove dask-workers based on load
> ✨ enable auto-adaptation of gateway clusters

- .github/workflows/ci-release.yml
- .github/workflows/ci-staging.yml
- .github/workflows/ci-testing-deploy.yml
upgrade Docker buildx to latest version v0.7.1
> ⬆️ upgrade docker buildx to v0.7.1

- services/web/server/src/simcore_service_webserver/statics_settings.py
> 🐛Fixes typo in env variable

- services/dynamic-sidecar/Dockerfile
- services/dynamic-sidecar/requirements/_base.in
- services/dynamic-sidecar/requirements/_base.txt
- services/dynamic-sidecar/requirements/_test.txt
- services/dynamic-sidecar/requirements/_tools.txt
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py
The `dynamic-sidecar` will no longer decompress formats like xlsx docx (which are simple zip archives). Using libmagic to detect file type should improve this a lot.
- closes https://github.com/ITISFoundation/osparc-issues/issues/71
> 🐛 zip compressed file formats will no longer be decompressed in outputs

- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers.py
Reloading containers will no longer cause logs to stop being propagated to the UI logger.
> 🐛dynamic-sidecar logs fetching is resumed/paused when reloading the containers

- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/volumes_resolver.py
Changes vfs-cache mode for rclone docker volume.
> ♻️ Set vfs-cache to minimal

- packages/settings-library/src/settings_library/_constants.py
- packages/settings-library/src/settings_library/email.py
- packages/settings-library/src/settings_library/rabbit.py
- packages/settings-library/tests/test_email.py
- services/web/server/src/simcore_service_webserver/login/utils.py
- services/web/server/tests/data/default_app_config-unit.yaml
- SMTP password was used as a secret and would always result being wrong
- added test to check that SMTP configuration does not contain invalid combinations
- https://github.com/ITISFoundation/osparc-issues/issues/428
> 🐛 Fixed email sending

- .github/workflows/ci-release.yml
- .github/workflows/ci-staging.yml
show all environs
The branch name was retrieved using a git call that fails when there are branches lying around.
This was changed to use Github generated variable that contain the branch name.
fixes #2888
> 🐛 CI: correctly find branch name in Github Workflow

- services/dask-sidecar/requirements/_base.txt
- services/dask-sidecar/requirements/_dask-complete.txt
- services/dask-sidecar/requirements/_dask-distributed.txt
- services/dask-sidecar/requirements/_packages.txt
- services/director-v2/requirements/_base.txt
- services/director-v2/requirements/_test.txt
Following dask-related libraries are upgraded to the latest and greatest:
dask: 2022.2.0 -> 2022.2.1
distributed: 2022.2.0 -> 2022.2.1
fsspecs: 2022.1.0 -> 2022.2.0
pillow: 8.2.0 -> 9.0.1
numpy: 1.20.3 -> 1.22.3
jupyter-server-proxy: 3.0.2 -> 3.2.1
aleviating some security risks as shown by dependabot.
> ⬆️ Maintenance/upgrade dask libraries

- services/web/server/src/simcore_service_webserver/garbage_collector.py
- services/web/server/src/simcore_service_webserver/socketio/plugin.py
- services/web/server/src/simcore_service_webserver/socketio/server.py
Follows up fixes in #2899 to get GC working in master-deploy for the first time. 
- Covered by CI
> 🚑️ hotfix GC: adds missing plugin dependency

- services/web/server/src/simcore_service_webserver/login/plugin.py
Follows up fixes in #2904 to get GC working in master-deploy for the first time.
- #2757 
- Covered by CI
> 🚑️ GC hotfix: fixes bad setup

- packages/models-library/src/models_library/function_service/parameters.py
- packages/models-library/src/models_library/function_service/probes.py
- services/web/client/source/class/osparc/component/node/ParameterEditor.js
- services/web/client/source/class/osparc/component/workbench/NodeUI.js
- services/web/client/source/class/osparc/ui/form/ContentSchemaArray.js
- services/web/client/source/class/osparc/utils/Ports.js
This PR adds support in the frontend for Parameters and Probes with arrays:
> Parameters and Probes support arrays

- docs/releasing-workflow-instructions.md
We had  a corner-case problem while releasing to staging today. This adds a caveat to the release-documentation highlighting the potential pitfall.
Related issue: https://github.com/ITISFoundation/osparc-simcore/issues/2969
>  📝 Add caveat to release notes

- services/web/client/source/class/osparc/component/form/Auto.js
- services/web/client/source/class/osparc/component/form/renderer/PropFormBase.js
- services/web/client/source/class/osparc/component/widget/CollapsibleViewLight.js
- services/web/client/source/class/osparc/component/widget/logger/LoggerTable.js
- services/web/client/source/class/osparc/component/widget/logger/LoggerView.js
- services/web/client/source/class/osparc/component/workbench/BaseNodeUI.js
- services/web/client/source/class/osparc/component/workbench/NodeUI.js
- services/web/client/source/class/osparc/component/workbench/SvgWidget.js
- services/web/client/source/class/osparc/desktop/CollapseWithUserMenu.js
- services/web/client/source/class/osparc/desktop/SlideshowToolbar.js
- services/web/client/source/class/osparc/desktop/WorkbenchView.js
- services/web/client/source/class/osparc/file/FileDrop.js
- services/web/client/source/class/osparc/navigation/BreadcrumbsSlideshow.js
- services/web/client/source/class/osparc/navigation/UserMenuButton.js
- services/web/client/source/class/osparc/theme/ColorDark.js
- services/web/client/source/class/osparc/theme/ColorLight.js
- services/web/client/source/class/osparc/theme/Decoration.js
- services/web/client/source/class/osparc/theme/zmt/ColorDark.js
- services/web/client/source/class/osparc/theme/zmt/ColorLight.js
> Frontend UI/UX

- packages/settings-library/src/settings_library/r_clone.py
- packages/settings-library/src/settings_library/s3.py
- packages/settings-library/tests/test_s3.py
Validator order was not respected. Added regression tests to make sure this will not fail in the future.
> 🐛 Fix issues with parsing S3Settings

- Makefile
- packages/dask-task-models-library/requirements/_tools.txt
- packages/models-library/requirements/_tools.txt
- packages/postgres-database/requirements/_tools.txt
- packages/service-integration/requirements/_tools.txt
- packages/service-library/requirements/_tools.txt
- packages/settings-library/requirements/_tools.txt
- packages/simcore-sdk/requirements/_tools.txt
- requirements/tools/Dockerfile
- services/api-server/requirements/_tools.txt
- services/catalog/requirements/_tools.txt
- services/dask-sidecar/requirements/_tools.txt
- services/datcore-adapter/requirements/_tools.txt
- services/director-v2/requirements/_tools.txt
- services/dynamic-sidecar/requirements/_tools.txt
- services/storage/requirements/_tools.txt
- services/web/server/requirements/_tools.txt
- tests/public-api/requirements/_tools.txt
- tests/swarm-deploy/requirements/_tools.txt
⬆️  Upgrades ``pip-tools==6.6.1`` to https://github.com/jazzband/pip-tools/releases/tag/6.6.1 that fixes the problem with latest ``pip`` upgrade
> ⬆️ Upgrades pip-tools==6.6.1

- services/dynamic-sidecar/docker/entrypoint.sh
Minor change, helpful for local deployment
> ♻️ Add self-signed-certificate processing to dy-sidecar

- packages/dask-task-models-library/requirements/_tools.txt
- packages/models-library/requirements/_tools.txt
- packages/postgres-database/requirements/_tools.txt
- packages/service-integration/requirements/_tools.txt
- packages/service-library/requirements/_tools.txt
- packages/settings-library/requirements/_tools.txt
- packages/simcore-sdk/requirements/_tools.txt
- services/api-server/requirements/_tools.txt
- services/catalog/requirements/_tools.txt
- services/dask-sidecar/requirements/_tools.txt
- services/datcore-adapter/requirements/_tools.txt
- services/director-v2/requirements/_tools.txt
- services/dynamic-sidecar/requirements/_tools.txt
- services/storage/requirements/_tools.txt
- services/web/server/requirements/_tools.txt
- tests/public-api/requirements/_tools.txt
- tests/swarm-deploy/requirements/_tools.txt
Probably you noticed that ``pip-tools`` was failing with the latest ``pip==22.1.1`` update (e.g. via ``make reqs``). This PR updates repo-wide to the latest  ``pip-tools=6.6.2`` together with all the tooling libraries (i.e. ``_tools.*`` 🔧)
- #packages before: 7
- #packages after : 7
|   1 | dill                      | 0.3.4           | 0.3.5.1    |            | 1 | dynamic-sidecar🔧 |
|   2 | filelock                  | 3.6.0           | 3.7.0      | *minor*    | 17 | api-server🔧</br>catalog🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>datcore-adapter🔧</br>director-v2🔧</br>dynamic-sidecar🔧</br>models-library🔧</br>postgres-database🔧</br>public-api🧪</br>service-integration🔧</br>service-library🔧</ …
> ⬆️  maintenance/ updates pip-tools repo-wide

- tests/e2e/tutorials/sim4life.js
Adapt the call to `waitForService` to make it appropriate for the case of a service using the dynamic sidecar.
> 🐛 Fix the state detection logic for the dy case

- Makefile
> Adjust Makefile Hints for Releasing to Production

- packages/models-library/src/models_library/service_settings_labels.py
- requirements/constraints.txt
- services/api-server/requirements/_base.txt
- services/api-server/requirements/_test.txt
- services/catalog/requirements/_base.txt
- services/catalog/requirements/_test.txt
- services/datcore-adapter/requirements/_base.txt
- services/datcore-adapter/requirements/_test.txt
- services/director-v2/requirements/_base.txt
- services/director-v2/requirements/_test.txt
- services/director-v2/src/simcore_service_director_v2/api/routes/dynamic_services.py
- services/director-v2/src/simcore_service_director_v2/modules/director_v0.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/client_api.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py
- services/director-v2/tests/conftest.py
- services/director-v2/tests/unit/test_modules_director_v0.py
- services/director-v2/tests/unit/test_modules_dynamic_sidecar_scheduler.py
- services/director-v2/tests/unit/test_routes_dynamic_services.py
- services/director-v2/tests/unit/with_dbs/test_route_computations_tasks.py
- services/dynamic-sidecar/requirements/_base.in
- services/dynamic-sidecar/requirements/_base.txt
- tests/public-api/requirements/_test.txt
Updates repo-wide ``httpx`` due to https://github.com/advisories/GHSA-h8pj-cxx2-jfg2
- 🐛[Fixes httpx DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content](https://github.com/ITISFoundation/osparc-simcore/pull/3087/commits/aa6da489e0b7f5fb1ff01051a844fc5d0407b52a) 
- minor cleanup
- #packages before: 3
- #packages after : 3
|   1 | charset-normalizer        | 2.0.10          | 🗑️ removed |  | 1 | catalog⬆️ |
|   2 | httpcore                  | 0.14.7, 0.14.4  | 0.15.0     | *minor*    | 10 | api-server⬆️🧪</br>catalog⬆️🧪</br>datcore-adapter⬆️🧪</br>director-v2⬆️🧪</br>dynamic-sidecar⬆️</br>public-api🧪 |
|   3 | httpx                     | 0.22.0, 0.21.3  | 0.23.0     | *minor*    | 10 …
> ⬆️ Maintenance/security update httpx

- .github/workflows/ci-testing-deploy.yml
This PR shall re-enable caching in Github actions when setting up python/node in tests, and gaining about 1-3 minutes per test
> ♻️ Maintenance: Re-enable caching in github CI workflow

- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers.py
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/shared_handlers.py
While debugging some studies which were not starting with @mguidon we observed that containers (started by `docker-compose up`) which do not get properly cleaned up, prevent the dynamic-sidecar from properly starting services.
The dynamic-sidecar will now remove all stopped containers and anonymous volumes attached to them.
These operation will be executed before running `docker-compose up` and after running `docker-compose down`.
NOTE: @pcrespov I know you are refactoring this module. Since this PR is more impactful on user experience, I did not wait for the new pattern to be in. I will leave the refactoring for a later date.
> 🐛 adds container cleanup before starting and after closing

- packages/service-library/src/servicelib/logging_utils.py
- services/web/server/src/simcore_service_webserver/login/handlers.py
- services/web/server/src/simcore_service_webserver/socketio/handlers.py
- ✨ logs login/logout
-  ✨ adds ``log_context`` helper
- closes ITISFoundation/osparc-simcore#3200
- login, should show
- logout should show
> ✨ Is3200/log user during login/logout

- services/dask-sidecar/requirements/_base.txt
- services/dask-sidecar/requirements/_dask-complete.txt
- services/dask-sidecar/requirements/_dask-distributed.txt
- services/dask-sidecar/requirements/_packages.txt
- services/dask-sidecar/requirements/constraints.txt
- services/director-v2/requirements/_base.txt
- services/director-v2/requirements/_test.txt
The Dask scheduler dashboard was not showing and issuing an error message saying that the library bokeh must be >=2.1.1.
In effect we do have 2.4.3.
Problem was identified and due to the Jinja2 library that was constrained due to some old issue that has already been fixed.
Therefore Jinja2 was upgraded everywhere now.
- #packages before: 1
- #packages after : 1
|   1 | jinja2                    | 2.11.3          | 3.1.2      | **MAJOR**  | 6 | dask-sidecar⬆️⬆️⬆️⬆️</br>director-v2⬆️🧪 |
*Legend*: 
> 🐛 Dask dashboard not showing

- services/dask-sidecar/requirements/_base.txt
- services/storage/tests/unit/test_handlers_simcore_s3.py
fixes dependabot detected issue:
> ⬆️ Dask upgrades

- services/storage/Dockerfile
since git is used in the test requirements it is also needed in the docker image.
> 🐛 add git to storage devel container

- scripts/maintenance/check_consistency_data.py
- scripts/maintenance/consistency/README.md
upgrade the data-consistency script to use the latest version of the file_meta_data table
adds a readme file for easier usage
> ✨ Maintenance/upgrade maintenance script

- api/specs/webserver/openapi-projects.yaml
- packages/models-library/src/models_library/projects_state.py
- services/web/client/source/class/osparc/data/Resources.js
- services/web/client/source/class/osparc/utils/Study.js
- services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
- services/web/server/src/simcore_service_webserver/projects/projects_handlers_crud.py
- services/web/server/src/simcore_service_webserver/projects/projects_utils.py
- services/web/server/tests/unit/isolated/test_projects_utils.py
- services/web/server/tests/unit/with_dbs/02/test_projects_cancellations.py
- services/web/server/tests/unit/with_dbs/02/test_projects_handlers__list.py
- services/web/server/tests/unit/with_dbs/02/test_projects_handlers__open_close.py
- services/web/server/tests/unit/with_dbs/02/test_projects_handlers_crud.py
- tests/e2e/tutorials/tutorialBase.js
- tests/performance/locust_files/locustfile.py
This PR allows to copy any study through the webserver API by replacing:
```POST /projects from_template={template_uuid}```
by
```POST /projects from_study={study_uuid}```
NOTE: Currently this does not provide any progress or anything similar it is just one long request
It is worthy to mention that currently a 10GB study could be copied but not a 100GB.
@odeimaiz some magic is needed for adding this to the frontend. I will try to devise the next PR for changing the API.
relates to ITISFoundation/osparc-issues#558
> ✨ Allow copy of closed studies through same mechanism as templates

- packages/service-library/requirements/_fastapi.in
- packages/service-library/requirements/_fastapi.txt
- packages/service-library/requirements/_test.txt
- requirements/how-to-unify-versions.md
- services/api-server/requirements/_base.txt
- services/catalog/requirements/_base.txt
- services/datcore-adapter/requirements/_base.txt
- services/director-v2/requirements/_base.txt
- services/director-v2/requirements/_test.in
- services/director-v2/requirements/_test.txt
- services/dynamic-sidecar/requirements/_base.txt
- services/dynamic-sidecar/requirements/_test.in
- services/dynamic-sidecar/requirements/_test.txt
- **Remove**s ``async-asgi-testclient`` from ``servicelib/requirements/_fastapi.in``  since it is a **test tool**. Added explicitly in each case when needed
- cleanups requirement listings by propagating changes downstream to services
- #packages before: 5
- #packages after : 0
|   1 | async-asgi-testclient     | 1.4.11          | 🗑️ removed |  | 6 | api-server⬆️</br>catalog⬆️</br>datcore-adapter⬆️</br>director-v2⬆️</br>dynamic-sidecar⬆️</br>service-library🧪 |
|   2 | charset-normalizer        | 2.0.12          | 🗑️ removed |  | 1 | service-library🧪 |
|   3 | multidict                 | 6.0.2           | 🗑️ removed |  | 2 | datcore-adapter⬆️</br>service-library🧪 |
|   4 | requests                  | …
> 🗑️Maintenance/fix servicelib downstream

- packages/service-library/src/servicelib/aiohttp/long_running_tasks/_dependencies.py
- packages/service-library/src/servicelib/aiohttp/long_running_tasks/_routes.py
- packages/service-library/src/servicelib/aiohttp/long_running_tasks/_server.py
- packages/service-library/src/servicelib/aiohttp/long_running_tasks/server.py
- packages/service-library/src/servicelib/fastapi/long_running_tasks/_dependencies.py
- packages/service-library/src/servicelib/fastapi/long_running_tasks/_routes.py
- packages/service-library/src/servicelib/fastapi/long_running_tasks/_server.py
- packages/service-library/src/servicelib/fastapi/long_running_tasks/server.py
- packages/service-library/src/servicelib/long_running_tasks/_models.py
- packages/service-library/src/servicelib/long_running_tasks/_task.py
- packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks.py
- packages/service-library/tests/fastapi/long_running_tasks/test_long_running_tasks.py
- packages/service-library/tests/fastapi/long_running_tasks/test_long_running_tasks_context_manager.py
- packages/service-library/tests/fastapi/long_running_tasks/test_long_running_tasks_routes.py
- packages/service-library/tests/fastapi/long_running_tasks/test_long_running_tasks_task.py
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_tasks.py
- services/web/server/src/simcore_service_webserver/activity/handlers.py
- services/web/server/src/simcore_service_webserver/director_v2_handlers.py
- services/web/server/src/simcore_service_webserver/login/api_keys_handlers.py
- services/web/server/src/simcore_service_webserver/projects/projects_handlers_crud.py
Cleanups ♻️  and docs 📝 long running operation interface
> ♻️ 📝 refactors and docs long running tasks

- services/web/client/source/class/osparc/component/node/BaseNodeView.js
- services/web/client/source/class/osparc/dashboard/Dashboard.js
- services/web/client/source/class/osparc/data/Permissions.js
- services/web/client/source/class/osparc/desktop/SlideshowToolbar.js
- services/web/client/source/class/osparc/desktop/WorkbenchView.js
- services/web/client/source/class/osparc/navigation/NavigationBar.js
- Templates and Services only visible to testers
- Stop and Edit App mode only available to testers
- Show number of outputs next to the output button
USER:
TESTER:
Number of outputs:
> TI Tester functionalities

- tests/e2e/tests/tags.tes.js
> 🐛 e2e: Disable tags test

- tests/e2e/tutorials/ti-plan.js
- tests/e2e/utils/auto.js
- tests/e2e/utils/utils.js
Show key version of the services:
**Bonus**: Fix deleting studies in the TI Plan
> e2e: Show key version of the services

- scripts/mypy.bash
> ⬆️ CI: fix issue when codestyling dy-sidecar

- services/web/client/source/class/osparc/auth/Manager.js
- services/web/client/source/class/osparc/component/tutorial/ti/Slides.js
- services/web/client/source/class/osparc/dashboard/ResourceBrowserBase.js
- tests/e2e/tutorials/ti-plan.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
- Bugfix: Wrong password
- Teach puppeteer to close the Quick Start window
> 🐛 bugfix: Wrong password

- services/catalog/requirements/_test.in
- services/catalog/setup.cfg
- services/catalog/src/simcore_service_catalog/db/repositories/services.py
- services/catalog/tests/unit/with_dbs/test_services_access_rights.py
Fixes bug with auto upgrade of access rights in catalog. (Fixes it but does not make it efficient)
- Fixes ITISFoundation/osparc-simcore#2518
>   🐛 Sort services naturally and adapt test

- ci/github/integration-testing/director-v2.bash
- ci/github/integration-testing/simcore-sdk.bash
- ci/github/integration-testing/webserver.bash
following #3309, an issue was detected in the CI while running integration tests. this fixes it.
> ensure correct images are available in master

- .github/workflows/ci-testing-deploy.yml
- ci/github/unit-testing/dask-task-models-library.bash
- packages/dask-task-models-library/Makefile
- packages/dask-task-models-library/requirements/ci.txt
- packages/service-library/tests/fastapi/test_request_decorators.py
- packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py
- services/director-v2/tests/integration/02/utils.py
- services/director-v2/tests/unit/test_modules_dask_client.py
- trial to fix codeclimate coverage metrics
- improves flakyness of servicelib request cancellation test
> ♻️ Maintenance/reduce flakyness

- services/storage/src/simcore_service_storage/simcore_s3_dsm.py
> 🐛 Fix Unknown label in FilesTree

- packages/models-library/src/models_library/basic_types.py
- services/web/server/src/simcore_service_webserver/products_db.py
- services/web/server/src/simcore_service_webserver/products_events.py
In order to ease product setup (i.e. ``products`` table) this PR enhances the parsing mechanism to overcome some common human mistakes (e.g. using blanks ``""`` strings instead of ``null``).  This also add more log errors to facilitate debugging when issues are detected
Based on issues experienced configuring ``tip-staging``
```
pytest -vv tests/**/test_product*.py
```
> ✨ Improvement: safer product setup

- tests/e2e/portal/2D_Plot.js
- tests/e2e/portal/3D_Anatomical.js
- tests/e2e/portal/3D_EM.js
- tests/e2e/portal/Bornstein.js
- tests/e2e/portal/CC_Human.js
- tests/e2e/portal/CC_Rabbit.js
- tests/e2e/portal/Kember.js
- tests/e2e/portal/Mattward.js
- tests/e2e/portal/Voila.js
- tests/e2e/portal/opencor.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/utils.js
Fixes a bug from https://github.com/ITISFoundation/osparc-simcore/pull/3404
> 🐛 Fix: p2e

- packages/service-library/src/servicelib/aiohttp/monitoring.py
Fix typo checking the X-Simcore_User_Agent  instead of X-Simcore-User-Agent
> 🐛 Fix checking wrong header to filter automatic testing

- .github/CODEOWNERS
- .github/workflows/ci-release.yml
- .github/workflows/ci-staging.yml
A release or pre-release workflows boils down to retagging and existing image (source image) and pushing it back to dockerhub. How the source image is found depends whether the current (pre)release follows from the standard workflow (master -> staging pre-release -> production release)  or from an exceptional hotfix.
Changes in the scripts consider by default the standard workflow except if the checked out commit is the head of a hotfix branch (prefix names are ``hotfix_staging_*`` and ``hotfix_v*`` for staging and production respectively)
- [Failed release](https://github.com/ITISFoundation/osparc-simcore/actions/runs/3180367133/jobs/5183854181): with the previous script, releasing to production from staging-hotfix branches failed to run any of the ``deploy`` jobs. Notice that at least …
> 🔨 Fix/gh-actions scripts for release  workflow

- requirements/constraints.txt
- services/dask-sidecar/requirements/_base.txt
- ``nbconvert``: https://github.com/advisories/GHSA-9jmq-rx5f-8jwq
- ``protobuf``: https://github.com/advisories/GHSA-8gq9-2x98-w8hf
- Could not upgrade since it is constraint by ``pennsieve-python``. Requested update https://github.com/Pennsieve/pennsieve-python/issues/17
> 🔒️⬆️ Maintenance/upgrade vulnerable dependencies

- Makefile
- services/docker-compose-build.yml
Since https://github.com/ITISFoundation/osparc-simcore/pull/3458 the CI fails the ``deploy`` step because it cannot find the ``integration-library`` image to push.
This PR fixes it by adding the image in the services list.
> 🔨 Fix/CI build&deploy jobs with integration-library image

- .github/workflows/ci-testing-deploy.yml
- services/datcore-adapter/src/simcore_service_datcore_adapter/modules/pennsieve.py
Simple PR to re-trigger CI since merged PR #3474 did not start it!
- adds ``typecheck`` step to some jobs
- Fixes ``typecheck`` for ``datcore-adapter`` and some mypy errors:
```
Mypying  osparc-simcore/services/datcore-adapter/src:
src/simcore_service_datcore_adapter/modules/pennsieve.py:100:13: error: Returning Any from function declared to return "PennsieveAuthorizationHeaders"
src/simcore_service_datcore_adapter/modules/pennsieve.py:119:9: error: Returning Any from function declared to return "PennsieveAuthorizationHeaders"
```
> 🔨 Maintenance/typecheck steps in CI

- .github/workflows/ci-testing-deploy.yml
- api/tests/requirements.txt
- packages/dask-task-models-library/requirements/_test.txt
- packages/models-library/requirements/_test.txt
- packages/postgres-database/requirements/_test.txt
- packages/service-integration/requirements/_test.txt
- packages/service-library/requirements/_test.txt
- packages/settings-library/requirements/_test.txt
- packages/simcore-sdk/requirements/_test.txt
- services/api-server/requirements/_base.txt
- services/api-server/requirements/_test.txt
- services/autoscaling/requirements/_test.txt
- services/catalog/requirements/_test.txt
- services/catalog/requirements/_tools.txt
- services/dask-sidecar/requirements/_base.txt
- services/dask-sidecar/requirements/_dask-complete.txt
- services/dask-sidecar/requirements/_test.txt
- services/datcore-adapter/requirements/_test.txt
- services/director-v2/requirements/_base.txt
- services/director-v2/requirements/_test.txt
- services/dynamic-sidecar/requirements/_base.txt
- services/dynamic-sidecar/requirements/_test.txt
- services/storage/requirements/_base.txt
- services/storage/requirements/_test.txt
- services/web/server/requirements/_base.txt
- services/web/server/requirements/_test.txt
- tests/environment-setup/requirements/requirements.txt
- tests/public-api/requirements/_test.txt
- tests/swarm-deploy/requirements/_test.txt
- ⬆️ upgrades to latest ``pytest`` repo-wide
- ⬆️ upgrades to latest ``aiohttp`` repo-wide (support for 3.11. SEE #3489 )
- 🔒️ ``pillow`` vulnerability https://github.com/advisories/GHSA-hr8g-f6r6-mr22
- 🔒️ ``jupyter-core`` vulnerability CVE-2022-39286
| #   | name         | before       | after     | upgrade | count | packages                                                                                                                                                                                                                                                                                                                                              |
| --- | ------------ | ------------ | --------- | ------- | ----- | ------------------------------------------------------------------- …
> ⬆️ 🔒️ Maintenance/week-44: upgrades pytest, aiohttp, jupyter-core and pillow

- .github/workflows/ci-testing-deploy.yml
- packages/postgres-database/tests/docker-compose.yml
- packages/service-library/tests/aiohttp/with_postgres/docker-compose.yml
- scripts/maintenance/consistency/docker-compose.yml
- services/api-server/tests/utils/docker-compose.yml
- services/catalog/docker-compose-extra.yml
- services/director-v2/docker-compose-extra.yml
- services/director/tests/test_producer.py
- services/docker-compose.yml
- services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py
- services/web/server/tests/unit/with_dbs/01/test_studies_dispatcher_studies_access.py
- services/web/server/tests/unit/with_dbs/docker-compose-devel.yml
- services/web/server/tests/unit/with_dbs/docker-compose.yml
upgrades postgresql to 14.5 alpine
⚠️ devops: postgres data must be upgraded before this change is merged.
@mrnicegyu11
> ⬆️ Upgrade postgres to 14.5 alpine⚠️ devops

- .github/workflows/ci-testing-deploy.yml
- packages/pytest-simcore/src/pytest_simcore/helpers/rawdata_fakers.py
- services/web/server/requirements/_base.txt
- services/web/server/requirements/_test.in
- services/web/server/requirements/_test.txt
- services/web/server/requirements/_tools.txt
-  🔨 increased to 25 mins timeout
-  ⬇️ Reverts #3524 in webserver's requirements 
- ✅ Fixes fake for user name (produced strings with multiple dots)
> ✅ Fixing webserver 02 unit test

- services/docker-compose.yml
This reverts commit fc2f166f0e09311abe166268f3102857b9bfc07b.
remove last PR that breaks:
dask-sidecar unit tests
simcore-sdk integration tests
> 🐛 Revert "Revise docker networks (#3543)"

- packages/models-library/README.md
- packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py
Doc and modifies helper scripts while testing against four different deployed registries.  Test results were archived in ``filesrv`` under ``itis-osparc/DEVELOPERS/registries-diagnostics``
- 📝  steps to run diagnostics on deployed registries
- 🔨 fixes scripts to download metadata from registry
- Improving service integration
> 🔨📝 Maintenance/fix registry tests

- services/static-webserver/client/source/class/osparc/component/form/tag/TagItem.js
- services/static-webserver/client/source/class/osparc/ui/list/ClusterListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/OrganizationListItem.js
- tests/e2e/tutorials/jupyterlabs.js
This PR is a continuation of PR https://github.com/ITISFoundation/osparc-simcore/pull/3591
They can be used:
Only some can be patched/deleted:
> ✨ FE: Tags response includes access-rights

- services/docker-compose.yml
Upgrade Traefik to latest version 2.9.5 from 2.5.6
It seems that 2.5.6 was affected with some memory leaks.
see the releases changelogs from traefik
[https://github.com/traefik/traefik/releases](https://github.com/traefik/traefik/releases)
> ⬆️ Upgraded simcore traefik to latest 2.9.5 (⚠️ devops)

- services/static-webserver/client/source/class/osparc/component/widget/SlideBar.js
- services/static-webserver/client/source/class/osparc/dashboard/GroupedToggleButtonContainer.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
- services/static-webserver/client/source/class/osparc/dashboard/SearchBarFilter.js
- services/static-webserver/client/source/class/osparc/navigation/Manuals.js
- services/static-webserver/client/source/class/osparc/ui/window/Dialog.js
> ✨Tutorials Grouping review

- services/web/server/src/simcore_service_webserver/scicrunch/_resolver.py
- services/web/server/src/simcore_service_webserver/scicrunch/service_client.py
- services/web/server/tests/integration/02/scicrunch/test_scicrunch__resolver.py
Currently  ``test_scicrunch_resolves_all_valid_rrids`` fails since scicrunch resolver API does not guarantee returned order. Actions taken:
- Modified the test to check all returned items. 
- Modified ``resolve_rrid``
- We have no way to know which is the right one! For the moment, we still use only the first returned value (i.e. our interface is non-idempotent :-( )
- Added notes on changes over time in the scicruch API and fixes. In future reviews all these comments should be a valuable source to discuss alternative options with k-core.
> ♻️ Changes osparc's scicrunch client to handle changes in scicrunch service API specs

- .pre-commit-config.yaml
- services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py
- services/autoscaling/src/simcore_service_autoscaling/models.py
- services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py
- services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
- services/autoscaling/tests/unit/conftest.py
- services/autoscaling/tests/unit/test_dynamic_scaling_core.py
- services/autoscaling/tests/unit/test_models.py
- services/autoscaling/tests/unit/test_modules_ec2.py
- services/autoscaling/tests/unit/test_utils_docker.py
0. pending services due to missing resources
1. start 1 EC2 instance
2. wait for the instance to run and connect to the docker swarm
3. label the node
4. wait 5 seconds and check if there are still pending services
0. pending services due to missing resources
1. check how many EC2 instances are needed, **start them all at once**
2. wait for the instance**s** to run and connect **them** to the docker swarm
3. label the node**s**
4. wait 5 seconds and check if there are still pending services
this PR unlocks some parallelism, but not all of it. Nevertheless it should allow to create many new instances at once
> ✨ Autoscaling: Allow creation of multiple EC2 instances

- services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py
- services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py
- services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py
- services/autoscaling/tests/unit/test_modules_rabbitmq.py
- services/autoscaling/tests/unit/test_utils_rabbitmq.py
Ensure there are **no more** than the defined amount of instances started
> 🐛♻️ Autoscaling: small fixes

- services/static-webserver/client/source/class/osparc/CookiePolicy.js
- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/info/MergedLarge.js
- services/static-webserver/client/source/class/osparc/info/StudyLarge.js
Before:
After:
Classifiers excluded:
closes https://github.com/ITISFoundation/osparc-issues/issues/818
> 🐛✨ Cookie text, Fit thumbnail height and hide Classifiers from s4l-lite

- api/specs/webserver/components/schemas/group.yaml
- packages/postgres-database/setup.cfg
- packages/postgres-database/src/simcore_postgres_database/models/products.py
- packages/postgres-database/src/simcore_postgres_database/utils_products.py
- packages/postgres-database/tests/products/test_utils_products.py
- services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
- services/web/server/src/simcore_service_webserver/groups.py
- services/web/server/src/simcore_service_webserver/groups_api.py
- services/web/server/src/simcore_service_webserver/groups_handlers.py
- services/web/server/src/simcore_service_webserver/groups_models.py
- services/web/server/src/simcore_service_webserver/products.py
- services/web/server/src/simcore_service_webserver/products_events.py
- services/web/server/src/simcore_service_webserver/products_model.py
- services/web/server/tests/conftest.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_2fa_resend.py
- services/web/server/tests/unit/with_dbs/03/test_products_db.py
- services/web/server/tests/unit/with_dbs/conftest.py
- ✨ New optional ``products.vendor.invitation_url``
- ✨ ``services/webserver`` API  ``0.13.1 → 0.14.0``
- ``GET /groups`` returns an item with ``product`` group 
- ``product.group_id`` returned as well via ``/statics``
- ✨ event to ensure all products have an associated group-id
- MINOR: adds an optional ``products.vendor.invitation_url`` ask @odeimaiz for config upon deploy
- Implements parts of ITISFoundation/osparc-issues#765
- ``Include s4l-lite registered users in product-specific everyone organization`` 
-  ``API: return ``product`` group``
- ``Invitations``
-  ``Add how to get an invitation link to product vendor info in DB. S4L-Lite should point to the zmt website form``
- ``product.group_id=12``:
- This is with ``user_id=1``
- This is with ``user_id=9``
```json
{
"data": {
"me": …
```
> Is765/product group and vendor (🗃️ DB change) 

- services/static-webserver/client/source/class/osparc/About.js
- services/static-webserver/client/source/class/osparc/auth/Manager.js
- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
- services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/PreferencesWindow.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ClustersPage.js
- services/web/server/src/simcore_service_webserver/statics_settings.py
Contact us. This user is not part of the s4llite product-group:
Share:
About:
> ✨ Contact-Us message for "product-stranger" users

- services/web/server/src/simcore_service_webserver/login/_confirmation.py
- services/web/server/src/simcore_service_webserver/login/_constants.py
- services/web/server/src/simcore_service_webserver/login/handlers_change.py
- services/web/server/src/simcore_service_webserver/login/handlers_confirmation.py
- services/web/server/src/simcore_service_webserver/login/routes.py
-  🐛  Fixes password reset: In `` validate_confirmation_and_redirect``, we forgot to unmask confirmation code when returned since it was stored in a ``SecretStr``
- ♻️  some renaming
- Fixes ITISFoundation/osparc-issues#823
- reproduce ITISFoundation/osparc-issues#823
> 🐛 Is823/Fixes password reset

- services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js
- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
In some cases the loading page (Starting, Creating...) was not removed. This PR makes sure that the ones added by the StudyBrowser are removed.
> 🐛 Frontend: Hide Loading Page

- tests/e2e/custom-jest-setup.ts
- tests/e2e/jest.config.js
- tests/e2e/package-lock.json
- tests/e2e/package.json
- tests/e2e/s4l/sim4life-lite.js
- tests/e2e/tests/register.test.js
- tests/e2e/tests/startupCalls.test.js
- tests/e2e/utils/auto.js
This reverts commit afb340fb6d8056b6adbc1aee66a65a869f5f23a8.
Broke e2e. Solution: quoting @odeimaiz ``Next step: Update the itisfoundation/puppeteer:14 base image that is used by gitlab.`` need to be done at the same time.
> Revert "⬆️ Update e2e packages (#3762)"

- services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/OrganizationsPage.js
- services/static-webserver/client/source/class/osparc/info/MergedLarge.js
- services/static-webserver/client/source/class/osparc/ui/list/ListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/MemberListItem.js
There were some issues with promoting/demoting users in an organization. This PR fixes them and improves the logic a bit.
Enhancements:
- Added "demote To Member" feature
- Sort organizations by your role in it and name.
- Sort members by their role and email.
- Red font on "Removing member" option
- Explain each role's permissions
closes https://github.com/ITISFoundation/osparc-issues/issues/833
closes https://github.com/ITISFoundation/osparc-issues/issues/834
> 🐛✨ Bugfixed and enhanced organization member promoting/demoting

- services/static-webserver/client/source/class/osparc/data/model/Node.js
> 🐛 bugfix: Add dynamic service to workbench

- services/static-webserver/client/source/class/osparc/dashboard/GridButtonPlaceholder.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonPlaceholder.js
- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/OrganizationsPage.js
- services/static-webserver/client/source/class/osparc/ui/list/CollaboratorListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/MemberListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/OrganizationListItem.js
- services/static-webserver/client/source/class/osparc/ui/window/Confirmation.js
ITISFoundation/osparc-issues#765
> ✨🐛 Frontend: Improve orgs and members sorting

- packages/postgres-database/requirements/_migration.in
- services/director-v2/src/simcore_service_director_v2/core/events.py
- services/director-v2/src/simcore_service_director_v2/meta.py
- services/migration/Dockerfile
- services/migration/docker/entrypoint.sh
- services/web/server/src/simcore_service_webserver/_meta.py
- services/web/server/src/simcore_service_webserver/application.py
- services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py
- 🐛  Fixes broken migration because requirements were not frozen and sqlalchemy was updated to version 2.0
- ✨ Updates implementation of the ``_meta`` module in different services to force also integration tests to be run in this CI
This is installed in migration now:
```requirements
alembic==1.8.1
certifi==2022.12.7
charset-normalizer==2.1.1
click==8.1.3
docker==6.0.1
greenlet==2.0.1
idna==3.4
Mako==1.2.4
MarkupSafe==2.1.1
multidict==6.0.3
packaging==21.3
psycopg2-binary==2.9.5
pyparsing==3.0.9
requests==2.28.1
simcore-postgres-database @ file:///build
six==1.16.0
SQLAlchemy==1.4.44
tenacity==8.1.0
urllib3==1.26.13
websocket-client==0.59.0
yarl==1.8.2
```
> 🐛 freezes migration service requirements

- services/static-webserver/client/compile.json
- services/static-webserver/client/source/boot/index.html
- services/static-webserver/client/source/class/osparc/Application.js
- services/static-webserver/client/source/class/osparc/NewRelease.js
- services/static-webserver/client/source/class/osparc/auth/LoginPage.js
- services/static-webserver/client/source/class/osparc/auth/LoginPageS4L.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
- services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js
- services/static-webserver/client/source/class/osparc/data/model/Node.js
- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
- services/static-webserver/client/source/class/osparc/store/Support.js
- services/static-webserver/client/source/class/osparc/ui/message/Loading.js
🐛
✨
- ~[ ] Maintenance text updated~
> 🐛✨ Frontend: Fix duplicate bug and last minute changes

- services/static-webserver/client/source/class/osparc/Application.js
- services/static-webserver/client/source/class/osparc/CookiePolicy.js
- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/PreferencesWindow.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/OrganizationsList.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/TagsPage.js
- services/static-webserver/client/source/class/osparc/info/MergedLarge.js
- services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
- services/static-webserver/client/source/class/osparc/info/StudyLarge.js
- services/static-webserver/client/source/class/osparc/info/StudyMedium.js
- services/static-webserver/client/source/class/osparc/navigation/UserMenuButton.js
- services/static-webserver/client/source/class/osparc/product/Utils.js
> ♻️ Frontend refactoring: Product functions

- services/web/server/src/simcore_service_webserver/email_core.py
- services/web/server/src/simcore_service_webserver/templates/osparc/registration_email.jinja2
- services/web/server/tests/unit/with_dbs/03/login/conftest.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_change_email.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_registration.py
- services/web/server/tests/unit/with_dbs/03/login/test_login_reset_password.py
- services/web/server/tests/unit/with_dbs/03/test_email.py
Following last spam issues reported by @oetiker (thx!). email plugin :
- ensures that emails are rendered with a complete html
- removes comments in templates used for testing (legacy)
- cleans up ``templates/osparc/registration_email.jinja2`` html with https://www.htmlcorrector.com/ (and some manual touches) to comply with html standard
- tests extra template rendering and html validation
```cmd
pytest -vv tests/unit/**/test_*email*.py
```
> Enhances email formatting to avoid being flagged as spam

- services/web/server/src/simcore_service_webserver/login/decorators.py
- services/web/server/src/simcore_service_webserver/rest_handlers.py
- services/web/server/src/simcore_service_webserver/socketio/handlers_utils.py
- services/web/server/src/simcore_service_webserver/socketio/plugin.py
- services/web/server/tests/unit/isolated/test_rest.py
- 🐛 Protects ``/v0/scheduled_maintenance`` entrypoint
- @odeimaiz do we need modifications in the front-end? i.e. do do this request after login?
- ♻️ adds tests to entrypoint
- EXTRA: ♻️ 📝 doc and annotations of ``socketio``
- ``cd services/web/server``
- ``make install-dev``
- ``pytest -vvtests/unit/**/test_rest.py``
> 🐛 Fixes ``/scheduled_maintenance`` entrypoint

- packages/service-library/requirements/_fastapi.txt
- packages/service-library/src/servicelib/fastapi/long_running_tasks/_server.py
- requirements/constraints.txt
- ⬆️ Removing fastapi version constrains
- ♻️ Fixing custom exception handler (it should not be initialized in the startup even handler function)
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3896
> Removing fastapi constraints + upgrade

- services/static-webserver/client/source/class/osparc/DownloadLinkTracker.js
> 🐛 Fix: Download Study Data from Firefox

- services/director-v2/src/simcore_service_director_v2/api/routes/clusters.py
- services/director-v2/src/simcore_service_director_v2/core/application.py
- services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
- services/director-v2/src/simcore_service_director_v2/utils/dags.py
- services/osparc-gateway-server/.gitignore
An external gateway may go offline. the director-v2 was outputting misleading error code in this case.
Bonus:
- remove log pollution of aio_pika, aiormq
- remove log pollution when creating computations
- related to https://github.com/ITISFoundation/osparc-issues/issues/885
- related to https://github.com/ITISFoundation/osparc-issues/issues/675
- related to https://github.com/ITISFoundation/osparc-simcore/issues/2945
> 🐛Dask: Handle when gateway is offline

- services/web/server/src/simcore_service_webserver/computation_subscribe.py
- services/web/server/tests/unit/isolated/test_computation_subscribe.py
Fixes an issue where the `node_id` which was missing in the fronted, was added in the wrong place.
- ✨ added regression test
NOTE: 🚑️ can be hotfixed taking into consideration that only the webserver needs to be restarted
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4046
- related to https://github.com/ITISFoundation/osparc-issues/issues/675
> 🐛 fixes broken node progress

- services/osparc-gateway-server/src/osparc_gateway_server/backend/models.py
- services/osparc-gateway-server/src/osparc_gateway_server/backend/utils.py
- services/osparc-gateway-server/tests/unit/test_utils.py
fix an issue where dask gateway function would raise an exception when a task is not found
> 🐛 Dask gateway: Fix raised exception when service or task is not found

- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_scheduler.py
Fixed coroutine which was not awaited, causing some messages to not be displayed.
> 🐛 coroutine not awaited in director-v2

- mypy.ini
- scripts/mypy/requirements.txt
- services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter.py
- services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter_settings.py
- services/storage/src/simcore_service_storage/db.py
- services/storage/src/simcore_service_storage/dsm_cleaner.py
- services/storage/src/simcore_service_storage/s3_client.py
- services/storage/src/simcore_service_storage/settings.py
- services/storage/src/simcore_service_storage/simcore_s3_dsm.py
- services/storage/src/simcore_service_storage/utils.py
relates to https://github.com/ITISFoundation/osparc-issues/issues/675
> ⬆️Maintenance: update mypy to 1.2.0

- Makefile
- packages/dask-task-models-library/src/dask_task_models_library/container_tasks/errors.py
- packages/dask-task-models-library/src/dask_task_models_library/container_tasks/events.py
- packages/dask-task-models-library/tests/container_tasks/test_events.py
- packages/pytest-simcore/src/pytest_simcore/db_entries_mocks.py
- services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
- services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/errors.py
- services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py
- services/dask-sidecar/tests/unit/test_tasks.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
- services/director-v2/src/simcore_service_director_v2/utils/dask_client_utils.py
- services/director-v2/src/simcore_service_director_v2/utils/scheduler.py
- services/director-v2/tests/unit/test_modules_dask_client.py
- services/director-v2/tests/unit/with_dbs/conftest.py
- services/director-v2/tests/unit/with_dbs/test_api_route_computations.py
- services/osparc-gateway-server/src/osparc_gateway_server/backend/osparc.py
- services/storage/tests/unit/test_handlers_datasets.py
- services/storage/tests/unit/test_handlers_files.py
- services/storage/tests/unit/test_handlers_locations.py
- services/storage/tests/unit/test_handlers_simcore_s3.py
- services/storage/tests/unit/test_s3_client.py
- services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py
- services/web/server/src/simcore_service_webserver/computation_subscribe.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
- services/web/server/src/simcore_service_webserver/projects/projects_db.py
- services/web/server/tests/conftest.py
- services/web/server/tests/unit/with_dbs/01/test_comp_tasks_listening_task.py
- service_started metrics is still handled
- service state change is still handled
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/3991
> ♻️🐛Computational backend: reduce load on osparc services

- services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py
The call to /study was missing a call to the director-v2 to update the comp_tasks table in the DB which is used by the dynamic-sidecar to push/pull data to ports.
Somehow the ordering of calls seems to have change and the need to have the database ready seems to come earlier than ever before.
- https://github.com/ITISFoundation/osparc-issues/issues/675
> 🐛/study entrypoint missing call to update comp_tasks DB

- services/static-webserver/client/source/class/osparc/component/share/Collaborators.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
Shows template's permalink. 
- Follows https://github.com/ITISFoundation/osparc-simcore/pull/4008
- fixes https://github.com/ITISFoundation/osparc-issues/issues/806
> permalink for templates

- services/static-webserver/client/source/class/osparc/component/filter/CollaboratorToggleButton.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/data/model/NodeProgressSequence.js
- tests/e2e/tutorials/tutorialBase.js
This PR adds a second plus button for the TI product. In order to show them, the corresponding templates need to be available: the first plus button will point to a template labeled "TI Planning Tool", while for the second one "mTI Planning Tool" is required.
Bonus:
related to https://github.com/ITISFoundation/osparc-issues/issues/831
> ✨ TIP v2: 2 plus buttons

- services/web/server/tests/unit/with_dbs/02/test_projects_handlers__list.py
- services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py
- services/web/server/tests/unit/with_dbs/03/tags/conftest.py
- services/web/server/tests/unit/with_dbs/03/test_project_db.py
- services/web/server/tests/unit/with_dbs/conftest.py
> ♻️ Maintenance: move some tests to webserver 03

- services/web/server/requirements/_base.txt
> ⬆️Upgrade socketio to 5.8.0

- tests/public-api/requirements/ci.txt
Install the `osparc` python package available on Pypi rather than taking `master` from https://github.com/ITISFoundation/osparc-simcore-clients. *This is a temporary fix* which will be corrected once that repo has been setup properly.
Fixes [this](https://github.com/ITISFoundation/osparc-simcore/actions/runs/5319311892/jobs/9631979977) issue.
> 🐛 take osparc package from pypi

- services/static-webserver/client/source/class/osparc/AnnouncementTracker.js
- services/static-webserver/client/source/class/osparc/file/FilePicker.js
- services/web/server/src/simcore_service_webserver/studies_dispatcher/_projects.py
> 🐛 Bugfix: FP extractLabelFromLink + Announcement Validator

- services/migration/Dockerfile
increase the number of retries before defining the migration service as unhealthy
@mrnicegyu11 the memory limitations in master 64MB were to stringent.
> 🐛 increase time before killing migration app

- .ruff.toml
- .vscode/extensions.json
- .vscode/settings.template.json
- Makefile
- requirements/devenv.txt
This linter shall at some point replace PyUpgrade, Flake8, and possibly Pylint at some point (although that is not the case yet). It has also some duplications with codeclimate. Nevertheless it is really supermega fast. It goes over the whole src code (without tests folders for now) in a few seconds. Also it has a pre-commit option that we could add soon.
Once we refine the parameters, we can make use of it and remove some tools. 
```bash
make devenv
make ruff
```
> ✨Maintenance: add Ruff

- services/static-webserver/client/source/class/osparc/Application.js
- services/static-webserver/client/source/class/osparc/component/node/UpdateResourceLimitsView.js
- services/static-webserver/client/source/class/osparc/data/Permissions.js
- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
- services/static-webserver/client/source/class/osparc/store/Store.js
Remove from frontend the hardcoded ``services.all.updateLimits`` permission and ask the backend instead for the more flexible ``override_services_specifications`` one.
Flag set to false:
Flag set to true:
closes https://github.com/ITISFoundation/osparc-simcore/issues/4435
closes https://github.com/ITISFoundation/osparc-simcore/issues/4436
related to https://github.com/ITISFoundation/osparc-issues/issues/618
> ✨ Frontend: ask backend for ``override services specifications``

- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- Classic TI
- Multi-channel TI
- Phase-modulated TI
related to https://git.speag.com/oSparc/ti-solutions/-/issues/21
> 🎨 TIP v2: 3 plus buttons

- services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
Fixes the following bug. I don't really know how to reproduce it so I can't post a before and after animation...
closes https://github.com/ITISFoundation/osparc-issues/issues/1008
> 🐛 Frontend: pageContext property might not be yet initialized

- services/dask-sidecar/src/simcore_service_dask_sidecar/utils.py
> 🐛Dask-sidecar: fix how GPUs are detected

- services/dynamic-sidecar/Dockerfile
Somehow this was merged to master and the dynamic-sidecar image did not build any longer.
I'm not sure how this ended up to master.
> 🐛 fixes broken image build in master

- services/static-webserver/client/source/class/osparc/component/node/StartStopButton.js
- services/static-webserver/client/source/class/osparc/data/model/Node.js
- services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
As requested, a Start button is also shown in the Service Options:
closes https://github.com/ITISFoundation/osparc-simcore/issues/4463
> 🎨 Feature: Stop, and Start, buttons in service options

- packages/models-library/src/models_library/rabbitmq_messages.py
Next steps:
- connect dynamic services @GitHK 
- connect computational services @sanderegg 
- solves https://github.com/ITISFoundation/osparc-issues/issues/1019
> ✨Resource usage tracking: RabbitMQ messages 

- services/static-webserver/client/source/class/osparc/component/notification/RibbonNotification.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
Renames:
Announcement:
related to https://github.com/ITISFoundation/osparc-issues/issues/831
> 🎨 TIP v2: Last aesthetics changes

- services/web/server/src/simcore_service_webserver/projects/lock.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
- services/web/server/src/simcore_service_webserver/storage/_handlers.py
- services/web/server/tests/unit/with_dbs/03/test_storage_handlers.py
Fixes the issue where files could not be uploaded through the frontend anymore.
The issue arose from https://github.com/ITISFoundation/osparc-simcore/pull/4490
> 🐛Uploading files works again

- services/web/server/src/simcore_service_webserver/wallets/_api.py
- services/web/server/src/simcore_service_webserver/wallets/_db.py
- services/web/server/src/simcore_service_webserver/wallets/_handlers.py
- services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py
- 🐛 bugfix on wallet update endpoint
> 🐛 bugfix on wallet update

- services/static-webserver/client/source/class/osparc/component/study/ResourceSelector.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Utils.js
- services/static-webserver/client/source/class/osparc/desktop/wallets/WalletsList.js
> 🎨 Wallets: some defaults

- .github/ISSUE_TEMPLATE/4_pre_release.yml
- improve release to staging template
> 🎨Release workflow improvements

- services/static-webserver/client/source/class/osparc/desktop/credits/BuyCredits.js
- services/static-webserver/client/source/class/osparc/desktop/credits/WalletsMiniViewer.js
- services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
- services/static-webserver/client/source/class/osparc/utils/Utils.js
This PR enabled the Wallets on staging
> 🎨 Feature: Wallets on staging

- packages/service-library/src/servicelib/file_utils.py
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py
Somehow builds in master are failing due to mypy errors. Not sure how these got here, but now they are removed.
> 🐛 Unlocks the deploy of builds on master

- tests/e2e/tutorials/ti-plan.js
- tests/e2e/tutorials/tutorialBase.js
- tests/e2e/utils/auto.js
This PR teaches puppeteer how to go through the TIP v2 workflow
> e2e: Update TIP test

- services/director-v2/src/simcore_service_director_v2/models/comp_runs.py
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4637
> 🐛Handle case where metadata in comp_runs are NULL

- packages/models-library/src/models_library/api_schemas_webserver/catalog.py
- services/web/server/src/simcore_service_webserver/catalog/_handlers.py
- services/web/server/src/simcore_service_webserver/wallets/_db.py
- Response for `list_services` times-out in some computers due to `assert parse_obj_as(list[ServiceGet], data_array) is not None  # nosec` check. Removed
- Fixes code duplication detected by sonarcloud https://sonarcloud.io/component_measures?metric=new_duplicated_lines_density&selected=ITISFoundation_osparc-simcore%3Apackages%2Fmodels-library%2Fsrc%2Fmodels_library%2Fapi_schemas_webserver%2Fcatalog.py&view=list&pullRequest=4626&id=ITISFoundation_osparc-simcore
> ♻️ Removes assert w/ validator and fixes code redundancy

- services/director-v2/src/simcore_service_director_v2/utils/db.py
- services/director-v2/tests/unit/test_models_comp_tasks.py
- services/director-v2/tests/unit/test_utils_db.py
fixes the issue where a task that disappeared from the dask-scheduler (and reported as having UNKNOWN state) was not properly converted to our db values (which follow StateType enum).
fixes problem that shows such as
```bash
log_level=ERROR | log_timestamp=2023-08-25 08:42:59,657 | log_source=simcore_service_director_v2.modules.comp_scheduler.background_task:scheduler_task(33) | log_uid=None | log_msg=Unexpected error in computational scheduler task, restarting scheduler now...\nTraceback (most recent call last):\n  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/comp_scheduler/background_task.py", line 21, in scheduler_task\n    await scheduler.schedule_all_pipelines()\n  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/ …
```
> 🐛Director-v2: Fix UNKNOWN state not correctly converted

- packages/models-library/src/models_library/rabbitmq_messages.py
relates to https://github.com/ITISFoundation/osparc-simcore/issues/4674
> ✨Tracking messages get a discriminator

- packages/models-library/src/models_library/rabbitmq_messages.py
- services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
- services/director-v2/src/simcore_service_director_v2/models/comp_runs.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
- services/director-v2/src/simcore_service_director_v2/utils/rabbitmq.py
- services/director-v2/tests/unit/with_dbs/test_utils_rabbitmq.py
- ✨ Add new fields in the RabbitResourceTrackingStartedMessage
relates https://github.com/ITISFoundation/osparc-simcore/issues/4674
> ✨ modify rabbit resource tracking started message

- .github/CODEOWNERS
- services/docker-compose-build.yml
- services/docker-compose-deploy.yml
- Fixes CI https://github.com/ITISFoundation/osparc-simcore/actions/runs/6011252354/job/16307897989 in master 
- Fails to push new `payments` service created in #4676
- Updates ownership
- Updates image labels
> 🔨 Fixes deploy push payment service

- services/storage/src/simcore_service_storage/application.py
- services/storage/src/simcore_service_storage/s3_client.py
- services/storage/src/simcore_service_storage/simcore_s3_dsm.py
Storage was keeping a db connection while it's not required and it was timing out. This is no longer the case
> 🐛 storage better logging

- services/storage/src/simcore_service_storage/simcore_s3_dsm.py
Allows to better debug what is happening in storage when copying projects
> ♻️ adding logs to project copy in storage

- packages/models-library/src/models_library/api_schemas_webserver/projects_nodes.py
- packages/service-library/src/servicelib/rabbitmq/_client.py
- services/storage/src/simcore_service_storage/simcore_s3_dsm.py
- shows the correct number of files when copying projects
- adds some notes on why the lock on storage happened. we might still have problem if many copies are started concurrently though
> 🐛Storage: Improve documentation and fix number of files shown to be copied

- services/storage/src/simcore_service_storage/application.py
reduce logging impact of botocore, aiobotocore, aio-pika, aiormq, sqlalchemy
> ♻️Storage: Reduce noisy loggers impact

- packages/pytest-simcore/src/pytest_simcore/docker_compose.py
- packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker.py
Due to removal of module scoped fixtures for the FileStash service in *utils_docker.py* environment variables were set to run docker compose config.
This was done with the assumption that these environment variables were *added* to the current ones which was wrong. Therefore the variables are now fetched from the environment and the additional environment variables added if needed.
> 🐛Fix tests failing issue with newer docker compose (>2.21.0)

- services/director-v2/src/simcore_service_director_v2/core/settings.py
- services/docker-compose-build.yml
- ♻️ adjust container labels to the new standard
- replace `org.label-schema.vcs-ref` with `org.opencontainers.image.revision`
> ♻️ adjust container labels to new standard

- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/desktop/credits/BuyCredits.js
- services/static-webserver/client/source/class/osparc/store/Store.js
related to https://github.com/ITISFoundation/osparc-issues/issues/1027
> ✨ Frontend: Listen to Credits Updated WS event

- packages/service-library/src/servicelib/file_utils.py
- packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py
Created directories are now removed after each test.
- https://github.com/ITISFoundation/osparc-issues/issues/1108
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4801
> 🐛 Fix flaky test (CI worker ran out of space)

- .github/PULL_REQUEST_TEMPLATE.md
- 🔨 add new helper comment to the GitHub PR template
> 🔨 add new helper comment to the GitHub PR template 

- scripts/release/monitor/monitor_release/cli.py
- scripts/release/monitor/monitor_release/settings.py
> 🔨 fix release monitoring cli

- services/static-webserver/client/source/class/osparc/dashboard/StudyThumbnailExplorer.js
- services/static-webserver/client/source/class/osparc/editor/ThumbnailSuggestions.js
- services/static-webserver/client/source/class/osparc/info/MergedLarge.js
- services/static-webserver/client/source/class/osparc/info/StudyLarge.js
- services/static-webserver/client/source/class/osparc/product/Utils.js
> 🐛 Fix: Mesh viewer

- services/static-webserver/client/source/class/osparc/po/Invitations.js
This PR follows https://github.com/ITISFoundation/osparc-simcore/pull/4850.
It simply exposes one more option for the invitation creation.
> ✨ Frontend: expose extra credits in the invitation

- services/static-webserver/client/source/class/osparc/study/TierButton.js
Show ``Unit extra info`` on Tier button. We expect these dictionary to be short key short value style, so that it fits on the Tier card:
> 🎨 Show ``Unit extra info`` on Tier button

- services/static-webserver/client/source/class/osparc/auth/LoginPageFlex.js
> 🐛 Fix: Buggy flexible Login Page

- services/static-webserver/client/source/class/osparc/auth/LoginPage.js
- services/static-webserver/client/source/class/osparc/auth/LoginPageFlex.js
- services/static-webserver/client/source/class/osparc/auth/ui/RegistrationView.js
After a resize, when reloading the different login pages in the stack, we used to recreate them loosing context (which page was selected) in the stack. This PR fixes it by not recreating the views and the stack after switching to the compact view:
> 🐛 Fix: Flexible Login Page

- services/static-webserver/client/source/class/osparc/auth/ui/RequestAccount.js
- services/static-webserver/client/source/class/osparc/data/Permissions.js
- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/OneTimePayment.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Overview.js
- services/static-webserver/client/source/class/osparc/navigation/UserMenuButton.js
- services/static-webserver/client/source/class/osparc/resourceUsage/OverviewTable.js
- services/static-webserver/client/source/class/osparc/store/Store.js
- services/static-webserver/client/source/class/osparc/utils/Utils.js
Improvements to the Usage Table:
> ✨ Usage overview: Improvements to the table

- services/static-webserver/client/source/class/osparc/desktop/credits/ProfilePage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenter.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenterWindow.js
- services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
- services/static-webserver/client/source/class/osparc/notification/NotificationsButton.js
- services/static-webserver/client/source/class/osparc/resourceUsage/OverviewTable.js
I never saw it in any of our deployments, but the e2e test, maybe because old the browser?, fails when starting a s4l-lite project. I believe/hope that this minor change fixes it.
> 🐛 Fix s4l-lite test

- README.md
- services/api-server/README.md
- services/director-v2/README.md
Add instruction on how to perform dev build.
Clean up the READMEs of api-server and director-v2 services
N/A
Read the READMEs ;-)
N/A
> 📝 Improve dev readme

- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Activity.js
- services/static-webserver/client/source/class/osparc/desktop/credits/BuyCredits.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Summary.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Transactions.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Usage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenter.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenterWindow.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Utils.js
- services/static-webserver/client/source/class/osparc/desktop/credits/WalletsMiniViewer.js
- services/static-webserver/client/source/class/osparc/desktop/paymentMethods/PaymentMethods.js
- services/static-webserver/client/source/class/osparc/navigation/UserMenuButton.js
- services/static-webserver/client/source/class/osparc/notification/NotificationUI.js
Hide (and do not make requests that will fail) wallet actions to users with only read access.
User with WRITE access:
User with READ access only:
> 🐛 Hide wallet actions to users with only read access

- services/static-webserver/client/source/class/osparc/WindowSizeTracker.js
- services/static-webserver/client/source/class/osparc/auth/LoginPage.js
- services/static-webserver/client/source/class/osparc/auth/ui/RequestAccount.js
- services/static-webserver/client/source/class/osparc/navigation/LogoOnOff.js
- services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
- services/static-webserver/client/source/class/osparc/product/Utils.js
- services/static-webserver/client/source/class/osparc/ui/basic/Logo.js
- services/static-webserver/client/source/class/osparc/ui/basic/LogoWPlatform.js
Show long SIM4LIFE logo on large screens and switch to the short S4L version in small screens:
> 🎨 Long flexible SIM4LIFE logo

- services/static-webserver/client/source/class/osparc/Preferences.js
- services/static-webserver/client/source/class/osparc/data/Roles.js
- services/static-webserver/client/source/class/osparc/desktop/MainPage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Activity.js
- services/static-webserver/client/source/class/osparc/desktop/credits/BuyCredits.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Summary.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Transactions.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Usage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenter.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UserCenterWindow.js
- services/static-webserver/client/source/class/osparc/desktop/credits/Utils.js
- services/static-webserver/client/source/class/osparc/desktop/credits/WalletsMiniViewer.js
- services/static-webserver/client/source/class/osparc/desktop/paymentMethods/PaymentMethods.js
- services/static-webserver/client/source/class/osparc/desktop/wallets/WalletsList.js
- services/static-webserver/client/source/class/osparc/store/Store.js
- services/static-webserver/client/source/class/osparc/study/StudyOptions.js
The application has a Context Wallet defined in its Store, and the Credits Indicator and User Center are bound to it.
- if there is NO study open, the favourite wallet is the Context Wallet
- if there is a study open with a Wallet attached, this wallet is the Context Wallet
> ✨ Context Wallet throughout the Application

- services/web/server/src/simcore_service_webserver/director_v2/_handlers.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
- services/web/server/src/simcore_service_webserver/wallets/_api.py
- 🐛 fix wrong populating variables
- Note: e2e test caught it, i am planning to add an integration test which would catch it sooner. Now this should unblock the master.
> 🐛 fix wrong populating variables

- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/desktop/credits/AutoRecharge.js
> 🐛 Demo fixes

- .github/CODEOWNERS
- CITATION.cff
- docs/coding-conventions.md
- 📝 Propose naming conventions for  factory fixtures (See `CC3`). Please comment!
- 📝 updates citation list for new contributors
- 🔨updates CODEOWNERSHIP of front-end (after @odeimaiz left for :palm_tree: ). **REMEMBER**: @ignapas and @jsaq007 own now (i.e. always **required** to review) all changes in the front-end
None
None
NOne
> 🔨 📝 Maintenance: code-ownership, citations and conventions [skip CI]

- services/invitations/openapi.json
- services/invitations/requirements/_base.txt
- services/invitations/requirements/_test.txt
- services/invitations/requirements/_tools.txt
Upgrades all dependencies of `invitations` services
- #packages before: 41
- #packages after : 46
|   1 | aio-pika                  | 9.1.2           | 9.3.0      | *minor*    | 1 | invitations⬆️ |
|   2 | aiofiles                  | 22.1.0          | 23.2.1     | **MAJOR**  | 1 | invitations⬆️ |
|   3 | aiohttp                   | 3.8.5           | 3.8.6      |            | 1 | invitations⬆️ |
|   4 | aiormq                    | 6.7.6           | 6.7.7      |            | 1 | invitations⬆️ |
|   5 | anyio                     | 3.6.2           | 4.0.0      | **MAJOR**  | 2 | invitations⬆️🧪 |
|   6 | arrow                     | 1.2.3           | 1.3.0      | *minor*    | 1 | invitations⬆️ |
|   7 | …
> ⬆️ Maintenance: upgrades `invitations` service requirements

- .github/workflows/ci-staging.yml
change the regex for staging to allow for numbers in the sprint name
> 🎨 releasing process: allow sprint names with numbers

- .github/ISSUE_TEMPLATE/4_pre_release.yml
- .github/ISSUE_TEMPLATE/5_release.yml
Operations, in this order are better.
> ♻️ Improve release templates

- .github/PULL_REQUEST_TEMPLATE.md
These changes introduce a reminder and a link to the documentation about updating ENV variables in `repo.config`s
* https://github.com/ITISFoundation/osparc-ops-environments/issues/404
* https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/136
> 📝 Add update env reminder

- services/clusters-keeper/src/simcore_service_clusters_keeper/core/settings.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters_management_core.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/modules/ec2.py
- services/clusters-keeper/tests/unit/conftest.py
- services/clusters-keeper/tests/unit/test_modules_clusters.py
- services/clusters-keeper/tests/unit/test_modules_clusters_management_core.py
- services/clusters-keeper/tests/unit/test_modules_ec2.py
- services/clusters-keeper/tests/unit/test_rpc_ec2_instances.py
When the clusters-keeper shutdown a computational cluster it will now ensure that all created cluster "workers" are also shutdown and prevent EC2 instance leaking.
> ✨Clusters keeper: shutdown all workers on cluster close

- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_utils.py
This PR sets a ratio for the RAM margin of 10%.
for example a g4dn.2xlarge advertises 32GiB but has only 30GiB (6.25%)
a g4dn.xlarge advertises 16Gib but has only 15Gib (6.25%)
> ♻️ Computational backend: set RAM margin to 10%

- services/director-v2/tests/unit/with_dbs/test_api_route_computations.py
fixes failing test due to https://github.com/ITISFoundation/osparc-simcore/pull/5013
> 🐛Director-v2: fix unit test

- packages/postgres-database/src/simcore_postgres_database/utils_projects_nodes.py
- packages/postgres-database/tests/test_utils_projects_nodes.py
- services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
- services/director-v2/src/simcore_service_director_v2/models/comp_runs.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_runs.py
- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/projects.py
- services/director-v2/src/simcore_service_director_v2/modules/db/repositories/projects_metadata.py
- services/director-v2/src/simcore_service_director_v2/utils/dask.py
- services/director-v2/src/simcore_service_director_v2/utils/rabbitmq.py
- services/director-v2/tests/unit/with_dbs/test_modules_db_repositories_projects.py
In the use-case where a user starts a computational pipeline from a s4l node, the backend creates a new project.
The resource usage UI shows a completely different study and node.
This PR changes this by passing the "parent" node name and study name to RUT.
This will then show the sim4life project/node name in the Usage dialog.
NOTE: this does not change the Node ID or Study ID. This would cause a lot of trouble for tracing jobs in the logs, and/or break many things in the backend.
This is a first step. Next ones might be: showing the logs of the "sub"computational pipelines in the log UI, showing the state in the dashboard.
> ✨Computational backend: Trace parent node

- tests/e2e/utils/utils.js
After the latest Dashboard UI update, the function used by Puppeteer to select the correct service card was not working anymore.
The fix could potentially fix many other tests.
None. E2E fix.
> 🐛 Puppeteer fix: Card selection by title

- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_scheduler_utils.py
For some users service stop immediately after starting. I require more logs to peak into what is happening just before they shut down.
> ♻️ Add debug logs for unknown issue

- services/static-webserver/client/source/class/osparc/desktop/credits/UsageTable.js
Only show “credits” column in usage table if wallets/payments are activated in the product
- resolves https://github.com/ITISFoundation/osparc-issues/issues/1182
> 🎨 Only show “credits” col in usage table if wallets

- services/static-webserver/client/source/class/osparc/desktop/MainPageDesktop.js
Resolves UI: PO center should be visible in all products if user has this role #5052
- resolves #5052
> 🐛 PO center should be visible in all products #5052

- services/static-webserver/client/source/class/osparc/auth/ui/RequestAccount.js
Address info required in request form
- closes https://z43.fogbugz.com/f/cases/189875/New-feedback-login-page-address
none
> 🎨  Adds address+country as required in the request form

- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
After some observations, it seems that sometimes the computational pipeline gets locked in WAITING_FOR_CLUSTER and never stops.
This PR brings a 10 minutes timeout that will eventually FAIL a pipeline after its state never moved out of WAITING_FOR_CLUSTER by auto-stopping the tasks.
This should not prevent from destroying clusters as these would be re-created on the fly and the state would change again before the 10 minutes threshold is reached.
> ✨Computational backend: timeout pipeline if WAITING_FOR_CLUSTER state takes more than 10 minutes

- packages/service-library/src/servicelib/background_task.py
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py
It gets very hard to debug, with all the extra logs in the sidecars. This will help greatly and reduce confusion for everybody.
> ♻️ disable noisy logger for background tasks form dynamic sidecar

- packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_client.py
- packages/simcore-sdk/tests/unit/test_node_ports_common_storage_client.py
Storage client inside nodeports fails to reach storage service sometimes. Adding retries to mitigate he situation and alight the communication with all our other services.
> 🎨 Add retries to storage client inside nodeports

- tests/e2e-playwright/requirements/ci.txt
- Create a Make recipe `install-ci` in the e2e-playwright tests. Should fix issues [here](https://git.speag.com/oSparc/e2e-backend/-/pipelines?page=1&scope=all&ref=e2e-osparc-staging.speag.com)
> 🐛 Add `install-ci` Make recipe in playwrigt e2e tests

- services/static-webserver/client/source/class/osparc/dashboard/GridButtonPlaceholder.js
Bring the duplicate progress bar back as this was causing error which could have prevented rendering.
Relates to https://z43.manuscript.com/f/cases/190810/New-feedback-Studies-disappear
Duplicate a large study and refresh the page
PASS: If this commit fixes the issue you should see all studies in the dashboard including the new duplicate loading
FAIL: All studies in the dashboard disappear
>  🐛 Bring back progress for duplicating studies

- .github/workflows/ci-testing-deploy.yml
- services/director-v2/src/simcore_service_director_v2/api/routes/dynamic_services.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py
- services/director-v2/tests/integration/02/conftest.py
- services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py
- services/web/server/src/simcore_service_webserver/projects/_project_nodes_pricing_unit_handlers.py
- services/web/server/src/simcore_service_webserver/projects/db.py
- services/web/server/src/simcore_service_webserver/projects/exceptions.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
- services/web/server/src/simcore_service_webserver/users/_preferences_api.py
- services/web/server/tests/unit/with_dbs/02/test_project_nodes_pricing_unit_handlers.py
This PR ensures that service resources in _projects_nodes_ are properly setup in case of a product where EC2 instances may be selected.
Also fixes an issue in director-v2 that was assigning the EC2 type to the label instead of the placement constraints
> ✨Dynamic backend: Allow the use of EC2 instance types and properly fuse their resources

- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/theme/Appearance.js
- services/static-webserver/client/source/class/osparc/theme/mixin/Color.js
Fixes the issue where, if a user clicked on the icons in the footer of the card the open button had no impact.
Minor UI change with the hover effect of the cards based on feedback from @ignapas (Thanks I hope this is better)
- fixes https://z43.manuscript.com/f/cases/190686/New-feedback-pressing-the-Open-button-in
> 🐛 Studies cant be opened

- .github/workflows/ci-testing-deploy.yml
- ci/github/system-testing/e2e-playwright.bash
- services/static-webserver/client/source/class/osparc/workbench/WorkbenchUI.js
- tests/e2e-playwright/Makefile
- tests/e2e-playwright/requirements/_test.in
- tests/e2e-playwright/requirements/_test.txt
- tests/e2e-playwright/requirements/_tools.txt
- tests/e2e-playwright/tests/conftest.py
- tests/e2e-playwright/tests/sleepers/conftest.py
- tests/e2e-playwright/tests/sleepers/sleepers.py
- tests/e2e-playwright/utils/wait_for_services.py
This PR adds a github CI step to run the sleeper:2.1.6 (current latest version) directly as an additional system test.
Next steps will be to remove the CI steps run via puppeteer.
- look into e2e-playwright.bash
> ✨E2E: add playwright sleepers test in CI

- services/static-webserver/client/source/class/osparc/auth/Manager.js
- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/desktop/MainPageHandler.js
- services/static-webserver/client/source/class/osparc/desktop/organizations/MembersList.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ClustersPage.js
- services/static-webserver/client/source/class/osparc/desktop/wallets/MembersList.js
- services/static-webserver/client/source/class/osparc/filter/CollaboratorToggleButton.js
- services/static-webserver/client/source/class/osparc/filter/OrganizationMembers.js
- services/static-webserver/client/source/class/osparc/filter/OrganizationsAndMembers.js
- services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyUpdate.js
- services/static-webserver/client/source/class/osparc/share/Collaborators.js
- services/static-webserver/client/source/class/osparc/share/NewCollaboratorsManager.js
- services/static-webserver/client/source/class/osparc/store/Store.js
- services/static-webserver/client/source/class/osparc/utils/Utils.js
* Handles the the situation where the app failed to load when a user didn't have a first or last name set.
- fixes  #5244 
- Change the user first and last name in the database to null
- Login with the user 
If the page loads normally this issue should be resolved.
> 🐛 Handle nullables for firstName lastName in me response #5244

- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py
- services/dynamic-sidecar/tests/unit/test_core_docker_utils.py
Refactor progress pulling so that it can never fail.
Added edge case causing us issues.
> 🐛 Fix pull progress issues

- packages/service-library/src/servicelib/rabbitmq/_utils.py
In case `ChannelPreconditionFailed` is raised when running `rabbit_client.subscribe` generated via `servicelib/rabbitmq/_utils.py:declare_queue`. Check notes at the following link: https://github.com/ITISFoundation/osparc-simcore/blob/master/packages/service-library/src/servicelib/rabbitmq/_utils.py#L74-L86
```python
ERROR: [2024-02-02 13:39:13,364/MainProcess] [uvicorn.error:send(121)]  -  Traceback (most recent call last):
File "/home/scu/.venv/lib/python3.10/site-packages/aiormq/channel.py", line 182, in rpc
result = await countdown(self.rpc_frames.get())
File "/home/scu/.venv/lib/python3.10/site-packages/aiormq/tools.py", line 95, in __call__
return await coro
File "/usr/local/lib/python3.10/asyncio/queues.py", line 159, in get
await getter
asyncio.exceptions.CancelledError
During …
```
> ✨ added notes with actions to take if rabbitmq queues are no longer created

- services/static-webserver/client/source/class/osparc/ErrorPage.js
- resolves https://github.com/ITISFoundation/osparc-issues/issues/1252
> 🎨 UI: Changed title of error page 

- Makefile
- services/docker-compose-build.yml
This will make the CI build and publish the docker images once again.
Renames accidentally renamed `dynamic-scheduer` image.
> 🐛 Fixing broken CI builds

- packages/models-library/src/models_library/errors.py
- packages/service-library/src/servicelib/redis.py
- packages/service-library/tests/test_redis.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rest/_dependencies.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rest/_health.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/application.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/settings.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/redis.py
- services/dynamic-scheduler/tests/conftest.py
- services/dynamic-scheduler/tests/unit/api_rest/test_api_rest__health.py
- services/dynamic-scheduler/tests/unit/api_rest/test_api_rest__meta.py
- services/dynamic-scheduler/tests/unit/api_rpc/test_api_rpc__services.py
- services/dynamic-scheduler/tests/unit/test_services_rabbitmq.py
- services/dynamic-scheduler/tests/unit/test_services_redis.py
In case the the `RabbitMQ` or `Redis` have errors, the health of the `dynamic-scheduler` fails causing a service restart.
- ✨Added health check task to `RedisClientSDK` that can be used by other services as well.
- ✨`dynamic-schduler` is not connected to `Redis`
> ✨ `dynamic-scheduler` healthcheck now restart the service

- services/docker-compose-deploy.yml
correcting expected image name when pushing images.
> 🐛 fish push step of CI

- services/api-server/src/simcore_service_api_server/services/log_streaming.py
- Introduce additional logging in the callback passed by the api-server to the rabbitMQ client. The purpose with this is to figure out if the missing messages (https://github.com/ITISFoundation/osparc-issues/issues/1254) messages from the rabbit enters this callback but don't get acknowledged or if they simply never reach the rabbitmq client.
- https://github.com/ITISFoundation/osparc-issues/issues/1254
> ⚗️ Add DEBUG log messages in the callback the API-server passes to the RabbitMQ client

- packages/settings-library/src/settings_library/node_ports.py
- packages/settings-library/src/settings_library/utils_service.py
- packages/settings-library/tests/test_node_ports_settings.py
- packages/settings-library/tests/test_utils_service.py
- packages/simcore-sdk/tests/unit/test_storage_client.py
- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py
- services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs_sidecar.py
- services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py
- services/dynamic-sidecar/tests/unit/test_core_settings.py
Allows to configure the endpoint to use `https` instead of the default `http`.
- https://github.com/ITISFoundation/osparc-simcore/pull/5361
> ✨ added `STORAGE_SECURE` to `StorageAuthSettings`

- packages/simcore-sdk/src/simcore_sdk/node_ports_common/_filemanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_client.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_endpoint.py
- packages/simcore-sdk/tests/unit/test_storage_client.py
Inside `simcore-sdk` a few endpoints were called without providing authorisation.
> 🐛 Adds auth to `simcore_sdk` endpoints that were missing it

- services/api-server/src/simcore_service_api_server/api/errors/httpx_client_error.py
- services/api-server/src/simcore_service_api_server/services/_service_exception_handling.py
- ensure exception message is logged when receiving bad status from backend
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/5375
> improve logging when raising exception coming from backend services

- packages/postgres-database/setup.py
- services/dynamic-sidecar/docker/boot.sh
This PR removes the alias of ```simcore-service``` of the ```simcore-postgres-database``` package. This generates issues in the deployment pipeline ```validate_simcore``` that is anyway skipping the migration service.
Also the dynamic-sidecar in devel mode appears to have issues with uv installation --> disabled for now.
> 🐛UV related issues

- tests/e2e-playwright/Makefile
- tests/e2e-playwright/tests/sleepers/sleepers.py
This PR flexibilise the sleepers test to adapt its expectation on the output files, depending on the version of the sleepers being tested.
> 🎨E2E: sleepers test adapt expected output files to sleepers version

- .github/workflows/ci-release.yml
- .github/workflows/ci-staging.yml
- .github/workflows/ci-testing-deploy.yml
Since Docker is not locked, there is no reason to block buildx.
> ⬆️Maintenance: remove blocking docker buildx version

- services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/core/settings.py
Removes env-var `MACHINE_FQDN`. which was not captured and unused.
> ♻️ Remove `$MACHINE_FQDN` from resource usage tracker

- tests/e2e-playwright/tests/jupyterlab.py
- tests/e2e-playwright/tests/resource_usage_tracker.py
- tests/e2e-playwright/tests/sim4life.py
imports to the logging utils were not updated...
> 🐛E2e: fix imports

- scripts/maintenance/computational-clusters/osparc_clusters.py
> 🎨Maintenance: osparc clusters improvements

- .github/workflows/ci-testing-deploy.yml
Remove unused caches which were causing issues.
> 🐛 Fix issues with pip cache in ci python setup

- .github/workflows/ci-testing-deploy.yml
- scripts/maintenance/computational-clusters/osparc_clusters.py
> ⚗️Disable e2e playwright for now

- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/info/StudyLarge.js
- services/static-webserver/client/source/class/osparc/info/StudyUtils.js
- services/static-webserver/client/source/class/osparc/study/StudyPreview.js
> 🎨 Study home page redesign II

- .github/workflows/ci-testing-deploy.yml
- scripts/maintenance/computational-clusters/osparc_clusters.py
> ♻️Maintenance: re-enable playwright E2E test in CI

- .github/PULL_REQUEST_TEMPLATE.md
- services/web/server/src/simcore_service_webserver/login/_registration_api.py
- services/web/server/src/simcore_service_webserver/login/_registration_handlers.py
- services/web/server/src/simcore_service_webserver/templates/common/request_account.jinja2
- services/web/server/tests/unit/with_dbs/03/test_email.py
- Adds all available ip-info. Last tests showed that it does not get the right IPs on master deployement
- Improves readability of email by adding json-dump
- Follow up improvements on https://github.com/ITISFoundation/osparc-simcore/pull/5391
- Request an account in master deploy
- Should be sent to fogbugz and assigned to @eofli
> 🎨 Improves request-account email

- services/static-webserver/client/source/class/osparc/workbench/DiskUsageIndicator.js
Better Telemetry background color for light and dark modes
> Telemetry background color  to address theme change issue

- scripts/maintenance/computational-clusters/osparc_clusters.py
For now the script will just tell the user how to cope with it. This currently only affects AWS-master.
> 🎨Maintenance: script now explains issue when repo.config has terraform entries

- services/web/server/src/simcore_service_webserver/login/storage.py
This PR fixes confirmation links used e.g. during registration, changing password, etc 
Using numerical code to avoid encoding problems when exchanging data in the confirmation links
Found while manually testing https://github.com/ITISFoundation/osparc-simcore/pull/5391. See details of test workflows there.
> 🐛 Fixes confirmation link

- packages/service-library/src/servicelib/long_running_tasks/_task.py
- Log stack trace in `DEBUG` level when task is removed from task manager.
- After analyzing the issue which occurs (return status 404) when running a study from Taylor I can conclude that the task (which creates a project) is removed from the task manager before the status is returned to the API server. This PR is an attempt to understand why it is deleted.
- resolves #5454
> 🎨 log stack trace when removing task from task manager

- packages/models-library/src/models_library/payments.py
- services/payments/src/simcore_service_payments/services/auto_recharge_process_message.py
- services/web/server/src/simcore_service_webserver/payments/_methods_api.py
- services/web/server/src/simcore_service_webserver/payments/_onetime_api.py
- services/web/server/src/simcore_service_webserver/payments/_rpc_invoice.py
> ✨ fix user name in invoice

- services/static-webserver/client/compile.json
- services/static-webserver/client/source/class/osparc/auth/LoginPage.js
- services/static-webserver/client/source/class/osparc/auth/ui/RequestAccount.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
- services/static-webserver/client/source/class/osparc/navigation/LogoOnOff.js
- services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
- services/static-webserver/client/source/class/osparc/product/AboutProduct.js
- services/static-webserver/client/source/class/osparc/product/Utils.js
- services/static-webserver/client/source/class/osparc/product/quickStart/Utils.js
- services/static-webserver/client/source/class/osparc/product/quickStart/s4lacad/Welcome.js
- services/static-webserver/client/source/class/osparc/store/VendorInfo.js
- services/static-webserver/client/source/class/osparc/utils/Utils.js
- services/static-webserver/client/source/resource/osparc/tours/s4l_tours.json
> 🐛 Last minute frontend fixes/updates

- api/tests/test_individual_openapi_schemas.py
- packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker.py
- packages/pytest-simcore/src/pytest_simcore/helpers/utils_postgres.py
- packages/service-library/setup.py
- packages/service-library/tests/fastapi/test_httpx_utils.py
- packages/simcore-sdk/setup.py
- packages/simcore-sdk/tests/conftest.py
- packages/simcore-sdk/tests/integration/conftest.py
- packages/simcore-sdk/tests/integration/test_node_data_data_manager.py
- packages/simcore-sdk/tests/integration/test_node_ports_v2_nodeports2.py
- packages/simcore-sdk/tests/unit/test_node_ports_v2_port.py
- services/agent/setup.py
- services/clusters-keeper/setup.py
- services/dask-sidecar/setup.py
- services/datcore-adapter/setup.py
- services/director-v2/setup.py
- services/dynamic-sidecar/setup.py
- services/web/server/setup.py
- services/web/server/tests/integration/01/test_exporter_requests_handlers.py
- services/web/server/tests/integration/02/test_computation.py
Various minor but noisy refactoring 
- unified `setup` modules
- unused tests
Maintenance
using tests in place
> ♻️ Cleanup of setup and tests tooling

- packages/service-integration/Dockerfile
> 🐛Dockerfile service-integration has missing ampersands

- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/desktop/credits/BillingCenter.js
- services/static-webserver/client/source/class/osparc/desktop/credits/DesktopCenter.js
- services/static-webserver/client/source/class/osparc/desktop/credits/MyAccount.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/PreferencesWindow.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/BasePage.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/GeneralPage.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/TagsPage.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/TokensPage.js
- services/static-webserver/client/source/class/osparc/po/POCenter.js
This PR cleans up the Preferences window:
S4L:
oSPARC:
> 🎨 Clean up Preferences window

- Makefile
- services/autoscaling/tests/manual/Makefile
- services/autoscaling/tests/manual/docker-compose-computational.yml
- services/autoscaling/tests/manual/docker-compose.yml
- services/clusters-keeper/Makefile
- services/clusters-keeper/src/simcore_service_clusters_keeper/data/docker-compose.yml
- services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py
- services/osparc-gateway-server/Makefile
- This PR mirrors the changes in osparc-infra by @YuryHrytsuk 
- the dns field in the docker-compose files used for manual testing were removed
- NOTE: developers will ensure they delete the docker swarm
> 🎨Maintenance: use the same swarm address pools as in osparc-infra

- scripts/maintenance/computational-clusters/osparc_clusters.py
> 🎨Maintenance: improve clusters overview script

- scripts/maintenance/computational-clusters/osparc_clusters.py
- ♻️ [x] refactoring of code
- 🎨 [x] uses now the ENV from both autoscaling and clusters-keeper from deploy configuration in order to list the running autoscaled nodes
- ✨ [x] copes with different regions on autoscaling and clusters-keeper
- 🎨 [x] improves display of dynamic services in the terminal (in particular the graylog link)
- 🎨 [x] better handling of terraform based ENVs
> ✨Clusters monitoring script: Allow to look for different regions

- services/web/server/src/simcore_service_webserver/statics/settings.py
- services/web/server/src/simcore_service_webserver/users/_schemas.py
- Validates and normalizes input country names in the registry. As a consequence, all pre-registration table will use the same names for each country.
- Sorts alphabetically list of countries in the output ( requested by @odeimaiz )
- Follows up from https://github.com/ITISFoundation/osparc-simcore/pull/5503
> 🎨 Enhances country names in registration

- scripts/maintenance/computational-clusters/osparc_clusters.py
- improve display of dynamic instances (graylog links)
- improve display of computational clusters (graylog links + dask metrics, dask processing jobs)
- optimize speed of dynamic instances parsing
> 🎨Maintenance: Clusters monitoring optimize dynamic monitoring and better display

- services/api-server/openapi.json
- services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs_getters.py
- Move logstreaming endpoint from `dev` mode to `production` mode. The main reason for this is the way in which we test the api-server. Due to resent failures in the logstreaming we want to have an e2e-test which detects failing logstreaming on sim4life.io
> 👽️ Expose logstreaming endpoint api server

- services/clusters-keeper/src/simcore_service_clusters_keeper/data/docker-compose.yml
Since the command was changed, it is compulsory to set the location of the configuration file as well.
it was missing in https://github.com/ITISFoundation/osparc-simcore/pull/5530 and this PR fixes this.
> 🐛Monitoring: Fix missing configuration location in prometheus startup command

- services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/utils/ec2.py
- services/clusters-keeper/tests/unit/test_modules_clusters.py
- services/clusters-keeper/tests/unit/test_utils_ec2.py
This PR adds a ```role``` tag to the EC2 machines (worker for the ones created by the autoscaling, manager for the ones created by the clusters-keeper). This will be helpful for gathering metrics.
> ✨Clusters-keeper: add machine role

- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/desktop/credits/TransactionsTable.js
- services/static-webserver/client/source/class/osparc/desktop/credits/TransactionsTableModel.js
- services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
@sanderegg 5555
For showing a payment invoice, instead of opening the old (and expirable) link, request a new one when it's demanded.
follows https://github.com/ITISFoundation/osparc-simcore/pull/5537
> 🚨🎨 Request new link for invoice

- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/dashboard/SortedByMenuButton.js
- Resolves Studies sorting: make clear direction after sorting
- Fixes issue where study sorting needs 3 clicks
- Fixes issue where study detail page shortcuts are wrongly linked
- resolves ITISFoundation/osparc-issues#1302
- fixes ITISFoundation/osparc-issues#1301
- resolves ITISFoundation/osparc-issues#1303
> 🐛 Feedback and bug fixes

- services/static-webserver/client/source/class/osparc/dashboard/ResourceMoreOptions.js
- services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
- services/static-webserver/client/source/class/osparc/service/PricingUnitsList.js
> ✨ Frontend feature: Show available Tiers in Service metadata

- packages/pytest-simcore/src/pytest_simcore/faker_payments_data.py
- services/payments/src/simcore_service_payments/services/payments.py
- services/payments/tests/unit/test_services_payments__get_invoice.py
- 🐛 make invoice link backward compatibility. Before we introduced this change: https://github.com/ITISFoundation/osparc-simcore/pull/5537 where we started to populate DB with `stripe_invoice_id` we had a `invoice_url` in the DB. Even though this URL will expire, we will use it for those old invoices. There will be at least nice UI asking user to regenerate the invoice link via his email. 
- relates to https://github.com/ITISFoundation/osparc-simcore/pull/5537
> 🐛 invoice link backward compatibility

- services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs_getters.py
- services/api-server/src/simcore_service_api_server/api/routes/studies.py
- services/api-server/src/simcore_service_api_server/services/webserver.py
- Clean up exception classes which are not actually used/raised
- fixes #5611
> 🎨  Clean up webserver exception types

- services/static-webserver/client/source/class/osparc/notification/NotificationsButton.js
fixes: https://github.com/ITISFoundation/osparc-issues/issues/1361
> 🐛 Frontend Fix: Tap Notification

- tests/e2e-playwright/tests/conftest.py
- tests/e2e-playwright/tests/sleepers/sleepers.py
After adding the sleeper node, wait for the nodes response before continuing.
> e2e-playwright sleepers: add ``/nodes`` context

- services/storage/src/simcore_service_storage/s3.py
- services/storage/src/simcore_service_storage/s3_client.py
- services/storage/tests/unit/test_s3_client.py
- the boto library needs to handle differently the creation of buckets in the us-east-1 region or in all the other regions [see boto3 issue](https://github.com/boto/boto3/issues/125)
> ✨Storage is now compatible with using multiple S3 regions

- services/clusters-keeper/tests/unit/conftest.py
- services/storage/.env-devel
- services/storage/src/simcore_service_storage/application.py
- services/storage/src/simcore_service_storage/settings.py
- services/storage/tests/conftest.py
- services/storage/tests/unit/test_s3.py
- services/storage/tests/unit/test_s3_client.py
- tests/environment-setup/test_used_python.py
- it makes no sense to run the storage service without S3 and postgres settings
- added validation of settings
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5680
> 🎨Storage: disallow optional S3/postgres settings

- services/payments/src/simcore_service_payments/services/notifier_email.py
- 🐛 fix attachment invoice (It is important that attachment is added after body)
> 🐛 fix attachment invoice

- tests/e2e-playwright/tests/conftest.py
This is needed so that it is easy to filter in prometheus
> ✨E2E Playwright: add extra headers for all requests

- services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/proxy.py
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5754
- next step will be to re-enable web security on playwright.
> ✨Dynamic proxy: add allowed CORS header

- tests/e2e-playwright/tests/conftest.py
- follow-up after https://github.com/ITISFoundation/osparc-simcore/pull/5756
- re-enable the --web-security in the playwright runner since CORS headers are now correctly handled.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5757
> 🎨E2E: re-enable web-security when running playwright

- packages/service-library/src/servicelib/aiohttp/profiler_middleware.py
- packages/service-library/src/servicelib/fastapi/profiler_middleware.py
- pyinstrument seems to make some decision about what to show in its profile or not depending on how packages are installed (edit mode etc). By enabling `show-all` we get the full profile even in deployed osparc-simcore
> 🎨 enable `show-all` in profiling middleware to ensure profile is fully detailed

- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
> ✨ TIP frontend: 4th plus button (#5766)

- services/docker-compose.yml
```
make .stack-simcore-production.yml
```
> 🐛 🔨 Fixes wb-api-server configuration

- packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone.py
- packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py
- This hopefully should help with making RClone not destroy machines
- In a first step this is an experiment as this is a bit difficult to reproduce
- improvements on transfer speed are not part of this PR so that it can be easily hotfixed
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5789
> 🐛⚗️RClone: Disable multi-threading 🚨

- services/agent/src/simcore_service_agent/modules/volumes_cleanup/_s3.py
This PR ensures the fix in https://github.com/ITISFoundation/osparc-simcore/pull/5790 is also applied to the agent, even if I am not sure what its use currently is.
> 🐛Agent: ensure RClone does not create kernel panics

- tests/e2e-playwright/.gitignore
- tests/e2e-playwright/report.xml
- tests/e2e-playwright/tests/ti_plan.py
- 🐛 improve tip e2e test
- Highlights: waiting for button color change:
```python
run_button = ti_page.get_by_role("button", name="Run Optimization")
run_button.click()
for attempt in Retrying(
wait=wait_fixed(5),
stop=stop_after_attempt(20),  # 5*20= 100 seconds
retry=retry_if_exception_type(AssertionError),
reraise=True,
):
with attempt:
_run_button_style = run_button.evaluate(
"el => window.getComputedStyle(el)"
)
assert (
_run_button_style["backgroundColor"] == "rgb(0, 128, 0)"
)
```
> 🐛 improve tip e2e test

- services/osparc-gateway-server/tests/system/requirements/_test.txt
- services/osparc-gateway-server/tests/system/requirements/_tools.txt
- fixes missing dask upgrade of requirements
> 🐛⬆️Osparc-gateway-server: missing requirements update

- services/web/server/src/simcore_service_webserver/projects/_crud_api_create.py
Removes strange messages appearing in the frontend.
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1457
> 🐛Webserver: Fix show weird messages in the frontend UI

- packages/aws-library/src/aws_library/ec2/client.py
- disable PublicIP request when creating EC2s for autoscaled nodes
> 🎨Autoscaling/Clusters-keeper: disable public IP address

- packages/aws-library/src/aws_library/ec2/client.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/utils/dask.py
> 🐛♻️Clusters-keeper: use private dns name instead of public IP

- services/static-webserver/client/source/class/osparc/desktop/credits/UsageTable.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UsageTableModel.js
Show ``root_parent_project_name`` instead of ``project_name`` (which are the same if the project has no parent)
follows https://github.com/ITISFoundation/osparc-simcore/pull/5891
> 🎨 Frontend: Usage table: show ``root_parent_project_name`` instead of ``project_name``

- services/static-webserver/client/source/class/osparc/dashboard/DataBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
- services/static-webserver/client/source/class/osparc/ui/basic/LoadingPageHandler.js
The side spacer  we have in the Dashboard were also part of the Study Editor, this PR fixes that.
Fixed:
> 🐛 [Frontend bugfix] Move side spacer to Resource Browser

- packages/service-library/tests/test_redis_utils.py
disable ```test_exclusive_parallel_lock_is_released_and_reacquired``` as this prevents the CI from running.
since https://github.com/ITISFoundation/osparc-simcore/pull/5888 the test does not pass the CI
> 🐛Maintenance: disable CI problematic test

- services/static-webserver/client/source/class/osparc/CookiePolicy.js
- services/static-webserver/client/source/class/osparc/auth/LoginPage.js
- services/static-webserver/client/source/class/osparc/auth/ui/LoginView.js
- services/static-webserver/client/source/class/osparc/auth/ui/RequestAccount.js
The Request Account form will be shown on those products that ``invitation_required`` and are ``billable``.
I guess that the form for TIP will change a bit, for now, only the Privacy Policy link was updated, it points to IT'IS Privacy Policy.
related to https://github.com/ITISFoundation/osparc-issues/issues/1513
> 🎨 [Frontend] Request Account form for Billable products

- services/docker-compose-deploy.yml
correct typo introduced in https://github.com/ITISFoundation/osparc-simcore/pull/5937
> 🐛Bugfix: fix typo in docker-compose for CI deployment

- services/static-webserver/client/source/class/osparc/service/ServiceListItem.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsService.js
Fix: patching service access rights was broken
> 🐛 [Frontend bugfix] patch Services access rights

- services/static-webserver/client/source/class/osparc/file/FileDrop.js
- services/static-webserver/client/source/class/osparc/workbench/WorkbenchUI.js
Show error message saying that ``Folders are not accepted. You might want to upload a zip file.`` when users drop a folder on the Workbench:
related to https://z43.fogbugz.com/f/cases/198533
> 🎨 [Frontend] Refuse folder drop on Workbech

- services/static-webserver/client/source/class/osparc/data/model/Node.js
follows https://github.com/ITISFoundation/osparc-simcore/pull/5968
> 🐛 [Frontend] Stringify fetch response

- tests/e2e-playwright/tests/conftest.py
> 🐛E2E: --product-url is an url not a string

- packages/postgres-database/docker/Dockerfile
- packages/service-integration/Dockerfile
- requirements/tools/Dockerfile
- scripts/mypy/Dockerfile
- services/agent/Dockerfile
- services/api-server/Dockerfile
- services/autoscaling/Dockerfile
- services/catalog/Dockerfile
- services/clusters-keeper/Dockerfile
- services/dask-sidecar/Dockerfile
- services/datcore-adapter/Dockerfile
- services/director-v2/Dockerfile
- services/dynamic-scheduler/Dockerfile
- services/dynamic-sidecar/Dockerfile
- services/efs-guardian/Dockerfile
- services/invitations/Dockerfile
- services/migration/Dockerfile
- services/osparc-gateway-server/Dockerfile
- services/payments/Dockerfile
- services/resource-usage-tracker/Dockerfile
- services/storage/Dockerfile
- services/web/Dockerfile
> ⬆️Maintenance: upgrade uv to 0.2 in Dockerfiles

- services/web/server/src/simcore_service_webserver/login/_sql.py
- services/web/server/src/simcore_service_webserver/projects/_nodes_utils.py
- services/web/server/src/simcore_service_webserver/projects/exceptions.py
- services/web/server/src/simcore_service_webserver/projects/projects_api.py
Applied these two conventions so solve gh's code scanning alerts:
- Avoid logging critical info (even in debug level)
- Avoid generic message exceptions, instead create a specific exception inherited from  `OsparcErrorMixin` and set a concrete user-friendly `msg_template`.
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/6018
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/6017
> 🔒️ Resolves security scanning alerts

- tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py
@YuryHrytsuk asked for a test that checks AIRAM is available. An indirect solution is to run a service that relies on AIRAM.
Therefore the jupyterlabs playwright test was flexibilized and made compatible with jupyter-ml-pytorch.
> ✨E2E: jupyterlabs test compatible with jupyter-ml

- services/static-webserver/client/source/class/osparc/data/model/IframeHandler.js
- services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
- services/static-webserver/client/source/class/osparc/node/NodeView.js
- services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js
> 🐛 [Frontend] Do not duplicate poll calls

- tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py
> 🐛E2e: fix typo

- services/web/server/src/simcore_service_webserver/projects/projects_api.py
This PR ensures a safe margin of 1GB is removed on the RAM reservations/limits when starting a service
Fixes the issue where the electrode-selector would not start on a "small" t3.medium machine
> 🐛Autoscaling: Ensure a safe memory margin is removed to account for OPS services when starting dynamic services

- tests/performance/Makefile
- seems I forgot to remove a make target in my previous PR
> 🐛 Fix `install-ci` make target in `tests/performance`

- services/web/server/src/simcore_service_webserver/security/_authz_access_roles.py
- services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py
- services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handlers__patch.py
- 🎨 Guest user can perform project node update the same as he/she can perform project update
- @odeimaiz This should fix the permissions issues in the e2e portal tests in the master
> 🎨 Guest can perform project node update

- services/static-webserver/client/source/class/osparc/desktop/organizations/MembersList.js
- services/static-webserver/client/source/class/osparc/info/StudyUtils.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsStudy.js
- services/static-webserver/client/source/class/osparc/study/SaveAsTemplate.js
> 🐛 [Frontend] Fix PATCH access rights

- services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
- services/static-webserver/client/source/class/osparc/info/ServiceUtils.js
- services/static-webserver/client/source/class/osparc/service/ServiceListItem.js
- services/static-webserver/client/source/class/osparc/service/Utils.js
- services/static-webserver/client/source/class/osparc/workbench/ServiceCatalog.js
> 🐛 [Frontend] ``dev/services`` fixes

- api/specs/director/schemas/node-meta-v0.0.1.json
Updates director node schema for @mguidon 
- https://github.com/ITISFoundation/osparc-issues/issues/1419
- https://github.com/ITISFoundation/osparc-issues/issues/1420 
No
> 🎨 Update director's schema

- tests/e2e-playwright/README.md
- tests/e2e-playwright/tests/conftest.py
- tests/e2e-playwright/tests/sleepers/test_sleepers.py
- improve logging in E2E
- adjust README
> 🎨E2E: improve logging in E2E

- tests/e2e-playwright/tests/sim4life/test_sim4life.py
- ensure websocket acquisition is done when s4l starts
> 🎨E2E: ensure websocket is correctly acquired

- .github/workflows/ci-testing-deploy.yml
- packages/aws-library/requirements/_test.txt
- packages/aws-library/setup.cfg
- packages/dask-task-models-library/src/dask_task_models_library/container_tasks/events.py
- packages/dask-task-models-library/src/dask_task_models_library/container_tasks/io.py
- packages/models-library/src/models_library/generics.py
> ♻️Maintenance: mypy fixes for AWS-library, Dask-task-lib

- .github/workflows/ci-testing-deploy.yml
- packages/notifications-library/requirements/_test.in
- packages/notifications-library/requirements/_test.txt
- packages/notifications-library/requirements/_tools.txt
- packages/notifications-library/setup.cfg
- packages/notifications-library/src/notifications_library/_email.py
- services/invitations/setup.cfg
- services/invitations/src/simcore_service_invitations/_meta.py
- services/invitations/src/simcore_service_invitations/api/_dependencies.py
- services/invitations/src/simcore_service_invitations/cli.py
- services/invitations/src/simcore_service_invitations/core/application.py
- services/invitations/src/simcore_service_invitations/core/settings.py
- services/osparc-gateway-server/setup.cfg
- services/osparc-gateway-server/src/osparc_gateway_server/app.py
- services/osparc-gateway-server/src/osparc_gateway_server/backend/osparc.py
- services/osparc-gateway-server/src/osparc_gateway_server/backend/utils.py
- services/osparc-gateway-server/src/osparc_gateway_server/remote_debug.py
> ♻️Maintenance: mypy notifications-library, osparc-gateway-server, invitations

- .github/workflows/ci-testing-deploy.yml
- packages/models-library/src/models_library/rpc_pagination.py
- services/catalog/requirements/_test.in
- services/catalog/requirements/_test.txt
- services/catalog/setup.cfg
- services/catalog/src/simcore_service_catalog/_constants.py
- services/catalog/src/simcore_service_catalog/api/dependencies/services.py
- services/catalog/src/simcore_service_catalog/api/rest/_services.py
- services/catalog/src/simcore_service_catalog/api/rest/_services_ports.py
- services/catalog/src/simcore_service_catalog/api/rest/_services_resources.py
- services/catalog/src/simcore_service_catalog/api/rpc/_services.py
- services/catalog/src/simcore_service_catalog/core/background_tasks.py
- services/catalog/src/simcore_service_catalog/db/repositories/_services_sql.py
- services/catalog/src/simcore_service_catalog/db/repositories/services.py
- services/catalog/src/simcore_service_catalog/exceptions/handlers/_http_error.py
- services/catalog/src/simcore_service_catalog/services/access_rights.py
- services/catalog/src/simcore_service_catalog/services/compatibility.py
- services/catalog/src/simcore_service_catalog/services/director.py
- services/catalog/src/simcore_service_catalog/services/function_services.py
- services/catalog/src/simcore_service_catalog/services/manifest.py
- services/catalog/src/simcore_service_catalog/services/services_api.py
- services/catalog/src/simcore_service_catalog/utils/versioning.py
> ♻️Maintenance: mypy catalog

- .github/workflows/ci-testing-deploy.yml
- packages/models-library/src/models_library/api_schemas_storage.py
- packages/service-library/src/servicelib/common_aiopg_utils.py
- packages/simcore-sdk/requirements/_test.in
- packages/simcore-sdk/requirements/_test.txt
- packages/simcore-sdk/requirements/_tools.txt
- packages/simcore-sdk/setup.cfg
- packages/simcore-sdk/src/simcore_sdk/node_data/data_manager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/_filemanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/constants.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/dbmanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone_utils.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_client.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/links.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/nodeports_v2.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py
- packages/simcore-sdk/src/simcore_sdk/node_ports_v2/serialization_v2.py
> ♻️Maintenance: mypy simcore sdk

- services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
- services/web/server/src/simcore_service_webserver/projects/_crud_api_read.py
- services/web/server/src/simcore_service_webserver/projects/_crud_handlers.py
- services/web/server/src/simcore_service_webserver/projects/_crud_handlers_models.py
- services/web/server/src/simcore_service_webserver/projects/db.py
- services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__list_with_query_params.py
- ✨ introduce `folder_id` query parameter in the project listing
- @odeimaiz tomorrow morning I will finish this PR https://github.com/ITISFoundation/osparc-simcore/pull/6132 just for Primary Group ID. And I think we might manage to connect it to frontend.  
- closes https://github.com/ITISFoundation/osparc-issues/issues/1567
- relates https://github.com/ITISFoundation/osparc-issues/issues/716
> ✨ project listing with folder_id

- services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js
> 🐛 [Frontend] Fix ``guest``'s viewer

- services/static-webserver/client/source/class/osparc/info/MergedLarge.js
- services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
- services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyUpdate.js
- services/static-webserver/client/source/class/osparc/share/ShareePermissions.js
- services/static-webserver/client/source/class/osparc/widget/NodeOutputs.js
Instead of showing it to testers only, show it also to service owners
Bonus:
- Fix: show service name and version in Sharee warning view
- Fix: update output value in Outputs view
> 🎨 [Frontend] Show Integration version to owners

- .github/workflows/ci-testing-deploy.yml
The `[build] docker images` is getting cancelled in the CI, this sets a reliable timeout and not some default used by GitHub.
> 🎨 Maintenance: sets a timeout to [build] docker images stage

- .github/workflows/cleanup-caches-by-branches.yml
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#managing-caches
This comes from the official documentation and shall prevent caches to grow forever.
> ✨Maintenance: adds CI workflow to cleanup caches when a branch is merged

- services/static-webserver/client/source/class/osparc/data/Resources.js
- services/static-webserver/client/source/class/osparc/desktop/SlideshowView.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsIndicatorButton.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsServiceListItem.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js
- services/static-webserver/client/source/resource/osparc/tours/tis_tours.json
In the credits-left-widget, show where the credits were consumed for different time ranges.
Inspired by https://apps.apple.com/us/app/tripmode/id1513400665?mt=12
Related to https://github.com/ITISFoundation/osparc-issues/issues/1409
> ✨ [Frontend] Credits per service summary

- services/static-webserver/client/source/class/osparc/workbench/ServiceCatalog.js
Fixes what wasn't properly fixed in [here](https://github.com/ITISFoundation/osparc-simcore/pull/6138)
> 🐛 [Frontend] Service catalog, don't list deprecated

- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
Show "No usage found" message if there was nothing found.
> 🎨 [Frontend] No usage found in time range

- services/static-webserver/client/tools/qooxdoo-kit/builder/Dockerfile
- the venerable static-webserver which boasted version v1.16.0-alpine seems to have a memory leak and is 3 years old
- the new 2.32.1-alpine is the latest, built now on Rust and does not seem to show the same problem
btop reports about 65MB of memory usage and quite stable
> ⬆️Maintenance: upgrade static-webserver to latest 2.32.1-alpine

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/4_pre_release.yml
- .github/ISSUE_TEMPLATE/5_release.yml
- .github/ISSUE_TEMPLATE/6_hotfix.yml
- Makefile
A collection of minor changes
- ⬆️  Fixes **deprecation warning** in docker CLI
- ♻️ Updates t**emplates for releases** to include planned release date
- 🔧 Removes @bisgaard-itis from **CODEOWNER** until he is back
- maintenace
> 🔧⬆️ Maintenance: updates repo templates and scripts

- services/static-webserver/client/source/class/osparc/data/Permissions.js
- services/static-webserver/client/source/class/osparc/desktop/account/MyAccount.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsStudy.js
- services/static-webserver/client/source/class/osparc/share/ShareePermissions.js
Do not push ``TEMPLATE_SHARED`` notification:
Tester:
User:
closes https://github.com/ITISFoundation/osparc-issues/issues/1591
closes https://github.com/ITISFoundation/osparc-issues/issues/1592
> [Frontend] 🎨 TIP enhancements

- services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
> 🐛 [Frontend] Fix: List grouped tagged templates

- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
- services/static-webserver/client/source/class/osparc/data/Permissions.js
- services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyUpdate.js
fixes https://github.com/ITISFoundation/osparc-issues/issues/1693
> 🎨 [Frontend] UI/UX: Study updates

- services/static-webserver/client/source/class/osparc/form/renderer/PropForm.js
reported by @AntoninoMarioC 
Fixes the link <-> unlink port button's logic.
> 🐛 [Frontend] Fix: unlink port

- .pre-commit-config.yaml
- scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/constants.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/core.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/models.py
- Makes autoscaling monitoring tool compatible with non-billable deployments (e.g. where there is no wallet_id defined)
- added range cancellation @mguidon
> ✨Autoscaling monitoring tool: make compatible with non-billable deploys

- packages/aws-library/src/aws_library/ssm/_client.py
the response from AWS is slightly different
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/5864
> 🐛Autoscaling: SSM client key error fix

- api/specs/web-server/_projects_workspaces.py
- api/specs/web-server/openapi.py
- services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
- services/web/server/src/simcore_service_webserver/projects/_crud_api_create.py
- services/web/server/src/simcore_service_webserver/projects/_folders_db.py
- services/web/server/src/simcore_service_webserver/projects/_groups_db.py
- services/web/server/src/simcore_service_webserver/projects/_workspaces_api.py
- services/web/server/src/simcore_service_webserver/projects/_workspaces_handlers.py
- services/web/server/src/simcore_service_webserver/projects/plugin.py
- services/web/server/src/simcore_service_webserver/security/_authz_access_roles.py
- services/web/server/tests/unit/with_dbs/03/workspaces/test_workspaces__moving_projects_between_workspaces.py
- 🎨 moving projects between workspaces
- https://github.com/ITISFoundation/osparc-issues/issues/716
- https://github.com/ITISFoundation/osparc-issues/issues/1606
`test_workspaces__moving_projects_between_workspaces.py`
> 🎨 moving projects between workspaces

- scripts/maintenance/computational-clusters/Makefile
- scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/constants.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/core.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/dask.py
- scripts/maintenance/computational-clusters/autoscaled_monitor/ssh.py
- scripts/maintenance/computational-clusters/pyproject.toml
- compatible with tip.science
- some small improvements with errors
```bash
cd scripts/maintenance/computational-clusters
make
make install
autoscaled-monitor --deploy-config ../../../../../gitlab/osparc-ops-deployment-configuration/deployments/sim4life.io summary
```
NOTE: any other deployment might be used.
NOTE2: you need the ```repo.config``` available in the deployment configuration.
> 🎨Autoscaling monitoring tool: compatible with TIP, small improvements

- services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
- services/static-webserver/client/source/class/osparc/data/Permissions.js
- services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
Tester:
User:
Service headers:
closes https://github.com/ITISFoundation/osparc-simcore/issues/6313
closes https://github.com/ITISFoundation/osparc-simcore/issues/6309
> 🐛 [Frontend] TIP: Hide Boot Options

- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsIndicatorButton.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsServiceListItem.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js
- closes https://github.com/ITISFoundation/osparc-issues/issues/1672
- closes https://github.com/ITISFoundation/osparc-issues/issues/1622
- related to https://github.com/ITISFoundation/osparc-issues/issues/1409
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1712
> 🎨 [Frontend] Credits summary: Show time

- services/static-webserver/client/source/class/osparc/editor/MarkdownEditor.js
- services/static-webserver/client/source/class/osparc/info/CommentUI.js
- services/static-webserver/client/source/class/osparc/info/ServiceUtils.js
- services/static-webserver/client/source/class/osparc/info/StudyUtils.js
- services/static-webserver/client/source/class/osparc/metadata/QualityEditor.js
- services/static-webserver/client/source/class/osparc/node/slideshow/BaseNodeView.js
- services/static-webserver/client/source/class/osparc/ui/markdown/Markdown.js
closes https://github.com/ITISFoundation/osparc-issues/issues/1704
> 🎨 [Frontend] Prettify markdown's outcome

- services/static-webserver/client/source/class/osparc/study/StudyPricingUnits.js
> 🐛 [Frontend] Do not list/request ``/frontend/`` service's pricing plans

- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
If folders are disabled in the backend, the Study Browser will fail to load, this PR fixes it.
> 🐛 [Frontend] Fix for Folders disabled scenario

- Makefile
small adjustments to Makefile to allow to build without pyenv
> ♻️Maintenance: adjustments to Makefile to use UV instead of pyenv

- services/static-webserver/client/source/class/osparc/utils/Utils.js
The ``replaceTokens`` function was buggy for localized strings, making the Plus Button creation fail
> 🐛 [Frontend] Fix replaceTokens function

- services/docker-compose.devel.yml
- 🐛 Remove Efs Guardian for devel model - efs is running as a root which causes troubles when running devel mode locally.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6537
> 🐛 Remove Efs Guardian for devel model

- packages/service-library/src/servicelib/deferred_tasks/_utils.py
fix issue with conflicting libraries
fast-depends in service-library was upgraded lately... and accepts a kwargs in RejectMessage, and dynamic-schdlr has an older version that cannot handle that.
> 🐛Deferred tasks: issue with library changing its syntax

- .codecov.yml
- .github/workflows/ci-testing-deploy.yml
- .gitignore
- packages/aws-library/Makefile
- packages/dask-task-models-library/Makefile
- packages/models-library/Makefile
- packages/notifications-library/Makefile
- packages/postgres-database/Makefile
- packages/service-integration/Makefile
- packages/service-library/Makefile
- packages/settings-library/Makefile
- packages/simcore-sdk/Makefile
- scripts/common-service.Makefile
> 🔨Fix codecov2

- .codecov.yml
- solves https://github.com/ITISFoundation/osparc-simcore/issues/6235
> 🔨Fix codecov3

- .github/workflows/ci-testing-deploy.yml
- disable caching of UV packages as it seems to blow up Github CI cache
> 🔨CI: disable uv caching

- services/agent/src/simcore_service_agent/core/settings.py
- services/api-server/src/simcore_service_api_server/core/settings.py
- services/autoscaling/src/simcore_service_autoscaling/core/settings.py
- services/catalog/src/simcore_service_catalog/core/settings.py
- services/clusters-keeper/src/simcore_service_clusters_keeper/core/settings.py
- services/dask-sidecar/src/simcore_service_dask_sidecar/settings.py
- services/datcore-adapter/src/simcore_service_datcore_adapter/core/settings.py
- services/director-v2/src/simcore_service_director_v2/core/settings.py
- services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/settings.py
- services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/settings.py
- services/efs-guardian/src/simcore_service_efs_guardian/core/settings.py
- services/invitations/src/simcore_service_invitations/core/settings.py
- services/payments/src/simcore_service_payments/core/settings.py
- services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/core/settings.py
- services/storage/src/simcore_service_storage/settings.py
- services/web/server/src/simcore_service_webserver/application_settings.py
> ⬆️ Pydantic V2: after upstream merge -> fixes

- tests/e2e/portal-files/VTK_file.js
- ♻️ increase timeout on VTK E2E test
> ♻️ increase timeout on VTK E2E test

- services/static-webserver/client/source/class/osparc/desktop/organizations/MembersList.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ClustersPage.js
- services/static-webserver/client/source/class/osparc/node/UpdateResourceLimitsView.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsService.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsStudy.js
- services/static-webserver/client/source/class/osparc/share/CollaboratorsWorkspace.js
requested by @mguidon 
More meaningful Flash Messages when dealing with Study, Template, Service, Workspace and Organization permissions.
> 🎨 [Frontend] Rephrase sharing messages

- packages/aws-library/requirements/_base.txt
- packages/aws-library/requirements/_test.txt
- packages/dask-task-models-library/requirements/_base.txt
- packages/notifications-library/requirements/_base.txt
- packages/postgres-database/requirements/_base.txt
- packages/service-library/requirements/_fastapi.txt
- services/agent/requirements/_base.txt
- services/api-server/requirements/_base.txt
- services/autoscaling/requirements/_base.txt
- services/catalog/requirements/_base.txt
- services/clusters-keeper/requirements/_base.txt
- services/datcore-adapter/requirements/_base.txt
- services/director-v2/requirements/_base.txt
- services/dynamic-scheduler/requirements/_base.txt
- services/dynamic-sidecar/requirements/_base.txt
- services/efs-guardian/requirements/_base.txt
- services/invitations/requirements/_base.txt
- services/payments/requirements/_base.txt
- services/resource-usage-tracker/requirements/_base.txt
Versions were not aligned, this PR aligns them for Pydantic v2 and fastapi.
> ⬆️ Align versions for pydantic/fastapi

- services/director/src/simcore_service_director/core/settings.py
> ⬆️Pydantic V2: missing import in director-v0

- services/static-webserver/client/source/class/osparc/data/model/Wallet.js
- services/static-webserver/client/source/class/osparc/desktop/credits/BuyCreditsStepper.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
- services/static-webserver/client/source/class/osparc/desktop/credits/CurrentUsage.js
- services/static-webserver/client/source/class/osparc/desktop/credits/TransactionsTableModel.js
- services/static-webserver/client/source/class/osparc/desktop/credits/UsageTableModel.js
- services/static-webserver/client/source/class/osparc/pricing/UnitData.js
- services/static-webserver/client/source/class/osparc/pricing/UnitEditor.js
- services/static-webserver/client/source/class/osparc/widget/PersistentIframe.js
> 🐛 [Frontend] pydanticV2: Decimals are now Strings

- .github/workflows/ci-testing-deploy.yml
- 🐛 Fix GitHub CI (This should help address situations where, with auto-merge enabled, changes are merged before integration and system tests complete).
> 🐛 fix github ci

- .github/workflows/ci-testing-deploy.yml
- temporarily removes api checks from system tests to check if this is what's blocking the deployment
> ⚗️ remove api checks from system tests

- .github/workflows/ci-testing-deploy.yml
> 🐛 yet another fix

- .github/workflows/ci-testing-deploy.yml
- .github/workflows/ci-testing-pull-request.yml
- replaces https://github.com/ITISFoundation/osparc-simcore/pull/6994
- Upgrade UV action in Github CI to v5
- Upgrade UV version used to 0.5.x
- cleanup ci-testing-pull-request and removed unnecessary UV setup in 2 jobs (hopefully correct)
> ⬆️Maintenance: Upgrade CI UV action and UV to 0.5.x

- tests/e2e-playwright/requirements/Makefile
- tests/e2e-playwright/requirements/_test.in
- tests/e2e-playwright/requirements/_test.txt
- tests/e2e-playwright/requirements/_test_wo_playwright.in
- tests/e2e-playwright/requirements/_test_wo_playwright.txt
- tests/e2e-playwright/requirements/_tools.txt
- tests/e2e-playwright/requirements/ci_wo_playwright.txt
- provide a requirement listing without playwright installed for CI builds that use a base image where playwright is already pre-installed
> ♻️ E2E: provide a requirements file without playwright installed

- .github/mergify.yml
Added automation for upgrading the branch automatically if it's behind and was marked as "ready to be merged by Mergify"
> Mergify automatically update branch if behind in commits

- .github/mergify.yml
The current configuration would use the automation workflows to help you merge the code, which did not address the main issue we are having: `Multiple concurrent PRs ready to be merged`.
To avoid waisting time and resources the usage of the merge queue is the appropriate solution.
> 🎨 Trying to make Mergify use the merge queue

- .github/mergify.yml
The previous configuration would have never allowed for any PR to be queued. This configuration actually helps the user to forget about the PR until it's merged to master.
> 🎨 Update PR queueing rules for Mergify

- services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
Fixes billable product creation view.
> 🐛 [Frontend] Fix: "New" translation

- services/static-webserver/client/source/class/osparc/study/PricingUnitLicense.js
- services/static-webserver/client/source/class/osparc/ui/markdown/MarkdownWindow.js
- services/static-webserver/client/source/class/osparc/ui/window/Dialog.js
- services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelDetails.js
With this PR, before Renting a model, its Terms and Conditions must be accepted.
Note: The frontend expects a link to the markdown raw content.
- related to https://github.com/ITISFoundation/osparc-issues/issues/1732
> 🎨 [Frontend] ViP Market: force accept Terms and Conditions

- services/static-webserver/client/source/class/osparc/dashboard/NewPlusMenu.js
- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/store/Pricing.js
- services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelDetails.js
- services/static-webserver/client/source/class/osparc/vipMarket/Market.js
In order to show the "Open Access Models", the pricing units of the pricing plans assigned to all licensedItems are required (those with a single pricing unit with cost 0 will fall in this category).
In this PR we cache the pricing units, making the population of the "Open Access Models" category faster and less stressful for the backend.
Before:
After:
- Fixed Guest users startup calls
> 🎨 [Frontend] ViP Market: Cache pricing units

- services/static-webserver/client/source/class/osparc/Application.js
- services/static-webserver/client/source/class/osparc/WatchDog.js
- services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
- services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js
- services/static-webserver/client/source/class/osparc/dashboard/DragWidget.js
- services/static-webserver/client/source/class/osparc/dashboard/FolderButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js
- services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonBase.js
- services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js
- services/static-webserver/client/source/class/osparc/dashboard/NewPlusMenu.js
- services/static-webserver/client/source/class/osparc/dashboard/WorkspaceButtonItem.js
- services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
- services/static-webserver/client/source/class/osparc/desktop/preferences/pages/TagsPage.js
- services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
- services/static-webserver/client/source/class/osparc/info/ServiceUtils.js
- services/static-webserver/client/source/class/osparc/navigation/LogoOnOff.js
- services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
- services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
- services/static-webserver/client/source/class/osparc/store/Tags.js
- services/static-webserver/client/source/class/osparc/theme/Appearance.js
- services/static-webserver/client/source/class/osparc/theme/mixin/Color.js
- services/static-webserver/client/source/class/osparc/ui/basic/Logo.js
- services/static-webserver/client/source/class/osparc/utils/Utils.js
- Simplify navBar bgColor
- Unify menu's appearances
- Add ``alt``ernative text to some images 
- Do not initialize (load) Three.js and Plotly.js, they are currently not used
- Fetch tags' accessRights when really needed: speed up start up
> ♻️ [Frontend] Maintenance: Refactor decorators

- api/specs/web-server/_storage.py
- services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
Webserver OpenAPI
[![ReDoc](https://img.shields.io/badge/OpenAPI-ReDoc-85ea2d?logo=openapiinitiative)](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/sanderegg/osparc-simcore/229f35cf437f4bf62e58d44cc713628189628f9e/services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml)
> 🐛Webserver: re-generate wrong openapi

- services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
- services/static-webserver/client/source/class/osparc/vipMarket/MarketWindow.js
> ♻️ [Frontend] Rename: "Model Store" -> "The Shop"

- services/storage/src/simcore_service_storage/api/rest/_files.py
- solves https://github.com/ITISFoundation/osparc-issues/issues/1858
> 🐛Storage: quote returned links such that they are usable with files containing parentheses

- services/static-webserver/client/source/class/osparc/desktop/wallets/MemberListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/CollaboratorListItem.js
- services/static-webserver/client/source/class/osparc/ui/list/MemberListItem.js
> 🐛 [Frontend] Fix: Update members list after sharing

- services/static-webserver/client/source/class/osparc/vipMarket/LicensedItemListItem.js
reported by @capbrown 
Buggy:
Fixed:
> 🐛 [Frontend] Shop: Fix thumbnail

- services/web/server/src/simcore_service_webserver/projects/projects_service.py
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1861
NOTE: this should probably go in a hotfix if it works
comparison between UUID and str never resolves
> 🐛Cannot refresh page when only 1 study per user is allowed

- services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
- services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js
- services/static-webserver/client/source/class/osparc/data/PollTask.js
- services/static-webserver/client/source/class/osparc/file/FileLabelWithActions.js
- services/static-webserver/client/source/class/osparc/store/PollTasks.js
- services/static-webserver/client/source/class/osparc/task/Duplicate.js
- services/static-webserver/client/source/class/osparc/task/Export.js
- services/static-webserver/client/source/class/osparc/task/Import.js
- services/static-webserver/client/source/class/osparc/task/TaskUI.js
- services/static-webserver/client/source/class/osparc/task/TasksButton.js
- services/static-webserver/client/source/class/osparc/task/TasksContainer.js
- services/static-webserver/client/source/class/osparc/task/ToTemplate.js
- services/static-webserver/client/source/class/osparc/ui/window/Confirmation.js
- services/static-webserver/client/source/class/osparc/ui/window/Progress.js
As requested by @pcrespov in [here](https://github.com/ITISFoundation/osparc-simcore/pull/7458#pullrequestreview-2733099589), this PR shows file deletion progress and allows aborting the operation.
- related to https://github.com/ITISFoundation/osparc-issues/issues/1635
> 🎨 [Frontend] Enh: Show deleting files progress

- services/web/server/src/simcore_service_webserver/projects/_crud_api_create.py
Revert message as it was before arrival of storage HA.
> 🐛Webserver: duplication of studies, ensure message does not contain progress

- scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
> 🎨Monitoring script: allow to terminate non-billable clusters

- services/api-server/src/simcore_service_api_server/models/schemas/_base.py
- Fix bug introduced https://github.com/ITISFoundation/osparc-simcore/pull/7447 due to my eager use of AI when refactoring. This fix has been manually tested.
- The bug prevented the new `Programs` section from being functional. E.g. 
would always return 500 because it cannot construct the program object internally.
> 🐛 Dont freeze fields in `ApiServerOutputSchema`

- services/docker-api-proxy/Dockerfile
- services/docker-api-proxy/docker/entrypoint.sh
Replaced `gosu` with drop-in replacement `su-exec`. This allows the image to be build for different architectures other than amd64 linux
> ♻️ making `docker-api-proxy` buildable on arm

- services/static-webserver/client/source/class/osparc/dashboard/NewPlusMenu.js
- services/static-webserver/client/source/resource/osparc/ui_config.json
Hypertools (if any available), have their own menu in the new-menu. All templates marked as ``project.ui.templateType===hypertool`` will be listed there.
- related to https://github.com/ITISFoundation/private-issues/issues/7
> 🎨 [Frontend] Hypertools in menu

- packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
- shall fix the fail fast mechanism
- shall fix tip test constantly failing due to missing yield
> 🎨E2E: fixing fail fast when websocket messages missing, fixing missing yield

- packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
> 🎨 E2E: Handle success value to True when no messages came in

- .github/workflows/_reusable-build-images.yml
- .github/workflows/ci-arm-build.yml
- .github/workflows/ci-pact-master.yml
- .github/workflows/ci-testing-deploy.yml
- .github/workflows/ci-testing-pull-request.yml
- packages/common-library/src/common_library/pydantic_basic_types.py
This pull request introduces several updates to GitHub Actions workflows, focusing on reusability, dependency updates, and environment configuration improvements. The most significant changes include the addition of a reusable workflow for building Docker images, updates to the `uv` setup action version, and environment variable adjustments to address compatibility issues.
* Added a new reusable workflow in `.github/workflows/_reusable-build-images.yml` for building backend and frontend Docker images. This workflow supports configurable inputs and outputs for flexibility across different jobs.
* Refactored `ci-testing-deploy.yml` to use the new reusable workflow for Docker image builds, replacing repetitive steps with a simplified `uses` directive. …
> ♻️CI: Upgraded setup-uv to v6, try fix ARM build, modularization of CI file

- .github/workflows/ci-arm-build.yml
- packages/service-integration/Dockerfile
> 🐛⚗️ARM CI: build fail in CI on ARM

- .github/workflows/_reusable-build-images.yml
- .github/workflows/ci-testing-deploy.yml
- services/agent/Dockerfile
- services/api-server/Dockerfile
- services/autoscaling/Dockerfile
- services/catalog/Dockerfile
- services/clusters-keeper/Dockerfile
- services/dask-sidecar/Dockerfile
- services/datcore-adapter/Dockerfile
- services/director-v2/Dockerfile
- services/director/Dockerfile
- services/dynamic-scheduler/Dockerfile
- services/dynamic-sidecar/Dockerfile
- services/efs-guardian/Dockerfile
- services/invitations/Dockerfile
- services/migration/Dockerfile
- services/notifications/Dockerfile
- services/payments/Dockerfile
- services/resource-usage-tracker/Dockerfile
- services/storage/Dockerfile
- services/web/Dockerfile
> ⚗️CI: Improvements and addition ARM64 fixes

- services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json
- 🐛 fix project-v0.0.1.json schema
- fixes api test that started to fail after https://github.com/ITISFoundation/osparc-simcore/pull/7677
> 🐛 fix project-v0.0.1.json schema

- services/efs-guardian/requirements/_base.txt
- services/efs-guardian/requirements/_test.txt
- services/resource-usage-tracker/requirements/_base.txt
- services/resource-usage-tracker/requirements/_test.txt
- services/web/server/requirements/_base.txt
- services/web/server/requirements/_test.txt
- ♻️ upgrade `markupsafe`
Now all code base is on the latest version
> ♻️ upgrade `markupsafe`

- services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py
- 🐛 fix wrong project name in billing center usage view for computational services (before there was "undefined-metadata")
- reported by @capbrown
> 🐛 fix wrong project name in billing center usage view

- services/static-webserver/client/source/class/osparc/editor/HtmlEditor.js
- services/static-webserver/client/source/class/osparc/editor/MarkdownEditor.js
- services/static-webserver/client/source/class/osparc/editor/TextEditor.js
- services/static-webserver/client/source/class/osparc/info/CommentUI.js
- services/static-webserver/client/source/class/osparc/utils/Avatar.js
- services/static-webserver/client/source/resource/osparc/ui_config.json
This reverts commit c6d1b64a6b7a1e176dc1f751c694bfbe63d72716. to unblock master
> Revert "🎨 [Frontend] Second app on Sim4Life.lite (#7807)"

- tests/e2e-playwright/tests/sleepers/test_sleepers.py
> 🐛E2E playwright: fix flakyness

- services/web/server/tests/data/default_app_config-integration.yaml
fixes issues in integration tests introduced by https://github.com/ITISFoundation/osparc-simcore/pull/8199
> 🐛Fixes webserver integration tests

- services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json
Changes introduced by https://github.com/ITISFoundation/osparc-simcore/pull/8170 did not trigger the api tests in the CI. This fixes the failure in master CI.
> ⬆️ Webserver node locking: missing change

- services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_api_keys.py
> 🐛 Remove redundant logging for each expired API key removal
