packages/models-library/src/models_library/api_schemas_resource_usage_tracker/pricing_plans.py
packages/models-library/src/models_library/resource_tracker.py
packages/models-library/src/models_library/wallets.py
services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_utils.py
services/director-v2/src/simcore_service_director_v2/modules/resource_usage_tracker_client.py
services/director-v2/tests/unit/test_modules_dynamic_sidecar_scheduler.py
services/director-v2/tests/unit/with_dbs/test_api_route_computations.py
services/resource-usage-tracker/openapi.json
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/models/resource_tracker_pricing_units.py
services/resource-usage-tracker/tests/unit/with_dbs/test_api_resource_tracker_pricing_plans.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py

🐛Computational backend: re-enable service resources override

---

.vscode/settings.template.json
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
tests/e2e/utils/wait_for_services.py

- removed deprecated entries in vscode ```.settings-template.yml```
- wait longer in e2e testing
- #packages before: 61
- #packages after : 69
|   1 | aio-pika                  | 9.1.2           | 9.3.0      | *minor*    | 1 | autoscaling⬆️ |
|   2 | aioboto3                  | 10.4.0          | 12.0.0     | **MAJOR**  | 1 | autoscaling⬆️ |
|   3 | aiobotocore               | 2.4.2           | 2.7.0      | *minor*    | 1 | autoscaling⬆️ |
|   4 | aiofiles                  | 23.1.0          | 23.2.1     | *minor*    | 1 | autoscaling⬆️ |
|   5 | aiohttp                   | 3.8.5           | 3.8.6      |            | 1 | autoscaling⬆️ |
|   6 | aiormq                    | 6.7.6           | 6.7.7      | …

⬆️Maintenance: upgrade autoscaling

---

services/payments/requirements/_base.txt
services/payments/requirements/_test.txt
services/payments/requirements/_tools.txt

Updates dependencies of `payments` service
- #packages before: 29
- #packages after : 30
|   1 | aio-pika                  | 9.2.2           | 9.3.0      | *minor*    | 1 | payments⬆️ |
|   2 | aiohttp                   | 3.8.5           | 3.8.6      |            | 1 | payments⬆️ |
|   3 | alembic                   | 1.11.3          | 1.12.1     | *minor*    | 1 | payments⬆️ |
|   4 | anyio                     | 3.7.1           | 4.0.0      | **MAJOR**  | 2 | payments⬆️🧪 |
|   5 | arrow                     | 1.2.3           | 1.3.0      | *minor*    | 1 | payments⬆️ |
|   6 | cffi                      | 1.15.1          | 1.16.0     | *minor*    | 1 | payments⬆️ |
|   7 | charset-normalizer        | …

  ⬆️ Maintenance: upgrades payments service requirements

---

services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/requirements/_tools.txt

- #packages before: 34
- #packages after : 35
|   1 | aio-pika                  | 9.2.2           | 9.3.0      | *minor*    | 1 | clusters-keeper⬆️ |
|   2 | aioboto3                  | 11.3.0          | 12.0.0     | **MAJOR**  | 1 | clusters-keeper⬆️ |
|   3 | aiobotocore               | 2.6.0           | 2.7.0      | *minor*    | 1 | clusters-keeper⬆️ |
|   4 | aiohttp                   | 3.8.5           | 3.8.6      |            | 2 | clusters-keeper⬆️🧪 |
|   5 | anyio                     | 3.7.1           | 4.0.0      | **MAJOR**  | 2 | clusters-keeper⬆️🧪 |
|   6 | arrow                     | 1.2.3           | 1.3.0      | *minor*    | 1 | clusters-keeper⬆️ |
|   7 | black                     | …

⬆️ Maintenance: upgrade of clusters-keeper

---

services/storage/requirements/_base.txt
services/storage/requirements/_test.txt
services/storage/requirements/_tools.txt

- #packages before: 41
- #packages after : 41
|   1 | aio-pika                  | 9.2.2           | 9.3.0      | *minor*    | 1 | storage⬆️ |
|   2 | aioboto3                  | 11.3.0          | 12.0.0     | **MAJOR**  | 1 | storage⬆️ |
|   3 | aiobotocore               | 2.6.0           | 2.7.0      | *minor*    | 1 | storage⬆️ |
|   4 | aiohttp                   | 3.8.5           | 3.8.6      |            | 2 | storage⬆️🧪 |
|   5 | alembic                   | 1.11.3          | 1.12.1     | *minor*    | 1 | storage⬆️ |
|   6 | arrow                     | 1.2.3           | 1.3.0      | *minor*    | 1 | storage⬆️ |
|   7 | asyncpg                   | 0.28.0          | 0.29.0     | *minor*    | 1 | …

⬆️ Maintenance: Upgrade of storage

---

services/api-server/src/simcore_service_api_server/models/schemas/profiles.py
services/web/server/src/simcore_service_webserver/users/schemas.py

- Add the `user_id` to the `get_profile` endpoint on the api-server. I will need this to investigate running instances in AWS
- https://github.com/ITISFoundation/osparc-issues/issues/1180

🎨 Add `user_id` to api server profile

---

packages/service-library/requirements/_fastapi.in
packages/service-library/requirements/_fastapi.txt
packages/service-library/requirements/_test.in
packages/service-library/requirements/_test.txt
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters_management_task.py
services/clusters-keeper/tests/unit/conftest.py
tests/environment-setup/test_requirements.py
tests/environment-setup/test_used_docker_compose.py

- In PR https://github.com/ITISFoundation/osparc-simcore/pull/4982 I did a mistake by adding a testing library like `respx` in a base listing. This propagated into the cluster-keeper  after https://github.com/ITISFoundation/osparc-simcore/pull/4997
- Adds a tests that detects some test libraries in base requirements listing
- EXTRA: adds patch by @sanderegg that might fix timeout error in cluster-keeper tests.
- Fixes requirements modified in https://github.com/ITISFoundation/osparc-simcore/pull/4982
- Fixes problem caused in https://github.com/ITISFoundation/osparc-simcore/pull/4997
- adds a test that check for some common test libraries
None

🔨 Removes `respx` library from base requirements listing (`fastapi.in`)

---

.pre-commit-config.yaml
scripts/precommit/pytest-testit.bash
services/autoscaling/requirements/_base.in
services/autoscaling/requirements/_base.txt
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py
services/autoscaling/src/simcore_service_autoscaling/utils/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/computational_scaling.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_modules_ec2.py
services/autoscaling/tests/unit/test_utils_computational_scaling.py
services/clusters-keeper/tests/unit/conftest.py

- drained node instance resources were computed using docker facilities instead of EC2, thus leading to an infinite creation of EC2 instance.
- fixes time to terminate
- shows logs before terminating in info
- adds a pre-commit hook to check for pytest.mark.testit
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4999

🐛Prevent autoscaling from creating workers indefinitely

---

services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py

Some issues are difficult to reproduce locally, such as a full docker swarm.
Therefore some additional logs are needed to better understand the issue that the autoscaling does not scale up by more than 1 machine when multiple s4l are started.

♻️Autoscaling: Debug logs for issue with scaling up

---

.vscode/extensions.json
.vscode/settings.template.json
README.md

Taking advantage that I had to do a full installation from scratch  I updated some of the doc and default settings
- updates README: mainly installation instructions
- updates vscode settings
- launcher (rm invalid entries)
- settings (rm deprecated entries)
- recommended extensions
None
None
None

📝 Maintenance: cleanup readme and vscode settings

---

services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_base.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_dynamic.py
services/autoscaling/src/simcore_service_autoscaling/utils/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/computational_scaling.py
services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py
services/autoscaling/tests/manual/.env-devel
services/autoscaling/tests/manual/Makefile
services/autoscaling/tests/manual/README.md
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_utils_computational_scaling.py
services/autoscaling/tests/unit/test_utils_dynamic_scaling.py

This PR fixes the following issue:
- dynamic autoscaling service setup
- creating dynamic services does create a new machine and goes there
- creating another service **does not** create a new machine and the service stays forever
root cause:
- autoscaling analyzes the current cluster and divides it in active, pending, drained and missing nodes respectively,
- it then tries to assign the "unrunnable" tasks to these 4 types of nodes in this order,
- it was not subtracting the current usage of the active node, therefore always thinking there were enough machines around.
Testing can only be made directly on AWS machines, which makes testing a bit annoying.
to @pcrespov : I will not refactor yet the filter function as I do not want to break this now again. especially since testing is tedious.

🐛Dynamic autoscaling: not scaling beside 1 machine

---

packages/dask-task-models-library/requirements/_base.in
packages/dask-task-models-library/requirements/ci.txt
packages/dask-task-models-library/requirements/dev.txt
packages/dask-task-models-library/src/dask_task_models_library/container_tasks/events.py
packages/dask-task-models-library/src/dask_task_models_library/container_tasks/io.py
packages/dask-task-models-library/src/dask_task_models_library/container_tasks/protocol.py
packages/dask-task-models-library/tests/container_tasks/test_events.py
packages/dask-task-models-library/tests/container_tasks/test_protocol.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/tasks.py
services/dask-sidecar/tests/unit/conftest.py
services/dask-sidecar/tests/unit/test_dask_utils.py
services/dask-sidecar/tests/unit/test_file_utils.py
services/dask-sidecar/tests/unit/test_tasks.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/unit/_dask_helpers.py
services/director-v2/tests/unit/test_modules_dask_client.py
services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py

This PR brings:
- refactoring/cleaning of the dask-sidecar remote function signature
- allows to pass optional _parent_node_id_ and _parent_project_id_ arguments to the computational job, which is also passed back through the logs/progress events
- _director-v2_ then sends the logs of the node in the _logs_ exchange in RabbitMQ using both the topic of the current project id and of the parent project id if it exists, which means that the _logs_ pane in the GUI shows the logs of a computational service started by a parent service through the public API (sim4life use-case)

✨Dask sidecar: pass job origin and show child computational service logs in workbench

---

services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/test_utils_docker.py

This PR adds the ```--ignore-pull-failures``` flag such that if an invalid image is pulled using the pull script it will not fail the other image pulls but complete them.

✨Docker pull script uses --ignore-pull-failures flag

---

services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py

This PR ensures the same computation is done when autoscaling service tests if a service may fit in a machine and after the machine was created.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5071

🐛Dynamic autoscaling creates new machines indefinitely due to bad specifictions of service

---

services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py

This PR changes slightly how progress of a computational service is reported by weighting the parsed progress with a value of 0.99.
This will fix the issue where a job is hitting 100% progress but which state is still not one of FAILED/SUCCESS. This confused users. Running the container will amount to 99% progress, the remaining 1% is basically reserved for uploading outputs/service logs.
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1181

🐛♻️ Comp backend: progress of a processing container is now limited to 99%

---

services/dask-sidecar/src/simcore_service_dask_sidecar/utils.py

This PR changes slightly how the dask-sidecar detects the number of GPUs by imposing Docker default log-driver to use.
After testing it came as a surprise that the number of GPUs on a multi-gpu machine was reported wrong!
The machine was setup as such:
```bash
cat /etc/docker/daemon.json
{
"metrics-addr": "0.0.0.0:9323",
"experimental": true,
"default-runtime": "nvidia",
"runtimes": {
"nvidia": {
"path": "/usr/bin/nvidia-container-runtime",
"runtimeArgs": []
}
},
"log-driver": "gelf",
"log-opts": {
"gelf-address": "udp://0.0.0.0:12201"
},
"data-root": "/mnt/docker/data",
"exec-root": "/mnt/docker/exec",
"default-address-pools": [
{
"base": "172.17.0.0/12",
"size": 20
},
{
"base": "192.168.0.0/16",
"size": 24
}
]
}
```
Note that the log-driver is set to _gelf_ and probably the url is wrong …

🐛Dask-Sidecar: improper detection of GPUs on multi-GPU machines if log-driver is improperly set

---

packages/service-library/src/servicelib/archiving_utils.py
packages/service-library/src/servicelib/progress_bar.py
packages/service-library/tests/test_progress_bar.py
packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py
packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port.py
packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py
packages/simcore-sdk/tests/integration/test_node_data_data_manager_.py
packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py
packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py
packages/simcore-sdk/tests/integration/test_node_ports_v2_nodeports2.py
packages/simcore-sdk/tests/unit/test_node_data_data_manager.py
packages/simcore-sdk/tests/unit/test_node_ports_common_file_io_utils.py
packages/simcore-sdk/tests/unit/test_node_ports_v2_nodeports_v2.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py
services/dask-sidecar/tests/unit/test_tasks.py
services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_manager.py
services/storage/src/simcore_service_storage/simcore_s3_dsm.py
services/web/server/src/simcore_service_webserver/director_v2/_core_dynamic_services.py

**This PR brings some refactoring and new features to the _ProgressBarData_ class:**
**This PR also refactors the main dask-sidecar function:**

♻️✨Comp backend: refactor progress + allow internal progress bar to use weights

---

services/director-v2/src/simcore_service_director_v2/modules/dask_clients_pool.py
services/storage/src/simcore_service_storage/exceptions.py
services/storage/src/simcore_service_storage/handlers_files.py
services/storage/src/simcore_service_storage/simcore_s3_dsm.py

This PR fixes the issue where using on-demand clusters would not properly use S3 file types but instead were locked on presigned links.
This had the consequence of limiting uploads to max 5Gib, but is also the sad fact that we still do not properly fixed it by using the public API from the dask-sidecars.
Use a python runner and run the following script:
```python
import os
def generate_large_file(file_path, size_gb):
with open(file_path, "wb") as f:
chunk_size = 1024 * 1024  # 1 MB chunks
for _ in range(size_gb * 1024):
data = os.urandom(chunk_size)
f.write(data)
def create_file():
desired_file_path = "/outputs/large_file.txt"
desired_size_gb = 6  # Adjust this to your desired size in gigabytes
generate_large_file(desired_file_path, desired_size_gb)
print(f"Large file created: …
```

🐛Correctly handle file type of on-demand clusters

---

packages/dask-task-models-library/src/dask_task_models_library/resource_constraints.py
packages/dask-task-models-library/tests/test_resource_constraints.py
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/dask.py
services/autoscaling/src/simcore_service_autoscaling/utils/computational_scaling.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py

During testing it was found that in the use case where  a user starts 16 jobs:
- no cluster workers are created because the autoscaling is currently set with ```EC2_INSTANCES_MAX_INSTANCES``` set to 10,
- the autoscaling services completely refuses to create any instance
This PR changes that behavior by creating up to ```EC2_INSTANCES_MAX_INSTANCES``` instances (currently hard-coded to 10) so that the computation may still go through.
also includes:
https://github.com/ITISFoundation/osparc-simcore/pull/5137

🐛Bugfix/autoscaling does not scale above limit

---

packages/aws-library/src/aws_library/ec2/models.py

this PR let the regex be more flexible (even though it is not strictly speaking compatible with AWS tag values)

🐛 Less stringent regex for AWS tag value

---

scripts/maintenance/computational-clusters/README.md
scripts/maintenance/computational-clusters/osparc_clusters.py
scripts/maintenance/requirements.txt

This PR brings a new monitoring tool based on the fabulous Typer library.
It allows to get an instant screenshot of the autoscaling situation by running the following:
```bash
cd scripts/maintenance
make
cd computational-clusters
./osparc-clusters.py --help # will show the help
./osparc-clusters.py PATH_TO_SIM4LIFE.IO/repo.config --ssh-key-path=PATH_TO_SSH_KEY_SIM4LIFE.IO
```
this will show something like the below:

✨Monitoring tools: CLI to monitor what is going on

---

scripts/maintenance/computational-clusters/Makefile
scripts/maintenance/computational-clusters/osparc_clusters.py
scripts/maintenance/computational-clusters/requirements.txt

✨Monitoring tools: show more information about computational clusters

---

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_user_services.py

Something is fishy with the internals of the `director-v2`. Without any external inputs it decides to shut down services.
Adding some extra log lines in oder to figure out what exactly is causing this.

✨ Extending logging while starting new style dynamic services

---

packages/service-library/src/servicelib/background_task.py
packages/service-library/src/servicelib/decorators.py
packages/service-library/tests/test_decorators.py
services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_base.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/resource_tracking/_core.py
services/dynamic-sidecar/tests/unit/test_api_workflow_service_metrics.py

The heart beat was sent as soon as the service was started. Since the order of events is not guaranteed, it can arrive before the start event.
With @matusdrobuliak66 we have decided to skip the first heartbeat event.
Bonus:
- fixes flaky tests in `tests/unit/test_modules_dynamic_sidecar_client_api_base.py`: `test_connection_error` and possibly flaky `test_retry_on_errors_by_error_type` 
- https://github.com/ITISFoundation/osparc-simcore/issues/5169

♻️ do not send heartbeat as soon as the service is started

---

packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/dynamic_scheduler/services.py

To avoid possible regressions, bump timeout of the client from 5 to 20 seconds. This timeout comes form the aiohttp client used inside the webserver to comunicate with the director-v2.

♻️ Aligned default timeout with the old client

---

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events.py
services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py

The director-v2 was asking for the default pricing info for some unknown reason??
it is already passed by the webserver.

🐛Dynamic scheduler is using the wrong information for hardware info

---

services/web/server/src/simcore_service_webserver/projects/projects_api.py

Increases the CPU margin by 0.2

⚗️Dynamic backend: need more CPUs for dy-proxy

---

.github/workflows/ci-testing-deploy.yml
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
services/director-v2/src/simcore_service_director_v2/utils/comp_scheduler.py

This PR tries to fix/improve the issue where:
- a task is submitted to an external cluster (the cluster gets created), task is in WAITING_FOR_CLUSTER state
- at some point the cluster primary (with dask-scheduler) comes up and the dask client submits the job
- it seems that under load when the director-v2 asks for the task the dask-scheduler does not know *yet* of the task and then it is correctly reported as UNKNOWN
- the director-v2 then wrongly triage that task to be STARTED and at the same time COMPLETED, and sends a *start event* over the wire to ResourcesUsageTracker (RUT) (that is the wrong one)
- during the time when the task is waiting, no *heartbeat event* is sent to RUT, which considers the task as FAILED
- later the task appears in the dask-scheduler, and is eventually …

🐛⚗️Computational backend: tasks in UNKNOWN state are sometimes only temporarily in that state

---

services/web/server/src/simcore_service_webserver/projects/_project_nodes_pricing_unit_handlers.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py

Sometimes a project service resources are empty due to historical reasons.
This PR allows to use defaults in case this happens and will fill the missing data on the go.
Potentially shall be hotfixed to sim4life.io

🐛Hotfix: Dynamic-backend shall work even if resources were initially empty

---

scripts/maintenance/computational-clusters/README.md
scripts/maintenance/computational-clusters/osparc_clusters.py
scripts/maintenance/computational-clusters/requirements.txt

new commands to clean dask-scheduler jobs (TO USE WITH CARE).
some improvements in displaying the computational clusters.
new commands:
```bash
❯ ./osparc_clusters.py --help
Usage: osparc_clusters.py [OPTIONS] COMMAND [ARGS]...                                                                                                                                                                                                                                                          
Manages external clusters                                                                                                                                                                                                                                                                                      
╭─ Options …
```

🎨Improving computational clusters cli monitoring tool

---

packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/clusters_keeper/clusters.py
services/clusters-keeper/tests/unit/conftest.py
services/clusters-keeper/tests/unit/test_rpc_clusters.py

when running many jobs through the public API, we actually create as many projects as jobs for 1 same user.
When starting them all at the same time, we actually need to _get_or_create_ the very same cluster at the same time which means there are as many very same call to the clusters-keeper via RPC, then locking a distributed lock, then calling into AWS.
This PR ensures that:
- the call for the very same cluster are sent in sequence instead of concurrently
- the call for the very same cluster are cached 5 seconds
In effect, this prevents calls from going more often than once every 5 seconds for the same user_id/wallet_id combination

🐛Clusters-keeper: calling >100 times for the same new cluster now returns cached information

---

packages/service-library/src/servicelib/fastapi/httpx_utils.py
packages/service-library/src/servicelib/logging_utils.py
packages/service-library/src/servicelib/utils_secrets.py
packages/service-library/tests/fastapi/test_httpx_utils.py
packages/service-library/tests/test_utils_secrets.py
services/director-v2/src/simcore_service_director_v2/modules/osparc_variables_substitutions.py

Fixes `Clear-text logging of sensitive information` detected by code-scanning alerts 27, 28, 29 (in osparc variables), 18 (in log decorators) and 
- ✨ adds `mask_sensitive_data` to mask values in a `dict[str, Any]`
- ♻️ uses `mask_sensitive_data` in existing log functions
Unnecessary logs:
- https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/29
- https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/28
- https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/27
Mask secrets in logs:
- https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/18

🔒️ Maintenance: Fixes issues detected by code scanning

---

services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
tests/e2e-playwright/Makefile
tests/e2e-playwright/requirements/_test.in
tests/e2e-playwright/requirements/_test.txt
tests/e2e-playwright/utils/wait_for_services.py

This PR adds some tracing logs that might prove useful when looking at computational jobs after they were run and the cluster was terminated.
Bonus:
- adds retry mechanism in e2e playwright tests to retry giving access to services

✨Computational backend: add helpful tracing log

---

.github/CODEOWNERS
packages/postgres-database/src/simcore_postgres_database/migration/versions/392a86f2e446_all_users_must_have_a_product.py

This PR adds a migration script that will assign the default product on all `ACTIVE` users that have no product associated. This will guarantee that all ACTIVE users have at least an associated product
- This is a pre-condition for the product-based login #5117 
- This scenario is encountered on users created **before** the product feature was created. Currently all new users are automatically added to a product (see invitation workflow)
Before the migration some active users might not have at least a product group. After the migration all users should have a product group. 
To see the default product run ... and check the first
```sql
SELECT p.group_id, p.name
FROM products p
WHERE p.group_id IS NOT NULL
ORDER BY p.priority ASC
```            
Run this query **before** (should list users …

🔨  Ensures all active users have at least a product's group (🗃️)

---

packages/service-library/src/servicelib/redis_utils.py
packages/service-library/tests/test_redis.py
packages/service-library/tests/test_redis_utils.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/prometheus_metrics.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/resource_tracker.py

Some services like `resource-usage-tracker` and `dynamic-scheduler` require to run periodic tasks that run once regardless of the number of running instances (whether this number is 1 or higher).
- ✨ added tests for `exclusive` decorator
- ♻️ refactored solution form `resource-usage-tracker` to receive a generic task to run at periodic intervals
- ♻️ `resource-usage-tracker` now uses `start_exclusive_periodic_task`
- required by https://github.com/ITISFoundation/osparc-simcore/pull/5212

♻️ Adds `start_exclusive_periodic_task` derived from resource usage tracker service

---

packages/service-library/src/servicelib/redis_utils.py
packages/service-library/tests/test_redis_utils.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/resource_tracker.py

The interval parameters were unintentionally swapped.
- ✨ added new `exclusive_task_starter_interval` default to 1 second which can be overwritten
- 🐛 fixed resource usage tracker to work as previously intended

🐛 Fixed unintentional interval swapping for `start_exclusive_periodic_task`

---

packages/pytest-simcore/src/pytest_simcore/environment_configs.py
packages/pytest-simcore/src/pytest_simcore/helpers/typing_env.py
packages/pytest-simcore/src/pytest_simcore/helpers/utils_envs.py
packages/settings-library/src/settings_library/base.py
packages/settings-library/tests/conftest.py
packages/settings-library/tests/test_base.py
packages/settings-library/tests/test_email.py

Some configurations with  `BaseCustomSettings` subclasses raised `TypeError: issubclass() arg 1 must be a class`. 
This is raised by `issubclass` when using pydantic subclasses (e.g. `BaseCustomSettings` inherits from `BaseSettings`) in combination with "composed" types as `dict[str, str]`.
```cmd
>>> issubclass(dict[str, str], dict)
False
>> issubclass(dict[str, str], BaseSettings)
File "<string>", line 1, in <module>
File "/home/crespo/.pyenv/versions/3.10.13/lib/python3.10/abc.py", line 123, in __subclasscheck__
return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```
Some more information and references to pydantic issues are provided in the code's tests
Tests that reproduces the bug in 
```cmd
cd …
```

🐛Fixes `TypeError: issubclass() arg 1 must be a class` while building BaseCustomSettings classes

---

services/director-v2/src/simcore_service_director_v2/models/dask_subsystem.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_core.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/unit/test_modules_dask_client.py
services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py

This PR fixes https://github.com/ITISFoundation/osparc-simcore/issues/5237 by:
- **NOT** swallowing a raised exception
- a bit of refactoring
I will intentionally not undergo heavy refactoring now
fixes https://github.com/ITISFoundation/osparc-simcore/issues/5237

🐛Fix infinite Waiting for cluster when dask-scheduler is restarted

---

scripts/mypy/requirements.txt
services/web/server/requirements/_base.in
services/web/server/requirements/_base.txt
services/web/server/requirements/_test.in
services/web/server/requirements/_test.txt
services/web/server/requirements/_tools.in
services/web/server/requirements/_tools.txt
services/web/server/src/simcore_service_webserver/catalog/_api.py
services/web/server/src/simcore_service_webserver/catalog/_models.py
services/web/server/src/simcore_service_webserver/catalog/client.py
services/web/server/tests/unit/isolated/test_catalog_models.py

This PR analyses and provides a temporary solution for the incident #5267 that reports very long delays in `GET /catalog/services` entrypoint. In addition the front-end can at time spawn up to 17 parallel calls to this entrypoint point (probably due to some retry mechanism)
We are well aware that the original design does not scale with the amount of services. A proper resolution of this issue therefore requires a redesign that should incorporate at least _pagination_ and lighter item objects with bounded fields.
For the moment we decided to go with a strategic TTL cache that will reduce the overhead of postprocessing **every service item** in the webserver. Note that the webserver does not just forward the service object provided by the `catalog` service but also computes and adds some …

🎨 Reduces response time of catalog/services listing entrypoint

---

services/docker-compose-ops.yml
services/docker-compose.yml

In preparation for https://github.com/ITISFoundation/osparc-simcore/pull/5212
I have already merged https://github.com/ITISFoundation/osparc-ops-environments/pull/501 which requires Redis to start one extra db. This will fix redis commander on master.

✨Adds new Redis database

---

services/web/server/tests/unit/isolated/test_security_api.py

`test_time_overhead_on_handlers_of_auth_decorators` would run sequentially two requests (w/ and w/o auth) and compare their times to make sure the overhead of `auth_decorators` was bound. 
@sanderegg correctly pointed out that this test was not well defined since in the CI multiple tests are run in parallel and we cannot control how busy the machines are . Therefore even if in the original test we do a relative comparison, we cannot guarantee that each of the individual runs were done in "equivalent" conditions.
To resolve this issue, this test has been refactored to run multiple times each request and compute use the median of each of the runs do the comparison ( Note that the mean is strongly affected by outliers and is not necessarily a typical example of the data points. For a more …

♻️ fixes flaky test_time_overhead_on_handlers_of_auth_decorators

---

services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py

Since the AMI shall already have the AWS-cli installed. there is no need to do it here.
This will make startup faster.

🎨 Clusters-keeper: No need to install AWS CLI, it is already in AMI

---

scripts/maintenance/computational-clusters/osparc_clusters.py

- Enhance the osparc_clusters.py script to be compatible with the newly added dask certificates
- also computes the remaining disk space on the ```/docker``` partition for dynamic autoscaled EC2s
- simplify the usage of the script by just pointing to the deploy-config location in the osparc-ops-deployment-configuration/deployments/

🎨Maintenance: add dask security to clusters maintenance script

---

services/api-server/src/simcore_service_api_server/services/catalog.py
services/web/server/src/simcore_service_webserver/catalog/_api.py
services/web/server/src/simcore_service_webserver/catalog/_models.py
services/web/server/tests/unit/isolated/test_catalog_models.py

- 🐛 Fixes missing outputs in hash key generator. In the logs, we found that a request like `GET /v0/catalog/services/simcore/services/dynamic/jupyter-smash/3.0.7/inputs:match` responds 500 due to
```log
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/catalog/_handlers.py", line 199, in get_compatible_inputs_given_source_output
data = await _api.get_compatible_inputs_given_source_output(
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/catalog/_api.py", line 180, in get_compatible_inputs_given_source_output
service_output = await get_service_output(
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/catalog/_api.py", line 234, in get_service_output
ServiceOutputGetFactory.from_catalog_service_api_model(servic …
```

🐛 🚑️ Fixes internal server error in port matching

---

Makefile
packages/pytest-simcore/src/pytest_simcore/simcore_services.py
services/docker-compose-build.yml
services/docker-compose-deploy.yml
services/docker-compose.devel.yml
services/docker-compose.local.yml
services/docker-compose.yml
services/dynamic-scheduler/tests/conftest.py

Due to limitations in how long the hostnames are, on some deployments it is not possible to use the full name `dynamic-scheduler`, instead using `dynamic-schdlr` will work.
- addresses https://github.com/ITISFoundation/osparc-ops-environments/issues/503

Renaming `dynamic-scheduler` in docker-compose files

---

services/web/server/src/simcore_service_webserver/studies_dispatcher/_errors.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_users.py

This PR aims to remove a recent "flaky" test in master
```
FAILED tests/unit/with_dbs/01/studies_dispatcher/test_studies_dispatcher_studies_access.py::test_guest_user_is_not_garbage_collected[64] - AssertionError: Expected /study/uuid, got /error?message=We+have+reached+the+maximum+of+anonymous+users+allowed+the+platform.+Please+try+later+or+login+with+a+registered+account.&status_code=429
```
It enhances error handling and cleanup during creation of guest users in the `studies_dispatcher` plugin.
Part of
- https://github.com/ITISFoundation/osparc-simcore/issues/3421
- https://github.com/ITISFoundation/osparc-simcore/issues/3977
None

🎨 Fixes flaky `test_studies_dispatcher_studies_access`

---

packages/service-library/src/servicelib/rabbitmq/_client.py
packages/service-library/tests/rabbitmq/test_rabbitmq.py

There was a double that having no subscribers attached could send the message in an infinite loop between the delay queue and the main queue. This does not happen.

🎨 Add extra tests for no registered subscriber when using `RabbitMQClient.subscribe`

---

services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/payments/_socketio.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py
services/web/server/src/simcore_service_webserver/socketio/_handlers.py
services/web/server/src/simcore_service_webserver/socketio/messages.py
services/web/server/src/simcore_service_webserver/socketio/server.py
services/web/server/tests/integration/02/conftest.py
services/web/server/tests/integration/02/notifications/test_rabbitmq_consumers.py
services/web/server/tests/unit/isolated/notifications/test_rabbitmq_consumers.py
services/web/server/tests/unit/with_dbs/03/wallets/payments/test_payments.py
services/web/server/tests/unit/with_dbs/03/wallets/payments/test_payments_methods.py

The problem reported in **incident 48** (see related issues) indicate that the `socketio` exchange is overloaded with messages that are not attended. Those seem to be produced by those queued from the web-server's `emit` call. Most of those calls do not actually need to be queued because the client is directly connected to that server!
- 🎨 [Disabled queue](https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/async_server.py#L155-L161) when message was directly delivered to the client to avoid filling `socketio` exchange with messages going to and back to the server
- 🎨stopped `gathering` the `emit` coroutines since the latter is not [designed to run concurrently](https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/async_server.py#L163-L167). …

🎨 Enhances setup to remediate accumulation of messages in socketio exchange

---

Makefile
services/autoscaling/requirements/_base.txt
services/autoscaling/src/simcore_service_autoscaling/core/application.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py

https://github.com/ITISFoundation/osparc-simcore/pull/5340 introduced a big change on how nodes are treated.
A few issues were found that this PR should fix:
- terminating node was relying on the docker node _UpdatedAt_ field which is not changed anymore the same way as when the node was drained/activated via docker facilities
- the label for osparc readyness was changed to follow inverse URL notations
NOTE: these changes are compatible with both modes.

🐛 Autoscaling: issues with labelled drained nodes

---

services/docker-compose-ops.yml

Leaving quotes around this path, makes docker compose translate this into '"/data"', which generates a path with quotes in it, and makes minio store data in its container instead of the minio volume
Remove the quotes around "/data" in docker compose
(at least for Docker Compose version v2.24.5)
Enable minio in a local deployment. Run: 
make up-prod
Put some data in the minio store, but for example uploading some file to a local osparc study. Run:
make down; make leave; make down;
Next time when run make up-prod, the data in Minio is gone.
One can also attach to the minio container with portainer, and verify the location of the data. After the fix it should be in /data, before the fix the data will be in a directory called '"' in the /
- [ X ] No ENV changes or I properly updated ENV …

 🐛 Remove quotes around "/data" in MINIO_VOLUMES var

---

packages/pytest-simcore/src/pytest_simcore/playwright_utils.py
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/jupyterlab.py
tests/e2e-playwright/tests/resource_usage_tracker.py
tests/e2e-playwright/tests/sim4life.py
tests/e2e-playwright/tests/sleepers/conftest.py
tests/e2e-playwright/tests/sleepers/sleepers.py

After reviewing the e2e with @sanderegg we thought _it might be handy to have timestamps to measure how long it take a particular section of the the test_. 
The standard way to solve this is to use a proper logger instead of `print`. In addition, this PR implements some extra convenience utilities to simplify logging scopes/sections. For that we have a *log context* and a separate *formatter class* to include indentation in the messages as the context managers get nested. 
A dedicated `pytest_simcore.playwritght_utils.test_logger` in setup with that formatter. Note that indentation mechanism is therefore optional. You just have to use another logger.
To demo this utility I first enabled the [live log](https://docs.pytest.org/en/7.1.x/how-to/logging.html#live-logs) with timestamps and some …

🔨  Adds logs in e2e with timestamps

---

services/payments/src/simcore_service_payments/api/rpc/_payments_methods.py
services/payments/src/simcore_service_payments/services/auto_recharge_process_message.py
services/payments/src/simcore_service_payments/services/notifier.py
services/payments/src/simcore_service_payments/services/notifier_abc.py
services/payments/src/simcore_service_payments/services/notifier_email.py
services/payments/src/simcore_service_payments/services/payments.py
services/payments/tests/unit/test_services_payments.py

This PR sends also send an email to the user for a succesful payment using a saved payment method (e.g. when auto-recharge mechanism is enabled). 
- `NotifierService` uses  fire&forget to notify
- `pay_with_payment_method` incorporates `notifier` but excludes websocket notifications
- email notifications currently upon success payment only (not websockets notify also failures)
- Follows up from https://github.com/ITISFoundation/osparc-simcore/pull/5310
- All emails notifications in payments for #5227
- Tested in master by payment w/ payment-method
- Tested in master by payment with auto-recharge
- Driving tests `test_services_payments`
None

🎨 Send email on successful payment w/ payment-method

---

packages/aws-library/src/aws_library/ec2/client.py

This PR adds tagging of the EC2 linked EBS storage and Network-interfaces for better cost monitoring.
- fixes #5403

✨Autoscaling/Clusters-keeper tags also volume and network-interface

---

services/web/server/src/simcore_service_webserver/notifications/_constants.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_nonexclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/projects/_observer.py

After some Graylog analysis it came up that the following issue callback would happen quite often. It was found that both _rabbitmq_nonexclusive_queue_consumers and _rabbitmq_exclusive_queue_consumers were using the same ```app[APP_RABBITMQ_CONSUMERS_KEY]``` to store their respective consumers. E.G. on initialization the last one would replace the first one, and on deletion as well, thus the errors shown in Graylog. Not sure if this could also have some influence on the lost logs issues.
Another issue was also identified when a user is logging out (also visible in e2e tests), and for this an additional log output was added.
```bash
Unhandled exception:
File "/home/scu/.venv/lib/python3.10/site-packages/aiormq/channel.py", line 182, in rpc
result = await …
```

🐛Webserver: exclusive/non-exclusive RabbitMQ consumers are deleting each other, and also probably replacing each other

---

services/api-server/src/simcore_service_api_server/core/settings.py

It fixes a bug that only affects the api server capture mode. It was supposed to only work in dev mode, but the code actually only threw an exception about that 'in debug mode'
Enable api server capture mode, run osparc in dev mode, api server should start without crashing

  🐛 Fix bug that throws error when capturing api responses in dev mode

---

scripts/maintenance/computational-clusters/osparc_clusters.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/auto_scaling_core.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_utils_auto_scaling_core.py
services/autoscaling/tests/unit/test_utils_ec2.py

This PR fixes the issue where a different machine type could replace the intended buffer machine type.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5453
@mguidon this should allow setting multiple machine types, and still keeping the correct type of buffer machines (iSeg use-case)

🐛Autoscaling: Ensure buffer machine type remains the same over the app session

---

services/web/server/src/simcore_service_webserver/login/handlers_registration.py
services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py

Removes check on existing phone number
- Follows up with https://github.com/ITISFoundation/osparc-simcore/pull/5460
Driving test
```
pytest -vv tests/unit/with_db -k test_can_register_same_phone_in_different_accounts
```

🐛 Fix: drops phone check

---

packages/postgres-database/src/simcore_postgres_database/errors.py
packages/postgres-database/src/simcore_postgres_database/models/users.py
packages/postgres-database/tests/conftest.py
packages/postgres-database/tests/test_users.py

If a user is `CONFIRMATION_PENDING` and tries to register, the webserver responds 500 because `UserStatus` constructor raises `ValuerError`
NOTE that the values stored in the database for `UserStatus.CONFIRMATION_PENDING` before this change were not "PENDING" but `CONFIRMATION_PENDING`. Therefore this change does not require a database migration script.
- Error while manual exploratory testing of registration of @NielsKuster 
- Better handling of 500 error messages in https://github.com/ITISFoundation/osparc-simcore/pull/5487
```cmd
cd packages/postgres-database
pytest tests/test_users.py
```

🐛 Fixes error upon registration of pending email confirmation

---

services/static-webserver/client/source/class/osparc/po/Invitations.js

Fix: increase credits limit in invitations to 1000

🐛 Fix: increase credits limit in invitations to 1000

---

services/static-webserver/client/source/class/osparc/notification/NotificationsButton.js

Tapping the notifications bell when the notifications are visible, hides them.
Before:
After:
related to https://z43.manuscript.com/f/cases/190690/New-feedback-Project-Shared-covers-task

🎨 UI/UX: Notifications bell tapping

---

Makefile

Since we don't want to enforce non-python developers on the same minimum python requirement, the python version test is moved to a dependency of devenv
https://github.com/ITISFoundation/osparc-simcore/pull/5504
Run make devenv on system with old/correct python version, make devenv should fail/succeed respectively.
- [ x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

♻️Move python version test to devenv dependency

---

api/specs/web-server/_products.py
api/specs/web-server/_users.py
services/static-webserver/client/source/class/osparc/data/Permissions.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/po/POCenter.js
services/static-webserver/client/source/class/osparc/po/PreRegistration.js
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/security/_authz_access_roles.py
services/web/server/src/simcore_service_webserver/users/_handlers.py
services/web/server/src/simcore_service_webserver/users/_schemas.py
services/web/server/tests/unit/with_dbs/03/test_users.py

PO can now pre-register a user by copy&pasting the request form (JSON) in the Pre-registration page of the PO-center.
- 🎨 normalizes values from the request form (e.g. capitalization, spaces, country names etc) so pre-registration data is as clean as possible
- 🎨 tags OAS entrypoints with PO exclusive access as `po`. This way swagger renders them in the same group
- Pre-registration part in #5507
- Get the JSON from a fogbugz case
- Open PO center -> **Pre-Registration** 
- Add input & **submit**
- If successful, open PO center -> **Users**
- add the email & press **search**

✨ PO Pre-registration UI Step

---

services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation.py

This PR changes the names of the metrics generated by the autoscaling application to use
- a namespace defined as the ```APP_NAME == simcore_service_autoscaling```
- a subsystem defined either as ```dynamic``` or ```computational```
that means that the metrics created are prefixed with ```namespace_subsystem```

🎨Autoscaling metrics: define namespace and subsystem

---

services/clusters-keeper/src/simcore_service_clusters_keeper/data/docker-compose.yml
services/clusters-keeper/src/simcore_service_clusters_keeper/data/prometheus.yml
services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py
services/clusters-keeper/tests/manual/README.md
services/clusters-keeper/tests/unit/test_utils_clusters.py

This PR adds a prometheus instance to gather metrics on the computational cluster (dask, autoscaling, ...)
Here is a reminder of how a computational cluster looks like:
This PR is a first step to allow to scrape each computational clusters to monitor its status in prometheus
Added a test to monitor the size of the EC2 UserData. currently at 12.2KB (max is 16KB).

✨Comp backend: add local prometheus in every cluster to gather metrics

---

services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py

🐛Clusters-keeper: correct typo preventing running computational clusters

---

services/static-webserver/client/source/class/osparc/auth/LoginPage.js
services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js
services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js
services/static-webserver/client/source/class/osparc/dashboard/GridButtonNew.js

- Fixed the issue where the app mode button over lapped the updates button in the study card footer
- Fix the issue where the create new study failed to render rich text for sim4life lite
resolves https://github.com/ITISFoundation/osparc-issues/issues/1260

🐛 Various issue in the study cards

---

packages/aws-library/requirements/_base.txt
packages/aws-library/requirements/_test.txt
packages/aws-library/requirements/_tools.txt
packages/dask-task-models-library/requirements/_base.txt
packages/dask-task-models-library/requirements/_test.txt
packages/dask-task-models-library/requirements/_tools.txt
requirements/constraints.txt
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
services/autoscaling/requirements/_tools.txt
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/requirements/_tools.txt
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_dask-distributed.txt
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/requirements/_tools.txt
services/director-v2/requirements/_base.txt
services/director-v2/requirements/_test.txt
services/director-v2/requirements/_tools.txt
services/director-v2/requirements/constraints.txt
services/director-v2/tests/integration/conftest.py
services/osparc-gateway-server/requirements/_base.txt
services/osparc-gateway-server/requirements/_test.txt
services/osparc-gateway-server/requirements/_tools.txt

- #packages before ~ 154
- #packages after ~ 148
|   1 | aio-pika                  | 9.3.0, 9.2.2, 9.1.2 | 9.4.1      | *minor*    | 4 | aws-library🧪</br>dask-sidecar⬆️</br>director-v2⬆️🧪 |
|   2 | aioboto3                  | 12.0.0          | 12.3.0     | *minor*    | 2 | aws-library🧪</br>director-v2🧪 |
|   3 | aiobotocore               | 2.7.0, 2.5.4    | 2.12.2,2.11.2 | *minor*    | 3 | aws-library🧪</br>dask-sidecar⬆️</br>director-v2🧪 |
|   4 | aiocache                  | 0.12.1          | 0.12.2     |            | 1 | director-v2⬆️ |
|   5 | aiofiles                  | 23.1.0          | 23.2.1     | *minor*    | 1 | director-v2⬆️ |
|   6 | aiohttp                   | 3.9.3, 3.8.5, 3.8.6, 3.9.1 | …

⬆️Maintenance: Upgrade of dask-based services and libs

---

services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_utils.py
services/web/server/src/simcore_service_webserver/projects/_nodes_handlers.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py

When the clusters-keeper application is down, paused or not accessible, then it is impossible to start a dynamic service and/or start a computation for the following reasons:
- the clusters-keeper provides an interface to the AWS EC2 API to get the EC2 resources (CPU, RAM),
- if the clusters-keeper is not accessible or shutdown for whatever reason, then this interface is not available,
- therefore it is not possible to set the service resources to run dynamic services and computational services which makes  sense
This PR improves the situation by returning a 503 when a dynamic service cannot start due to that fact.
Basically for billable products, starting a service depends on the clusters-keeper being up and running.

🎨 Improve exception when clusters-keeper is not running in billable products

---

.vscode/launch.template.json
services/api-server/src/simcore_service_api_server/api/routes/studies_jobs.py
services/api-server/src/simcore_service_api_server/services/study_job_models_converters.py
services/api-server/src/simcore_service_api_server/services/webserver.py
services/api-server/tests/unit/api_studies/test_api_routes_studies_jobs.py
services/api-server/tests/unit/conftest.py

- ✨ Moves and adapts `POST /v0/studies/{study_id}/jobs/{job_id}/outputs` implementation from https://github.com/wvangeit/osparc-simcore/tree/studies_api
- ♻️ Fixes `httpx` deprecation
```
DeprecationWarning: The 'app' shortcut is now deprecated. 
Use the explicit style 'transport=ASGITransport(app=...)' instead.
```  
This is just a PR to move the implementation. I will follow up with more improvements in a separate PR 
- https://github.com/ITISFoundation/osparc-issues/issues/1291
Minimal test (for now)
```
cd services/api-server
pytest -vv --pdb tests/unit -k test_get_study_job_outputs
```

✨ api-server: Adds job outputs

---

services/storage/src/simcore_service_storage/handlers_files.py
services/storage/tests/unit/test_handlers_files_metadata.py

Some legacy tests fail with 
because deprecated client expects `data` field always as an object as can be seen here
https://github.com/ITISFoundation/osparc-simcore/blob/cfdf4f86d844ebb362f4f39e9c6571d561b72897/services/storage/client-sdk/python/simcore_service_storage_sdk/models/file_meta_data_enveloped.py#L33-L38
- Reverts some changes from PR #5659
- Fixes https://github.com/ITISFoundation/osparc-simcore/issues/5676

🐛 Restores compatibility with deprecated storage API used in legacy services

---

packages/notifications-library/tests/conftest.py
packages/pytest-simcore/src/pytest_simcore/__init__.py
packages/pytest-simcore/src/pytest_simcore/docker_registry.py
packages/pytest-simcore/src/pytest_simcore/environment_configs.py
packages/service-library/src/servicelib/docker_utils.py
packages/service-library/src/servicelib/fastapi/docker_utils.py
packages/service-library/src/servicelib/progress_bar.py
packages/service-library/tests/conftest.py
packages/service-library/tests/fastapi/test_docker_utils.py
packages/service-library/tests/test_progress_bar.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py
services/dynamic-sidecar/tests/unit/test_core_docker_utils.py
services/payments/tests/conftest.py

- moved code to pull a set of docker images out of the dynamic-sidecar inside servicelib
- added tests around the pull of the images
Progress bar wise, the pulling of images was divided like so:
```100% / NUM_IMAGES then for each image the progress goes like IMAGE_SIZE * 3 / (DOWNLOADED_SIZE + 2* EXTRACTED_SIZE```
Since services such as s4l are composed of 5 images, where 1 image is about 30GiB, the even distribution of the progress is problematic.
Using a "weighted" progress bar fixes this, by giving part of the progress a higher weight. The downside is that some concurrent code cannot be run concurrently for now, until the progress bar with weights becomes compatible.

🎨Ensure pulling s4l returns smooth increment of progress (Part 1)

---

packages/service-library/src/servicelib/docker_utils.py
packages/service-library/src/servicelib/fastapi/docker_utils.py
packages/service-library/tests/aiohttp/test_docker_utils.py
packages/service-library/tests/fastapi/test_docker_utils.py

- using the overall size of all images, this brings back the old behavior of parallelized pulling of images (improved performance when pulling multiple images)
- ensure progress reporting kind of works in case where it is not possible to retrieve docker image layer information prior to pulling
- tests consistency
- test when no layer information is available
@odeimaiz next PR will bring the current size/total size

🎨Image pulling progress: use overall size (Part 2)

---

services/static-webserver/client/source/class/osparc/data/model/Node.js
services/static-webserver/client/source/class/osparc/widget/PersistentIframe.js

In order to detect multiple iframes in playwright's context, this PR sets the ``osparc-test-id=iframe_nodeID`` attribute.

e2e: set ``osparc-test-id`` attribute to iframes

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/desktop/SlideshowView.js
services/static-webserver/client/source/class/osparc/node/NodeView.js
services/static-webserver/client/source/class/osparc/product/Utils.js

In order to save resources in the new TIP deployment in AWS, it was decided not to autostart the three (or two) steps in the TIP pipeline. For that, we simply need to set the Disable Auto Start checkbox to true in the TIP templates (exposing this feature to TIP and templates was needed). So that the UX doesn't change too much, when the users get to a step in the pipeline, the frontend will automatically request the current dynamic service to start.
closes https://github.com/ITISFoundation/osparc-issues/issues/1396

✨Frontend: Do not auto start TIP

---

services/static-webserver/client/source/class/osparc/desktop/preferences/pages/TokensPage.js
services/static-webserver/client/source/class/osparc/desktop/preferences/window/CreateAPIKey.js
services/static-webserver/client/source/class/osparc/desktop/preferences/window/ShowAPIKey.js
tests/e2e-playwright/tests/ti_plan.py

closes https://github.com/ITISFoundation/osparc-simcore/issues/4541
closes https://github.com/ITISFoundation/osparc-simcore/issues/5658

🎨 Frontend: API Keys enhancements

---

services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/desktop/organizations/ServicesList.js
services/static-webserver/client/source/class/osparc/info/ServiceUtils.js

fixes https://github.com/ITISFoundation/osparc-issues/issues/1350

🐛 Fix Frontend SharedResourceItem's icon

---

services/storage/src/simcore_service_storage/_meta.py
services/storage/src/simcore_service_storage/application.py
services/web/server/src/simcore_service_webserver/diagnostics/_monitoring.py

- Ensure aiohttp services use the same naming convention in their prometheus instrumentation
- Currently they don't use the same naming conventions and it makes creating grafana dashboards tricky.

Ensure aiohttp services use the same naming convention in prometheus

---

services/autoscaling/src/simcore_service_autoscaling/core/settings.py
services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py

Tests have shown that with the newest tooling we are now down from 3 minutes to <1 minutes to start an EC2 instance.

🎨Autoscaling: Change max time to wait for EC2 readyness to 1 minute

---

tests/e2e-playwright/tests/conftest.py

some tests seem to fail when the extra header is set up in playwright.
- When the extra header is set, then connecting to the services gives CORS error (maybe linked to https://github.com/microsoft/playwright/issues/21811)
For now the playwright system is run without web security (as puppeteer was as well I discovered)
The problem can be resolved I think by setting the traefik labels to allow the headers to go through:
https://github.com/ITISFoundation/osparc-simcore/issues/5754

🐛E2e: Playwright disable web security

---

packages/postgres-database/requirements/_base.in
packages/postgres-database/requirements/_base.txt
packages/postgres-database/src/simcore_postgres_database/utils_projects_nodes.py
services/web/server/src/simcore_service_webserver/director_v2/_core_dynamic_services.py
services/web/server/src/simcore_service_webserver/dynamic_scheduler/api.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_orphans.py
services/web/server/src/simcore_service_webserver/projects/_crud_api_create.py
services/web/server/src/simcore_service_webserver/projects/db.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py
services/web/server/tests/unit/isolated/test_garbage_collector_core.py
services/web/server/tests/unit/with_dbs/02/conftest.py
services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__delete.py
services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py
services/web/server/tests/unit/with_dbs/02/test_projects_states_handlers.py
services/web/server/tests/unit/with_dbs/03/garbage_collector/test_resource_manager.py
services/web/server/tests/unit/with_dbs/03/tags/conftest.py
services/web/server/tests/unit/with_dbs/03/test_project_db.py
services/web/server/tests/unit/with_dbs/03/version_control/conftest.py
services/web/server/tests/unit/with_dbs/03/wallets/conftest.py
services/web/server/tests/unit/with_dbs/conftest.py

One fundamental flaw in the GC was that the order of checking for orphaned services might lead to a wrong closing of these services:
1. Lookup of theoretical services running
2. Lookup of actual services running
That means that if any new project is started between 1 and 2, then the services found in 2 might not be in the previous call to 1. --> the GC then kills these services.
This could be identified by setting the GC Interval to 1 second locally.
This PR inverts this and also refactors slightly this part of the code.
Also the testing was improved hopefully.

🐛Garbage collector: possible fix to "spurious" shutdowns

---

services/static-webserver/client/source/class/osparc/cluster/ClustersDetails.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/desktop/credits/Usage.js
services/static-webserver/client/source/class/osparc/desktop/organizations/OrganizationsList.js
services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ClustersPage.js
services/static-webserver/client/source/class/osparc/metadata/QualityEditor.js
services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyBootOpts.js
services/static-webserver/client/source/class/osparc/node/BootOptionsView.js
services/static-webserver/client/source/class/osparc/po/MessageTemplates.js
services/static-webserver/client/source/class/osparc/pricing/Plans.js
services/static-webserver/client/source/class/osparc/study/BillingSettings.js
services/static-webserver/client/source/class/osparc/study/StudyOptions.js

Sometimes reproducible in Safari: it looks like, in this specific browser, when closing a window, the selection in the Select Boxes is reset.

🐛 Frontend Fix: Make sure SelectBox's selection is not null

---

services/docker-compose.devel.yml

PR [https://github.com/ITISFoundation/osparc-simcore/pull/5776](https://github.com/ITISFoundation/osparc-simcore/pull/5776) prevented ```make up-devel``` to be functional. This fixes that. The gunicorn is expecting a ```DEBUG``` env variable that is an integer and does not go well with booleans.
Also the log level in devel mode is set back to DEBUG level.

🐛Fix ```up-devel``` Makefile target

---

services/web/server/src/simcore_service_webserver/projects/models.py

- 🐛 add validators to ProjectDB model
- relates https://github.com/ITISFoundation/osparc-simcore/pull/5802

🐛 add validators to ProjectDB model

---

packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone.py
scripts/install_rclone.bash
services/agent/src/simcore_service_agent/modules/volumes_cleanup/_s3.py

After the tests done in https://github.com/ITISFoundation/osparc-simcore/discussions/5828 it is pretty visible that the new version of RClone, beside having a very bad bug that makes EC2 instances kernel panic that the current parameters make the download very slow, very bad.
Therefore this PR aims at downgrading the RClone back to 1.63.1 version, which seemed to be more stable even though still much slower (2x) than using official AWS tools. But at least it seems more or less bugfree.

🚑️Rclone: downgrade to 1.63.1

---

services/autoscaling/src/simcore_service_autoscaling/core/settings.py
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/src/simcore_service_autoscaling/utils/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_utils_auto_scaling_core.py
services/autoscaling/tests/unit/test_utils_docker.py

After [the changes that stopped using docker node drain ](https://github.com/ITISFoundation/osparc-simcore/pull/5340) a new issue arose: container IPs are not properly returned to the docker swarm https://github.com/ITISFoundation/osparc-ops-environments/issues/665.
So it is preferable to first drain a node before terminating it.
With this PR, the termination process was complexified. Once a node is deemed as terminateable (after empty time exceeds ```EC2_INSTANCES_TIME_BEFORE_TERMINATION```) the autoscaling service will begin the "termination" process.
**BEFORE:**
- the EC2 instance is instantly terminated
- the node is removed from the cluster
**AFTER:**
- the docker node is drained
- after ```EC2_INSTANCES_TIME_BEFORE_FINAL_TERMINATION=15seconds``` it will proceed with termination as …

✨Autoscaling: Drain node before terminating

---

packages/service-library/src/servicelib/resources.py
requirements/packages-notes.md
services/dynamic-sidecar/requirements/_test.in
services/dynamic-sidecar/requirements/_test.txt

Removes any reference to `pkg_resources`
-  closes https://github.com/ITISFoundation/osparc-simcore/issues/3151

🔨 Retires deprecated `pkg_resources` module

---

Makefile
packages/dask-task-models-library/requirements/_base.txt
packages/dask-task-models-library/requirements/_test.txt
packages/dask-task-models-library/requirements/_tools.txt
requirements/constraints.txt
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
services/autoscaling/requirements/_tools.txt
services/autoscaling/tests/unit/test_modules_dask.py
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/requirements/_tools.txt
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_dask-distributed.txt
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/requirements/_tools.txt
services/dask-sidecar/requirements/constraints.txt
services/director-v2/requirements/_base.txt
services/director-v2/requirements/_test.txt
services/director-v2/requirements/_tools.txt
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/integration/01/test_computation_api.py
services/osparc-gateway-server/requirements/_base.txt
services/osparc-gateway-server/requirements/_test.txt
services/osparc-gateway-server/requirements/_tools.txt

Test the upgrade to the latest dask library, hopefully fixing a long running issue.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4526
- #packages before ~ 57
- #packages after ~ 62
|   1 | aioboto3                  | 12.3.0          | 12.4.0     | *minor*    | 2 | autoscaling⬆️</br>clusters-keeper⬆️ |
|   2 | aiobotocore               | 2.11.2, 2.12.2  | 2.12.3,2.13.0 | *minor*    | 3 | autoscaling⬆️</br>clusters-keeper⬆️</br>dask-sidecar⬆️ |
|   3 | aiohttp                   | 3.9.3           | 3.9.5      |            | 8 | autoscaling⬆️</br>clusters-keeper⬆️🧪</br>dask-sidecar⬆️</br>director-v2⬆️🧪</br>osparc-gateway-server⬆️🧪 |
|   4 | astroid                   | 3.1.0           | …

⬆️ Maintenance: Dask upgrade to 2024.5.1 and upgrades of autoscaling/clusters-keeper/director-v2/dask-sidecar/osparc-gateway 🚨

---

packages/aws-library/src/aws_library/ec2/client.py
packages/aws-library/src/aws_library/ec2/models.py
packages/aws-library/tests/test_ec2_models.py
services/clusters-keeper/src/simcore_service_clusters_keeper/core/settings.py
services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters.py
services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters_management_core.py
services/clusters-keeper/src/simcore_service_clusters_keeper/modules/dask.py
services/clusters-keeper/src/simcore_service_clusters_keeper/rpc/clusters.py
services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py
services/clusters-keeper/src/simcore_service_clusters_keeper/utils/ec2.py
services/clusters-keeper/tests/unit/test_modules_clusters_management_core.py
services/clusters-keeper/tests/unit/test_utils_clusters.py

🚨Needs some testing in master **BEFORE** it goes anywhere else. as this is an AWS only feature.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5436

✨Clusters-keeper: terminate broken EC2s🚨

---

packages/aws-library/requirements/_base.txt
packages/service-library/requirements/_base.txt
packages/service-library/requirements/_test.txt
packages/simcore-sdk/requirements/_base.txt
services/agent/requirements/_base.txt
services/api-server/requirements/_base.txt
services/autoscaling/requirements/_base.txt
services/catalog/requirements/_base.txt
services/clusters-keeper/requirements/_base.txt
services/dask-sidecar/requirements/_base.txt
services/datcore-adapter/requirements/_base.txt
services/director-v2/requirements/_base.txt
services/dynamic-scheduler/requirements/_base.txt
services/dynamic-sidecar/requirements/_base.txt
services/invitations/requirements/_base.txt
services/payments/requirements/_base.txt
services/resource-usage-tracker/requirements/_base.txt
services/storage/requirements/_base.txt
services/web/server/requirements/_base.txt
services/web/server/requirements/_test.txt
services/web/server/requirements/_tools.txt
tests/swarm-deploy/requirements/_test.txt

To upgrade `faststream` `typer` had to be bumped as well. Since it was blocking the upgrade
- #packages before ~ 8
- #packages after ~ 4
|   1 | colorama                  | 0.4.6           | 🗑️ removed |  | 3 | invitations⬆️</br>payments⬆️</br>resource-usage-tracker⬆️ |
|   2 | faststream                | 0.5.2, 0.4.7, 0.2.12, 0.5.7, 0.5.4 | 0.5.10     |            | 18 | api-server⬆️</br>autoscaling⬆️</br>aws-library🧪</br>catalog⬆️</br>clusters-keeper⬆️</br>dask-sidecar⬆️</br>datcore-adapter⬆️</br>director-v2⬆️</br>dynamic-scheduler⬆️</br>dynamic-sidecar⬆️</br>invitations⬆️</br>payments⬆️</br>resource-usage-tracker⬆️</br>service-library🧪</br>simcore-sdk🧪</br>storage⬆️</br>swarm-deploy🧪</br>web⬆️ |
| …

⬆️ upgrading faststream repo wide

---

services/static-webserver/client/source/class/osparc/Preferences.js
services/static-webserver/client/source/class/osparc/desktop/preferences/pages/GeneralPage.js
services/static-webserver/client/source/class/osparc/info/StudyLarge.js
services/static-webserver/client/source/class/osparc/metadata/ClassifiersEditor.js
services/static-webserver/client/source/class/osparc/metadata/QualityEditor.js
services/static-webserver/client/source/class/osparc/navigation/CreditsMenuButton.js
services/web/server/src/simcore_service_webserver/users/_preferences_models.py

This PR will only affect the new users.
🚨 If we want to change the default value of the existing users, we need to go through the DB, either deleting ``WalletIndicatorVisibilityFrontendUserPreference`` preference entries or changing their value (I believe there is a sql script somewhere).
demo with user with no ``WalletIndicatorVisibilityFrontendUserPreference`` entry in the DB:
closes https://github.com/ITISFoundation/osparc-issues/issues/1474

🎨 Frontend: Credits indicator only visible in warning zone by default (🚨)

---

services/docker-compose.yml

The `default` network is not currently used by the `agent` service, this not required.
By removing it, it helps in dealing with issues caused by network IP exhaustion.
- https://github.com/ITISFoundation/osparc-ops-environments/issues/662

♻️ Removing default network form agent

---

packages/pytest-simcore/src/pytest_simcore/helpers/httpx_calls_capture_parameters.py
packages/pytest-simcore/src/pytest_simcore/httpx_calls_capture.py
services/api-server/src/simcore_service_api_server/api/routes/_jobs.py
services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py
services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs_getters.py
services/api-server/src/simcore_service_api_server/api/routes/studies_jobs.py
services/api-server/src/simcore_service_api_server/services/jobs.py
services/api-server/src/simcore_service_api_server/services/webserver.py
services/api-server/tests/mocks/cleanup.py
services/api-server/tests/mocks/test_get_and_update_study_job_metadata.json
services/api-server/tests/unit/api_studies/test_api_routers_studies_jobs_metadata.py
services/api-server/tests/unit/conftest.py

- ✨ Implements custom metadata entrypoint for study jobs
- `get_study_job_custom_metadata` as `GET/{study_id}/jobs/{job_id}/metadata`
- `replace_study_job_custom_metadata` as `PUT /{study_id}/jobs/{job_id}/metadata`
- It essentially reuses the implementation of the solver jobs couterparts
- 🔨 Enhances backend mock
-  New mock capture fully generated using new `--spy-httpx-calls-enabled=true`
- `mocked_backend` fixture prototypes how to [mock iterable responses](https://lundberg.github.io/respx/guide/#iterable). This is a prototype that will eventually move into the implementation of `create_respx_mock_from_capture` fixture
- ♻️ Moves `jobs` business logic to `services` following `controller/service/repository` pattern
- Implements custom metadata entrypoints in …

✨ api-server: New study jobs metadata entrypoints

---

packages/pytest-simcore/src/pytest_simcore/environment_configs.py
packages/pytest-simcore/src/pytest_simcore/helpers/utils_postgres.py
packages/pytest-simcore/src/pytest_simcore/postgres_service.py
packages/service-library/src/servicelib/fastapi/requests_decorators.py
packages/service-library/src/servicelib/fastapi/timing_middleware.py
packages/settings-library/tests/test_email.py
services/datcore-adapter/src/simcore_service_datcore_adapter/api/module_setup.py
services/payments/tests/conftest.py
services/payments/tests/unit/test_db_payments_users_repo.py
services/payments/tests/unit/test_services_notifier_email.py

Here are some changes in `pytest-simcore` and `servicelib` that can be useful in many services. I have used them in some of the services as example and will do systematically with many more in different PRs
- 🔨 new **fixture** `docker_compose_service_environment_dict`: **replicates the env vars that the real services will encounter**
- resolves `.env-devel` and the `environment` section of a `service_name`. Detects e.g. missing env vars in `.env-devel`
-  used in `payments` as example (NOTE: **recommended** to build `app_environment` fixture in all services services)
- 🔨 new **helper** `pytest_simcore.helpers.utils_postgres.insert_and_get_row_lifespan` context for a control lifespan of a new row.
- ♻️ moved **middleware** to `packages/service-library/src/servicelib/fastapi/timing_middlewar …

🔨 New pytest-simcore `environment_config` fixtures and `utils_postgres` helpers

---

services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
tests/e2e/Makefile

https://github.com/ITISFoundation/osparc-simcore/issues/5900 showed that if a user runs a computational service with multiple inputs, and these inputs have the same file name, there is a risk of collision. Therefore this PR disable concurrent pulling of inputs (this will slightly reduce execution performance but will ensure that there is no collision).
Bonus:
- removing puppeteer-based sleeper test

🐛Dask sidecar: disable concurrent pulling of files until new version is out

---

packages/models-library/src/models_library/api_schemas_dynamic_scheduler/dynamic_services.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/dynamic_scheduler/services.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rpc/_services.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/director_v2/_public_client.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/director_v2/_thin_client.py
services/dynamic-scheduler/tests/unit/api_rpc/test_api_rpc__services.py
services/web/server/src/simcore_service_webserver/dynamic_scheduler/api.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_orphans.py
services/web/server/src/simcore_service_webserver/projects/_nodes_handlers.py
services/web/server/src/simcore_service_webserver/projects/projects_api.py
services/web/server/tests/unit/isolated/test_dynamic_scheduler.py
services/web/server/tests/unit/isolated/test_garbage_collector_core.py
services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__delete.py
services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py
services/web/server/tests/unit/with_dbs/02/test_projects_states_handlers.py
services/web/server/tests/unit/with_dbs/03/garbage_collector/test_resource_manager.py

This code has to be deployed with all dynamic-services stopped. The service stop API from `webserver`-> `dynamic-scheduler` changed in a backwards incompatible way.
Adds `project_id` and `user_id` to the stop command sent to the `dynamic-scheduler`. These changes are required to cover an edge case: enables stopping a service that is not tracked by the scheduler.
These changes are part of https://github.com/ITISFoundation/osparc-simcore/pull/5892
- required by https://github.com/ITISFoundation/osparc-simcore/pull/5892

♻️ refactor stop service command ⚠️🚨

---

packages/service-library/src/servicelib/redis.py

This is an attempt to fix the broken CI due to hanging tests.

🐛 disable health check for Redis client

---

packages/service-library/tests/test_redis_utils.py
services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/share/Collaborators.js
services/static-webserver/client/source/class/osparc/share/CollaboratorsService.js
services/static-webserver/client/source/class/osparc/share/CollaboratorsStudy.js
services/static-webserver/client/source/class/osparc/share/NewCollaboratorsManager.js
services/static-webserver/client/source/class/osparc/share/PublishTemplate.js
services/static-webserver/client/source/class/osparc/store/Store.js
services/static-webserver/client/source/class/osparc/study/SaveAsTemplate.js

🐛 [Frontend bugfix] List everyone group and provide product-everyone group in potential collaborators

---

services/static-webserver/client/source/class/osparc/data/model/Node.js

Sometimes webkit based e2e tests still fail when switching from the loading page to the iframe's content.
The problem is that the frontend polls the state of the dynamic service and when this says ``Ready`` (which is the containers status) the frontend still needs to make sure the url is reachable, because some traefik rules that need to be added might not be there yet. In this "ping" call from the frontend to the dynamic service's content, the backend might respond with a [302 Redirection Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302), which is not [ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok), but it's still valid for a our purpose.

🎨 [Frontend] Switch to iframe's content also after 302 response

---

services/static-webserver/client/source/class/osparc/desktop/wallets/WalletsList.js
services/static-webserver/client/source/class/osparc/tours/Manager.js
services/static-webserver/client/source/resource/osparc/tours/tis_tours.json

As requested by some of you, the main elements in the Guided Tour are now highlighted:

🎨 [Frontend] Highlight elements in Guided Tour

---

services/static-webserver/client/source/class/osparc/data/model/Node.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

The previous [PR](https://github.com/ITISFoundation/osparc-simcore/pull/5963) didn't fix the issue.
This one logs (only in master) the response to the fetch call to a running service.

🐛 [Frontend] Log fetch call's response to running service

---

.coveragerc
services/storage/src/simcore_service_storage/simcore_s3_dsm.py
services/storage/tests/fixtures/data_models.py
services/storage/tests/unit/test_dsm_dsmcleaner.py
services/storage/tests/unit/test_handlers_simcore_s3.py

- This is the first step of fixing the storage issue w.r.t meta-modelling
- This PR disables the cleaning up of multipart uploads in AWS which will then rely on [bucket lifecycle configuration](https://docs.aws.amazon.com/AmazonS3/latest/userguide//mpu-abort-incomplete-mpu-lifecycle-config.html), which will be handled by @YuryHrytsuk  in https://github.com/ITISFoundation/osparc-ops-environments/issues/702
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/5975

♻️🐛Storage: disable handling of dangling multipart uploads

---

packages/models-library/src/models_library/api_schemas_webserver/projects.py
packages/models-library/src/models_library/basic_types.py
packages/models-library/tests/test_projects.py
services/api-server/src/simcore_service_api_server/api/routes/studies_jobs.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml

Fixes error produced when the user updates a study with a long description. After these changes very long descriptions (>1000 chars) and titles (>200 chars) will be truncated without reporting an error. Note that these truncation only happens for input strings in the API. As a general rule all input data to the API should be constrained either with a hard error or silently (e.g. truncating).
As a side note, the front-end should have reacted better to a 4XX errors provided that is a client error (the description maximum length was surpassed). I believe changes like https://github.com/ITISFoundation/osparc-simcore/pull/5487 should help in this direction .
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/5988
- Driving test `-k test_project_patch_truncates_description`
None

🐛 Fixes error while updated study with long description

---

api/specs/web-server/_computations.py
services/director-v2/openapi.json
services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
services/director-v2/tests/integration/01/test_computation_api.py
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
services/web/server/tests/integration/02/test_computation.py

Mismatch between the error code specified in the OAS and the actual error code when starting a computation.
- the director-v2 service would respond with [HTTP_403_FORBIDDEN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) for computation:start when the computation was started.  Nonetheless, the OAS was reporting [HTTP_409_CONFLICT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409). 
- This error was propagated via the web-server and handled in the api-server.
- Due to the mismatch, the error was not handled properly in the api-server causing errors like [this](https://monitoring.osparc-master.speag.com/graylog/messages/graylog_277/a55e2401-32be-11ef-8bc2-0242c0a80207)
- IMO [HTTP_409_CONFLICT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) is more …

🐛 Fixes mismatch on error status-code for start-computation

---

packages/service-library/src/servicelib/utils.py
packages/service-library/tests/test_archiving_utils.py
packages/service-library/tests/test_archiving_utils_extra.py
packages/service-library/tests/test_utils.py
scripts/mypy.bash
scripts/mypy/Dockerfile
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py

Reduced size of [https://github.com/ITISFoundation/osparc-simcore/pull/5981](https://github.com/ITISFoundation/osparc-simcore/pull/5981)
This PR brings learnings from this [article](https://death.andgravity.com/limit-concurrency#asyncio-wait):
Run concurrent asyncio awaitables without overloading the event loop. Tasks are created on the fly and based on need and are limited in number.
driving test: test_utils.py in servicelib.
Bonus:
- mypy script now uses uv
- fixed dynamic-sidecar new mypy issue by ignoring it @GitHK 
NOTE: I will not move that to async_utils.py yet to reduce noise.
- required by [https://github.com/ITISFoundation/osparc-simcore/pull/5981](https://github.com/ITISFoundation/osparc-simcore/pull/5981)

🎨 Maintenance: Add new concurrency tooling

---

packages/pytest-simcore/src/pytest_simcore/redis_service.py
packages/service-library/src/servicelib/aiohttp/rest_middlewares.py
packages/service-library/src/servicelib/aiohttp/rest_models.py
packages/service-library/src/servicelib/aiohttp/rest_responses.py
packages/service-library/tests/aiohttp/test_rest_responses.py
services/web/server/src/simcore_service_webserver/director_v2/_handlers.py
services/web/server/tests/integration/01/test_garbage_collection.py
services/web/server/tests/unit/with_dbs/conftest.py

Fixes deprecation warning in `redis` library, provided that `redis==5.0.4` already repo-wide
```
DeprecationWarning: Call to deprecated close. (Use aclose() instead) -- Deprecated since version 5.0.1.
await client.close(close_connection_pool=True)
```
- Fixes deprecation error in `aiohttp` library (SEE https://github.com/aio-libs/aiohttp/issues/2415)
```cmd
... /aiohttp/web_protocol.py:451: DeprecationWarning: returning HTTPException object is deprecated (#2415) and will be removed, please raise the exception instead
```

🎨 Fixes  Deprecation Warning on redis and aiohttp

---

packages/service-library/src/servicelib/file_utils.py
packages/service-library/tests/test_file_utils.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py

Enhances the logs of the sidecar and prints which files were modified when pulling the inputs. This will allow to better help users with debugging their studies.
- https://github.com/ITISFoundation/osparc-simcore/issues/5741

✨ dynamic-sidecar logs changes to input ports

---

services/web/server/src/simcore_service_webserver/studies_dispatcher/_redirects_handlers.py
services/web/server/tests/unit/with_dbs/01/studies_dispatcher/test_studies_dispatcher_handlers.py

Viewers based on new style services, running via dynamic-sidecar, can now be used.
- 🐛 Fixes an issue where generated projects did not update the project_networks table. This did not allow for the dynamic-sidecar to start.

🐛 viewers can now use new style dynamic services

---

.coveragerc
Makefile
packages/aws-library/requirements/_base.in
packages/aws-library/requirements/_base.txt
packages/aws-library/src/aws_library/ec2/client.py
packages/aws-library/src/aws_library/ec2/models.py
packages/aws-library/src/aws_library/ssm/__init__.py
packages/aws-library/src/aws_library/ssm/_client.py
packages/aws-library/src/aws_library/ssm/_error_handler.py
packages/aws-library/src/aws_library/ssm/_errors.py
packages/aws-library/tests/conftest.py
packages/aws-library/tests/test_ec2_client.py
packages/aws-library/tests/test_ssm_client.py
packages/pytest-simcore/src/pytest_simcore/aws_ec2_service.py
packages/pytest-simcore/src/pytest_simcore/aws_server.py
packages/pytest-simcore/src/pytest_simcore/aws_ssm_service.py
packages/pytest-simcore/src/pytest_simcore/helpers/aws_ec2.py
packages/pytest-simcore/src/pytest_simcore/helpers/moto.py
packages/service-library/src/servicelib/logging_utils.py
packages/service-library/tests/test_logging_utils.py
packages/settings-library/src/settings_library/ssm.py
scripts/maintenance/migrate_project/Makefile
services/autoscaling/tests/unit/conftest.py
services/clusters-keeper/tests/unit/conftest.py

This PR introduces in the AWS-library the interfacing with [AWS System Manager service (SSM)](https://aws.amazon.com/systems-manager/features/#:~:text=AWS%20Systems%20Manager%20provides%20configuration,%2C%20firewall%20settings%2C%20and%20more.)
Excerpt of AWS SSM:
```AWS Systems Manager allows you to safely automate common and repetitive IT operations and management tasks across multiple accounts and AWS Regions.```
This PR is a pre-requisite of https://github.com/ITISFoundation/osparc-simcore/pull/5923
In a nutshell, the SSM service allows to run arbitrary commands on EC2 machines when they are running. And this is needed in order to prepare EBS-based buffer machines.

✨AWS-library: Added interface to AWS SSM

---

services/api-server/requirements/_base.in
services/api-server/requirements/_base.txt
services/api-server/requirements/_test.txt
services/api-server/requirements/_tools.txt
services/api-server/src/simcore_service_api_server/exceptions/backend_errors.py
services/api-server/src/simcore_service_api_server/exceptions/service_errors_utils.py
services/api-server/tests/unit/test_exceptions.py

- Check that keyword arguments to backend clients match the exceptions to which http status errors are mapped. 
- Fix a bug detected by this new mechanism.
- Add https://github.com/r1chardj0n3s/parse as a dependency to api-server in order to parse inputs to f string template. 
- resolve https://github.com/ITISFoundation/osparc-simcore/issues/6056

🐛🎨 Fix backenderror name injection

---

services/api-server/src/simcore_service_api_server/services/study_job_models_converters.py
services/api-server/tests/mocks/get_job_outputs.json
services/api-server/tests/unit/api_studies/test_api_routes_studies_jobs.py

- This PR fixes a bug discovered by @wvangeit.
- It was caused by the changes I have recently done to how the error handling is done in the api-server
- I also add a test to ensure the function is covered by our tests. Seems that was not previously the case.

🐛  Fix create soft link kwargs

---

packages/service-library/src/servicelib/docker_utils.py
packages/service-library/tests/fastapi/test_docker_utils.py

ti-postpro:2.0.33 triggered some unforeseen issues in the docker pulling process due it seems to unexpected docker pulling status strings.
This PR shall ensure the process does not fail due to pydantic ValidationError but instead logs the issue so that it can be fixed later as this issue proved very hard to reproduce due to the sheer size of the involved docker image (it triggers timeouts while trying to reproduce in pytest, which is not the observed error).
For info: @Konohana0608

🐛Docker image pulling: progress issues while pulling ti-postpro

---

api/specs/web-server/_catalog.py
packages/models-library/src/models_library/api_schemas_webserver/catalog.py
services/catalog/src/simcore_service_catalog/db/repositories/_services_sql.py
services/catalog/src/simcore_service_catalog/models/services_db.py
services/catalog/src/simcore_service_catalog/services/services_api.py
services/catalog/tests/unit/test_db_repositories_services_sql.py
services/catalog/tests/unit/with_dbs/test_api_rpc.py
services/director/src/simcore_service_director/api/v0/schemas/node-meta-v0.0.1.json
services/web/server/src/simcore_service_webserver/catalog/_handlers.py
services/web/server/tests/unit/with_dbs/01/test_catalog_handlers__services.py

A user might gain access to the same service via different groups. This resulted in replicas after joins which made the catalog malfunction
- 🐛Fixes queries for users with multiple GID giving access to the same service
- ✅ Adds more tests for update
- 🐛now returns `versionDisplay` as well in the history
- Fixes on code for #5964 
in place
No
- Will reduce replicas of catalog in [osparc-config](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/730)

🐛 Fixes replicas in catalog services

---

packages/pytest-simcore/src/pytest_simcore/helpers/logging_tools.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
tests/e2e-playwright/Makefile
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/sim4life/conftest.py
tests/e2e-playwright/tests/sim4life/test_sim4life.py

- adds Makefile recipe to test ```make test-s4l-anywhere```
- improve logs
- refactor sim4life test
- adds ```--check-videostreaming``` option when running the s4l test
- playwright integrated chromium, webkit and firefox are unable to connect to videostreaming
- playwright can install and use chrome/msedge which both are able to connect to videostreaming
NOTE: in order to use chrome/msedge, one needs to run pytest with ```--browser-channel=chrome``` instead of ```---browser=chromium```
NOTE2: @ignapas once the osparc-test-id is attached to the bitrate element we can add a test that the bitrate grows. After discussions with @mguidon we need to check that the value grows over time to finalize the test.
```
make devenv
cd tests/e2e-playwright
make test-s4l-anywhere
```

♻️E2e: refactor S4L test

---

packages/models-library/src/models_library/api_schemas_webserver/projects_nodes.py
services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handlers__patch.py

- 🐛 Fix patch outputs @odeimaiz

🐛 Fix patch outputs

---

packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/catalog/services.py
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/data/model/IframeHandler.js
services/static-webserver/client/source/class/osparc/info/ServiceLarge.js
services/static-webserver/client/source/class/osparc/info/ServiceUtils.js
services/static-webserver/client/source/class/osparc/metadata/ServicesInStudy.js
services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyUpdate.js
services/static-webserver/client/source/class/osparc/service/Utils.js
services/static-webserver/client/source/class/osparc/share/PublishTemplate.js

Regardless what service key hardcoded in the [new_studies.json](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/static-webserver/client/source/resource/osparc/new_studies.json) file, the plus button will point to the latest compatible service.
related to https://github.com/ITISFoundation/osparc-issues/issues/1404
closes https://github.com/ITISFoundation/osparc-simcore/pull/5710

✨ [Frontend] Plus buttons escalate to latest compatible

---

.github/workflows/ci-testing-deploy.yml
services/dynamic-scheduler/setup.cfg
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rest/_dependencies.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rest/_meta.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/api/rpc/_services.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/settings.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/director_v2/_public_client.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/director_v2/_thin_client.py

Fixes mypy warnings
- https://github.com/ITISFoundation/osparc-simcore/issues/6115

Maintenance: mypy on dynamic-scheduler

---

packages/pytest-simcore/src/pytest_simcore/helpers/aws_ec2.py
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/buffer_machines_pool_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/buffer_machines_pool_core.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_modules_buffer_machine_core.py

This PR introduces EC2 Tag that contain the pre-pulled images list as another step towards fully fledged EBS-backed buffering.
This will be useful once OP modifies the list of pre-pulled images, or to check for compatiblilty.
Driving tests: 
- ```services/autoscaling/tests/unit/test_modules_buffer_machine_core.py```
- also tested against AWS from local

✨Autoscaling: EBS-backed buffer, label EC2 machines with prepulled images list

---

services/static-webserver/client/source/class/osparc/service/Utils.js
services/static-webserver/client/source/class/osparc/study/Utils.js

Bug found in the Service Catalog:
There might be cases where all the versions of a service are either retired or deprecated. This PR deals with that situation.
Fix getLatestCompatible helper function: it used to return null if there was no compatibility.

🐛 [Frontend] Fix Service listing helpers

---

.github/workflows/ci-testing-deploy.yml
packages/postgres-database/requirements/_test.in
packages/postgres-database/requirements/_test.txt
packages/postgres-database/setup.cfg
packages/postgres-database/src/simcore_postgres_database/cli.py
packages/postgres-database/src/simcore_postgres_database/migration/env.py
packages/postgres-database/src/simcore_postgres_database/migration/versions/009c81406676_add_project_running_state.py
packages/postgres-database/src/simcore_postgres_database/migration/versions/10b293fdcd56_alters_product_login_settings.py
packages/postgres-database/src/simcore_postgres_database/migration/versions/a8f0bacbbaef_product_issue_cols_nullable.py
packages/postgres-database/src/simcore_postgres_database/models/base.py
packages/postgres-database/src/simcore_postgres_database/utils_aiopg_orm.py
packages/postgres-database/src/simcore_postgres_database/utils_payments.py
packages/postgres-database/src/simcore_postgres_database/utils_users.py

♻️Maintenance: mypy postgres database package

---

packages/aws-library/src/aws_library/ec2/client.py
packages/aws-library/tests/test_ec2_client.py
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/buffer_machines_pool_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_modules_ec2.py
services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters.py

- renamed ```start_aws_instance``` to ```launch_instances``` in EC2 client
- ```terminated_instances``` in ```Cluster``` is now a list of ```NonAssociatedInstances```
- instrumentation around the autoscaling EC2 client is now automatic via decoration of the ```launch_instances```, ```stop_instances``` and ```terminate_instances``` methods -> no miss on metrics
- added more metrics related to the autoscaling Cluster class (added missing Gauges for broken, terminating and terminated fields)
- added Gauge for newer buffer instances field
- added Counters for started, stopped, launched and terminated instances
**--> this has implications on the Grafana dashboard for autoscaling which will require an update as the metrics names have changed. This will be done once this PR goes in.**
Driving …

✨Autoscaling: instrumentation improvements

---

services/director-v2/src/simcore_service_director_v2/core/application.py
services/director-v2/src/simcore_service_director_v2/core/errors.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/projects_networks.py
services/director-v2/src/simcore_service_director_v2/modules/projects_networks.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py

This will allow for the e2e to properly run the BIOS template in master@z43
- 🐛 Fixes an issue where the `webserver` did not update the project networks for anonymous user templates, only the comp jobs were updated.
- 🐛 Fixes an issue where the `director-v2` was reporting the wrong error. It is now reporting correctly.

🐛 Fixes broken anonymous user opening templates

---

services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js
services/static-webserver/client/source/class/osparc/node/LifeCycleView.js
services/static-webserver/client/source/class/osparc/service/Utils.js
services/static-webserver/client/source/class/osparc/study/Utils.js

The "Update available" icon was always visible, this PR fixes it.
Before:

🐛 [Frontend] Fix always visible Update available icon

---

services/static-webserver/client/source/class/osparc/utils/Utils.js
services/static-webserver/client/source/class/osparc/workbench/Annotation.js

When listing projects, pydantic, I believe, is translating the colors used in the annotations from hex to named colors. The frontend wasn't able to understand some of those named colors (i.e. #0FF -> Cyan).
This PR workarounds that problem by checking the named colors in a longer list and converting it again to hex. If the named color doesn't exist in the list it will default it to light gray.
The annotations that were failing in the deserialization step:

🐛 [Frontend] Annotations fix: Convert named colors to HEX

---

services/web/server/src/simcore_service_webserver/catalog/_api_units.py
services/web/server/src/simcore_service_webserver/catalog/_models.py

Occasionally, listing services respond with a 500 error.
The logs indicate that this issue is due to a validation error caused by an invalid key in the caching mechanism, which uses the **sync** library [cachetools](https://cachetools.readthedocs.io/en/stable/). The bug appears to stem from concurrent access to a synchronous cache registry. It's important to note that the new design requests each page concurrently, and validation is also performed asynchronously.
The likely solution is to switch to [`aiocache`](https://aiocache.aio-libs.org/en/latest/index.html) even for this synchronous case, but that would require some design changes. Before moving forward with that approach, I'd like to introduce these new variables to control the `cachetools` options and conduct some manual …

⚗️ env-vars to control cachetools

---

packages/pytest-simcore/src/pytest_simcore/__init__.py
packages/pytest-simcore/src/pytest_simcore/helpers/__init__.py

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6063

🐛Maintenance: fixes warning in pytest

---

services/static-webserver/client/source/class/osparc/data/model/Node.js
services/static-webserver/client/source/class/osparc/desktop/MainPage.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js

Our [old puppeteer's browser doesn't support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility) the ``hasOwn`` method, this PR replaces it with the ``in`` which does almost exactly the same.

e2e: Fix old puppeteer guests

---

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/proxy.py
services/director/src/simcore_service_director/producer.py
services/docker-compose.local.yml
services/docker-compose.yml

- Upgrades traefik to v3
- For now uses traefik-v2 style routing (this needs to be changed eventually...)
- Change: `docker` provider is now called `swarm`
- Change: Already prepare OTLP tracing and remove old-style jaeger/zipkin connection
- https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/770
- https://github.com/ITISFoundation/osparc-ops-environments/pull/731

⬆️ Upgrade traefik to major version 3

---

services/static-webserver/client/source/class/osparc/data/model/Workbench.js
services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js

Reproducible in the VTK study dispatcher.
Wait until the workbench is fully deserialized (we now need to fetch the metadata of the specific services) before starting pulling its state.

🐛 [Frontend] Fix: Guest Node viewer

---

services/docker-compose.yml

Fixes forgotten adjustment in the TraefikRuleSyntax which seem to have breaking compatibility *even* when the flag to use the V2-style syntax is set.
A bit experimental tbh.
See: https://doc.traefik.io/traefik/migration/v2-to-v3-details/#new-v3-syntax-notable-changes

Traefik v3 Rule Syntax Errors

---

services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js

This PR fixes a small glitch found during the RM presentation. Get rid of the duplicated initial call when opening the Credits Summary.

🐛 [Frontend] Fix: Credits summary time range

---

services/docker-compose.local.yml
services/docker-compose.yml

There were still issues with old-style traefik-v2 rules. It seems that hostregexp how we used it is disliked by traefik-v3
I will force-merge this one as well

🐛⚗️ Fix: Traefik v3 rule syntax (part 2)

---

services/web/server/requirements/_base.in
services/web/server/requirements/_base.txt
services/web/server/src/simcore_service_webserver/catalog/_api.py
services/web/server/src/simcore_service_webserver/catalog/_api_units.py
services/web/server/src/simcore_service_webserver/catalog/_models.py
services/web/server/tests/unit/isolated/test_catalog_models.py

During manual testing on the master deployment, specifically with [PR #6169](https://github.com/ITISFoundation/osparc-simcore/pull/6169), we identified that the caching mechanism for the services listing is failing due to issues with async concurrency. This problem causes the entire service call to fail.
- **Replaces Sync Caching with Async Caching:**
- The existing synchronous caching implementation using [`cachetools`](https://cachetools.readthedocs.io/en/stable/) has been replaced with an asynchronous caching solution using [`aiocache`](https://aiocache.aio-libs.org/en/latest/index.html) to better handle concurrent calls.
- This change eliminates the need for `asyncio.thread`, simplifying the implementation.
- The `cachetools` dependency has been removed from the project.
- **Improves …

🐛 fixes cache issue in web-server services i/o model

---

packages/models-library/src/models_library/errors_classes.py
packages/models-library/tests/test_errors_classes.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/catalog/services.py
services/api-server/src/simcore_service_api_server/exceptions/service_errors_utils.py
services/api-server/src/simcore_service_api_server/services/director_v2.py
services/api-server/tests/unit/api_solvers/test_api_routers_solvers_jobs_logs.py
services/api-server/tests/unit/test_services_directorv2.py

Addresses this error found in tip.science deploy
```
Unexpected KeyError: Oops! Something went wrong, 
but we've noted it down and we'll sort it out ASAP. 
Thanks for your patience! [OEC:139646582688800]
```
The api-server responds 500 to `GET /v2/computations/ ...`  instead of 404 (in this case) due to an unhandled error
- 🧪 Reproduced logs in `test_oec_139646582688800_missing_ctx_values_for_msg_template`
- The tests passes in HEAD master but tip.science is at [_v1.75.0_ ](https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.75.0)
- We believe this is caused because this fix https://github.com/ITISFoundation/osparc-simcore/pull/6064 was still not released there
- 🎨 Overrides ` OsparcErrorMixin.__str__`  to **avoid raising `KeyError` when key is missing in template error …

🐛 Fixes unhandled `KeyError` when missing keys in exception's `msg_template`

---

packages/simcore-sdk/tests/integration/test_node_ports_common_aws_s3_cli.py
packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py
services/catalog/src/simcore_service_catalog/services/services_api.py
services/storage/src/simcore_service_storage/handlers_files.py

This [https://github.com/ITISFoundation/osparc-simcore/pull/5786](https://github.com/ITISFoundation/osparc-simcore/pull/5786) changed how the webserver calls into storage by replacing uuid_filter with project_id. This in effect created an issue with how much files were returned.
This was indirectly fixed by [https://github.com/ITISFoundation/osparc-simcore/pull/5796](https://github.com/ITISFoundation/osparc-simcore/pull/5796), which introduced then another problem:
https://github.com/ITISFoundation/osparc-issues/issues/1587
so now, there is again an in-between, which should fix most of the issues. but maybe have a slight reduce
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1593
- Bonus:
- reduce needed storage to run tests and should implement …

🐛Bugfix: Cannot instantiate templates

---

services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js

Since we refactored the ``/services`` endpoint, the deserialization of the nodes in the workbench is an asynchronous step (specially when starting a project which its services are not up-to-date). In the App Mode, when starting the slides, it can happen that the workbench is not yet completely deserialized, this makes the slideshow to be shown empty.
This PR waits until the workbench is deserialized before the slideshow is started.

🐛 [Frontend] Fix App mode: Wait until the workbench is deserialized to start

---

.github/ISSUE_TEMPLATE/5_release.yml
.github/ISSUE_TEMPLATE/6_hotfix.yml

- 📝 revision of release template

📝 revision of release template

---

packages/service-library/src/servicelib/logging_utils.py
packages/service-library/tests/test_logging_utils.py

Addresses some issues with `servicelib.logging_utils`:
- 🎨 fixes `log_decorator` to log only in `level`
- ✨ new `log_exceptions` context manager
The idea of `log_decorator` is to log inputs/outputs of a function. Inputs are the function arguments and are logged **before** calling the function. Outputs are either returned values or exceptions which are logged **after** the call.
Let's look at this example. Assume I decorate `foo` to log in debug mode
```python
@log_decorator(_logger, logging.DEBUG)
def foo(x):
if x<0:
raise ValueError(x)
return 2*x
```
and then use it inside another function where I handle the exceptions it might raise
```python
def safe_foo(x):
try:
return foo(x)
except ValueError: 
return foo(abs(x)
```
Then, when I call  `safe_foo(-1)` what would you expect in the logs. …

🎨 Improving `servicelib.logging_utils`

---

services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6227

🐛Autoscaling in computational clusters could not start without SSM parameters 

---

.pre-commit-config.yaml
services/catalog/src/simcore_service_catalog/db/repositories/services.py
services/catalog/src/simcore_service_catalog/services/services_api.py
services/catalog/tests/unit/with_dbs/conftest.py
services/catalog/tests/unit/with_dbs/test_api_rpc.py
services/catalog/tests/unit/with_dbs/test_db_repositories.py

🐛 enforces access-rights for `get` and `update` on the catalog service
- Part of https://github.com/ITISFoundation/osparc-simcore/issues/6201
```
make devenv
cd services/catalog
pytest -v -k test_rpc_get_service_access_rights tests
```
None

🐛 catalog: fixes access-rights to `get` and `update` services

---

packages/aws-library/src/aws_library/ec2/_models.py
services/autoscaling/src/simcore_service_autoscaling/constants.py
services/autoscaling/src/simcore_service_autoscaling/modules/buffer_machines_pool_core.py
services/autoscaling/src/simcore_service_autoscaling/utils/buffer_machines_pool_core.py
services/autoscaling/tests/unit/test_modules_buffer_machine_core.py
services/autoscaling/tests/unit/test_utils_buffer_machines_pool_core.py
services/clusters-keeper/tests/unit/test_core_settings.py

during early testing, this was identified as a problem. AWS EC2 Tags take a maximum of 256 characters. When pre pulling images in buffer EC2, a tag with the pre-pulled images is set on the instance for fast retrieval.
Since the list of pre pulled images can be quite long now this is chunked.
```services/autoscaling/tests/unit/test_utils_buffer_machines_pool_core.py```
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6230

🎨Autoscaling: chunk prepulled image AWS EC2 tags

---

services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/buffer_machines_pool_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation.py

- too many buffer machines were created due to an incorrect analysis of the buffer pools
- the Gauges metrics for the cluster machines were not correctly decreasing, thus showing wrong metrics on the number of  nodes. Especially in pending nodes. @JavierGOrdonnez 
- small log improvements
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6250
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6123

🐛Autoscaling: Cluster gauges not reset correctly, too many buffer created, log improvements

---

services/docker-compose.yml

Portal links opening failed in master.
The reason is that the Traefik-Rule for sending `/study/UUID` to the webserver would not trigger, as the old-style go-regexp doesnt work anymore in traefik-v3. I have changed the old UUID-catching Regexps to the style of the already updated, already functional one that catches modern (dv2) dynamic services.
I will forcemerge this after some consideration.

🐛 Fix wrong go-style UUID regexp - made portal links fail

---

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/proxy.py
services/docker-compose.yml

partially reverts https://github.com/ITISFoundation/osparc-simcore/pull/6257 which made the CORS error appear.
Also the 502 catch all was broken.

🐛Traefik: partially revert changes

---

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/proxy.py
services/docker-compose.yml

- this should fix the CORS error in the deployments.
- might break it in the local builds

🐛Traefik v3: adapt Go regexp (2nd trial)

---

services/catalog/src/simcore_service_catalog/services/director.py
services/docker-compose.yml

using v3 syntax in deployments vs using v2 locally is not a good thing

🐛Traefikv3: Use v3 regexp syntax

---

services/docker-compose.yml

v2 traefik used regexp named as such ```{node_uuid: REGEX}``` where v3 uses now Golang rexexp that go like so ```(?P<node_uuid>REGEX)```

🐛Traefik v3: replace v2 regexp with v3 regexp

---

packages/aws-library/src/aws_library/s3/__init__.py
packages/aws-library/src/aws_library/s3/_client.py
packages/aws-library/tests/test_s3_client.py
services/storage/src/simcore_service_storage/s3_utils.py
services/storage/src/simcore_service_storage/simcore_s3_dsm.py

it seems the interface to copy_file in aioboto3 changed a bit and the progress callback now returns the file total size
this PR fixes the progress reporting
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6209
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1681

🐛Storage: Copying returns wrong size

---

packages/simcore-sdk/src/simcore_sdk/node_ports_common/data_items_utils.py
packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py
packages/simcore-sdk/tests/conftest.py
packages/simcore-sdk/tests/helpers/utils_port_v2.py
packages/simcore-sdk/tests/integration/test_node_ports_v2_nodeports2.py
packages/simcore-sdk/tests/unit/test_node_ports_v2_port.py

This issue was simple to reproduce, but we never had a good report. This was a nightmare for so many people reporting missing files in their inputs.
If input ports contain more than one port with files, these would get downloaded two at a time.
What happened? `threading.get_ident()` would return a unique id for the given thread. Too bad that this ID can be reassigned. To avoid future issues uuid4 replaced it.
It is now possible to pull 10 ports with each containing a 1GB file without any issue. It now works reliably every time.
Before this, almost always you would have issues when pulling 5 ports with a 1GB file in each port.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6276

🐛 More than 1 input port containing files can be safely pulled

---

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6293

🐛Computational backend: if a pipeline raises, it should not prevent handling of other pipelines

---

services/storage/src/simcore_service_storage/s3_utils.py

Removes the "changing" part of the message going to the frontend, so that @odeimaiz can change how copying is shown.
Maybe when time is right we shall better go with https://github.com/ITISFoundation/osparc-simcore/pull/6288 but for now this appears to critical to apply it.
- relates to https://github.com/ITISFoundation/osparc-issues/issues/1628

🎨 Backend part of UX improvements

---

packages/aws-library/src/aws_library/s3/_client.py
packages/aws-library/src/aws_library/s3/_constants.py
services/storage/src/simcore_service_storage/s3_utils.py
services/storage/tests/unit/test_simcore_s3_dsm.py

https://github.com/ITISFoundation/osparc-simcore/pull/6272 did not completely fix the issue of the progress while duplicating studies or instantiating templates:
- we use boto3 which officially wraps the AWS API for python,
- the copy() function of boto3 auto-switches between copy_object and multipart copying based on a threshold that was overriden by us at a value of 5GB instead of the default value of 8MB,
- this was done as copy_object seemed much faster and seemed to not download/upload data contrary to the multipart counterpart,
- the problem here is that copy_object does not provide any kind of feedback on the copy progress,
- the copy callback for progress would only be called with files larger than 5GB, which is not ideal.
This PR therefore adds:
1. explicit call on the progress …

🐛S3: when copying files there is no callback if the multipart threshold is not reached

---

services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_models.py

The metrics values for the autoscaling EBS buffers were always showing 0.
This PR fixes this issue as the Gauge used were overriden due to multiple instance types. Using a flat list fixes this.
related dashboard:

🐛Autoscaling: Buffer pools metrics always showing 0

---

packages/service-library/src/servicelib/rabbitmq/__init__.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/catalog/services.py
services/web/server/src/simcore_service_webserver/payments/_rpc.py

Increases timeout of some critical rpc calls until finding out what is slowing down these calls (feedback @mguidon)
- @mguidon feedback
In place
None

⚗️ Increases timeout of rpc calls

---

services/web/server/docker/boot.sh
services/web/server/requirements/_base.txt
services/web/server/requirements/_test.txt
services/web/server/requirements/_tools.txt

In master deploy webserver cannot start in one of the nodes and we speculate that it is due to guvicorn and how it uses memory.  This PR upgrades `gunicorn` 
|   1 | gunicorn                  | 20.1.0          | 23.0.0     | **MAJOR**  | 1 | web⬆️ |
|   2 | packaging                 | 23.1            | 24.1       | **MAJOR**  | 3 | web⬆️🧪🔧 |
|   3 | setproctitle              | 1.2.3           | 1.3.3      | *minor*    | 1 | web⬆️ |
|   4 | tomli                     | 2.0.1           | 🗑️ removed |  | 2 | web🧪🔧 |
- in master deploy webserver cannot start in one of the nodes and we speculate that it is due to guvicorn and how it uses memory
in place
None

⬆️ upgrades gunicorn dependencies in webserver

---

scripts/maintenance/computational-clusters/autoscaled_monitor/dask.py
services/autoscaling/src/simcore_service_autoscaling/models.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_base.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_dynamic.py
services/autoscaling/src/simcore_service_autoscaling/modules/dask.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_constants.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_models.py
services/autoscaling/tests/manual/docker-compose-computational.yml
services/autoscaling/tests/unit/conftest.py

Autoscaled Cluster was expanded to also keep _retired_nodes_.
These nodes were retired via dask scheduler mechanism, that removes idle workers and transfer their memory to other workers based on some internal mechanisms.
These "retired" workers are now properly recognized, and are forcefully drained. This way they can be:
- re-used, by undraining and restarting a dask-sidecar in case a new arrives in between,
- or terminated if there is nothing else to do
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6319

🐛Autoscaling/Comp backend: drain retired nodes so that they can be re-used

---

services/static-webserver/client/source/class/osparc/dashboard/ContainerHeader.js
services/static-webserver/client/source/class/osparc/dashboard/FolderButtonItem.js
services/static-webserver/client/source/class/osparc/dashboard/FoldersTree.js
services/static-webserver/client/source/class/osparc/dashboard/MoveResourceToWorkspace.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceFilter.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/WorkspaceHeader.js
services/static-webserver/client/source/class/osparc/dashboard/WorkspacesAndFoldersTree.js
services/static-webserver/client/source/class/osparc/dashboard/WorkspacesTree.js
services/static-webserver/client/source/class/osparc/editor/WorkspaceEditor.js
services/static-webserver/client/source/class/osparc/share/CollaboratorsWorkspace.js
services/static-webserver/client/source/class/osparc/store/Folders.js
services/static-webserver/client/source/class/osparc/store/Workspaces.js

related to https://github.com/ITISFoundation/osparc-simcore/issues/6315
related to https://github.com/ITISFoundation/osparc-issues/issues/716

🐛 [Frontend] Folders tree: Fixes I

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright_sim4life.py
tests/e2e-playwright/Makefile
tests/e2e-playwright/tests/sim4life/test_sim4life.py
tests/e2e-playwright/tests/sim4life/test_template.py

https://github.com/ITISFoundation/osparc-simcore/pull/6353 introduced a new state in the progress status report of dynamic services.
E2E was broken because of it.
This PR fixes it.
Bonus:
- fixes the Makefile that was broken

🎨E2E: adapt test to new service startup status

---

services/web/server/src/simcore_service_webserver/folders/_folders_api.py
services/web/server/src/simcore_service_webserver/folders/_folders_db.py
services/web/server/src/simcore_service_webserver/folders/_folders_handlers.py
services/web/server/src/simcore_service_webserver/folders/errors.py
services/web/server/tests/unit/with_dbs/03/folders/test_folders.py

- 🐛 do not allow moving folder to a child folder

🐛 do not allow moving folder to a child folder

---

packages/settings-library/src/settings_library/redis.py

After the upgrade of python `3.11` enums work a bit differently. `class X(int, Enum)` and `class X(IntEnum)` work differently when serialising them in a string. To maintain the same behaviour it is required to use the `IntEnum`
Previous serialisation `redis://:***@redis:6379/RedisDatabase.ANNOUNCEMENTS` -> current fixed one `redis://:***@redis:6379/5`

🐛 Fixed Redis issue where keys ended up in the wrong deployment.

---

.github/workflows/ci-testing-deploy.yml

MyPy'ing autoscaling service takes a very long time. I could not really find why it is taking sooo much time, but it does not like the structure of autoscaling code, which is not that big.
I guess one other option could be to keep the mypy cache between CI runs, as running mypy a second time goes orders of magnitudes faster.
For now the timeout on autoscaling is increased by 1 minute.

♻️CI: increase timeout on autoscaling to fix mypy slowness

---

services/static-webserver/client/source/class/osparc/dashboard/WorkspaceHeader.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditorIdlingTracker.js

reported by @cosfor1 
If, in the user preferences, the "Automatic Shutdown of Idle Instances" is set to 0, the Idling tracker should never start.
Currently, as soon as the service starts, the frontend will ask the backend if it's inactive, the backend will say, "yes, it's inactive", and the frontend will react as the user was Idle, closing the project.

🐛 [Frontend] Fix ``Automatic Shutdown`` = 0

---

services/docker-compose.yml

The traefik timeout defaults changed between minor versions 2.10 and 2.11: https://doc.traefik.io/traefik/migration/v2/#v211
This PR also adds the increased timeouts of 6h that have been set in the ops-traefik to the simcore traefik, as dy-services such as S4L do fileupload using a singular POST requests that goes via `client --> ops-traefik -- > simcore-traefik -- > caddy --> nginx`. When the REST requests' long-running conenction exceeds `60s`, traefik `>2.10`by default severs the connection. Nginx indicates this client disconnect by responding the unique status code `499`.

🚨🐛 Mitigate dy-service file upload bug: Increase traefik timeouts

---

services/static-webserver/client/scripts/post-compile.py
services/static-webserver/client/source/class/osparc/NewUITracker.js
services/static-webserver/client/source/class/osparc/ui/message/FlashMessage.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

I finally found a user-friendly way to hard reload the app 🥳.
When the osparc detects the that there is a new version available, we will show the ``A new version of the application is now available.`` message together with ``Click the Reload button to get the latest features.`` and the Reload button.
This button will reload the page adding a qooxdoo-specific argument: ``"?qooxdoo:add-no-cache=true"``.
This argument, which is passed and consumed by the boot.js init file, adds a ``nocache=rand()`` query argument to the js resource calls. This forces a hard reload!

✨ [Frontend] Force reload ``no-cache``

---

packages/service-library/src/servicelib/fastapi/prometheus_instrumentation.py
packages/service-library/src/servicelib/fastapi/tracing.py
packages/service-library/src/servicelib/instrumentation.py
services/agent/tests/unit/test_core_routes.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_models.py
services/autoscaling/src/simcore_service_autoscaling/modules/instrumentation/_utils.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_instrumentation_utils.py
services/director-v2/src/simcore_service_director_v2/modules/instrumentation/_models.py

- since https://github.com/ITISFoundation/osparc-simcore/pull/6168 came in, the unit tests in autoscaling started to fail randomly (for example like [this one](https://github.com/ITISFoundation/osparc-simcore/actions/runs/10937502398/job/30363827202))
Here is probably what was happening:
- in tests we use asgi-lifespan to emulate what fastapi does (this is how fastapi recommend of doing)
- since the tracing was introduced, it seems that initialization phase in the tests takes longer, and times-out sometimes (default is 5 seconds)
- the `prometheus_fastapi_instrumentator` library introduced by @bisgaard-itis a long time ago uses a global _CollectorRegistry_, and is initialized,
- after the time out happen, this is not cleaned up (since global are :imp: ),
- all subsequent tests fail, as …

🐛⚗️Prometheus instrumentation incorrectly setup

---

packages/pytest-simcore/src/pytest_simcore/helpers/logging_tools.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright_sim4life.py
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/sim4life/test_sim4life.py
tests/e2e-playwright/tests/sim4life/test_template.py

- increases the timeout when checking S4l videostreaming to 30 seconds
- logs warning if the websocket(s) are closed
- logs error if the websocket(s) have errors

✨E2E: increase timeout for video streaming and improve a bit logs about websockets

---

.github/workflows/ci-testing-deploy.yml

- increase the timeout on unit test of autoscaling to 22 minutes
- mypying the autoscaling services takes >5 minutes!! something is not going well there.
- maybe we should keep the mypy cache. or better, find what is going on!

♻️CI: autoscaling mypy takes longer and longer.

---

packages/models-library/src/models_library/users.py
services/web/server/src/simcore_service_webserver/payments/_onetime_api.py
services/web/server/src/simcore_service_webserver/users/_db.py
services/web/server/src/simcore_service_webserver/users/exceptions.py
services/web/server/src/simcore_service_webserver/wallets/_constants.py
services/web/server/src/simcore_service_webserver/wallets/_handlers.py
services/web/server/tests/unit/with_dbs/03/wallets/payments/test_payments.py

Improved Error Handling for Missing Pre-registration and Billing Details**
Previously, when account setup was incomplete or pre-registration information (such as billing country) was missing, the payment process would fail raising an 500 that displayed confusing message in the front-end (should be address in https://github.com/ITISFoundation/osparc-simcore/pull/5487). This was due to the REST handlers not properly addressing the absence of required billing details.
With this update, the service now responds with `HTTP_503_SERVICE_UNAVAILABLE` and an explicit message indicating that the payment service is unavailable until the necessary billing details are provided. Currently, these details can only be supplied on the service side (filling the `user_pre_registration` table).
Additionally, …

 🐛 Improved Error Handling for Missing  Billing Details

---

services/web/server/src/simcore_service_webserver/products/_model.py
services/web/server/tests/unit/isolated/test_products_model.py

The configuration of the products are currently set directly in the database via adminer. I found that it is easy to make a mistake and introduce spaces in `Product.host_regex` which lead to the system not delivering the right product.
This PR ensures that the Product pre-validator trims all leading and trailing whitespaces in the regex entry
Maintenance
```
pytest tests/unit/isolated -k test_product_host_regex_with_spaces
```

🎨 Enhances Product parsing to strip whitespaces in host_regex

---

services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
services/static-webserver/client/source/class/osparc/product/TIPTeaser.js

Bonus:
related to https://github.com/ITISFoundation/osparc-issues/issues/1701

🎨 [Frontend] Access Full TIP

---

services/static-webserver/client/source/class/osparc/data/model/Study.js

reported by @Konohana0608 
If a File Picker is uploading a file, the backend could override the current state with some older state.

🐛 [Frontend] Fix: Do not listen to output related backend updates if the node is a frontend node

---

tests/e2e-playwright/tests/tip/test_ti_plan.py

- Fixes wrong check in `test_classic_tip_plan` in the case of non-lite version (also reported by @matusdrobuliak66 )
- Follows up from https://github.com/ITISFoundation/osparc-simcore/pull/6388
- Issue in e2e reported by @matusdrobuliak66

✅ fixes check on full version

---

services/static-webserver/client/source/class/osparc/announcement/AnnouncementUIFactory.js
services/static-webserver/client/source/class/osparc/auth/ui/LoginView.js

Right now, all announcements are shown in the login page.
Before:
After:
related to https://github.com/ITISFoundation/osparc-issues/issues/1701

🐛 [Frontend] Announcements: allow in ribbon only

---

tests/e2e-playwright/tests/tip/test_ti_plan.py

fixes wrong sequence in classic tip 
- Follows up https://github.com/ITISFoundation/osparc-simcore/pull/6445

e2e: fixes wrong sequence in classic tip 

---

packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone_utils.py
packages/simcore-sdk/tests/unit/test_node_ports_common_r_clone_utils.py

This issue was polluting the logs with tracebacks, event though it had no side effect.
Issue was caused by a missing parser for a log line similar to `'{"level":"info","msg":"There was nothing to transfer","source":"sync/sync.go:954","time":"2024-09-25T10:18:04.904537+00:00"}'`
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6429

🐛 Fixes issue with parsing logs polluting sidecar logs

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py

🐛 fix tip e2e test

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py

Enhancements:
- Logs expected number of expected states transmitted via socketio
- Dedicated function to check states: `received_required_node_progress_types`
- Timeout is ignored only when progress of all required_node_progress_types are received (https://github.com/ITISFoundation/osparc-simcore/issues/6449)
- Follows https://github.com/ITISFoundation/osparc-simcore/pull/6458

✅ e2e: Final touches to tip testing

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
tests/e2e-playwright/tests/conftest.py

Fixes a typo in logger formatter in https://github.com/ITISFoundation/osparc-simcore/pull/6459
This should fix e2e master failures
CC: batman @mrnicegyu11 
- Fixes on https://github.com/ITISFoundation/osparc-simcore/pull/6459
NOne

✅ e2e: Fixes typo in tests

---

packages/models-library/src/models_library/errors_classes.py
packages/models-library/tests/test_errors_classes.py
packages/service-library/src/servicelib/logging_utils.py
packages/service-library/tests/test_error_codes.py
packages/service-library/tests/test_logging_utils.py
services/web/server/src/simcore_service_webserver/_constants.py
services/web/server/src/simcore_service_webserver/users/_constants.py
services/web/server/src/simcore_service_webserver/users/_handlers.py
services/web/server/src/simcore_service_webserver/users/api.py
services/web/server/src/simcore_service_webserver/users/exceptions.py

This PR provides some helpers for better error-handling and diagnostics.  This is applicable to any type of excption but in this case, we apply to a common unhandled error we found when a platform product is partially configured and the `groups_extra_properties` configuration is missing.
- The exception is first categorized as `MissingGroupExtraPropertiesForProductError` error in the web-server
- Using decorator `_handle_users_exceptions` we handle it in the users rest API handlers
There we handle as
An exception is handled at the rest-handler level. This exception cannot be resolved and we need to send a comprehensive message to the front-end user as well as log sufficient information in the server for troubleshooting.  The handling of the exception has the following steps
1. create an …

🐛🎨 Fixes unhandled config error and new log helpers for better troubleshotting

---

services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js

At the moment, if the service that the plus button points to is deprecated (defined in the ``new_studies.json``), the plus button will not be shown.
Since we want to be very flexible, and deprecate the old versions only in some cases, this PR changes that behaviour. We assume that the deprecated service will have an updatable non deprecated key/version.

🎨 [Frontend] S4L and S4L lite: Include deprecated versions in plus button, they should all be updatable to a non deprecated one

---

services/static-webserver/client/source/class/osparc/dashboard/ToggleButtonContainer.js
services/static-webserver/client/source/class/osparc/tours/Manager.js
services/static-webserver/client/source/class/osparc/utils/Utils.js
services/static-webserver/client/source/class/osparc/widget/logger/LoggerView.js

reported by @cosfor1 
If the ``selector`` defined in the Guided Tour was present more than once, the frontend would try to point to the first match, but it could happen that the ``selector`` wasn't on screen. This PR will fix that scenario by pointing only at the first on-screen-match.
- closes https://github.com/ITISFoundation/osparc-simcore/issues/6462

🐛 [Frontend] Guided Tours: point to visible selector or skip

---

services/agent/requirements/_base.txt
services/agent/requirements/_test.txt
services/agent/requirements/_tools.txt
services/agent/src/simcore_service_agent/core/application.py
services/agent/src/simcore_service_agent/core/settings.py
services/agent/tests/conftest.py
services/agent/tests/unit/test_modules_volumes_cleanup_s3.py

Upgrades the agent service to Pydantic v2.
- resolves #4481

Upgrade agent service (Pydantic v2)

---

services/efs-guardian/requirements/_base.txt
services/efs-guardian/requirements/_test.txt
services/efs-guardian/requirements/_tools.txt
services/efs-guardian/src/simcore_service_efs_guardian/core/application.py
services/efs-guardian/src/simcore_service_efs_guardian/core/settings.py
services/efs-guardian/src/simcore_service_efs_guardian/exceptions/_base.py

Upgrade the EFS guardian service to Pydantic v2.
- resolves #4481

Upgrade EFS guardian service (Pydantic v2)

---

packages/common-library/src/common_library/serialization.py
packages/models-library/src/models_library/invitations.py
services/invitations/openapi.json
services/invitations/requirements/_base.txt
services/invitations/requirements/_test.txt
services/invitations/requirements/_tools.txt
services/invitations/src/simcore_service_invitations/api/_invitations.py
services/invitations/src/simcore_service_invitations/api/_meta.py
services/invitations/src/simcore_service_invitations/cli.py
services/invitations/src/simcore_service_invitations/core/settings.py
services/invitations/src/simcore_service_invitations/services/invitations.py
services/invitations/tests/unit/api/conftest.py
services/invitations/tests/unit/api/test_api_invitations.py
services/invitations/tests/unit/api/test_api_meta.py
services/invitations/tests/unit/conftest.py
services/invitations/tests/unit/test__model_examples.py
services/invitations/tests/unit/test_cli.py
services/invitations/tests/unit/test_invitations.py

Upgrade the invitation service (Pydantic v2).
- resolves #4481

Upgrade invitations service (Pydantic v2)

---

services/static-webserver/client/compile.json
services/static-webserver/client/source/class/osparc/dashboard/GridButtonNew.js
services/static-webserver/client/source/class/osparc/dashboard/ListButtonNew.js
services/static-webserver/client/source/class/osparc/dashboard/NewStudies.js
services/static-webserver/client/source/class/osparc/product/AboutProduct.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4llite/Dashboard.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4llite/S4LLiteSpecs.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4llite/S4LLiteUI.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4llite/Welcome.js
services/static-webserver/client/source/resource/osparc/new_studies.json

🎨 [Frontend] Rebranding: S4L lite -> Sim4Life.lite

---

packages/settings-library/src/settings_library/utils_session.py
services/docker-compose-dev-vendors.yml

Apparently `Firefox` handles cookies differently than `Chrome` and `Safari`. It keeps cookies with the same name but different domains.
Even after invalidating the session key for the cookies. You login into `Firefox` open a new style dynamic service and authentication fails. Apparently it send out old cookie, the one with domain `osparc.io` (which is invalid) instead of the one with `.osparc.io` domain. This causes a 401 reply when opening `UUID.services.osparc.io`.
To avoid issues for users, the session cookie is being renamed.
- https://github.com/ITISFoundation/osparc-simcore/pull/6484

♻️ Renaming session cookie once again

---

services/api-server/requirements/_base.txt
services/api-server/requirements/constraints.txt
services/api-server/src/simcore_service_api_server/models/pagination.py

Enhancements to Customization in `fastapi_pagination` and Fix for `limit` Query Parameter Customization
- ⬆️ Upgrades `fastapi_pagination` page by removing version limit in `constraints.txt`
-  ♻️🐛 Uses new  `CustomizedPage` to customise query parameters and name of the `Page` model. We also replace `Field` by `Query` to avoid error reported in `constraints.txt`  (`AttributeError: 'FieldInfo' object has no attribute 'in_'`). @giancarloromeo I believe this is also causing the same issues we see in https://github.com/ITISFoundation/osparc-simcore/issues/6511. 
**REMINDER**: @giancarloromeo when this is merged into `master`, do not forget to resync your branches with `master` so you get this change.
- Supports https://github.com/ITISFoundation/osparc-simcore/issues/6511 
- Part of …

⬆️ ♻️ Upgrade pagination customisation in api-server

---

services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_runs.py
services/director-v2/tests/unit/with_dbs/conftest.py
services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py

Issue: the project metadata are not set correctly in the comp_runs table when sim4life runs a job
Observations:
- Tried to reproduce the issue using a Jupyterlab and running the osparc client to no avail, it works there properly,
- Tried to add the exact same metadata and it still works.
Actions:
- added a debug log to see if the call in the director-v2 is doing some weird behavior.
- improved testing in dv-2 regarding metadata
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/6530

♻️Sim4Life computational jobs are not parented correctly

---

services/static-webserver/client/source/class/osparc/auth/ui/LoginView.js

As requested by @calys, this PR makes the ``Request Account`` button in https://tip.itis.swiss/ behave differently. Hardcoded in the frontend code, it will pop a dialog saying:
```
This version of the planning tool will be phased out soon and no longer accepts new users.
Please visit TIP.lite or TIP instead. See here for more information.
```

🎨 [Frontend] TIP.itis.swiss: Show Phase out message at Request Account

---

services/static-webserver/client/source/class/osparc/utils/Utils.js

After logging in, the frontend creates a ``client_session_id`` used by the websocket and some projects related request headers. This ``client_session_id`` is kept in the ``sessionStorage`` of the borwser.
If somehow this one gets deleted or disappears, whenever it's required, the frontend will create a new one that will be only used by the projects related requests, the websocket after reconnecting it will keep the previous ``client_session_id``. This misalignment makes the Garbage Collector kill services that are started with this new session id.
This PR fixes this scenario by checking (and reusing) if the websocket has a ``client_session_id`` before creating a new one.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6087

🐛 [Frontend] Reuse ``client_session_id`` from socket's query instead of creating a new one

---

services/dask-sidecar/requirements/_base.in
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py
services/dask-sidecar/tests/unit/test_file_utils.py

as explained in https://github.com/ITISFoundation/osparc-simcore/issues/6244 this PR makes sure we use deterministic Zipping when uploading files from the dask-sidecar.
`test_push_file_to_remote_creates_reproducible_zip_archive`
The test shows that the current implementation already created deterministic zip files (e.g. hash of 2 zips containing the same files created at different time points are the same). Nevertheless, since the computational backend currently allows to pass only 1 file and the services are actually responsible for creating their own zip files, this is probably mostly useless at the moment.
When we allow to have folders to be compressed by the dask-sidecar this might prove useful.

🎨Dask sidecar: use reproducible zipfile library

---

packages/aws-library/requirements/_base.txt
packages/service-library/requirements/_base.txt
packages/service-library/src/servicelib/deferred_tasks/_utils.py
packages/simcore-sdk/requirements/_base.txt
services/agent/requirements/_base.txt
services/api-server/requirements/_base.txt
services/autoscaling/requirements/_base.txt
services/catalog/requirements/_base.txt
services/clusters-keeper/requirements/_base.txt
services/dask-sidecar/requirements/_base.txt
services/datcore-adapter/requirements/_base.txt
services/director-v2/requirements/_base.txt
services/dynamic-scheduler/requirements/_base.txt
services/dynamic-sidecar/requirements/_base.txt
services/invitations/requirements/_base.txt
services/payments/requirements/_base.txt
services/resource-usage-tracker/requirements/_base.txt
services/storage/requirements/_base.txt
services/web/server/requirements/_base.txt
tests/swarm-deploy/requirements/_test.txt

###
reverted change from https://github.com/ITISFoundation/osparc-simcore/pull/6575
- #packages before ~ 1
- #packages after ~ 1
|   1 | fast-depends              | 2.4.11, 2.4.2, 2.4.7 | 2.4.12     |            | 19 | agent⬆️</br>api-server⬆️</br>autoscaling⬆️</br>aws-library🧪</br>catalog⬆️</br>clusters-keeper⬆️</br>dask-sidecar⬆️</br>datcore-adapter⬆️</br>director-v2⬆️</br>dynamic-scheduler⬆️</br>dynamic-sidecar⬆️</br>invitations⬆️</br>payments⬆️</br>resource-usage-tracker⬆️</br>service-library🧪</br>simcore-sdk🧪</br>storage⬆️</br>swarm-deploy🧪</br>web⬆️ |
*Legend*: 

⬆️Fast depends: update version due to syntax breaking change

---

services/static-webserver/client/source/class/osparc/utils/Utils.js
services/static-webserver/client/source/class/osparc/widget/logger/LoggerView.js

When Downloading the log file in Firefox wasn't adding any newlines. This PR fixes it.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6074

🐛 [Frontend] Fix: Download logs with newlines (Firefox)

---

packages/service-library/src/servicelib/deferred_tasks/_deferred_manager.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/application.py

This PR sets the default log level of faststream RabbitBroker to DEBUG.
@GitHK will need to review this, as this can't just be that so many messages are created here.
An [issue](https://github.com/ITISFoundation/osparc-simcore/issues/6588) was created for him to review this.

🐛Deferred tasks: set default log level of messages in Faststream broker to DEBUG

---

packages/common-library/src/common_library/serialization.py
packages/settings-library/src/settings_library/utils_cli.py
services/dask-sidecar/requirements/_base.in
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/errors.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/models.py
services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/settings.py
services/dask-sidecar/src/simcore_service_dask_sidecar/tasks.py
services/dask-sidecar/src/simcore_service_dask_sidecar/utils.py
services/dask-sidecar/tests/unit/conftest.py
services/dask-sidecar/tests/unit/test_cli.py
services/dask-sidecar/tests/unit/test_dask_utils.py
services/dask-sidecar/tests/unit/test_docker_utils.py
services/dask-sidecar/tests/unit/test_file_utils.py
services/dask-sidecar/tests/unit/test_models.py
services/dask-sidecar/tests/unit/test_tasks.py
services/dask-sidecar/tests/unit/test_utils.py

⬆️Dask sidecar: migration to v2

---

services/datcore-adapter/requirements/_base.in
services/datcore-adapter/requirements/_base.txt
services/datcore-adapter/src/simcore_service_datcore_adapter/_meta.py
services/datcore-adapter/src/simcore_service_datcore_adapter/api/errors/http_error.py
services/datcore-adapter/src/simcore_service_datcore_adapter/api/errors/pennsieve_error.py
services/datcore-adapter/src/simcore_service_datcore_adapter/api/errors/validation_error.py
services/datcore-adapter/src/simcore_service_datcore_adapter/api/routes/files.py
services/datcore-adapter/src/simcore_service_datcore_adapter/core/application.py
services/datcore-adapter/src/simcore_service_datcore_adapter/core/settings.py
services/datcore-adapter/src/simcore_service_datcore_adapter/models/schemas/datasets.py
services/datcore-adapter/tests/unit/conftest.py
services/datcore-adapter/tests/unit/test_route_datasets.py
services/datcore-adapter/tests/unit/test_route_files.py
services/datcore-adapter/tests/unit/test_route_health.py

- completed `datcore-adapter` migration to pydantic V2
- upgraded fastapi-pagination to be in sync with https://github.com/ITISFoundation/osparc-simcore/pull/6545

⬆️Datcore adapter: migration

---

services/static-webserver/client/source/class/osparc/dashboard/ContextBreadcrumbs.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceFilter.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowserHeader.js
services/static-webserver/client/source/class/osparc/dashboard/WorkspacesAndFoldersTree.js
services/static-webserver/client/source/class/osparc/store/StaticInfo.js

Before introducing yet another context for the StudyBrowser (``trash``), [as pointed out by @pcrespov,](https://github.com/ITISFoundation/osparc-simcore/pull/6587#discussion_r1814723488) this PR refactors its code to make contexts more readable and maintainable.

♻️ [Frontend] Context property for the StudyBrowser

---

services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/desktop/organizations/OrganizationsList.js

Found in the organizations list. Fix: make them empty objects
Bug:
Fixed:

🐛 [Frontend] Fix: Avoid null parameters in requests

---

.codecov.yml
.github/workflows/ci-testing-deploy.yml
.gitignore
packages/aws-library/Makefile
packages/dask-task-models-library/Makefile
packages/models-library/Makefile
packages/notifications-library/Makefile
packages/postgres-database/Makefile
packages/service-integration/Makefile
packages/service-library/Makefile
packages/settings-library/Makefile
packages/simcore-sdk/Makefile
scripts/common-service.Makefile
services/static-webserver/client/source/class/osparc/dashboard/ContextBreadcrumbs.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceFilter.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowserHeader.js
services/static-webserver/client/source/class/osparc/dashboard/WorkspacesAndFoldersTree.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/desktop/organizations/OrganizationsList.js

- upgrade from upstream/master
NOTE: this **must be** merged-commited

⬆️Update from upstream (must be merged-commited)

---

services/web/server/src/simcore_service_webserver/projects/projects_api.py

- 🐛 Removes call to director-v2 which is not needed for patching of project data
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6443

🐛 FIX: project patch when wallet not shared

---

api/specs/web-server/_projects_crud.py
packages/models-library/src/models_library/api_schemas_webserver/projects.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/projects/_crud_handlers.py
services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers.py
services/web/server/tests/unit/with_dbs/02/test_projects_states_handlers.py
services/web/server/tests/unit/with_dbs/03/folders/test_folders.py
services/web/server/tests/unit/with_dbs/03/meta_modeling/test_meta_modeling_iterations.py
services/web/server/tests/unit/with_dbs/03/version_control/conftest.py
services/web/server/tests/unit/with_dbs/03/workspaces/test_workspaces__folders_and_projects_crud.py

- ♻️ Remove PUT project endpoint
- closes https://github.com/ITISFoundation/osparc-simcore/issues/6236

♻️ Remove PUT project endpoint

---

.github/workflows/ci-testing-deploy.yml

🔨Use one cache for UV and pin version to 0.4

---

.github/workflows/ci-testing-deploy.yml
ci/github/unit-testing/notifications-library.bash
ci/github/unit-testing/python-linting.bash
ci/helpers/install_pylint.bash

use per package cache

---

packages/pytest-simcore/src/pytest_simcore/pydantic_models.py

This PR resolves the issue where tests validating examples were previously skipped due to an incomplete upgrade of `iter_model_examples_in_module`. 
NOte that most likely your tests on examples will fail due to the following: Pydantic 2 behavior, which now enforces that fields cannot have `None` as a default unless explicitly declared as nullable (i.e., `field: Type | None`). This update ensures compatibility with these stricter type requirements.
NOTE: when approved, I will force-merge into the branch so we can review the example tests separately.
- Part of #4481

 ⬆️ upgrades `iter_model_examples_in_module` to enable all example tests

---

services/static-webserver/client/source/class/osparc/workbench/DiskUsageController.js
services/static-webserver/client/source/class/osparc/workbench/DiskUsageIndicator.js

This PR follows https://github.com/ITISFoundation/osparc-simcore/pull/6520
When the EFS storage is enabled, the backend sends two different data storage information: "HOST" and "STATE_VOLUMES".
This information (so far "HOST" only) goes into a progress bar above the iframe and it's also displayed in the NodeUI, so that users are aware of their data storage used.
In this PR, the most critical (most ``used_percentage``) data storage will be shown in the indicators, and the tooltip will show all the available information.
- related to https://github.com/ITISFoundation/osparc-simcore/issues/6411

🎨 [Frontend] Show EFS data storage

---

packages/aws-library/tests/test_s3_client.py
packages/models-library/src/models_library/docker.py
packages/postgres-database/tests/test_utils_projects.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/agent/volumes.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/dynamic_sidecar/disk_usage.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/resource_usage_tracker/service_runs.py
packages/simcore-sdk/src/simcore_sdk/node_ports_common/aws_s3_cli_utils.py
packages/simcore-sdk/src/simcore_sdk/node_ports_v2/nodeports_v2.py
packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py
packages/simcore-sdk/tests/integration/conftest.py
packages/simcore-sdk/tests/integration/test_node_data_data_manager.py
packages/simcore-sdk/tests/integration/test_node_ports_common_aws_s3_cli.py
packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py
packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py
packages/simcore-sdk/tests/unit/test_node_ports_common_r_clone_utils.py
services/dynamic-scheduler/requirements/_base.txt
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/service_tracker/_models.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/utils.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_manager.py
services/dynamic-sidecar/tests/unit/test_modules_notifier.py
services/osparc-gateway-server/src/osparc_gateway_server/backend/models.py
services/payments/src/simcore_service_payments/services/payments_gateway.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/api/rpc/_resource_tracker.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/resource_tracker_utils.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/services/resource_tracker_service_runs.py
services/resource-usage-tracker/tests/unit/with_dbs/test_api_resource_tracker_service_runs__export.py

- fixed typing issue in aws-library -> green
- fixed weird assert in resource-usage-tracker + return proper AnyUrl --> green
- fixed wrong requirement in dynamic-scheduler
- fixed wrong imports here and there

♻️Pydantic V2 migration: various fixes

---

scripts/maintenance/migrate_project/src/db.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_catalog.py

I've encountered an issue several times where **ruff automatically converts expressions like `x == True` to `x is True`**. This becomes problematic in SQLAlchemy queries when expressions like `table.c.x == True` are involved, as ruff will transform it to `table.c.x is True`. While this is syntactically valid, it produces **a different SQL query** 
```python
import sqlalchemy as sa
from simcore_postgres_database.models.file_meta_data import *
from simcore_postgres_database.utils import *
wrong = sa.select(file_meta_data.c.file_id).where(file_meta_data.c.is_soft_link is True)  # WRONG
right = sa.select(file_meta_data.c.file_id).where(file_meta_data.c.is_soft_link.is_(True) ) # RIGHT
print( as_postgres_sql_query_str(wrong) )
print( as_postgres_sql_query_str(right) )
```
creates
```sql
SELECT …
```

♻️ Changing == by is_ in sqlalchemy queries

---

services/static-webserver/client/source/class/osparc/store/Services.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

🐛 [Frontend] Fix Service browser

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceFilter.js
tests/e2e-frontend/tests/serviceBrowser/leftFilters.spec.js
tests/e2e-frontend/tests/serviceBrowser/mainView.spec.js
tests/e2e-frontend/tests/studyBrowser/leftFilters.spec.js

This PR adds e2e-frontend tests for the Service Browser:

🎨 [e2e-frontend] Service browser

---

scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
scripts/maintenance/computational-clusters/autoscaled_monitor/constants.py

- lately the ssh key file path changed.

🔨Cluster monitoring script: update due to latest changes in osparc-config

---

api/specs/web-server/_groups.py
packages/models-library/src/models_library/api_schemas_webserver/groups.py
packages/models-library/src/models_library/utils/common_validators.py
packages/models-library/tests/test_api_schemas_webserver_groups.py
packages/service-library/tests/test_archiving_utils.py
packages/service-library/tests/test_async_utils.py
services/dynamic-sidecar/tests/unit/test_api_rest_containers.py
services/storage/tests/unit/test_utils.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/groups/_db.py
services/web/server/src/simcore_service_webserver/groups/_handlers.py
services/web/server/src/simcore_service_webserver/groups/_utils.py
services/web/server/src/simcore_service_webserver/groups/api.py
services/web/server/src/simcore_service_webserver/groups/exceptions.py
services/web/server/src/simcore_service_webserver/users/schemas.py
services/web/server/tests/unit/isolated/test_groups_models.py
services/web/server/tests/unit/with_dbs/01/test_groups.py

During a debugging session with @odeimaiz, we observed that the Swagger site was displaying an incorrect interface for the `/groups` endpoints. The web API lacked properly defined OpenAPI Specifications (OAS) since this plugin hadn’t yet been updated to use Pydantic models.
This PR addresses the problem by updating the OAS generator code and models in `api/webserver`, ensuring the [new OAS](https://editor.swagger.io/?url=https://raw.githubusercontent.com/ITISFoundation/osparc-simcore/646326768661bce87ca17c05a675a06dfc1e6e7a/services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml) correctly represent the interface and is better documented. Additionally, it now introduces input validation in the `handler` functions through these models, which wasn’t in place before. For now, …

♻️ Enhanced groups/organizations web-api specs and validation  🚨

---

services/static-webserver/client/source/class/osparc/data/Roles.js
services/static-webserver/client/source/class/osparc/desktop/organizations/MembersList.js
services/static-webserver/client/source/class/osparc/desktop/organizations/OrganizationDetails.js
services/static-webserver/client/source/class/osparc/desktop/organizations/OrganizationsList.js
services/static-webserver/client/source/class/osparc/desktop/organizations/ServicesList.js
services/static-webserver/client/source/class/osparc/desktop/organizations/SharedResourceListItem.js
services/static-webserver/client/source/class/osparc/desktop/organizations/TemplatesList.js
services/static-webserver/client/source/class/osparc/desktop/wallets/MemberListItem.js
services/static-webserver/client/source/class/osparc/desktop/wallets/WalletListItem.js
services/static-webserver/client/source/class/osparc/ui/list/CollaboratorListItem.js
services/static-webserver/client/source/class/osparc/ui/list/ListItem.js
services/static-webserver/client/source/class/osparc/ui/list/ListItemWithMenu.js
services/static-webserver/client/source/class/osparc/ui/list/OrganizationListItem.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

🎨 [Frontend] UX: Organization member's management

---

services/static-webserver/client/source/class/osparc/notification/NotificationUI.js

Some notifications can get deprecated if the resource they point to was deleted.
In this PR this scenario is handled by disabling the Notification so it is not actionable anymore.

🎨🐛 [Frontend] Notifications: disable unknown resources

---

services/static-webserver/client/source/class/osparc/study/PricingUnits.js

found by @mguidon 
There is a bug when the default pricing unit is the first in the list. This PR fixes it.

🐛 [Frontend] Highlight default Pricing Unit

---

services/storage/src/simcore_service_storage/s3.py

Added more logs to be able to better track what is happening during the setup.
Also fixed na issue where the yield would be swallowed in case of error.

🐛 Refactor storage setup functions to avoid errors

---

services/web/server/src/simcore_service_webserver/folders/_folders_api.py
services/web/server/src/simcore_service_webserver/folders/_folders_db.py
services/web/server/src/simcore_service_webserver/folders/_trash_api.py
services/web/server/src/simcore_service_webserver/workspaces/_groups_db.py
services/web/server/src/simcore_service_webserver/workspaces/_workspaces_db.py

This PR migrates the `folders` and `workspaces` repository layers to the new `asyncpg` engine. It also leverages the new `utils_repo` helpers to support building unit-of-work context managers.
- Preparation to create units-of-work for ITISFoundation/osparc-issues#468
- Part of https://github.com/ITISFoundation/osparc-simcore/issues/4529
```
make test-dev-unit
```
NOne

♻️ Migrates folders and workspaces repositories to asyncpg

---

tests/performance/Makefile
tests/performance/locust_files/platform_ping_test.py
tests/performance/locust_settings.py

This PR addresses the failure of performance tests to run in the CI environment after an e2e upgrade in Python.
- **Dependency Injection**: Adjusted `.env` generation as `make config` was producing an empty file. Now, dependencies are injected into `locust_settings.py` using `uv add --script ...`, allowing it to run as a standalone script.
- **CLI Argument Fix**: Corrected `cut` command arguments to ensure proper execution
- **Environment Variable Validation**: Added initial checks for additional required environment variables.
- portal e2e failures since `docker:latest` updated and installs new version of python
None

🔨 Fix: e2e Performance Tests in CI

---

services/autoscaling/tests/unit/test_core_settings.py

In PR https://github.com/ITISFoundation/osparc-simcore/pull/6701, the test `test_EC2_INSTANCES_ALLOWED_TYPES_empty_not_allowed` fails with the new Pydantic version, but it unexpectedly passes with the previous version. This PR modifies the test to highlight a bug in our `BaseCustomsSettings` logic when using Pydantic v1. 
The bug originates from a workaround initially applied by @YuryHrytsuk on the refactoring of docker-compose environments  (this is also related to this change https://github.com/ITISFoundation/osparc-ops-environments/issues/866), which involved using an empty dictionary `{}` as an environment variable value to simulate an "unset" state. This workaround impacts fields set with `auto-default-factory=True`, where empty dicts `{}` mark fields as `UNSET`.
In particular, this …

✅ Extends test_EC2_INSTANCES_ALLOWED_TYPES_empty_not_allowed

---

api/specs/web-server/_folders.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/folders/_folders_api.py
services/web/server/src/simcore_service_webserver/folders/_folders_db.py
services/web/server/src/simcore_service_webserver/folders/_folders_handlers.py
services/web/server/src/simcore_service_webserver/folders/_models.py
services/web/server/tests/unit/with_dbs/04/folders/test_folders__full_search.py

- 🐛 folder full search adding text query parameter (similar as in projects search)
- relates https://github.com/ITISFoundation/osparc-issues/issues/1725

🐛 folder full search adding text query parameter

---

services/static-webserver/client/source/class/osparc/dashboard/FolderButtonItem.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/store/Folders.js
services/static-webserver/client/source/class/osparc/store/Store.js

This PR extends the ``:search`` to ``/folders``
- closes https://github.com/ITISFoundation/osparc-issues/issues/1725
- related to https://github.com/ITISFoundation/osparc-issues/issues/716

✨ [Frontend] Enh: ``:search`` also ``/folders``

---

services/static-webserver/client/source/class/osparc/data/model/Folder.js
services/static-webserver/client/source/class/osparc/data/model/Study.js
services/static-webserver/client/source/class/osparc/store/Folders.js

The backend is already providing the ``trashedAt`` property, while the frontend [doesn't yet know](https://github.com/ITISFoundation/osparc-simcore/pull/6590/) how to handle it.
This PR brings some "Trash bin" logic to the frontend to make it compatible with the current frontend.

🎨🐛 Enh/fix: frontend knows about ``trashedAt``

---

services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/info/StudyLarge.js

The main plus button loads all the required information when the application loads. That's why if a mapped template becomes available after the start up, it wouldn't be available in the New Plans. This PR fixes this case.
New Plans after creating its template:
New Plans after renaming to the expected mapped name:
- closes https://github.com/ITISFoundation/osparc-issues/issues/1718

🐛 [Frontend] TIP: New plan after creating its template

---

services/web/server/src/simcore_service_webserver/folders/_folders_db.py
services/web/server/tests/unit/with_dbs/04/workspaces/test_workspaces__folders_and_projects_crud.py

- 🐛 Fix listing folders in workspace
- relates https://github.com/ITISFoundation/osparc-issues/issues/1725
- `test_listing_folders_and_projects_in_workspace__multiple_workspaces_created`

🐛 Fix listing folders in workspace

---

tests/e2e-playwright/tests/conftest.py

The workflow for starting projects changed a bit in [this PR](https://github.com/ITISFoundation/osparc-simcore/pull/6706). This PR updates the e2e tests to fit the new workflow.

🐛 [e2e-playwright] Fix tests

---

tests/e2e-playwright/tests/conftest.py

🐛 [e2e-playwright] Fix tests, 2nd attempt

---

scripts/demo-meta/meta_modeling_results.py
scripts/demo-meta/osparc_webapi.py
scripts/demo-meta/requirements.txt

Migrate scripts to Pydantic v2.

♻️ Migrate scripts (Pydantic v2)

---

services/director-v2/src/simcore_service_director_v2/modules/db/__init__.py
services/director-v2/src/simcore_service_director_v2/modules/db/_asyncpg.py

- 🎨 adding `asyncpg` to director-v2
- Example:
```python
from ...modules.db import get_asyncpg_engine
asyncpg_engine = get_asyncpg_engine(app)
repo = TagsRepo(asyncpg_engine)
project_tags = await repo.list_tag_ids_and_names_by_project_uuid(
project_uuid=project.uuid
)
```
- relates https://github.com/ITISFoundation/osparc-simcore/issues/4529

🎨 adding `asyncpg` to director-v2

---

packages/models-library/src/models_library/api_schemas_webserver/projects.py
packages/models-library/src/models_library/api_schemas_webserver/projects_nodes.py

Endpoints for creating a node and creating a new project did had some optional parameters that were not respected.
After the Pydantic v2 migration, these became mandatory, which was wrong. Aligned with what the OpenAPI spec (and the frontend) require.

🐛 Fixed webserver API endpoints

---

packages/models-library/src/models_library/rest_base.py
packages/models-library/src/models_library/rest_ordering.py
packages/models-library/tests/test_rest_ordering.py

Fixes models-library test_rest_ordering.
Will follow up in a separate PR with the changes in `api/specs/web-server`
- https://github.com/ITISFoundation/osparc-simcore/issues/4481

⬆️♻️ Fix/test models

---

packages/service-library/src/servicelib/fastapi/profiler_middleware.py

🎨 Ensure profiling middleware is compatible with fastapi

---

.github/CODEOWNERS
packages/models-library/src/models_library/boot_options.py
packages/models-library/src/models_library/projects_ui.py
packages/models-library/src/models_library/rest_base.py
packages/models-library/src/models_library/rest_pagination_utils.py
packages/models-library/src/models_library/socketio.py
packages/models-library/src/models_library/utils/common_validators.py
packages/models-library/tests/test_rest_ordering.py
packages/postgres-database/src/simcore_postgres_database/models/products.py
packages/service-library/src/servicelib/aiohttp/application_setup.py
packages/service-library/src/servicelib/rest_constants.py
packages/service-library/tests/aiohttp/test_requests_validation.py
services/director-v2/src/simcore_service_director_v2/models/comp_runs.py
services/web/server/src/simcore_service_webserver/resource_manager/registry.py
services/web/server/src/simcore_service_webserver/rest/healthcheck.py
services/web/server/src/simcore_service_webserver/security/_authz_access_model.py
services/web/server/src/simcore_service_webserver/security/_authz_access_roles.py
services/web/server/src/simcore_service_webserver/session/access_policies.py
services/web/server/src/simcore_service_webserver/statics/settings.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_projects_permalinks.py
services/web/server/src/simcore_service_webserver/utils.py

All `TypedDict` used in pydantic models for `python <3.12` should use the backport library `typing_extensions`
SEE https://docs.pydantic.dev/latest/api/standard_library_types/#typeddict
NOTE that we should not always import from the backport library `typing_extensions` but only those `TypedDict` used inside models.
----
- Fixes some remaining issue with migration of `rest_ordering.py` in https://github.com/ITISFoundation/osparc-simcore/pull/6763/files
- Fixes wrong exception raised in parse_json_pre_validator pydantic validator
- Fixes tests
- https://github.com/ITISFoundation/osparc-simcore/issues/4481

Uses typing_extensions.TypedDict in all instances used in pydantic models AND fixes with migration of rest_ordering

---

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/error_handlers.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/errors.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/settings.py
services/dynamic-sidecar/tests/unit/test_api_rest_containers.py
services/dynamic-sidecar/tests/unit/test_core_errors.py

Refactored errors in dynamic-sidecar thy all inherit from `OsparcErrorMixin`.
Makes all pylint checks pass.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6757

All errors in dynamic-sidecar inherit from `OsparcErrorMixin`

---

packages/common-library/src/common_library/basic_types.py
packages/models-library/src/models_library/basic_types.py
packages/settings-library/src/settings_library/application.py
packages/settings-library/src/settings_library/base.py
packages/settings-library/src/settings_library/basic_types.py
packages/settings-library/tests/test_utils_logging.py
services/web/server/tests/unit/with_dbs/03/resource_usage/test_usage_services__export.py
services/web/server/tests/unit/with_dbs/03/resource_usage/test_usage_services__list.py

- fixes [unit] webserver 03
- fixes settings library tests and mypy
- Part of https://github.com/ITISFoundation/osparc-simcore/issues/4481

Fixes [unit] webserver 03 and [unit] settings-library (both mypy and tests)

---

services/opentelemetry-collector-config.yaml
services/static-webserver/client/source/class/osparc/study/StudyOptions.js
tests/e2e-playwright/tests/conftest.py

The Open button in the Study Options view now depends on the title and selected wallet: if both are not set it will be disabled.
Sometimes the e2e would fail because playwright was opening the Study before the title was set.

🐛 [e2e] Study Options: Open button

---

packages/settings-library/src/settings_library/redis.py

Fix the Redis DSN scheme in case the `REDIS_SECURE` is set to `true`.

🐛 Fix Redis DSN scheme generation

---

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_event_filter.py
services/dynamic-sidecar/tests/unit/test_modules_outputs_event_filter.py

Redesign tests inside `services/dynamic-sidecar/tests/unit/test_modules_outputs_event_filter.py` to avoid flakiness.

🐛 Fixed flaky tests in  services/dynamic-sidecar/tests/unit/test_modules_outputs_event_filter.py

---

services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py

Use `list` instead of `set` so the expected JSON representation has a correct order of items.

🐛 Use list instead of set when building the expected result

---

services/static-webserver/client/source/class/osparc/dashboard/WorkspacesAndFoldersTree.js
services/static-webserver/client/source/class/osparc/study/StudyOptions.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

Merry xmas @wvangeit!
- closes https://github.com/ITISFoundation/osparc-simcore/issues/6788

🎨 [Frontend] Sort folders alphabetically

---

services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py
services/director/src/simcore_service_director/producer.py

After the upgrade of the director-v0 this was forgotten.
POSTGRES_ENDPOINT in legacy services only contain the HOST:PORT
This will fix the e2e-portal tests

🐛Director-V0: Legacy services expect Postgres Endpoint as host:port

---

services/director/src/simcore_service_director/registry_proxy.py
services/director/tests/unit/test_registry_proxy.py

This PR re-creates the background task that updates the  cache of the services

✨Director-v0: added background task that pre-builds the registry cache

---

packages/models-library/src/models_library/projects_nodes_ui.py
packages/models-library/src/models_library/projects_ui.py
packages/models-library/tests/test_projects_nodes_ui.py

Fix a serialization issue with `Color` fields in Pydantic v2.
In Web Server logs:
```
File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_webserver/projects/_crud_handlers.py", line 223, in list_projects
text=page.model_dump_json(**RESPONSE_MODEL_POLICY),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/scu/.venv/lib/python3.11/site-packages/pydantic/main.py", line 441, in model_dump_json
return self.__pydantic_serializer__.to_json(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic_extra_types.color.Color'>
```

🐛 Fix Color serialization in Pydantic v2

---

packages/models-library/src/models_library/projects_nodes_ui.py
packages/models-library/src/models_library/projects_ui.py
packages/models-library/tests/test_projects_nodes_ui.py
packages/models-library/tests/test_projects_ui.py

Colors are now **always** serialized in HEX format:
Example:
```
"#b7e28d" => "#b7e28d"
"Cyan" =>  "#0ff"
```
- Relates to: #6162

🎨 Serialize Colors as HEX

---

services/dynamic-scheduler/requirements/_base.txt
services/dynamic-scheduler/requirements/_test.txt
services/dynamic-scheduler/requirements/_tools.txt

- #packages before ~ 0
- #packages after ~ 0
*Legend*: 
- #reqs files parsed: 101
|#|name|versions-base|versions-test|versions-tool|
|-|----|-------------|-------------|-------------|
|   1 | aio-pika                  | 9.1.2, 9.4.1, 9.4.2, 9.4.3, 9.5.0 | 9.4.1, 9.4.3              |                           |
|   2 | aioboto3                  | 13.1.0, 13.1.1, 13.2.0    | 13.1.1, 13.2.0            |                           |
|   3 | aiobotocore               | 2.13.0, 2.13.1, 2.15.2    | 2.13.1, 2.15.2            |                           |
|   4 | aiocache                  | 0.11.1, …

⬆️ Maintenance: bump all dependencies for `dynamic-scheduler` service

---

packages/pytest-simcore/src/pytest_simcore/rabbit_service.py
packages/service-library/src/servicelib/rabbitmq/__init__.py
packages/service-library/src/servicelib/rabbitmq/_client.py
packages/service-library/src/servicelib/rabbitmq/_models.py
packages/service-library/src/servicelib/rabbitmq/_utils.py
packages/service-library/tests/rabbitmq/test_rabbitmq.py
services/api-server/src/simcore_service_api_server/services/log_streaming.py
services/autoscaling/tests/unit/test_modules_buffer_machine_core.py
services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py
services/efs-guardian/src/simcore_service_efs_guardian/services/process_messages_setup.py
services/payments/src/simcore_service_payments/services/auto_recharge_listener.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/services/process_message_running_service_setup.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_consumers_common.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_nonexclusive_queue_consumers.py

Before:
- The RabbitMQ consumer was setup with a name unique to the application, but this prevents from having multiple ones in the same application
After:
- the ConsumerTag is returned when subscribing to a Exchange/Queue
- unsubscribing a consumer from a Queue requires the ConsumerTag,
- Fixes unsubscribing when the connection to the RabbitMQ service is already shutdown,
- Upgraded derived services
- After discussion with @matusdrobuliak66 adds option for non-exclusive queues to define a specific queue name
- required by https://github.com/ITISFoundation/osparc-simcore/pull/6736

🎨 Allow to have multiple consumers for the same queue in 1 application and allow to optionally define queue name

---

services/storage/src/simcore_service_storage/handlers_simcore_s3.py

`aiohttp` [deprecated **returning** `HttpException`](https://docs.aiohttp.org/en/stable/web_quickstart.html#exceptions). Moreover, raising non-error creates false negatives as in the example below where `201` (Created) was shown as an error in our tracing
Jaeger captures these exceptions as errors in storage:
- Analogous to https://github.com/ITISFoundation/osparc-simcore/pull/6563
- Maintenance
None

♻️ `aiohttp` deprecation: Using `web.json_response` to return `2XX` responses instead of raising `HttpException`

---

services/agent/requirements/_base.txt
services/agent/requirements/_test.txt
services/agent/requirements/_tools.txt
services/agent/src/simcore_service_agent/core/settings.py

- #packages before ~ 68
- #packages after ~ 69
|   1 | aio-pika                  | 9.4.3           | 9.5.0      | *minor*    | 1 | agent⬆️ |
|   2 | aiodocker                 | 0.23.0          | 0.24.0     | *minor*    | 1 | agent⬆️ |
|   3 | aiohttp                   | 3.10.10         | 3.11.7     | *minor*    | 2 | agent⬆️🧪 |
|   4 | aws-sam-translator        | 1.91.0          | 1.94.0     | *minor*    | 1 | agent🧪 |
|   5 | blinker                   | 1.8.2           | 1.9.0      | *minor*    | 1 | agent🧪 |
|   6 | cfn-lint                  | 1.16.1          | 1.20.0     | *minor*    | 1 | agent🧪 |
|   7 | coverage                  | 7.6.3           | 7.6.8      |            | 1 | agent🧪 |
|   8 | …

⬆️ Maintenance: bump all dependencies for `agent` service

---

services/web/server/src/simcore_service_webserver/application_settings.py
services/web/server/tests/unit/isolated/test_application_settings.py

- Adds `WEBSERVER_TRASH` flag to indicate whether the trash functionality is available or not. 
- Since currently it is under development, it is aliased to `WEBSERVER_DEV_FEATURES_ENABLED` 
- The front-end can get this information via `GET /static-frontend-data.json`
- Needed before merging https://github.com/ITISFoundation/osparc-simcore/pull/6590
- Part of ITISFoundation/osparc-issues#468
```
pytest -vv tests/unit/isolated -k test_settings_to_client_statics_for_webserver_trash.py
```
None

 🎨  webserver's trash flag

---

services/invitations/openapi.json
services/invitations/requirements/_base.txt
services/invitations/requirements/_test.txt
services/invitations/requirements/_tools.txt

- #packages before ~ 94
- #packages after ~ 97
|   1 | aio-pika                  | 9.4.1           | 9.5.0      | *minor*    | 1 | invitations⬆️ |
|   2 | aiocache                  | 0.12.2          | 0.12.3     |            | 1 | invitations⬆️ |
|   3 | aiodocker                 | 0.21.0          | 0.24.0     | *minor*    | 1 | invitations⬆️ |
|   4 | aiofiles                  | 23.2.1          | 24.1.0     | **MAJOR**  | 1 | invitations⬆️ |
|   5 | aiohttp                   | 3.9.3           | 3.11.7     | *minor*    | 1 | invitations⬆️ |
|   6 | aiormq                    | 6.8.0           | 6.8.1      |            | 1 | invitations⬆️ |
|   7 | anyio                     | 4.3.0           | …

⬆️ Maintenance: upgrades `invitations` service requirements

---

services/api-server/src/simcore_service_api_server/exceptions/handlers/_log_streaming_errors.py
services/api-server/src/simcore_service_api_server/exceptions/log_streaming_errors.py
services/api-server/src/simcore_service_api_server/services/log_streaming.py
services/api-server/tests/unit/test_services_rabbitmq.py

- api-server's LogStreamerRegistionConflictError is a client error and must not be logged as a server error.
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/6714
None

🎨  api-server's LogStreamerRegistionConflictError not logged as a server error anymore

---

services/payments/gateway/openapi.json
services/payments/openapi.json
services/payments/requirements/_base.txt
services/payments/requirements/_test.txt
services/payments/requirements/_tools.txt
services/payments/src/simcore_service_payments/core/settings.py
services/payments/src/simcore_service_payments/models/schemas/acknowledgements.py
services/payments/tests/unit/test_services_payments__get_invoice.py
services/payments/tests/unit/test_services_payments_gateway.py

- #packages before ~ 100
- #packages after ~ 101
|   1 | aio-pika                  | 9.4.2           | 9.5.1      | *minor*    | 1 | payments⬆️ |
|   2 | aiocache                  | 0.12.2          | 0.12.3     |            | 1 | payments⬆️ |
|   3 | aiodocker                 | 0.22.2          | 0.24.0     | *minor*    | 1 | payments⬆️ |
|   4 | aiohappyeyeballs          | 2.3.4           | 2.4.3      | *minor*    | 2 | payments⬆️🧪 |
|   5 | aiohttp                   | 3.10.0          | 3.11.8     | *minor*    | 2 | payments⬆️🧪 |
|   6 | aiormq                    | 6.8.0           | 6.8.1      |            | 1 | payments⬆️ |
|   7 | alembic                   | 1.13.2          | 1.14.0     | *minor* …

⬆️ Maintenance: upgrades `payments` service requirements

---

services/web/server/src/simcore_service_webserver/application_settings.py
services/web/server/src/simcore_service_webserver/folders/_trash_handlers.py
services/web/server/src/simcore_service_webserver/projects/_trash_handlers.py
services/web/server/src/simcore_service_webserver/workspaces/_trash_handlers.py
services/web/server/tests/unit/isolated/test_application_settings.py

Enables trash entrypoitns in web-api
- Enables ITISFoundation/osparc-issues#468
- Unblocks https://github.com/ITISFoundation/osparc-simcore/pull/6590
None

🎨 Enables trash in web-api

---

services/static-webserver/client/source/class/osparc/CookiePolicy.js
services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
services/static-webserver/client/source/class/osparc/product/AboutProduct.js
services/static-webserver/client/source/class/osparc/product/Utils.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4l/Welcome.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4lacad/Welcome.js
services/static-webserver/client/source/class/osparc/product/quickStart/s4llite/Slides.js
services/static-webserver/client/source/class/osparc/store/Support.js

Bonus:
- closes https://github.com/ITISFoundation/osparc-simcore/issues/6879

🎨 [Frontend] Show support email in About window

---

.codecov.yml
.github/workflows/ci-testing-deploy.yml
packages/dask-task-models-library/requirements/_base.txt
packages/dask-task-models-library/requirements/_test.txt
packages/dask-task-models-library/requirements/_tools.txt
packages/pytest-simcore/src/pytest_simcore/dask_scheduler.py
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
services/autoscaling/requirements/_tools.txt
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/requirements/_tools.txt
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_dask-distributed.txt
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/requirements/_tools.txt
services/director-v2/requirements/_base.txt
services/director-v2/requirements/_test.txt
services/director-v2/requirements/_tools.txt
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/tests/unit/test_modules_dask_client.py

- Upgrade dask-models-library (full-upgrade)
- Upgrade dask-sidecar (full upgrade)
- Upgrade director-v2 (sync upgrade - dask)
- Upgrade autoscaling (sync upgrade - dask)
- Upgrade clusters-keeper (sync upgrade - dask)
- fixed codecov upload of reports, also for integration tests
- new dask version: 2024.12.0
- since 2024.7.0: Pub/Sub mechanism is deprecated [https://docs.dask.org/en/stable/changelog.html#publish-subscribe-apis-deprecated](https://docs.dask.org/en/stable/changelog.html#publish-subscribe-apis-deprecated) -> this is annoying and will need replacements
- [Dask changelog](https://docs.dask.org/en/stable/changelog.html#changelog)
- whenever the dask library changes it is important that all dask-related services are in sync,
- client/scheduler/workers - python versions, dask …

⬆️Upgrade dask related libraries and services (⚠️🚨)

---

.github/workflows/ci-testing-deploy.yml

🐛 ensure api spec ci jobs only run during prs

---

services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.in
services/autoscaling/requirements/_test.txt
services/autoscaling/requirements/_tools.txt
services/autoscaling/tests/unit/conftest.py
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/clusters-keeper/requirements/_tools.txt
services/clusters-keeper/tests/unit/conftest.py

- #packages before ~ 99
- #packages after ~ 102
|   1 | aio-pika                  | 9.4.1           | 9.5.3      | *minor*    | 2 | autoscaling⬆️</br>clusters-keeper⬆️ |
|   2 | aioboto3                  | 13.1.0          | 13.2.0     | *minor*    | 2 | autoscaling⬆️</br>clusters-keeper⬆️ |
|   3 | aiobotocore               | 2.13.1          | 2.15.2     | *minor*    | 2 | autoscaling⬆️</br>clusters-keeper⬆️ |
|   4 | aiocache                  | 0.12.2          | 0.12.3     |            | 2 | autoscaling⬆️</br>clusters-keeper⬆️ |
|   5 | aiodocker                 | 0.21.0          | 0.24.0     | *minor*    | 3 | autoscaling⬆️</br>clusters-keeper⬆️🧪 |
|   6 | aiofiles                  | 23.2.1 …

⬆️Full upgrade autoscaling/clusters-keeper

---

.github/workflows/ci-testing-deploy.yml
Makefile
packages/service-integration/Dockerfile
requirements/tools/Dockerfile
services/agent/Dockerfile
services/api-server/Dockerfile
services/autoscaling/Dockerfile
services/catalog/Dockerfile
services/clusters-keeper/Dockerfile
services/dask-sidecar/Dockerfile
services/datcore-adapter/Dockerfile
services/director-v2/Dockerfile
services/director/Dockerfile
services/dynamic-scheduler/Dockerfile
services/dynamic-sidecar/Dockerfile
services/efs-guardian/Dockerfile
services/invitations/Dockerfile
services/migration/Dockerfile
services/payments/Dockerfile
services/resource-usage-tracker/Dockerfile
services/storage/Dockerfile
services/web/Dockerfile

Building the frontend docker image seems to become more and more resource intensive on the github runners, especially when USA wakes up.
This PR:
- separates in 2 separate jobs building of the backend and the frontend,
- both upload now to an CI artifact named `docker-buildx-images-${{ runner.os }}-${{ github.sha }}-backend` and `docker-buildx-images-${{ runner.os }}-${{ github.sha }}-frontend` ,
- integration tests that _only_ need the backend depend only on the backend images being built
- system tests need both the backend and frontend now have that additional dependency
- improved `load images` step by parallelizing (gain of ~50%, ~1m20 to 30-40s),
- some small changes in dockerfile caching that might bring some help
- removed step to delete data that takes 1minute for deletion

⚗️CI: Separate image building of frontend

---

services/web/server/tests/unit/isolated/test_tracing.py

- 🐛 Fix failing opentelemetry unit test after merging this https://github.com/ITISFoundation/osparc-simcore/pull/6921 env var changes (webserver unit test didn't run)

🐛 Fix failing opentelemetry unit test

---

services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py

- https://github.com/ITISFoundation/osparc-simcore/pull/6898 brought an issue that this PR hopefully fixes
- the Docker Node tagging operation was not properly returning the updated _Node_ object, therefore the node would be activated and instantly de-activated, which prevents any service from starting

🐛Autoscaling: Fixes return value of Docker node activation

---

tests/e2e-playwright/tests/conftest.py

- 🎨 E2E TIP test: use default timeout 30 seconds

🎨 E2E TIP test: use default timeout 30 seconds

---

.codecov.yml
.github/workflows/ci-testing-deploy.yml
packages/pytest-simcore/src/pytest_simcore/helpers/aws_ec2.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/dask.py
services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_modules_buffer_machine_core.py
services/autoscaling/tests/unit/test_utils_auto_scaling_core.py

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6929
In case both warm and hot buffers are used for specific instance type, the warm buffers were not prioritized over launching a fresh instance. This would lead to inneficiencies and also additional costs as the warm buffer would only be used if more users than hot buffers were starting a service at the same time.

🐛Autoscaling: Warm buffers do not replace hot buffers

---

services/web/server/src/simcore_service_webserver/projects/projects_api.py

Whenever node's `inputs` are changed, the real state is calculated and returned back as message over WebSocket.
- Fixes: https://github.com/ITISFoundation/osparc-issues/issues/1811

🐛 Update state when patching node

---

services/static-webserver/client/source/class/osparc/data/model/IframeHandler.js
services/static-webserver/client/source/class/osparc/data/model/Service.js
services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
services/static-webserver/client/source/class/osparc/filter/NodeTypeFilter.js
services/static-webserver/client/source/class/osparc/filter/group/ServiceFilterGroup.js
services/static-webserver/client/source/class/osparc/service/ServiceList.js
services/static-webserver/client/source/class/osparc/service/ServiceListItem.js
services/static-webserver/client/source/class/osparc/workbench/ServiceCatalog.js
services/static-webserver/client/source/class/osparc/workbench/WorkbenchUI.js

🐛🎨 [Frontend] Fix: Filter and focus Service Catalog items

---

services/catalog/src/simcore_service_catalog/api/rest/_services.py

Solve serialization warnings like the following, mainly caused by a misuse of `model_construct` method:
```
Expected `Author` but got `dict` with value `{'name': 'nodetails', 'em...odetails@nodetails.com'}` - serialized value may not be as expected
Expected `Author` but got `dict` with value `{'name': 'nodetails', 'em...odetails@nodetails.com'}` - serialized value may not be as expected
Expected `Author` but got `dict` with value `{'name': 'nodetails', 'em...odetails@nodetails.com'}` - serialized value may not be as expected
Expected `Author` but got `dict` with value `{'name': 'nodetails', 'em...odetails@nodetails.com'}` - serialized value may not be as expected
Expected `Author` but got `dict` with value `{'name': 'nodetails', 'em...odetails@nodetails.com'}` - serialized value may not …
```

Fix Pydantic serialization warnings

---

tests/performance/locust_settings.py

- Remove uv header to fix webresponsitivity tests

🎨 fix locust_settings

---

tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py

In the latest jupyter-smash there are 2 "New Launcher" buttons, this PR fixes the e2e by clicking the first match.

🐛 [e2e] click the first ``New Launcher`` button

---

services/autoscaling/docker/boot.sh
services/clusters-keeper/docker/boot.sh
services/dynamic-scheduler/docker/boot.sh
services/efs-guardian/docker/boot.sh
services/invitations/docker/boot.sh
services/payments/docker/boot.sh
services/resource-usage-tracker/docker/boot.sh

- 🐛 fix uvicorn logs that were always on INFO (they did not respect the LOGLEVEL of specific service)

🐛 fix uvicorn logs that were always on INFO

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
tests/e2e-playwright/requirements/_test.txt
tests/e2e-playwright/requirements/_tools.txt
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py

- upgraded playwright to latest and greates (1.49) that is compatible with newer headless mode of chromium
- fixed issue where the check if a service is ready was done unauthenticated, therefore wrongly detecting a service as being ready (reproducible 100% times by running ```make test-s4l-anywhere```)
:warning: Do not use httpx in playwright tests. there is an api_context_manager that is authenticated automatically.

⬆️ Upgrade playwright to latest version and fix checking of service readyness

---

packages/service-library/src/servicelib/archiving_utils/_interface_7zip.py
packages/service-library/tests/archiving_utils/test_archiving__interface_7zip.py

Paths were not at all escaped. Added escaping via `shlex.quote`. This should cover all possible cases with all the paths involving 7zip: achieve names, destination folder, source folder
Just the `dynamic-sidecar` image is required for this hot to work. Requires `director-v2` reboot.

🚑️ Added escaping for 7zip paths

---

services/static-webserver/client/source/class/osparc/desktop/organizations/MembersList.js
services/static-webserver/client/source/class/osparc/store/Users.js

When a group is not ``read``able  by a user, but a resource is shared with them and this group is part of the sharees, the listing of members will fail showing an empty list.
Before:
After:

🐛 [Frontend] Bugfix: handle better ``groups/${gid}/users`` error

---

tests/performance/Makefile
tests/performance/docker/Dockerfile
tests/performance/requirements/_base.txt
tests/performance/requirements/requirements-dev.txt

- Add a docker image in which to run performance tests. This new image is not based on alpine, so it is easier to handle python version dependencies. 
- Related MR on the CI side: https://git.speag.com/oSparc/e2e-portal-testing/-/merge_requests/48

✨ Add docker test image for performance tests

---

.github/dependabot.yml
.github/workflows/ci-testing-deploy.yml
packages/postgres-database/docker/Dockerfile
packages/postgres-database/scripts/erd/Dockerfile
packages/service-integration/Dockerfile
requirements/tools/Dockerfile
scripts/erd/Dockerfile
scripts/maintenance/migrate_project/Dockerfile
scripts/openapi/oas_resolver/Dockerfile
scripts/pydeps-docker/Dockerfile
services/agent/Dockerfile
services/api-server/Dockerfile
services/autoscaling/Dockerfile
services/catalog/Dockerfile
services/clusters-keeper/Dockerfile
services/dask-sidecar/Dockerfile
services/datcore-adapter/Dockerfile
services/director-v2/Dockerfile
services/director/Dockerfile
services/dynamic-scheduler/Dockerfile
services/dynamic-sidecar/Dockerfile
services/efs-guardian/Dockerfile
services/invitations/Dockerfile
services/migration/Dockerfile
services/payments/Dockerfile
services/resource-usage-tracker/Dockerfile
services/storage/Dockerfile
services/web/Dockerfile
tests/performance/docker/Dockerfile

⬆️ UV upgrade to 0.5

---

packages/postgres-database/src/simcore_postgres_database/migration/versions/ecd4eadaa781_extract_workbench_column.py

Fix an issue when migrating a DB with already existing `project_nodes` in it.
- relates to: #7010

🐛 Set `key`, `version` and `label` columns as temporarily nullable

---

ci/github/helpers/install_aws_cli_v2.bash
ci/github/integration-testing/simcore-sdk.bash
packages/aws-library/src/aws_library/ec2/_client.py
packages/pytest-simcore/src/pytest_simcore/helpers/aws_ec2.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py

After https://github.com/ITISFoundation/osparc-simcore/issues/6929 changes, a missing hot buffer would be replaced by a warm buffer if possible.
A bug in the implementation of this feature had for consequence that all the available warm buffers would be started to replace 1 missing hot buffer which leads to:
- additional costs as too many machines are running
- longer waiting times as all the warm buffers were used to replace 1 hot buffer and it takes time to re-create the missing warm buffers
driving test: `test_warm_buffers_only_replace_hot_buffer_if_service_is_started_issue7071`
@matusdrobuliak66 @YuryHrytsuk This should be hotfixed 
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7071

🐛Autoscaling: Fix issue where all warm buffers would be used to replace hot buffers (🚨)

---

packages/simcore-sdk/src/simcore_sdk/node_ports_common/aws_s3_cli_utils.py

While per se this only generates tracebacks which have no impact on the functionality. It is creates noise when trying to check errors.
This fixes the below issue. ByteSize does not know what `Bytes` are. It only knows about `b` and omitting the word bytes if they are just bytes.
```python
2025-01-27 09:31:32 ERROR Unhandled exception:
File "/home/runner/work/osparc-simcore/osparc-simcore/.venv/lib/python3.11/site-packages/servicelib/logging_utils.py", line 383, in log_catch
yield
File "/home/runner/work/osparc-simcore/osparc-simcore/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/aws_s3_cli_utils.py", line 38, in __call__
_bytes = TypeAdapter(ByteSize).validate_python(_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

🐛 remove noisy errors form logs

---

.github/mergify.yml

I did not realise how the `Queue` worked. Now it will do all the heavy lifting, leaving the `Workflow Automation` to deal with only flaky tests.

🎨 Mergify queue takes over keeping in sync with master

---

services/docker-compose-dev-vendors.yml
services/docker-compose.local.yml
services/docker-compose.yml

* Update traefik router hardcoded priorities according to the rules below
- 1 --> 3
- 2 --> 6
-  3 --> 9
* Remove unnecessary priority from `manual` service
This PR introduces some space in-between the routers which we can use to flexibly add new routers. It shouldn't break existing priority hierarchy since numbers <10 are still below any other non-hardcoded priorities.
Remarks for future:
* Whenever introducing some priorities to traefik routers (or other similar cases) one better to make them spacious to retain flexibility. This case is a good example why "spacious" approach makes sense
* unblocks https://github.com/ITISFoundation/osparc-ops-environments/issues/218 
* https://github.com/ITISFoundation/osparc-ops-environments/pull/953
* …

 ♻️ Update traefik router hardcoded priorities

---

tests/e2e-playwright/tests/conftest.py
tests/e2e/utils/auto.js

Fixes e2e test workflows:
- sim4life start
- sim4life-lite start

🐛 [e2e] Fixes after new plus button

---

.github/mergify.yml

In our CI pipeline there are tests that fail but will still make the `unit-tests`, `integration-tests` and `system-tests` be green. This did not allow Mergify's Workflow Automation to restart the CI.
Added all the edge cases that could make the restart not occur.
Instead of manually enqueuing the PRs, Mergify will now add them automatically once conditions are met.

🔨 Allow Mergify to detect more failing cases for CI restarts & Automatically add PRs to queue

---

services/static-webserver/client/source/class/osparc/desktop/credits/CheckoutsTable.js
services/static-webserver/client/source/class/osparc/desktop/credits/CheckoutsTableModel.js
services/static-webserver/client/source/class/osparc/desktop/credits/PurchasesTable.js
services/static-webserver/client/source/class/osparc/desktop/credits/PurchasesTableModel.js
services/static-webserver/client/source/class/osparc/store/LicensedItems.js
services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelDetails.js
services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelListItem.js
services/static-webserver/client/source/class/osparc/vipMarket/Market.js
services/static-webserver/client/source/class/osparc/vipMarket/VipMarket.js

- follows https://github.com/ITISFoundation/osparc-simcore/pull/7144
- follows https://github.com/ITISFoundation/osparc-simcore/pull/7139
- related to https://github.com/ITISFoundation/osparc-issues/issues/1732

🎨 [Frontend] Licensed items: Adapt to new model and backend's catalog

---

.github/workflows/ci-testing-pull-request.yml
packages/service-library/src/servicelib/fastapi/tracing.py
packages/service-library/tests/fastapi/test_tracing.py
services/agent/src/simcore_service_agent/core/application.py
services/api-server/src/simcore_service_api_server/core/application.py
services/autoscaling/src/simcore_service_autoscaling/core/application.py
services/catalog/src/simcore_service_catalog/core/application.py
services/clusters-keeper/src/simcore_service_clusters_keeper/core/application.py
services/datcore-adapter/src/simcore_service_datcore_adapter/core/application.py
services/director-v2/src/simcore_service_director_v2/core/application.py
services/director/src/simcore_service_director/core/application.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/core/application.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py
services/efs-guardian/src/simcore_service_efs_guardian/core/application.py
services/invitations/src/simcore_service_invitations/core/application.py
services/payments/src/simcore_service_payments/core/application.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/core/application.py

Locally I did not manage to run the tracing setup, since it was disabled and I did not catch the issue. The `tracing` module only requires an initialize not a lifespan.
I have now correctly renamed it, to avoid future doubts.
- fixes issue introduced by https://github.com/ITISFoundation/osparc-simcore/pull/7149

🐛 Removed tracing lifespan which should be an initialize

---

packages/models-library/src/models_library/api_schemas_webserver/licensed_items.py
packages/models-library/src/models_library/licenses.py
packages/models-library/tests/test_licenses.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml

Fixes validation error in master deploy
```
File "/home/scu/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
return cls.__pydantic_validator__.validate_python(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for LicensedItemRestGet
licensed_resource_data.source.doi
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.10/v/string_type
```
- master deploy error reported by @odeimaiz 
```
cd packages/models-library
pytest -vv tests/test_licenses
```

🐛 fixes failure due to nullable doi in licensed-items web-api response

---

.github/workflows/ci-testing-pull-request.yml
packages/models-library/src/models_library/api_schemas_catalog/services.py
packages/models-library/src/models_library/api_schemas_webserver/catalog.py
packages/models-library/src/models_library/api_schemas_webserver/licensed_items.py
packages/models-library/src/models_library/services_access.py
packages/models-library/src/models_library/services_base.py
packages/models-library/src/models_library/services_metadata_editable.py
packages/models-library/tests/test_licenses.py
services/catalog/openapi.json
services/catalog/src/simcore_service_catalog/api/rest/_services.py
services/catalog/src/simcore_service_catalog/models/services_db.py
services/catalog/tests/unit/with_dbs/test_api_rest_services__list.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_api_route_computations.py
services/web/server/src/simcore_service_webserver/catalog/_api.py
services/web/server/src/simcore_service_webserver/catalog/client.py
services/web/server/src/simcore_service_webserver/exception_handling/_factory.py
services/web/server/tests/unit/with_dbs/01/test_catalog_handlers__pricing_plan.py
services/web/server/tests/unit/with_dbs/01/test_catalog_handlers__services.py

This PR refactors the `Service` resource (models and APIs) in the `catalog`, accessed via REST from the `api-server` and RPC from the `webserver`.
- 🗑️ Retired `update_service`
- the `catalog`'s REST `update_service` entry point (`PATCH /service/{*}/{*}`), as an alternative is now available in the `rpc` interface.
- Dropped `ServiceUpdate` in favor of `ServiceUpdateV2`.
- Retired `catalog`'s client in the `webserver` that calls to deprecated catalog entries.
- ♻️ Refactored schema example retrieval by using `ModelClass.model_json_schema()["examples"]` instead of `ModelClass.model_config["json_schema_extra"]["examples"]`
- 🐛 Fixed error messages by adding the missing `error_code` in the context.
- 🐛 Fix. `api-specs` job failed because `github.event.after` resolves as `null`
- part of …

♻️ Refactors catalog's `update_service` operation

---

services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/services/modules/db/service_runs_db.py

- 🐛 Fix showing tags in usage overview - tags should be shown based on `root_parent_project_id` (all projects/nodes created from root project ID should show the same tags)

🐛 Fix showing tags in usage overview

---

packages/service-library/src/servicelib/aiohttp/long_running_tasks/client.py
packages/service-library/src/servicelib/fastapi/long_running_tasks/_routes.py
packages/service-library/src/servicelib/fastapi/long_running_tasks/client.py
packages/service-library/src/servicelib/long_running_tasks/_constants.py
packages/service-library/src/servicelib/long_running_tasks/_models.py
packages/service-library/src/servicelib/redis/_project_lock.py
packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks_client.py
services/storage/src/simcore_service_storage/modules/s3.py
services/web/server/tests/unit/with_dbs/04/garbage_collector/test_resource_manager.py

- fixes issue where a study could not be duplicated following refactoring https://github.com/ITISFoundation/osparc-simcore/pull/7088
- fixes issue where the project lock release would not be notified to the frontend in case of error while copying
- ensure error in notification callback does not raise an error
- de-duplicated a few things

🐛Storage: fix copying of file and ensure project lock release is always notified safely

---

api/specs/web-server/_storage.py
services/storage/src/simcore_service_storage/modules/datcore_adapter/datcore_adapter.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml

After https://github.com/ITISFoundation/osparc-simcore/pull/7088 the access to Datcore was broken. This PR fixes it.

🐛Storage: fix access to DatCore

---

services/docker-compose.yml

There is no to give internet access to services on this network.
- closes https://github.com/ITISFoundation/osparc-simcore/issues/7219

♻️ Making `docker-api-network` internal

---

services/static-webserver/client/source/class/osparc/NewRelease.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceFilter.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/desktop/MainPage.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
services/static-webserver/client/source/class/osparc/desktop/credits/BuyCreditsInput.js
services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
services/static-webserver/client/source/class/osparc/navigation/StudyTitleWOptions.js
services/static-webserver/client/source/class/osparc/navigation/UserMenu.js
services/static-webserver/client/source/class/osparc/product/Utils.js
services/static-webserver/client/source/class/osparc/store/LicensedItems.js
services/static-webserver/client/source/class/osparc/store/Support.js
services/static-webserver/client/source/class/osparc/study/PricingUnitLicense.js
services/static-webserver/client/source/class/osparc/utils/Utils.js
services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelDetails.js

In the coming release, when creating a study with only one dynamic service in it, it will start in ``standalone`` mode. Since the real s4l<->osparc integration will not be released yet, we need to let the users escape that ``standalone`` mode.
This PR adds a "Restore" button to the study menu.
Bonus:
- Added Release Notes to the support menu.
- Buy Credits UX: wider fields, react to spinner's manual text changes and increase nCredits limit to 100000.
- Do not start the NewUITracker. This is already handled by the tag attached to the index.html request.
Restore button:
Bonus:
- related to https://github.com/ITISFoundation/osparc-issues/issues/1822

🎨 [Frontend] Restore standalone view

---

services/docker-compose.local.yml
services/static-webserver/client/source/class/osparc/store/LicensedItems.js
services/static-webserver/client/source/class/osparc/study/PricingUnitLicense.js
services/static-webserver/client/source/class/osparc/utils/Utils.js
services/static-webserver/client/source/class/osparc/vipMarket/AnatomicalModelDetails.js
services/static-webserver/client/source/class/osparc/vipMarket/Market.js

- List of model in the bundle
- Update label composition: `${name}, ${functionality}` -> `${name} ${version}, ${functionality}`
- Make the whole thing clickable and show pointer cursor
- Add white spaces every 3 digits in amount of cost credits
- Keep model's details size when switching models within bundle
- Select "My Models" by default
- Fix dynmic-schdlr in devel mode (WSL)

🎨 [Frontend] ViP Market: last minors

---

packages/models-library/src/models_library/services_base.py
packages/postgres-database/src/simcore_postgres_database/migration/versions/163b11424cb1_convert_empty_str_to_null.py
services/catalog/src/simcore_service_catalog/models/services_db.py

This PR fixes a validation issue caused by invalid values in the database.
A request to the catalog service was failing due to an invalid value in the database:
```sh
curl http://master_catalog:8000/v0/services/simcore%2Fservices%2Fdynamic%2Fjupyter-math/3.0.3?user_id=530
{"errors":["1 validation errors:\n  {'type': 'url_parsing', 'loc': ('response', 'icon'), 'msg': 'Input should be a valid URL, input is empty', 'input': '', 'ctx': {'error': 'input is empty'}}\n"]}
```
The issue occurred because the `icon` column in the second row **was set to an empty string** instead of either a valid URL or `NULL`.
This could have been introduced manually in the database or as a result of an unintended transformation between models in the system.
To address this, we implemented the following changes:
- …

🐛 catalog-api: Fixes validation errors on /services entrypoint

---

services/web/server/src/simcore_service_webserver/trash/_rest.py

Prevents that when the front-end requests `empty-trash` and subsequently requests the trash item list, it may still display items, misleading the user into thinking the `empty trash` operation failed.
- issue reported by @odeimaiz 
- enhancements on ITISFoundation/osparc-issues#468
Manually tested:
- trash many items
- Go to "Recently Deleted"
- Click `Delete all`
-  shows none

🎨 Improves empty-trash to avoid misleading the user

---

packages/models-library/src/models_library/api_schemas_storage/storage_schemas.py
services/storage/src/simcore_service_storage/models.py
services/storage/tests/conftest.py
services/storage/tests/unit/test_handlers_paths.py

This PR brings url encoding (including `/` characters) for the `display_path` field in `PathMetaData` object.
This is needed as project names and node names may contain any kind of characters including `/` characters.

🎨Storage: display path field is url encoded by parts

---

.pre-commit-config.yaml
packages/service-library/src/servicelib/fastapi/cancellation_middleware.py
packages/service-library/tests/fastapi/test_cancellation_middleware.py
services/storage/src/simcore_service_storage/core/application.py

This PR introduces a middleware for FastAPI-based services that cancel the server request via ```asyncio.CancelledError``` (same as what aiohttp-based application are doing).
driving test: ```packages/service-library/tests/fastapi/test_cancellation_middleware.py```
:warning: using fastapi BackgroundTasks will also be cancelled if this middleware is used. To use with care.
It is now activated in storage micro-service
- closes https://github.com/ITISFoundation/osparc-simcore/issues/7195

Storage: Add cancellation middleware

---

services/static-webserver/client/source/class/osparc/desktop/account/ProfilePage.js
services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ConfirmationsPage.js
services/static-webserver/client/source/class/osparc/desktop/preferences/pages/GeneralPage.js
services/static-webserver/client/source/class/osparc/product/AboutProduct.js
services/static-webserver/client/source/class/osparc/store/LicensedItems.js
services/static-webserver/client/source/class/osparc/vipMarket/Market.js

No glitch:
Strings Before:
Strings After:

🎨 [Frontend] App Team (04.03): Shop glitch and Strings

---

api/specs/web-server/_storage.py
packages/models-library/src/models_library/api_schemas_storage/storage_schemas.py
packages/models-library/src/models_library/api_schemas_webserver/storage.py
packages/service-library/src/servicelib/fastapi/rest_pagination.py
services/api-server/openapi.json
services/api-server/src/simcore_service_api_server/models/pagination.py
services/storage/openapi.json
services/storage/src/simcore_service_storage/api/rest/_paths.py
services/storage/tests/unit/test_handlers_paths.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml

required by frontend, to allow to do stepped upgrades. the max limit of the paths listing is increased to 1000

🎨Storage: Increased maximum number of returned paths to 1000

---

tests/e2e-playwright/Makefile
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py
tests/e2e-playwright/tests/sim4life/test_sim4life.py
tests/e2e-playwright/tests/sleepers/test_sleepers.py
tests/e2e-playwright/tests/tip/conftest.py

adds the option to define the service version **for sim4life and jupyterlabs** in E2E tests
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7072

🎨E2E: add --service_version option

---

services/static-webserver/client/source/class/osparc/desktop/credits/CreditsIndicatorButton.js
services/static-webserver/client/source/class/osparc/desktop/credits/CreditsPerService.js
services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js

Reported by @capbrown 
The Credits Summary widget used to have a 30px offset, making the widget stay when tapping other buttons in the navigation bar. This PR fixes this issue.
Buggy:
Fixed:

🐛 [Frontend] Fix: Credits Summary indicator's offset

---

scripts/maintenance/computational-clusters/autoscaled_monitor/dask.py

- fixes usage of dask client when cancelling futures

🐛Autoscaled instances monitoring script: small fixes

---

packages/postgres-database/src/simcore_postgres_database/utils_repos.py
services/resource-usage-tracker/src/simcore_service_resource_usage_tracker/services/modules/db/credit_transactions_db.py
services/storage/src/simcore_service_storage/datcore_dsm.py
services/storage/src/simcore_service_storage/modules/db/_base.py
services/storage/src/simcore_service_storage/modules/db/access_layer.py
services/storage/src/simcore_service_storage/modules/db/file_meta_data.py
services/storage/src/simcore_service_storage/modules/db/projects.py
services/storage/src/simcore_service_storage/modules/db/tokens.py
services/storage/src/simcore_service_storage/simcore_s3_dsm.py
services/storage/src/simcore_service_storage/utils/simcore_s3_dsm_utils.py
services/storage/tests/unit/test_db_access_layer.py
services/storage/tests/unit/test_dsm_dsmcleaner.py
services/storage/tests/unit/test_simcore_s3_dsm.py
services/web/server/src/simcore_service_webserver/groups/_groups_repository.py

This PR makes use of transaction helpers created by @pcrespov.
```python
async with transaction_context
async with pass_or_acquire_connection
```
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7312

♻️Storage: use transactions helpers

---

services/invitations/openapi.json
services/invitations/requirements/_base.txt
services/invitations/requirements/_test.txt
services/invitations/requirements/_tools.txt

- #packages before ~ 64
- #packages after ~ 65
|   1 | aio-pika                  | 9.5.0           | 9.5.5      |            | 1 | invitations⬆️ |
|   2 | aiohappyeyeballs          | 2.4.3           | 2.6.1      | *minor*    | 1 | invitations⬆️ |
|   3 | aiohttp                   | 3.11.7          | 3.11.13    |            | 1 | invitations⬆️ |
|   4 | aiosignal                 | 1.3.1           | 1.3.2      |            | 1 | invitations⬆️ |
|   5 | anyio                     | 4.6.2.post1     | 4.8.0      | *minor*    | 2 | invitations⬆️🧪 |
|   6 | astroid                   | 3.3.8           | 3.3.9      |            | 1 | invitations🔧 |
|   7 | attrs                     | 24.2.0          | 25.2.0 …

⬆️ invitations service: upgrades requirements

---

packages/common-library/src/common_library/error_codes.py
packages/common-library/tests/test_error_codes.py
packages/service-library/tests/aiohttp/test_rest_middlewares.py

This PR introduces a new fingerprinting mechanism for generating the *osparc error code* (OEC). Instead of computing the OEC from the exception instance, which produced a different OEC for every occurrence, we now generate the OEC from a fingerprint of the exception’s type and relevant context. This change ensures that identical errors will consistently yield the same OEC across multiple occurrences.
The OEC is included in the logs and passed to the front-end as a `supportId` (SEE OAS below), enabling users and support teams to trace and identify unexpected errors. It is also extracted by the logging system as `log_oec` and `log_userid` to associate errors with users and provide better observability across the platform.
Previously, identical errors thrown in different instances (even with …

🎨 New `OEC:{traceback}-{timestamp}` format for de-duplication purposes

---

services/autoscaling/tests/manual/docker-compose.yml
services/director-v2/docker-compose-extra.yml
services/docker-compose.yml
services/web/server/tests/unit/with_dbs/docker-compose-devel.yml
services/web/server/tests/unit/with_dbs/docker-compose.yml
tests/swarm-deploy/conftest.py

- solves https://github.com/ITISFoundation/osparc-simcore/issues/6867
NOTE: AWS deployments already use rabbitmq 3.13

⬆️Maintenance: upgrade rabbitmq to 3.13.7

---

.github/CODEOWNERS
Makefile
packages/service-library/src/servicelib/fastapi/cancellation_middleware.py
services/agent/docker/boot.sh
services/api-server/docker/boot.sh
services/autoscaling/docker/boot.sh
services/catalog/docker/boot.sh
services/clusters-keeper/docker/boot.sh
services/dask-sidecar/docker/boot.sh
services/datcore-adapter/docker/boot.sh
services/director-v2/docker/boot.sh
services/director/docker/boot.sh
services/docker-compose.devel.yml
services/dynamic-scheduler/docker/boot.sh
services/dynamic-sidecar/docker/boot.sh
services/efs-guardian/docker/boot.sh
services/invitations/docker/boot.sh
services/payments/docker/boot.sh
services/resource-usage-tracker/docker/boot.sh
services/storage/docker/boot.sh
services/web/server/docker/boot.sh
services/web/server/tests/unit/with_dbs/docker-compose-devel.yml
services/web/server/tests/unit/with_dbs/docker-compose.yml

- make booting in devel mode faster by mounting the host UV cache in the containers
- do not log a cancellation of the client when a handler completed (fastapi cancellation middleware)
- disable DB writing to disk as this is not necessary during test (initial test with the webserver) - not sure it changes much

🎨Maintenance: make devel mode faster to boot + log fixes + webserver DB disable write to disk

---

packages/service-library/src/servicelib/progress_bar.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/async_jobs/async_jobs.py
packages/service-library/tests/rabbitmq/conftest.py
packages/service-library/tests/rabbitmq/test_rabbitmq_rpc.py
packages/service-library/tests/rabbitmq/test_rabbitmq_rpc_interfaces_async_jobs.py
services/storage/src/simcore_service_storage/modules/celery/_celery_types.py
services/storage/src/simcore_service_storage/modules/celery/_task.py
services/storage/src/simcore_service_storage/modules/celery/models.py
services/web/server/docker/boot.sh

- introduces a client for calling async jobs via RPC (same as with long running tasks)
- adds some tests
- add some fixes for celery task in case of coroutines
- added example (THAT WILL BE USED IN THE NEXT PR) of using pydantic types in celery tasks

✨Async Jobs: add some tests +  an internal client

---

packages/service-library/src/servicelib/aiohttp/rest_middlewares.py
packages/service-library/src/servicelib/aiohttp/rest_responses.py
packages/service-library/tests/aiohttp/test_rest_responses.py

Fixes missing `supportID` on default `5XX` responses from the web-api:
- Issue reported by @odeimaiz  in the internal chat (see screenshot above)
- Follows up on https://github.com/ITISFoundation/osparc-simcore/pull/7394
```
make "install-dev[aiohttp]"
pytest -vv tests/aiohttp -k tests_exception_to_response
```
None

🐛web-api:  Fixes missing `supportID` on default `5XX` responses

---

services/storage/src/simcore_service_storage/modules/celery/_common.py

🐛 Fix redis ssl certificate issue

---

services/storage/src/simcore_service_storage/core/application.py
services/storage/src/simcore_service_storage/modules/rabbitmq.py

🐛Storage Worker does not need a RabbitMQ client

---

.github/workflows/ci-testing-deploy.yml
packages/pytest-simcore/src/pytest_simcore/docker_compose.py
packages/service-library/src/servicelib/rabbitmq/_client_rpc.py
packages/settings-library/src/settings_library/redis.py
services/storage/src/simcore_service_storage/api/rpc/_async_jobs.py

- stripped down of https://github.com/ITISFoundation/osparc-simcore/pull/7424 -> only taking validation fix
- fixes friendly naming in rabbit UI, also for RPC connections
- increase timeout on storage unit tests
- fsync=off for all tests
NOTE: this will be forcibly pushed

🐛Storage: Celery issues with validation

---

services/storage/src/simcore_service_storage/api/_worker_tasks/_paths.py
services/storage/src/simcore_service_storage/modules/celery/_celery_types.py
services/storage/src/simcore_service_storage/modules/celery/_task.py
services/storage/src/simcore_service_storage/modules/celery/client.py

- the definition of compute_path_size was wrong and not following what the decorator needs (typing issue)
- added TaskError to the serializable celery types
- adds the cache backend

🐛Storage: multiple user_id defined issue

---

packages/aws-library/src/aws_library/s3/_client.py
services/storage/src/simcore_service_storage/modules/celery/signals.py

🐛Storage-Worker: ensure startup waits for fastapi application readyness

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/store/PollTasks.js
services/static-webserver/client/source/class/osparc/task/TasksButton.js

reported by @sanderegg 
Bugfix: In this [PR](https://github.com/ITISFoundation/osparc-simcore/pull/7396) I forgot to push the last commit, making the removing of the task-card buggy
Buggy:
Fixed:

🐛 [Frontend] Fix: Remove Task

---

packages/service-library/src/servicelib/fastapi/client_session.py
services/director/src/simcore_service_director/core/application.py
services/director/src/simcore_service_director/core/settings.py
services/director/tests/unit/test_core_settings.py

- adds `DIRECTOR_REGISTRY_CLIENT_TIMEOUT` as a potential ENV variable. default value is now set to 20 seconds to be similar with old aiohttp client
If this really needs to become a fully fledged ENV, let me know @mrnicegyu11 
- solves https://github.com/ITISFoundation/osparc-simcore/issues/7456

🎨Director-v0: set default timeout to 20s and potentially allow setting it up

---

services/web/server/src/simcore_service_webserver/garbage_collector/_core.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_orphans.py

There where situations in which Step 3 of the GC was never executed, causing sidecars to be accumulated.
- in case of errors in step 1 and step 2 the GC would stop and not reach step 3 which is very important for removing system resource
- Instead of continuing the process wen `list_node_ids_in_project`  raised, the process is stopped. This could cause the GC to stop when services still required removal. (Issue introduced by  https://github.com/ITISFoundation/osparc-simcore/pull/7354)

🐛 Fixed issue where GC stopping too early

---

scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
scripts/maintenance/computational-clusters/autoscaled_monitor/core.py
scripts/maintenance/computational-clusters/autoscaled_monitor/ssh.py
scripts/maintenance/computational-clusters/pyproject.toml
scripts/maintenance/computational-clusters/uv.lock

The monitoring script has the following new features:
- command `summary` now accepts `--as-json` argument and will output the current autoscaled clusters status as json
- command `trigger-cluster-termination` now accepts a `force` argument (to use with **CARE**) that will first cancel all the computation jobs for that user-id/wallet-id combination, then change the last heartbeat on the primary machine, thus trigger termination procedure from the clusters-keeper micro-service
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7452
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7453

🎨Monitoring script: add json output for summary, allow to trigger computational cluster termination

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright_sim4life.py
tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py
tests/e2e-playwright/tests/sim4life/test_sim4life.py
tests/e2e-playwright/tests/sim4life/test_template.py
tests/e2e-playwright/tests/tip/test_ti_plan.py

- added fail fast conditions when:
- computational pipeline goes into FAILED,ABORTED state instead of waiting super long
- dynamic service goes into IDLE, FAILED service state by checking websocket ServiceStatus message
- 409 is raised when opening a project
- added missing states when checking for node progress types
- catch exception in playwright callback (that is very bad as this implies infinite loops)
- in case of dynamic service failing on start, **all** the websocket messages are json-formatted and written into `websocket.json` file in the test-results output for later debugging
E2E TIP issues

🎨E2E: Fail fast conditions + websocket logging in case of error

---

services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py

When a container does not throw any logs for 5 minutes, aiodocker throw a TimeoutError as it is based on aiohttp.
This PR changes that timeout to 1 hour.

🐛Dask-sidecar: set 1 hour timeout when waiting for container logs

---

services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/metadata/ServicesInStudyUpdate.js
services/static-webserver/client/source/class/osparc/store/Services.js
services/static-webserver/client/source/class/osparc/study/Utils.js

This PR fixes the classic "duplicate requests flood" problem. It happens a lot when multiple cards in the dashboard fetch the same service's metadata in parallel.
To solve it, a shared fetch cache or request deduplication was implemented.
Before:
After:

🎨 [Frontend] Enh service calls: avoid request deduplication

---

services/storage/src/simcore_service_storage/exceptions/errors.py
services/storage/src/simcore_service_storage/simcore_s3_dsm.py
services/storage/src/simcore_service_storage/utils/simcore_s3_dsm_utils.py
services/storage/tests/unit/test_rpc_handlers_simcore_s3.py
services/storage/tests/unit/test_simcore_s3_dsm.py
services/storage/tests/unit/test_simcore_s3_dsm_utils.py

- Restrict export data only for a select of files and folders coming from the same folder.
- No longer include the full path from the bucket root. Only include the path with regard to the user selection. Eg: `/some/selection/in/the/bucket/file/` will add only `file` inside the archive.

♻️ export data feature enhancements

---

services/docker-compose.yml

Fix a typo in Celery's cpu-bound queue name (`cpu-bound` -> `cpu_bound`).

🐛 Fix a typo in Celery's cpu-bound queue name

---

services/storage/tests/conftest.py
services/storage/tests/unit/test_async_jobs.py

- Fix bug in our celery test worker fixture.
- I double checked and signals should not be sent in the celery test worker, only connected. That means we were sending the shutdown signal twice which seems to be the thing causing the hang
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7486

🐛 Fix abort task test

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py

🎨 E2E: upgrade timings

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py

🎨E2E: fixed computation of timeouts

---

.github/copilot-instructions.md
docs/env-vars.md

This pull request includes significant updates to the documentation and best practices for using GitHub Copilot in the `osparc-simcore` repository, as well as a minor change to the environment variables documentation.
* Added a new file `.github/copilot-instructions.md` with guidelines and best practices for using GitHub Copilot in Python and Node.js projects. This includes general guidelines, Python-specific instructions, Node.js-specific instructions, and Copilot usage tips.
* Updated `docs/env-vars.md` to remove a redundant note about default values for environment variables.

✨Maintenance: added first draft of copilot instructions

---

services/api-server/openapi.json
services/api-server/src/simcore_service_api_server/api/routes/programs.py

- Don't expose listing of programs in this release because we are in the progress of adding a paginated version

♻️ Remove listing of programs

---

tests/e2e-playwright/tests/tip/test_ti_plan.py

The current wait-for-Run-Optimization doesn't work, either because the expected websocket message doesn't reach the frontend or something else.
In this PR we go back to the wait-to-the-button-go-green approach.

[e2e] Fix TIP test

---

packages/models-library/src/models_library/rpc/webserver/projects.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/webserver/projects.py
services/web/server/src/simcore_service_webserver/projects/_controller/projects_rpc.py
services/web/server/src/simcore_service_webserver/projects/_jobs_repository.py
services/web/server/src/simcore_service_webserver/projects/_jobs_service.py
services/web/server/src/simcore_service_webserver/projects/models.py
services/web/server/tests/unit/with_dbs/02/test_projects__jobs_service.py
services/web/server/tests/unit/with_dbs/02/test_projects_rpc.py

Exposes the `list_my_projects_marked_as_jobs` method on the `web-server` RPC interface to enable the `api-server` to retrieve a paginated list of all projects marked as jobs.
- Implements service-layer: `simcore_service_webserver.projects._jobs_service`
- Implements repository-layer: `simcore_service_webserver.projects._jobs_repository`
- Exposes function to RPC API
- server side: `projects._controller.projects_rpc`
- client side: `servicelib.rabbitmq.rpc_interfaces.webserver.projects`
- models: `models_library.rpc.webserver.projects` (shared)
- exceptions: `servicelib.rabbitmq.rpc_interfaces.webserver.errors` (shared)
**NOTE**: The current organization of RPC interfaces feels fragmented and hard to work with. We should consider restructuring them into dedicated Python packages (e.g., …

 ✨ web-server RPC: exposes `list_my_projects_marked_as_jobs` 

---

services/static-webserver/client/source/class/osparc/dashboard/SearchBarFilter.js
services/static-webserver/client/source/class/osparc/filter/TextFilter.js
services/static-webserver/client/source/class/osparc/form/tag/TagItem.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

I can't reproduce it in my local deployment, so this is an attempt to disable the autocompletion in the Dashboards Search tool by setting the ``autocomplete`` attribute to ``off``, and the input ``type`` from the default ``text`` to ``search``.
- closes https://github.com/ITISFoundation/osparc-issues/issues/1874

🐛 [Frontend] Disable Autocompletion

---

packages/service-library/src/servicelib/fastapi/lifespan_utils.py
packages/service-library/src/servicelib/fastapi/postgres_lifespan.py
packages/service-library/src/servicelib/fastapi/rabbitmq.py
packages/service-library/src/servicelib/fastapi/rabbitmq_lifespan.py
packages/service-library/src/servicelib/fastapi/redis_lifespan.py
packages/service-library/src/servicelib/rabbitmq/__init__.py
packages/service-library/src/servicelib/rabbitmq/_client_rpc.py
packages/service-library/tests/fastapi/test_lifespan_utils.py
packages/service-library/tests/fastapi/test_rabbitmq_lifespan.py
packages/service-library/tests/fastapi/test_redis_lifespan.py
packages/settings-library/src/settings_library/rabbit.py
packages/settings-library/src/settings_library/redis.py

Enhances the `servicelib.fastapi` module by extending its lifespan management functionality using a context manager pattern (`on_startup`/`on_shutdown`). This update introduces reusable lifespan contexts for managing RabbitMQ (both connection and RPC clients) and Redis resources (only clients).
All these new functions are reusable and should drastically reduce the boilerplate to create simcore-service. Please check tests to see usage
- Preparations for https://github.com/ITISFoundation/osparc-simcore/pull/7546
```
make "install-dev[all]"
pytest -vv tests/fastapi/test_*lifespan*.py
```
None

🎨 Add Reusable Lifespan Contexts for RabbitMQ and Redis in `servicelib.fastapi`

---

services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/form/tag/TagManager.js
services/static-webserver/client/source/class/osparc/info/StudyMedium.js
services/static-webserver/client/source/class/osparc/info/StudyUtils.js
services/static-webserver/client/source/class/osparc/store/Tags.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

🐛 [Frontend] Do not reload Studies when loading Tags

---

services/static-webserver/client/source/class/osparc/dashboard/NewStudies.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

Fixes the callback on the New Plans buttons

🐛 [Frontend] Fix TIP's New Plans

---

packages/service-library/tests/rabbitmq/test_rabbitmq_rpc_interfaces_async_jobs.py

Fix `service_library` tests adding the missing `AsyncJob`'s name.
```
cd packages/service-libraries
pytest tests/rabbitmq/test_rabbitmq_rpc_interfaces_async_jobs.py
```

🐛 Add missing `AsyncJob`'s name

---

.coveragerc
packages/models-library/src/models_library/api_schemas_catalog/services.py
packages/models-library/src/models_library/function_services_catalog/_key_labels.py
packages/models-library/src/models_library/rpc_filters.py
packages/models-library/src/models_library/services_constants.py
packages/models-library/src/models_library/services_regex.py
packages/pytest-simcore/src/pytest_simcore/helpers/catalog_rpc_server.py
packages/service-integration/src/service_integration/osparc_config.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/catalog/services.py
services/catalog/src/simcore_service_catalog/api/rpc/_services.py
services/catalog/src/simcore_service_catalog/models/services_db.py
services/catalog/src/simcore_service_catalog/repository/_services_sql.py
services/catalog/src/simcore_service_catalog/repository/services.py
services/catalog/src/simcore_service_catalog/service/catalog_services.py
services/catalog/tests/unit/with_dbs/test_api_rpc.py
services/catalog/tests/unit/with_dbs/test_repositories.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_catalog.py

Introduces a `filters: ServiceListFilters` argument in the listing functions of the catalog RPC API to enable service filtering.
- **`catalog` rpc-client**  
- Added `filters: ServiceListFilters` to `list_services_paginated` and `list_my_service_history_paginated`
- **`catalog` simcore-service**
- **Controller layer (`api.rpc`)**  
- Accepts `filters: ServiceListFilters` in listing endpoints  
- Maps `ServiceListFilters` to domain model `ServiceFiltersDB`  
- Updates RPC server mocks (`pytest_simcore.helpers.catalog_rpc_service`)
- **Service layer (`service.catalog_services`)**  
- Handles `filter: ServiceFiltersDB` in listing logic  
- **Repository layer (`repository.services`)**  
- Accepts `filter: ServiceFiltersDB`  
- Applies filters using `apply_services_filters` in SQLAlchemy …

 ✨ Adds filtering for Service Listing in Catalog's RPC API

---

services/static-webserver/client/source/class/osparc/dashboard/NewPlusMenu.js
services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/workbench/ServiceCatalog.js

reported by @bisgaard-itis 
It can happen that the frontend's services cache gets "contaminated" with inaccessible services.
This PR makes that listing more robust by filtering out the ``null``/inaccessible services.

🐛 [Frontend] Fix: Service catalog listing

---

.github/workflows/ci-pact-master.yml
.github/workflows/ci-testing-deploy.yml
.github/workflows/ci-testing-pull-request.yml
packages/postgres-database/docker/Dockerfile
packages/postgres-database/scripts/erd/Dockerfile
packages/service-integration/Dockerfile
requirements/tools/Dockerfile
scripts/erd/Dockerfile
scripts/maintenance/migrate_project/Dockerfile
scripts/openapi/oas_resolver/Dockerfile
scripts/pydeps-docker/Dockerfile
services/agent/Dockerfile
services/api-server/Dockerfile
services/autoscaling/Dockerfile
services/catalog/Dockerfile
services/clusters-keeper/Dockerfile
services/dask-sidecar/Dockerfile
services/datcore-adapter/Dockerfile
services/director-v2/Dockerfile
services/director/Dockerfile
services/dynamic-scheduler/Dockerfile
services/dynamic-sidecar/Dockerfile
services/efs-guardian/Dockerfile
services/invitations/Dockerfile
services/migration/Dockerfile
services/payments/Dockerfile
services/resource-usage-tracker/Dockerfile
services/storage/Dockerfile
services/web/Dockerfile

This pull request updates the `uv` dependency version across multiple CI workflows to ensure compatibility with the latest features and improvements. The changes involve upgrading from version `0.5.x` to `0.6.x` in several `jobs` configurations within the `.github/workflows` directory.
* [`.github/workflows/ci-pact-master.yml`](diffhunk://#diff-5d849c811be153c45b50f3a97e7b7db4b515f9823cdd69106137765f237037f6L31-R31): Updated `uv` version to `0.6.x` in the `install uv` step.
* [`.github/workflows/ci-testing-deploy.yml`](diffhunk://#diff-9b5d06fc85e79182a6a8e352fea2c8f992876b2617bb2c246946fd78128daff9L362-R362): Updated `uv` version to `0.6.x` in multiple `install uv` steps across various job configurations, ensuring consistency throughout the workflow. …

⬆️ Maintenance: Upgrade UV to 0.6.x

---

ci/helpers/requirements/requirements.txt
packages/aws-library/requirements/_base.txt
packages/aws-library/requirements/_test.txt
packages/service-library/requirements/_test.txt
packages/simcore-sdk/requirements/_test.txt
requirements/constraints.txt
services/agent/requirements/_test.txt
services/api-server/requirements/_base.txt
services/api-server/requirements/_test.txt
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_test.txt
services/datcore-adapter/requirements/_base.txt
services/director-v2/requirements/_base.txt
services/director-v2/requirements/_test.txt
services/docker-compose-ops-ci.yml
services/docker-compose-ops.yml
services/dynamic-sidecar/requirements/_test.txt
services/efs-guardian/requirements/_base.txt
services/efs-guardian/requirements/_test.txt
services/resource-usage-tracker/requirements/_base.txt
services/resource-usage-tracker/requirements/_test.txt
services/storage/requirements/_base.txt
services/storage/requirements/_test.txt
services/web/server/requirements/_base.txt
tests/swarm-deploy/requirements/_test.txt

🚨🚨🚨: Check CEPH S3 compatibility when deleting a file
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7127
The issue arising in tests was coming from Minio: https://github.com/minio/minio/issues/20845, updating the minio to the latest version `RELEASE.2025-04-22T22-12-26Z` solves the problem
- #packages before ~ 10
- #packages after ~ 6
|   1 | aioboto3                  | 13.3.0, 13.1.0, 13.2.0 | 14.1.0     | **MAJOR**  | 10 | agent🧪</br>autoscaling⬆️</br>aws-library🧪</br>clusters-keeper⬆️</br>director-v2🧪</br>dynamic-sidecar🧪</br>efs-guardian⬆️</br>resource-usage-tracker⬆️</br>simcore-sdk🧪</br>storage⬆️ |
|   2 | aiobotocore               | 2.16.0, 2.15.2, 2.13.1 | 2.21.1     | …

⬆️Maintenance: unblock boto3 🚨🚨🚨🚨

---

packages/aws-library/src/aws_library/s3/__init__.py
packages/aws-library/src/aws_library/s3/_client.py
services/dask-sidecar/requirements/_base.txt
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/requirements/constraints.txt
services/storage/requirements/_base.in
services/storage/requirements/_base.txt
services/storage/requirements/_test.txt
services/storage/requirements/constraints.txt

our CEPH S3 is not 100% compatible anymore (or at least for our use) anymore with AWS S3 since [botocore 1.36.0](https://github.com/boto/botocore/tree/1.36.0) was released this year.
Until CEPH is updated botocore version is locked which has implications on many other libraries.
this is now constrained on storage and dask-sidecar services which are the only one uploading data to S3 at this time.
The current CEPH S3 is incompatible with botocore, the AWS CLI, and any other tools based on botocore (which is almost everything)
- #packages before ~ 5
- #packages after ~ 5
|   1 | aioboto3                  | 14.1.0          | 13.3.0     | 🔥 downgrade     | 1 | storage⬆️ |
|   2 | aiobotocore …

🐛lock botocore<1.36.0 until CEPH S3 is updated to be compatible with AWS S3

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py

🎨E2E: when service legacy there is no need to wait for the running events

---

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/utils.py
packages/dask-task-models-library/src/dask_task_models_library/models.py
packages/dask-task-models-library/tests/container_tasks/test_utils.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_core.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_base.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_computational.py
services/autoscaling/src/simcore_service_autoscaling/modules/auto_scaling_mode_dynamic.py
services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py
services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py
services/autoscaling/tests/unit/conftest.py
services/autoscaling/tests/unit/test_modules_auto_scaling_computational.py
services/autoscaling/tests/unit/test_modules_auto_scaling_dynamic.py
services/autoscaling/tests/unit/test_modules_buffer_machine_core.py
services/autoscaling/tests/unit/test_modules_rabbitmq.py
services/autoscaling/tests/unit/test_utils_auto_scaling_core.py
services/autoscaling/tests/unit/test_utils_docker.py
services/autoscaling/tests/unit/test_utils_rabbitmq.py
services/director-v2/src/simcore_service_director_v2/models/dask_subsystem.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_dask.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/unit/with_dbs/conftest.py
services/director-v2/tests/unit/with_dbs/test_utils_dask.py

This PR improves logging of the autoscaling micro-service w.r.t computational tasks:
- now parse the dask tasks to discover `user_id`, `project_id` and `node_id` so that logs can be published accordingly
The effect is that the autoscaling service in computational mode now also sends minimal log messages into RabbitMQ that can be displayed in the frontend.
This is a pre-requisite to sending events that can be shown for job submission feature.
- code for generating/parsing dask job id moved from DV-2 to dask-task-models-library
- code now also used in autoscaling
- refactored autoscaling rabbitMQ message publications
- driving tests: `test_utils_rabbitmq.py`
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/6667

🎨Autoscaling in computations: send log/progress messages to rabbitMQ

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
tests/e2e-playwright/tests/tip/test_ti_plan.py

- tip-light: getting button by role when disabled is not allowed and fails
- tip: AWS-tip checking service endpoint is very slow and needs way more than 5 seconds, so this is increased to 30 seconds

🐛E2E: TIP test fixes

---

.github/PULL_REQUEST_TEMPLATE.md
docs/devops-checklist.md
services/web/server/tests/unit/with_dbs/04/studies_dispatcher/test_studies_dispatcher_studies_access.py

- Fixes #7005 
```
pytest -vv tests/unit -k test_guest_user_is_not_garbage_collected 
```

✅ Fixes flaky: test_guest_user_is_not_garbage_collected

---

scripts/maintenance/computational-clusters/autoscaled_monitor/cli.py
scripts/maintenance/computational-clusters/autoscaled_monitor/core.py

This pull request introduces enhancements to the `autoscaled_monitor` CLI tool, primarily focusing on adding support for outputting results to a file and improving the flexibility of certain functions. The changes include updates to the `summary` command, modifications to the output handling logic, and adjustments to function parameters for better usability.
```bash
autoscaled-monitor --deploy-config my_osparc summary --as-json --output test.json
```
* Added an optional `output` parameter of type `Path` to the `summary` command in `cli.py`, allowing users to specify a file for saving the command's output. [[1]](diffhunk://#diff-cd78fe84a38b754ca7765cebc4a0d2f8f7e7f474443e133f72ea24a973413d31R130-R134) [[2]](diffhunk://#diff-cd78fe84a38b754ca7765cebc4a0d2f8f7e7f474443e133f72ea24a973413d31L1 …

✨Maintenance: autoscaled clusters allows to write outputs to a file

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
packages/pytest-simcore/src/pytest_simcore/helpers/playwright_sim4life.py
tests/e2e-playwright/tests/jupyterlabs/test_jupyterlab.py
tests/e2e-playwright/tests/sim4life/test_sim4life.py
tests/e2e-playwright/tests/sim4life/test_template.py
tests/e2e-playwright/tests/tip/test_ti_plan.py

♻️E2e: definite fix to ensure idle timeout is always smaller than waiting timeout

---

packages/postgres-database/tests/test_comp_tasks.py
packages/pytest-simcore/src/pytest_simcore/db_entries_mocks.py
packages/pytest-simcore/src/pytest_simcore/postgres_service.py
services/director-v2/requirements/_test.in
services/director-v2/requirements/_test.txt

This PR definitely removes aiopg dependency from dv-2, even from tests requirements.
Also adds a warning in the `aiopg_engine` fixture in pytest-simcore.
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/4529

♻️Director-v2: removed aiopg dependency also from tests

---

scripts/maintenance/computational-clusters/autoscaled_monitor/core.py

🐛Autoscaling script: bugfix, invalid variable

---

services/director-v2/src/simcore_service_director_v2/api/routes/computations_tasks.py
services/director-v2/src/simcore_service_director_v2/utils/computations.py
services/director-v2/tests/unit/test_utils_computation.py

- 🎨 add `WAITING_FOR_RESOURCES` to `get_pipeline_state_from_task_states` --> fixing: if task was in state WAITING_FOR_RESOURCES it was reported as ERROR in the Comp runs
- relates https://github.com/ITISFoundation/osparc-issues/issues/1645

🎨 add `WAITING_FOR_RESOURCES` to `get_pipeline_state_from_task_states`

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
services/static-webserver/client/source/class/osparc/info/CommentAdd.js
services/static-webserver/client/source/class/osparc/info/CommentUI.js
services/static-webserver/client/source/class/osparc/info/Conversation.js
services/static-webserver/client/source/class/osparc/navigation/StudyTitleWOptions.js
services/static-webserver/client/source/class/osparc/store/Store.js
services/static-webserver/client/source/class/osparc/study/Conversations.js
services/static-webserver/client/source/class/osparc/task/ExportData.js

This PR replaces ``/comments`` with ``/conversations`` and, in order to support multiple conversations per project, it brings a UX similar to Notepad++'s tab, with an always present conversation-placeholder.
- follows https://github.com/ITISFoundation/osparc-simcore/pull/7591
- related to https://github.com/ITISFoundation/private-issues/issues/51

✨ [Frontend] Multiple ``conversations`` per project

---

services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py

This flag should silence the wrongly shown error message: 
```
ERROR: [2024-09-05 08:04:11,514/Dask Worker process (from Nanny)] [simcore_service_dask_sidecar.dask_utils:publish_logs(98)]  -  [sidecar] Task error:
[Errno %s not found. The URL contains glob characters: you maybe needed
to pass expand=True in fsspec.open() or the storage_options of 
your library. You can also set the config value 'open_expand'
before import, or fsspec.core.DEFAULT_EXPAND at runtime, to True.] https://s3.amazonaws.com/production-simcore/0cb0a922-6adf-11ef-a2bb-0242ac174682/69c7a296-f83f-4b61-abf1-a569b04f653a/input0.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIATHZO54NSLAMDH4NW/20240904/us-east-1/s3/aws4_request&X-Amz-Date=20240904T171209Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signat …
```

🐛Dask-Sidecar: explicitely set expand flag to remove confusing error message

---

services/payments/src/simcore_service_payments/services/auto_recharge_process_message.py
services/payments/tests/unit/test_services_auto_recharge_listener.py

- 🎨 Add a safety condition for auto-recharge: In case RabbitMQ messages were not being consumed for any reason and start being consumed later, auto-recharge will not be triggered if the messages are older than 5 minutes.

🎨 add safety condition for auto-recharge

---

packages/pytest-simcore/src/pytest_simcore/aws_s3_service.py
packages/service-library/tests/aiohttp/test_tracing.py
packages/service-library/tests/fastapi/test_tracing.py
scripts/maintenance/computational-clusters/autoscaled_monitor/dask.py
services/dask-sidecar/requirements/_test.in
services/dask-sidecar/requirements/_test.txt
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py
services/dask-sidecar/src/simcore_service_dask_sidecar/utils/files.py
services/dask-sidecar/tests/unit/conftest.py
services/dask-sidecar/tests/unit/test_utils_files.py

Refactored tests, tested against AWS when the glob error appears in fsspec.
This is actually the standard error when a file is not found.
if the file expired it is actually also the same.
Bonus:
- do not fail autoscaling monitoring when dask-certificates are missing @YuryHrytsuk 
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/6308

♻️Dask sidecar: Glob error tests + autoscaling monitoring fix

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/form/renderer/PropForm.js
services/static-webserver/client/source/class/osparc/node/ParameterEditor.js
services/static-webserver/client/source/class/osparc/service/Utils.js
services/static-webserver/client/source/class/osparc/study/CreateFunction.js
services/static-webserver/client/source/class/osparc/study/Utils.js

This PR is the first iteration on the Creation of Functions required by the Meta Modeling case.
In order to be able to create a function out of a study, the study pipeline needs:
- Inputs: at least one parameter (or file-picker (file type parameter))
- Outputs: at least one probe
- For now, only float type is supported @JavierGOrdonnez 
if these requirements are met, a Create Function section will appear in the Study Card. From here, one can give a name, description and decide which inputs and outputs will be exposed.
When Create Function is pressed, the frontend will request the backend to create a template from the study, and then it will call  "POST" the ``/functions`` endpoint ([coming here](https://github.com/ITISFoundation/osparc-simcore/pull/7539)). 
- related to …

✨ [Frontend] Create Functions

---

packages/service-library/src/servicelib/aiohttp/long_running_tasks/server.py
services/web/server/src/simcore_service_webserver/long_running_tasks.py
services/web/server/src/simcore_service_webserver/tasks/_rest.py

- Call long running tasks module in `service_lib` directly when listing legacy tasks instead of calling the REST interface.
- fixes #7654

🐛 Avoid 401 when listing in process tasks in webserver

---

packages/aws-library/requirements/_base.txt
packages/aws-library/requirements/_test.txt
packages/simcore-sdk/requirements/_test.txt
services/agent/requirements/_test.txt
services/autoscaling/requirements/_base.txt
services/autoscaling/requirements/_test.txt
services/clusters-keeper/requirements/_base.txt
services/clusters-keeper/requirements/_test.txt
services/director-v2/requirements/_test.txt
services/dynamic-sidecar/requirements/_test.txt
services/efs-guardian/requirements/_base.txt
services/efs-guardian/requirements/_test.txt
services/resource-usage-tracker/requirements/_base.txt
services/resource-usage-tracker/requirements/_test.txt
services/storage/requirements/_base.txt
services/storage/requirements/_test.txt

This PR upgrades `aioboto3` (and dependencies) in order to include the changes in https://github.com/terricain/aioboto3/pull/369.
- #packages before ~ 4
- #packages after ~ 4
|   1 | aioboto3                  | 14.1.0          | 14.3.0     | *minor*    | 10 | agent🧪</br>autoscaling⬆️</br>aws-library🧪</br>clusters-keeper⬆️</br>director-v2🧪</br>dynamic-sidecar🧪</br>efs-guardian⬆️</br>resource-usage-tracker⬆️</br>simcore-sdk🧪</br>storage⬆️ |
|   2 | aiobotocore               | 2.21.1          | 2.22.0     | *minor*    | 10 | agent🧪</br>autoscaling⬆️</br>aws-library🧪</br>clusters-keeper⬆️</br>director-v2🧪</br>dynamic-sidecar🧪</br>efs-guardian⬆️</br>resource-usage-tracker⬆️</br>simcore-sdk🧪</br>storage⬆️ …

⬆️ Maintenance: Upgrade `aioboto3`

---

services/web/server/docker/boot.sh
services/web/server/requirements/_base.in
services/web/server/requirements/_base.txt
services/web/server/requirements/_test.txt

After testing it looks like the `uvloop`-powered aiohttp gunicorn worker performs much better than the standard one.
note that the response time on this example project is notably improved.
uvloop is a drop-in replacement for the standard asyncio event loop (note that fastapi already uses it by default)
- relates to https://github.com/ITISFoundation/private-issues/issues/79

🎨Webserver: use uvloop and aiohttp UV loop worker to increase performances

---

services/docker-compose.yml

upgrade traefik from 3.1.2 to 3.4.0. it seems that earlier version was killing the performance by quite the number.
as shown in the following screenshot moving from traefik 3.1.2 to 3.4.0 brings back almost the raw performance of the webserver. That is locally on my machine a factor 4 in requests per seconds hitting `/` endpoint.

⬆️Maintenance: upgrade to traefik v3.4.0

---

services/dask-sidecar/src/simcore_service_dask_sidecar/utils/dask.py
services/dask-sidecar/tests/unit/conftest.py
services/dask-sidecar/tests/unit/test_utils_dask.py
services/dask-sidecar/tests/unit/test_worker.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_dask.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/src/simcore_service_director_v2/utils/dask_client_utils.py
services/director-v2/tests/unit/test_modules_dask_client.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_scheduler_dask.py

This PR introduces several updates to the Dask-sidecar and Director-v2 and their associated tests. 
The changes focus on transitioning from Dask's deprecated `Pub/Sub` mechanism to their recommended event-based communication. Additionally, minor refactoring and cleanup have been performed to streamline the codebase.
* Replaced Dask's `Pub/Sub` mechanism with event-based communication using `worker.log_event` for publishing task progress and logs. (`[services/dask-sidecar/src/simcore_service_dask_sidecar/utils/dask.pyL172-R181](diffhunk://#diff-27830c4191d3861064437bb2474d4cbd8e1d90a2d3b0e8217c028e14fb674a2bL172-R181)`)
* Removed all references to `distributed.Pub` and `distributed.Sub` throughout the codebase and tests. (`[[1]](diffhunk://#diff-27830c4191d3861064437bb2474d4cbd8e1d90a2d3b0e …

♻️Dask-sidecar: remove dask Pub/Sub

---

services/web/server/src/simcore_service_webserver/application_settings.py
services/web/server/tests/unit/isolated/test_application_settings.py

Fixes  configuration of `WEBSERVER_FUNCTIONS` 
`WEBSERVER_FUNCTIONS` was incorrectly configured: it was marked as `_X_FEATURE_UNDER_DEVELOPMENT`, which is correct, but it was also explicitly set to `False`. 
The `_X_FEATURE_UNDER_DEVELOPMENT` flag is meant to **disable features in production** while keeping the actuall setting in development. Explicitly setting `WEBSERVER_FUNCTIONS=False`  will always (either development or production) keep this feature disabled.
- Fixes `WEBSERVER_FUNCTIONS` such that it only runs if `WEBSERVER_DEV_FEATURES_ENABLED=True` and otherwise it is disabled.
- ♻️ Cleanup tests and flag names
**Side note:** 
- The mechanism depending on the `WEBSERVER_DEV_FEATURES_ENABLED` environment variable is INDEED misleading—likely the result of incremental changes without …

🐛 Fixes `WEBSERVER_FUNCTIONS` to run in development deploys

---

services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js
services/static-webserver/client/source/class/osparc/dashboard/SearchBarFilter.js
services/static-webserver/client/source/class/osparc/pricing/PlanEditor.js
services/static-webserver/client/source/class/osparc/pricing/Plans.js
services/static-webserver/client/source/class/osparc/store/Templates.js
services/static-webserver/client/source/resource/osparc/tours/osparc_tours.json
services/static-webserver/client/source/resource/osparc/tours/s4l_tours.json
services/static-webserver/client/source/resource/osparc/tours/s4llite_tours.json
tests/e2e-frontend/tests/navigationBar/navigationBar.spec.js
tests/e2e-playwright/tests/conftest.py
tests/e2e/utils/auto.js

🐛 [Frontend] Fix: Pricing plan creation and Edit

---

services/static-webserver/client/source/class/osparc/study/CreateFunction.js

There was a small inconsistency between the frontend function definition and the backend, introduced during changes in the functions API PR. It prevent the input/output schema's ending up in the db.
Also a small change in how default inputs are handled. Default inputs are only used when the parameter is not exposed by the user.
Also the function name is the 'title' field (in sync with other osparc objects).
Create a function in the frontend. Check in postgres if funcapi_functions table has the correct function with schema.
No change ENV

Fix functions frontend by using schema_content instead of schema_dict  🐛🚑️

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/utils/DisabledPlugins.js

This PR allows the backend disable the "Create Functions" section in the frontend by making the pluginsDisabled ``WEBSERVER_FUNCTIONS`` flag truthy.
- related to https://github.com/ITISFoundation/private-issues/issues/14

🎨 [Frontend] Enable/disable Create Functions

---

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/io.py
packages/dask-task-models-library/tests/container_tasks/test_io.py
scripts/maintenance/computational-clusters/pyproject.toml
scripts/maintenance/computational-clusters/uv.lock
services/director-v2/src/simcore_service_director_v2/core/errors.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_dask.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_scheduler_dask.py

@wvangeit discovered an issue where unexpected key-values in `outputs.json` would fail a run.
This PR fixes it and also improves on the error shown in the UI logs.
This PR also should fix the unreliability in on-demande computational clusters.
* Updated `from_task_output` in `io.py` to filter out any entries in the task output data that are not defined in the schema. This ensures only valid keys are retained.
* Added a new test `test_create_task_output_from_task_ignores_additional_entries` to verify that extra keys in task output files are ignored when creating task output data.
* Modified `get_errors` in `errors.py` to improve error message formatting by directly using the exception's string representation.
* Added handling for `UnboundPortError` in `parse_output_data` in `dask.py`, …

🐛Dask-sidecar: ignore unexpected key-value pairs in outputs json data + unreliable computational runs in on-demand clusters

---

packages/models-library/src/models_library/api_schemas_catalog/services.py
packages/pytest-simcore/src/pytest_simcore/helpers/catalog_rpc_server.py
packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/catalog/services.py
services/api-server/docs/api-server.drawio.svg
services/api-server/src/simcore_service_api_server/_service_solvers.py
services/api-server/src/simcore_service_api_server/api/routes/solvers.py
services/api-server/src/simcore_service_api_server/models/schemas/solvers.py
services/api-server/src/simcore_service_api_server/services_rpc/catalog.py
services/api-server/tests/unit/api_solvers/test_api_routers_solvers.py
services/api-server/tests/unit/conftest.py
services/catalog/src/simcore_service_catalog/api/rpc/_services.py
services/catalog/src/simcore_service_catalog/repository/_services_sql.py
services/catalog/src/simcore_service_catalog/repository/services.py
services/catalog/src/simcore_service_catalog/service/catalog_services.py
services/catalog/tests/unit/with_dbs/test_api_rpc.py
services/catalog/tests/unit/with_dbs/test_repositories.py
services/catalog/tests/unit/with_dbs/test_service_catalog_services.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml

This PR implements the public-api `GET /solvers/page` route to `List` **all** items of the `Solver`s collection (paginated) with query filters by attribute `solver_id` and `version_display` patterns
Examples
```
GET /solvers/page # gives you first page of solvers
GET /solvers/page?solver_id=*isolve*  # gives you all isolve flavours and versions
GET /solvers/page?solver_id=*isolve*&version_display=1.0.*  # gives you all isolve flavours on version 1.0.*
```
- 
- resolves #7692
- `api-server` 
- tests from rest-api to rpc-mocked backend
- `catalog`:
- `test_api_rpc.py`: tests catalog's rpc_client end-to-end
- `test_repositories.py`: tests repo-layer to end
- `tests_service_catalog_service.py`: tests service-layer to end
- Manual exploratory test using api-server swagger site
None

🎨 `api-server`: Add GET /solvers/page Public API Route with Pagination and Filter Support

---

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/rpc/_disk_usage.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/system_monitor/_disk_usage.py
services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/system_monitor/_setup.py
services/dynamic-sidecar/tests/unit/test_modules_notifier.py

To help with system debugging, when dynamic-sidecar starts it will print the available disk space, before it does any operation which requires disk space.

🎨 dynamic-sidecar prints disk usage on boot

---

services/static-webserver/client/source/class/osparc/jobs/ActivityCenterWindow.js
services/static-webserver/client/source/class/osparc/jobs/ActivityOverview.js
services/static-webserver/client/source/class/osparc/jobs/RunsTable.js
services/static-webserver/client/source/class/osparc/jobs/RunsTableModel.js
services/static-webserver/client/source/class/osparc/jobs/SubRunsBrowser.js
services/static-webserver/client/source/class/osparc/jobs/SubRunsTable.js
services/static-webserver/client/source/class/osparc/jobs/SubRunsTableModel.js
services/static-webserver/client/source/class/osparc/store/Jobs.js

This PR changes the UI/UX of a project's Activity Overview and it also allows sim4life-like project's tasks work.
- related to https://github.com/ITISFoundation/private-issues/issues/28

🎨 [Frontend] Fetch tasks from the given projectUuid

---

.github/copilot-instructions.md
packages/postgres-database/src/simcore_postgres_database/migration/versions/278daef7e99d_remove_whole_row_in_payload.py
packages/postgres-database/src/simcore_postgres_database/models/comp_tasks.py
packages/postgres-database/tests/test_comp_tasks.py
packages/pytest-simcore/src/pytest_simcore/db_entries_mocks.py
services/web/server/src/simcore_service_webserver/db_listener/_db_comp_tasks_listening_task.py
services/web/server/src/simcore_service_webserver/db_listener/_models.py
services/web/server/src/simcore_service_webserver/db_listener/plugin.py
services/web/server/tests/unit/with_dbs/04/notifications/test_notifications__db_comp_tasks_listening_task.py

This PR fixes the issue described in https://github.com/ITISFoundation/osparc-simcore/issues/7722. 
The _comp_tasks_ table uses an event trigger and the webservers _listens_ to that event to transmit changes in _comp_tasks_ _outputs_, _state_. This includes payload generation for table updates and ensures proper handling of `outputs` and `state` fields changes. The procedure used to transmit the whole row as payload through _pg_notify_. This is limited to 8000 bytes.
This PR changes the procedure to **not** pass the row in the payload anymore due to that limitation.
Therefore changes are now in the listener code of the webserver, such that an additional query to _comp_tasks_ is necessary in order to transmit the notifications to the next nodes/frontend.
- see the following up case: …

🐛Computational services with large amount of inputs/outputs fail to start (🗃️)

---

packages/service-library/src/servicelib/file_utils.py
packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py
packages/simcore-sdk/tests/integration/conftest.py
packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py
packages/simcore-sdk/tests/integration/test_node_ports_v2_nodeports2.py

* Increased the default `chunk_size` in the `create_sha256_checksum` function from `CHUNK_4KB` to `CHUNK_8MB` to improve performance when processing large files. (`packages/service-library/src/servicelib/file_utils.py`, [packages/service-library/src/servicelib/file_utils.pyL48-R51](diffhunk://#diff-049bd7e6a1b2b9badbc0c35c6fbc92ee9599c1b1ff0b0a999cc4ebb8f957749bL48-R51))

🎨 Maintenance: change default chunk size to compute checksums to 8MiB instead of 5KB

---

tests/performance/common/base_user.py

locust FastHttpUser does not like zstd compression that our production deployment are returning.

🐛 Fix: Add default headers for authenticated HTTP methods

---

api/specs/web-server/_projects_states.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/director_v2/_client_base.py
services/web/server/src/simcore_service_webserver/director_v2/_controller/_rest_exceptions.py
services/web/server/src/simcore_service_webserver/director_v2/_director_v2_service.py
services/web/server/src/simcore_service_webserver/director_v2/director_v2_service.py
services/web/server/src/simcore_service_webserver/director_v2/exceptions.py
services/web/server/src/simcore_service_webserver/exception_handling/__init__.py
services/web/server/src/simcore_service_webserver/exception_handling/_factory.py
services/web/server/src/simcore_service_webserver/projects/_controller/projects_states_rest.py

Avoids extra long error/debug messages when the director. This was caused because this error was not correctly handled in the web-server.  This PR removes custom handler for `DirectorServiceError` and updates to error mapping to 503 that will auto generate a `support ID` for the front-end and log a detailed troubleshooting to analyze the issue.
- fixes #7738 
- some changes needed in the front-end as well.  Will follow up in https://github.com/ITISFoundation/osparc-simcore/issues/7762

🐛 Fixes extra long error/debug message in the front-end

---

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/errors.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/task_shared_volume.py
services/dask-sidecar/src/simcore_service_dask_sidecar/utils/files.py
services/dask-sidecar/tests/unit/test_computational_sidecar_tasks.py

As part of the issues found by @wvangeit where a service would define file_to_key mapping for input and pass in a zip file.
Having a service input port defining a `file_to_key` mapping and at the same time passing a `zip` file at runtime produces confusing results:
1. the dask-sidecar downloads the input file which is a zip file,
2. renames the zip file to the key map (here `values.json`)
3. then since it's a zip file unzips the file which happened to also contain a `values.json` file which overrides the original `values.json` zip file
4. the dask-sidecar then removes the original zip file, which means deletes the `values.json` file
--> the jsonifier service would actually run with an empty input data and will not complain as it can run with no inputs.
This PR improves the dask-sidecar to …

🎨Computational backend: Fail fast in case of malformed input syntax and improve unzipping

---

packages/service-library/src/servicelib/aiohttp/rest_middlewares.py
packages/service-library/src/servicelib/aiohttp/rest_responses.py
packages/service-library/tests/aiohttp/test_rest_responses.py
services/web/server/src/simcore_service_webserver/director_v2/_controller/_rest_exceptions.py

This pull request introduces improvements to error handling and response generation in the `servicelib.aiohttp` package. The changes focus on enhancing the robustness and clarity of HTTP error responses, simplifying the codebase, and updating tests to reflect the new functionality.
* [`packages/service-library/src/servicelib/aiohttp/rest_middlewares.py`](diffhunk://#diff-ab323d5214684fb5d6a4db66c41cb80514b21dfca664abc79e51ec70e588aeefR91-R92): Added logic to truncate and sanitize HTTP error reasons using `safe_status_message` to prevent issues like excessively long status lines or multiline reasons. [[1]](diffhunk://#diff-ab323d5214684fb5d6a4db66c41cb80514b21dfca664abc79e51ec70e588aeefR91-R92) [[2]](diffhunk://#diff-ab323d5214684fb5d6a4db66c41cb80514b21dfca664abc79e51ec70e588aeefR112-R114) …

🎨♻️ Enhances web-server's error middle-ware for safe status-line and refactors aiohttp response helpers

---

services/web/server/src/simcore_service_webserver/catalog/_catalog_rest_client_service.py
services/web/server/src/simcore_service_webserver/catalog/_constants.py
services/web/server/src/simcore_service_webserver/catalog/_controller_rest_exceptions.py
services/web/server/src/simcore_service_webserver/catalog/errors.py

This PR refines the error handling logic using `catalog._cotnroller_rest_excetpions._handler_catalog_client_errors` to **log detail troubleshooting information** for diagnostics while keeping (for now), the current behavior:
* If the catalog service responds with a `404`, the webserver REST API returns a `404`.
* If the catalog service responds with **any other error**, it is translated into a `503` by the webserver REST API
IMO the current logic is overly coarse—many `4XX` errors may indicate client-side issues rather than catalog unavailability, but we will wait until we see the errors to enhance that.
- Improves error mapping to better diagnose the issue reported in #7814

 🎨 Improves webserver's  exception handling to enhance diagnoses of catalog's client errors 

---

services/docker-compose.yml

adds a docker healthcheck for simcore traefik container --> to ensure that the container is restarted in case it hangs.
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/7773

✨Add docker healthcheck of Simcore Traefik container

---

services/static-webserver/client/source/class/osparc/data/model/Study.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js

This PR fixes a bug in the front-end regarding the study patch handler.
The frontend keeps a json object of the latest state of the Study, and it relies on this object to know whether sometinhg changed. **After** patching a study or node, the frontend assumes that that is the latest state of the study in the backend. This assumption is not true: if the study changes during the PATCHing process there is the desynchronization between backend and frontend.
This is more reproducible in AWS, and it's even more noticeable when using the file picker, specially, when the file upload completion happens: the fronted patched the state of the file picker at progress 99%, and it is patching this state, the file uploading process gets completed (100%), when the patch is finished, the frontend think …

🐛 [Frontend] Fix: un-synced frontend's and backend's study objects

---

services/static-webserver/client/source/class/osparc/study/Utils.js

reported by @JavierGOrdonnez 
When starting a project from the apps tab, they ``ui`` ``mode`` always gets initialized as ``standalone``. If the started app is a computational service, it should be initialized as ``pipeline``.

🐛 [Frontend] Fix: init ui-mode

---

.vscode/settings.template.json
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/utils/files.py
services/dask-sidecar/tests/unit/test_utils_files.py

in a bid to find the culprit of https://github.com/ITISFoundation/osparc-issues/issues/1889 this PR adds a debug log of the file contents prior to uploading it to S3.
- relates to https://github.com/ITISFoundation/osparc-issues/issues/1889

⚗️Dask-sidecar: print file contents or partial contents

---

.github/workflows/ci-testing-deploy.yml

- Extend timeout limit for the webserver 02 unittest workflow to avoid timeouts in CI

🎨 Increase timeout for webserver 02 unittest workflow

---

services/static-webserver/client/source/class/osparc/desktop/preferences/window/ShowAPIKey.js
services/static-webserver/client/source/class/osparc/product/Utils.js

requested by @Konohana0608 
The page is not exposed in ``tis``, ``tiplite`` and ``s4llite``. This PR exposes it for testers regardless the product.
Bonus:
- closes https://github.com/ITISFoundation/osparc-simcore/issues/7599

🎨 [Frontend] Expose Tokens page to testers

---

.vscode/settings.template.json
services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py
services/dask-sidecar/src/simcore_service_dask_sidecar/utils/files.py
services/dask-sidecar/tests/unit/test_utils_files.py

This reverts commit 7cbacf2b0ba94628c1e2719f07d2f473ee885ae2.
- closes https://github.com/ITISFoundation/osparc-issues/issues/1900

Revert "⚗️Dask-sidecar: print file contents or partial contents (#7834)"

---

services/static-webserver/client/source/class/osparc/dashboard/NewPlusMenu.js

🐛 [Frontend] Fix: Tutorials tab link

---

services/director-v2/src/simcore_service_director_v2/modules/dask_client.py

- This PR increases the timeout when retrieving results from the computational backend from 5 to 35 seconds.

♻️Computational backend: increase timeout to get results to 35 seconds

---

services/web/server/src/simcore_service_webserver/catalog/_catalog_rest_client_service.py
services/web/server/src/simcore_service_webserver/catalog/_controller_rest.py
services/web/server/src/simcore_service_webserver/catalog/_controller_rest_exceptions.py
services/web/server/src/simcore_service_webserver/catalog/_models.py
services/web/server/src/simcore_service_webserver/catalog/catalog_service.py
services/web/server/src/simcore_service_webserver/projects/_controller/_rest_exceptions.py
services/web/server/src/simcore_service_webserver/projects/_controller/projects_rest.py
services/web/server/src/simcore_service_webserver/projects/_crud_api_read.py
services/web/server/src/simcore_service_webserver/projects/_projects_repository_legacy_utils.py
services/web/server/src/simcore_service_webserver/projects/utils.py
services/web/server/tests/unit/with_dbs/01/test_catalog_rest_client.py
services/web/server/tests/unit/with_dbs/02/conftest.py
services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__patch.py
services/web/server/tests/unit/with_dbs/02/test_projects_groups_handlers.py
services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handlers__patch.py
services/web/server/tests/unit/with_dbs/04/workspaces/conftest.py

**Mitigates performance bottleneck when retrieving project(s)**
Calls to `get_services_for_user_in_product` were causing significant delays, occasionally leading to timeouts when calling the following endpoints:
* ♻️ `GET /projects/{project_id}`
* ♻️ `GET /projects`
The root cause was a legacy call to a deprecated `catalog REST` endpoint that lists **all** services for a given user and product. This was originally used to determine whether the services associated with a project were accessible. However, more efficient alternatives are now available (e.g. `catalog_service.batch_get_my_services`), though the code was never updated.
As an interim solution, this PR introduces:
* A TTL cache keyed by (user, product) to reduce repeated calls.
* A smaller data footprint in the cached response to …

🐛 Mitigates "Projects not being listed on osparc-staging.io"

---

services/static-webserver/client/source/class/osparc/data/model/Study.js
services/static-webserver/client/source/class/osparc/data/model/Workbench.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js

reported by @sanderegg , thanks!
Similar issue as in https://github.com/ITISFoundation/osparc-simcore/pull/7828, but this time in the node level
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7863

🐛 [Frontend] Incomplete node data in the backend

---

services/static-webserver/client/source/class/osparc/data/model/NodeProgressSequence.js
services/static-webserver/client/source/class/osparc/ui/message/Loading.js

In small screens the loading page might get cropped, this PR changes its layout to improve the fitting.
Before:
After:

🎨 [Frontend] Enh: Better fit loading page

---

services/static-webserver/client/source/class/osparc/FlashMessenger.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7762

🐛 [Frontend] Fix: show support id when pipeline fails to start

---

packages/models-library/src/models_library/rest_error.py
services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml
services/web/server/src/simcore_service_webserver/director_v2/_controller/_rest_exceptions.py

Fixes wrong message comgin from directorv2
- reported by @GitHK

🐛 Fixes error message displayed to user coming from director-v2 failure

---

services/static-webserver/client/source/class/osparc/store/Support.js
services/static-webserver/client/source/class/osparc/utils/Utils.js

If the product is configured to request an account via the form, the "Request account" flash message shown to the guest users will show a link to the request-account form instead of the send-us-an-email approach.
When request account goes through the form:
When the product config expects an email:
- closes https://github.com/ITISFoundation/osparc-simcore/issues/7713

🎨 [Frontend] Redirect anonymous users to the "account request form" instead of asking them to send an email

---

services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/desktop/MainPage.js
services/static-webserver/client/source/class/osparc/study/CreateFunction.js

As discussed, this PR hides the template that is used to register a function and adds some ``project_metadata`` to it.
- closes https://github.com/ITISFoundation/osparc-issues/issues/1896

🎨 [Frontend] Hide template used to register function

---

services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/form/renderer/PropForm.js

Only ``data`` type ports were hideable in the node input ports view, this PR enhances this feature by supporting any type.
- Enable/Disable sections also for templates

🎨 [Frontend] Enh: Visible input ports

---

tests/e2e/jest.config.js
tests/e2e/tests/startupCalls.js

In Jest befereAll functions have a timeout that is set to 40s but we wait 60s in the function. so the timeout is set to 2 minutes.

🐛CI: Fix timeout value in CI e2e system test 

---

packages/models-library/src/models_library/functions.py
services/web/server/src/simcore_service_webserver/functions/_controller/_functions_rpc.py
services/web/server/src/simcore_service_webserver/functions/_functions_repository.py
services/web/server/tests/unit/with_dbs/04/functions_rpc/conftest.py
services/web/server/tests/unit/with_dbs/04/functions_rpc/test_function_job_collections_controller_rpc.py
services/web/server/tests/unit/with_dbs/04/functions_rpc/test_function_jobs_controller_rpc.py
services/web/server/tests/unit/with_dbs/04/functions_rpc/test_functions_controller_rpc.py

As spotted with @bisgaard-itis we discovered that running under load some functions would timeout while trying to acquire a DB connection. This should improve that situation.
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1913
- fixes https://github.com/ITISFoundation/osparc-issues/issues/1920

🎨 Reduce the number of acquisition/release of DB connection inside function repository

---

packages/service-library/src/servicelib/fastapi/long_running_tasks/_client.py
packages/service-library/src/servicelib/fastapi/long_running_tasks/_context_manager.py
packages/service-library/src/servicelib/long_running_tasks/http_endpoint_responses.py
packages/service-library/tests/fastapi/long_running_tasks/test_long_running_tasks_context_manager.py
services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py
services/dynamic-sidecar/tests/unit/test_api_rest_containers_long_running_tasks.py
services/dynamic-sidecar/tests/unit/test_api_rest_workflow_service_metrics.py

Fixed a corner case where the `director-v2` could not remove a sidecar due to an unhandled error raised by the long_running_tasks client. Task `attempt_pod_removal_and_data_saving` is allowed to raise only under certain situations. Added exception handling for unforeseen errors which addresses the below linked issue.
- closes https://github.com/ITISFoundation/osparc-simcore/pull/7903 in favour of this PR
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7905

🐛 Fixed director-v2 getting stuck when removing service

---

services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
services/static-webserver/client/source/class/osparc/store/Store.js
services/static-webserver/client/source/class/osparc/study/BillingSettings.js
services/static-webserver/client/source/class/osparc/study/Utils.js

When opening the project card, the frontend was loosing the ``IN_DEBT`` information of it, not letting the users pay the debt and keeping the project embargoed until the fix was manually made in the DB. This PR fixes that situation by tracking the debts in the Store.
- Found another way to get the project_in_debt response. So far it was only traced in the :open study call. In the animation, the information is received when trying to switch wallet. ~~@matusdrobuliak66 is there any other call where you attach the project_in_debt info?~~ All good
Buggy:
Fixed:

🐛 [Frontend] Fix in_debt tracking

---

services/static-webserver/client/source/class/osparc/study/CreateFunction.js

This PR makes the default values used for registering a function editable. It also adds all the input values to the ``defaultValues``. 
- closes https://github.com/ITISFoundation/osparc-issues/issues/1931

🎨 [Frontend] Create Functions: Make default input values editable

---

services/static-webserver/client/source/class/osparc/conversation/AddMessage.js
services/static-webserver/client/source/class/osparc/conversation/Conversation.js
services/static-webserver/client/source/class/osparc/conversation/MessageUI.js
services/static-webserver/client/source/class/osparc/data/Resources.js
services/static-webserver/client/source/class/osparc/study/Conversations.js

- related to https://github.com/ITISFoundation/private-issues/issues/51

✨ [Frontend] Conversations: Edit and Delete messages

---

services/web/server/src/simcore_service_webserver/conversations/_conversation_message_service.py
services/web/server/src/simcore_service_webserver/conversations/_socketio.py
services/web/server/src/simcore_service_webserver/projects/_conversations_service.py

This PR fixes the method called to send notifications for conversation messages.
- no issues, but it makes @odeimaiz happy

🐛 Send conversation message notifications to users

---

.github/prompts/update-user-messages.prompt.md
packages/service-library/src/servicelib/aiohttp/rest_middlewares.py
services/web/server/src/simcore_service_webserver/catalog/_constants.py
services/web/server/src/simcore_service_webserver/constants.py
services/web/server/src/simcore_service_webserver/director_v2/_controller/_rest_exceptions.py
services/web/server/src/simcore_service_webserver/folders/_common/exceptions_handlers.py
services/web/server/src/simcore_service_webserver/groups/_common/exceptions_handlers.py
services/web/server/src/simcore_service_webserver/invitations/errors.py
services/web/server/src/simcore_service_webserver/licenses/_common/exceptions_handlers.py
services/web/server/src/simcore_service_webserver/login/_constants.py
services/web/server/src/simcore_service_webserver/payments/_onetime_api.py
services/web/server/src/simcore_service_webserver/products/_controller/rest_exceptions.py
services/web/server/src/simcore_service_webserver/projects/_controller/_rest_exceptions.py
services/web/server/src/simcore_service_webserver/resource_usage/_constants.py
services/web/server/src/simcore_service_webserver/security/_constants.py
services/web/server/src/simcore_service_webserver/studies_dispatcher/_constants.py
services/web/server/src/simcore_service_webserver/tags/_rest.py
services/web/server/src/simcore_service_webserver/trash/_rest.py
services/web/server/src/simcore_service_webserver/users/_users_rest.py
services/web/server/src/simcore_service_webserver/utils_rate_limiting.py
services/web/server/src/simcore_service_webserver/wallets/_constants.py
services/web/server/src/simcore_service_webserver/workspaces/_common/exceptions_handlers.py
services/web/server/tests/unit/with_dbs/03/login/test_login_twofa.py

Introduces a new batch of user-facing messages, generated with the help of AI prompts and manually reviewed for accuracy.
**Workflow**
1. Annotate user-facing messages in the web server using the `user_message` function.
2. Generate suggestions via the AI prompt.
3. Manually review and correct outputs as needed.
4. Iteratively refine the prompt to prevent recurrence of identified issues.
It is important to audit the outputs
- **please** check randomly some message and assess whether they comply with [docs/user-messages-guidelines.md](https://github.com/itisfoundation/osparc-simcore/blob/431ac36c961cd5f169d5fb03c7f6e4d4856584cf/docs/user-messages-guidelines.md)
None

🎨📝 web-api: New batch of improved user-facing messages

---

services/docker-compose.yml
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/payments/_socketio.py
services/web/server/src/simcore_service_webserver/projects/_projects_service.py
services/web/server/src/simcore_service_webserver/socketio/messages.py
services/web/server/tests/integration/02/notifications/test_rabbitmq_consumers.py

Since https://github.com/ITISFoundation/osparc-simcore/pull/7839 (>2 weeks ago), the flow of logs/progresses was broken, as messages sent via SocketIO were not sent through the socketIO RabbitMQ Pub/Sub system but purposely ignoring the queuing since with a sticky connection it was unnecessary.
A second identified problem is that subscription/unsubscription to the project logs/progress RabbitMQ queue needs to be sticky as otherwise the webserver replica will not properly unsubscribe from a topic.
This PR fixes this issue.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/7960

🐛Sticky connection: Ensure emitted socketio messages for logs, progress, status updates and payments are not lost

---

packages/celery-library/src/celery_library/signals.py
packages/celery-library/tests/conftest.py
packages/service-library/src/servicelib/celery/app_server.py
packages/service-library/src/servicelib/fastapi/celery/app_server.py
tests/performance/locustfiles/deployment_max_rps_single_endpoint.py

This PR removes timeouts on startup so that App Server initialisation can complete before starting the Celery worker itself.
Compared to the previous version, all slow initialisation procedures (e.g. DB migration) can complete... while the `worker_init` waits for the `startup_completed_event` to finalize the execution.
Clean shutdown:
- fixes #7957
- fixes #7968

🐛 Use context manager for app server lifecycle in Celery workers

---

services/static-webserver/client/source/class/osparc/conversation/AddMessage.js
services/static-webserver/client/source/class/osparc/conversation/Conversation.js
services/static-webserver/client/source/class/osparc/conversation/MessageUI.js
services/static-webserver/client/source/class/osparc/conversation/NotificationUI.js
services/static-webserver/client/source/class/osparc/study/Conversations.js

This PR makes the Conversations listen the WebSocket events, reducing the GET messages calls and giving a better UX.
- follows https://github.com/ITISFoundation/osparc-simcore/pull/7941

✨ [Frontend] Conversation Messages: Listen to WebSocket

---

services/static-webserver/client/source/class/osparc/store/Store.js

Reported by @bisgaard-itis ft. @matusdrobuliak66 
This PR fixes a ~~hacky~~ situation where the wallets are created manually in the DB.
If the user gets access to two wallets without having a preferred wallet, this PR improves the logic by traying to choose the personal one.

🎨 [Frontend] Enh: Preferred Wallet

---

packages/models-library/src/models_library/conversations.py
services/web/server/src/simcore_service_webserver/conversations/_conversation_message_service.py
services/web/server/src/simcore_service_webserver/conversations/_conversation_service.py
services/web/server/src/simcore_service_webserver/conversations/_socketio.py
services/web/server/src/simcore_service_webserver/projects/_conversations_service.py
services/web/server/tests/unit/with_dbs/02/test_projects_conversations_handlers.py

This PR introduces new Socket.IO events sent whenever **conversations** are created, updated or deleted (See this other one for **conversation messages**: #7941).
- fixes https://github.com/ITISFoundation/private-issues/issues/215
```
pytest -vv --pdb tests/unit/with_dbs/02/test_projects_conversations_handlers.py
```
Nothing to do

🎨 Send Socket.IO events whenever conversations are created, updated or deleted

---

packages/service-library/src/servicelib/aiohttp/application_setup.py
packages/service-library/tests/aiohttp/test_application_setup.py
services/web/server/src/simcore_service_webserver/login/plugin.py

The `app_module_setup` decorator is typically used in web applications (like those built with `aiohttp`) to define *setup functions* that initialize parts of the application — e.g., routes, background tasks, signals, middleware, etc. These setup functions **must be idempotent**: they should only run once, even if they are called multiple times (e.g., by different parts of the app or due to reuse of shared components).
* Marks a function as a **module setup** function.
* Ensures it only runs **once per app** instance.
* Used to **register or configure** aspects of the application.
* May allow toggle/setup through config (e.g., optional plugins).
Refactoring `app_module_setup` into smaller decorators makes it:
* **Composable**: Combine different setup constraints or conditions.
* …

♻️ Refactor `app_module_setup` into Composable Decorators to Enable Modular and Idempotent App Setups

---

packages/service-library/src/servicelib/background_task.py
packages/service-library/src/servicelib/background_task_utils.py
services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_api_keys.py
services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_core.py
services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_trash.py
services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_users.py
services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_utils.py
services/web/server/src/simcore_service_webserver/garbage_collector/plugin.py
services/web/server/src/simcore_service_webserver/garbage_collector/settings.py
services/web/server/tests/integration/01/test_garbage_collection.py
services/web/server/tests/unit/isolated/test_garbage_collector_core.py

This PR unifies how the peridoic background tasks are setup in the garbage-collector domain of the web-server
- create a safe function template for the `cleanup_ctx` event in `tasks_utils.py`
- All background tasks within the garbage-collector are executed using exclusive periodic decorators ( `servicelib.baground_tasks.exclusive_periodic` )
Possible follow-ups (to discuss with @sanderegg ) in order to resolve https://github.com/ITISFoundation/osparc-simcore/issues/7931
- split "core" task into independent background tasks?
- increase test coverage
- refactor tests
- refactor garbage-collector domain skeleton
- add a gc stand-alone boot app
- resolves #7961 
- part of https://github.com/ITISFoundation/osparc-simcore/issues/7931
These are the (few) tests we have for the GC
- …

♻️ web-server: Upgrade GC periodic tasks to new `servicelib.background_task`

---

packages/celery-library/tests/conftest.py

This PR fixes hanging tests due to a missing initialization of AppServer mock in Celery tests.
The main issue here is that CI didn't detect the problem, since a cancelled test gave Unit Test passing.
```
cd packages/celery-library
make tests
```

🐛 Fix app server mock in `celery-library`

---

services/static-webserver/client/source/class/osparc/dashboard/AppBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js
services/static-webserver/client/source/class/osparc/dashboard/TutorialBrowser.js

This PR improves the UX of the "Starting osparc" message.
- We now say first "Starting osparc" while the resources that need to be fetched before the dashboard resources are fetched.
- Then each tab will say "Loading its {$resource}". 
- If there are no {$resources} found a message will be displayed.
- The loading page is now removed when the cards are renderer (avoiding the potential empty list that was shown while the backend resources were renderer as cards).

🎨 [Frontend] UX Enh: Starting osparc

---

packages/models-library/src/models_library/rabbitmq_messages.py
services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_manager.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_publisher.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py
services/director-v2/src/simcore_service_director_v2/utils/rabbitmq.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_api_route_computations.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_scheduler_dask.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/notifications/project_logs.py

While testing following issues were identified:
- in production, multiple computational pipelines of the same project were found (this should never happen),
- this most likely made the computational scheduler manager stop scheduling
- cancellation of computational pipelines showed an issue where changing some database rows took longer (maybe due to asyncpg migration), and a design issue where a DB row was changed _after_ requesting scheduling to RabbitMQ was effectively commited to the DB after the scheduling was done, thus generating an incorrect DB row. This was inversed, which should make cancelling a pipeline much more reactive.
- the pipeline state that is surfaced to the frontend was generated from the `comp_tasks` table due to the historical way we transmitted events from that …

🐛Improvements on pipeline cancellation and ensure pipeline state is consistent

---

.github/actions/download-load-docker-images/action.yml
.github/actions/setup-simcore-env/action.yml
.github/workflows/_reusable-build-images.yml
.github/workflows/ci-testing-deploy.yml
mypy.ini
scripts/common.Makefile

Running the CI and looking at the workflow file is not a nice experience. This PR is a first step towards rationalizing the CI runs.
This PR modularizes towards simpler CI workflow file with a longer term goal to have maybe faster CI feedback. Ideas currently around are:
- separate workflows for unit tests/integration tests/system tests that could have dependencies
- draft PRs could for example only run unit tests and non draft also the integration/system tests to have faster feedback
- other ideas??
This PR should not have any effect for now in terms of functionality but more in terms of sustainability

♻️CI: modularizing CI workflow towards faster feedback

---

.pre-commit-config.yaml
Makefile
packages/postgres-database/docker/Dockerfile
packages/postgres-database/scripts/erd/Dockerfile
packages/service-integration/Dockerfile
requirements/tools/Dockerfile
scripts/erd/Dockerfile
scripts/maintenance/migrate_project/Dockerfile
scripts/openapi/oas_resolver/Dockerfile
scripts/pydeps-docker/Dockerfile
services/agent/Dockerfile
services/api-server/Dockerfile
services/autoscaling/Dockerfile
services/catalog/Dockerfile
services/clusters-keeper/Dockerfile
services/dask-sidecar/Dockerfile
services/datcore-adapter/Dockerfile
services/director-v2/Dockerfile
services/director/Dockerfile
services/dynamic-scheduler/Dockerfile
services/dynamic-sidecar/Dockerfile
services/efs-guardian/Dockerfile
services/invitations/Dockerfile
services/migration/Dockerfile
services/notifications/Dockerfile
services/payments/Dockerfile
services/resource-usage-tracker/Dockerfile
services/storage/Dockerfile
services/web/Dockerfile

This pull request includes updates to dependency versions and Dockerfile configurations across multiple services and tools. The most important changes involve upgrading the `UV_VERSION` argument in Dockerfiles and updating pre-commit hooks for code formatting and sorting.
* [`.pre-commit-config.yaml`](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L25-R25): Updated `pyupgrade` to version `v3.20.0` and `isort` to version `6.0.1`. These are used for code upgrades and import sorting, respectively. [[1]](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L25-R25) [[2]](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L39-R39)
* Updated `UV_VERSION` from `0.6` to `0.7` across multiple Dockerfiles, …

⬆️Upgrade to UV 0.7, pre-commit tools and dump installation of pip/setuptools/wheels

---

services/efs-guardian/requirements/_base.txt
services/efs-guardian/requirements/_test.txt
services/efs-guardian/requirements/_tools.txt

- #packages before ~ 132
- #packages after ~ 132
|   1 | aio-pika                  | 9.4.3           | 9.5.5      | *minor*    | 1 | efs-guardian⬆️ |
|   2 | aioboto3                  | 14.3.0          | 15.0.0     | **MAJOR**  | 1 | efs-guardian⬆️ |
|   3 | aiobotocore               | 2.22.0          | 2.23.0     | *minor*    | 1 | efs-guardian⬆️ |
|   4 | aiodocker                 | 0.23.0          | 0.24.0     | *minor*    | 2 | efs-guardian⬆️🧪 |
|   5 | aiohttp                   | 3.12.12         | 3.12.13    |            | 2 | efs-guardian⬆️🧪 |
|   6 | aiosignal                 | 1.3.1           | 1.3.2      |            | 2 | efs-guardian⬆️🧪 |
|   7 | alembic                   | 1.13.3 …

⬆️ upgrade efs service requirements

---

tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/tip/conftest.py

since https://github.com/ITISFoundation/osparc-simcore/pull/7996 the default state on open is `NOT_STARTED`
- https://github.com/ITISFoundation/osparc-simcore/pull/7996

🐛E2E: check for NOT_STARTED state instead of UNKNOWN

---

services/static-webserver/client/source/class/osparc/desktop/credits/CreditsSummary.js
services/static-webserver/client/source/class/osparc/desktop/credits/DateFilters.js
services/web/server/src/simcore_service_webserver/projects/_conversations_service.py

- It was misleading to say ``Today`` while we meant ``Last 24h``.
- A new time range filter was added to the Usage table: ``Last 24h``, which is the default one.
- closes https://github.com/ITISFoundation/private-issues/issues/226

🎨 [Frontend] UX: Usage in the last 24h

---

services/static-webserver/client/source/class/osparc/store/Services.js

The frontend wasn't caching Service's Pricing Plans correctly. This PR fixes it.
Buggy:
Fixed:

🐛 [Frontend] Fix: Service's Pricing Plans

---

packages/pytest-simcore/src/pytest_simcore/db_entries_mocks.py
services/director-v2/tests/conftest.py
services/director-v2/tests/integration/01/test_computation_api.py
services/director-v2/tests/integration/02/test_dynamic_services_routes.py
services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py
services/director-v2/tests/integration/02/test_mixed_dynamic_sidecar_and_legacy_project.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_api_route_computations.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_api_route_computations_tasks.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_api_rpc_computations.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_db_repositories_comp_runs.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_manager.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_scheduler_dask.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_worker.py
services/director-v2/tests/unit/with_dbs/conftest.py
services/director-v2/tests/unit/with_dbs/test_cli.py
services/director-v2/tests/unit/with_dbs/test_modules_db_repositories_projects.py
services/director-v2/tests/unit/with_dbs/test_utils_rabbitmq.py
services/web/server/tests/data/workbench_2connected_jupyterlabs.json
services/web/server/tests/unit/with_dbs/04/notifications/test_notifications__db_comp_tasks_listening_task.py

These changes are originaly from https://github.com/ITISFoundation/osparc-simcore/pull/8016 but were transfer to reduce the code changes needed for doing a hotfix.
- `test_notifications__db_comp_tasks_listening_task.py` brings a more robust test of the DB listener with the whole app and DB backend
- this brings in some required changes in some faker in pytest-simcore, and some necessary changes are needed in other services to accomodate

🎨Improve testing on DB listener

---

services/static-webserver/client/source/class/osparc/po/POCenter.js
services/static-webserver/client/source/class/osparc/po/UsersPending.js

- closes https://github.com/ITISFoundation/osparc-simcore/issues/8044

🎨 [Frontend] PO Center: Approval/Deny of account requests

---

services/static-webserver/client/source/class/osparc/filter/CollaboratorToggleButton.js
services/static-webserver/client/source/class/osparc/share/NewCollaboratorsManager.js

In the New Collaborators list, if there is any extra information available about the user (full name, email) or group (description), it will be shown in a tooltip on an info button.
- related to https://github.com/ITISFoundation/osparc-simcore/issues/8072

🎨 [Frontent] New Collaborators: Info button with tooltip

---

services/static-webserver/client/source/class/osparc/dashboard/CardBase.js
services/static-webserver/client/source/class/osparc/dashboard/ResourceDetails.js
services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js
services/static-webserver/client/source/class/osparc/file/FileLabelWithActions.js
services/static-webserver/client/source/class/osparc/share/NewCollaboratorsManager.js
services/static-webserver/client/source/class/osparc/widget/StudyDataManager.js

When the Data Browser is opened from a Project, the frontend can know whether the user has delete access on its content.
This PR will disable the Delete file option if the user doesn't have Delete rights on the project.

🎨 [Frontend] UX: Disable Delete button

---

services/catalog/src/simcore_service_catalog/clients/director.py
services/director/src/simcore_service_director/core/application.py

- ensures that director-v0 exception are enveloped such that the catalog can handle them

🐛Director-v0: ensure error are enveloped too

---

services/static-webserver/client/source/class/osparc/conversation/Conversation.js
services/static-webserver/client/source/class/osparc/data/model/Node.js
services/static-webserver/client/source/class/osparc/data/model/Study.js
services/static-webserver/client/source/class/osparc/data/model/StudyUI.js
services/static-webserver/client/source/class/osparc/data/model/Workbench.js
services/static-webserver/client/source/class/osparc/study/Conversations.js
services/static-webserver/client/source/class/osparc/workbench/Annotation.js
services/static-webserver/client/source/class/osparc/workbench/WorkbenchUI.js

Fixes:
- related to https://github.com/ITISFoundation/private-issues/issues/51

🐛 [Frontend] Conversations: fixes

---

packages/models-library/src/models_library/api_schemas_webserver/projects_nodes.py
packages/models-library/src/models_library/projects_access.py
packages/models-library/src/models_library/projects_state.py
packages/pytest-simcore/src/pytest_simcore/socketio_client.py
services/web/server/src/simcore_service_webserver/dynamic_scheduler/api.py
services/web/server/src/simcore_service_webserver/exporter/_handlers.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_disconnected.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_guests.py
services/web/server/src/simcore_service_webserver/projects/_controller/projects_slot.py
services/web/server/src/simcore_service_webserver/projects/_controller/projects_states_rest.py
services/web/server/src/simcore_service_webserver/projects/_crud_api_create.py
services/web/server/src/simcore_service_webserver/projects/_crud_api_delete.py
services/web/server/src/simcore_service_webserver/projects/_projects_service.py
services/web/server/src/simcore_service_webserver/projects/_projects_service_delete.py
services/web/server/src/simcore_service_webserver/resource_manager/models.py
services/web/server/src/simcore_service_webserver/resource_manager/registry.py
services/web/server/src/simcore_service_webserver/resource_manager/user_sessions.py
services/web/server/src/simcore_service_webserver/socketio/_observer.py
services/web/server/tests/integration/01/test_garbage_collection.py
services/web/server/tests/integration/02/notifications/test_rabbitmq_consumers.py
services/web/server/tests/unit/isolated/test_garbage_collector_core.py
services/web/server/tests/unit/with_dbs/01/test_resource_manager_user_sessions.py
services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__delete.py
services/web/server/tests/unit/with_dbs/02/test_projects_states_handlers.py
services/web/server/tests/unit/with_dbs/04/garbage_collector/conftest.py
services/web/server/tests/unit/with_dbs/04/garbage_collector/test_garbage_collector.py
services/web/server/tests/unit/with_dbs/04/garbage_collector/test_resource_manager.py
services/web/server/tests/unit/with_dbs/04/garbage_collector/test_resource_manager_user_sessions.py
tests/e2e-playwright/tests/sleepers/test_sleepers.py

- ensures a projectUpdateEvent is emitted on project close
- refactors the garbage-collector to also use the same code for closing projects instead of doing its own stuff
- sorry: a bit more refactoring
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/8151

🎨♻️Simultaneous access: emit project update event when a user closes a project or the GC closes it

---

services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/notifier/_notifier.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/service_tracker/__init__.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/service_tracker/_api.py
services/dynamic-scheduler/src/simcore_service_dynamic_scheduler/services/status_monitor/_deferred_get_status.py

Notify project_id instead of node_id when the status of a node changes. Allows for multiple users to view the node's status change.
- https://github.com/ITISFoundation/osparc-issues/issues/1647
- run locally, services open as usual

🎨 dynamic service status is now propagated to the project_id and not the node_id

---

services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/tests/integration/02/notifications/test_rabbitmq_consumers.py
services/web/server/tests/unit/isolated/notifications/test_rabbitmq_consumers.py

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/8178

🐛Ensure nodeProgress event is sent to project chat

---

services/static-webserver/client/source/class/osparc/Preferences.js
services/static-webserver/client/source/class/osparc/data/model/Node.js
services/static-webserver/client/source/class/osparc/store/Products.js
services/static-webserver/client/source/class/osparc/viewer/NodeViewer.js

This PR enhances the frontend to support removing links when Real Time Collaborating. Next step: add node.
A couple of changes that should help with the portal2end testing:
- Stop requesting the ``/products/current/ui`` for ``Guest`` users
- Stop patching preferences for ``Guest`` users
- Stop patching preferences that do not change
- related to https://github.com/ITISFoundation/osparc-issues/issues/1647

🎨 [Frontend] RTC: support removing links

---

services/web/server/src/simcore_service_webserver/projects/utils.py

`None.copy()` does not exist if the annotation field is empty. Using `deepcopy` which can deal with such edge cases

🐛 `null` annotations can now be copied

---

packages/service-library/src/servicelib/docker_utils.py

When the dynamic sidecar pulls docker images, sometimes it retries and there are no warnings in the logs. this fixes it.

🎨When a docker pulling is retried, output a warning

---

services/director/src/simcore_service_director/registry_proxy.py

https://github.com/ITISFoundation/osparc-simcore/pull/8240 was missing the addition of headers when calling /manifests endpoints. this materialized when accessing from local development stack to master.

🎨Director-v0: Pass headers on /manifests call to let the registry know we accept all manifest versions

---

packages/pytest-simcore/src/pytest_simcore/helpers/playwright.py
tests/e2e-playwright/tests/tip/test_ti_plan.py

the frontend behavior changed recently and the test was not accustomed to it.

E2E: Fix classic TIP test

---

packages/models-library/src/models_library/projects_state.py
packages/models-library/src/models_library/rabbitmq_messages.py
packages/pytest-simcore/src/pytest_simcore/docker_registry.py
services/director-v2/src/simcore_service_director_v2/utils/computations.py
services/director-v2/tests/integration/02/test_dynamic_services_routes.py
services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_exclusive_queue_consumers.py
services/web/server/src/simcore_service_webserver/projects/_nodes_repository.py
services/web/server/src/simcore_service_webserver/projects/_nodes_service.py
services/web/server/src/simcore_service_webserver/projects/_projects_service.py
services/web/server/tests/integration/01/test_computation.py
tests/public-api/conftest.py

- fixes https://github.com/ITISFoundation/osparc-issues/issues/1979

🎨Send NodeUpdate when computational pipeline completes

---

services/static-webserver/client/source/class/osparc/service/Utils.js
services/static-webserver/client/source/class/osparc/store/Services.js

This PR fixes the release date display on Service Cards by properly extracting release dates from service metadata's history.
- closes https://github.com/ITISFoundation/osparc-issues/issues/1982

🐛 [Frontend] Fix: Release date on Service Card

---

packages/aws-library/tests/test_ec2_client.py
services/autoscaling/src/simcore_service_autoscaling/modules/cluster_scaling/_auto_scaling_core.py
services/autoscaling/tests/unit/test_modules_cluster_scaling_dynamic.py

- requires https://github.com/ITISFoundation/osparc-simcore/pull/8210
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/8273

🐛Autoscaling: ensure unstarteable warm buffer are replaced by cold instances if available

---

services/director-v2/src/simcore_service_director_v2/utils/computations.py
services/director-v2/tests/unit/test_utils_computation.py

An issue was found while running metamodeling pipelines where a pipelines' tasks where in the following state:
the function that transforms separate computational tasks statuses in pipeline status would transform to UNKNOWN which was a missing use-case.
UNKNOWN is then saved as FAILED in the DB. Since we now access the result from outside the DV-2 this became an issue in function jobs caching.

🐛Director-v2 computational scheduler: tasks specific state combination was missing and returning UNKNOWN pipeline state

---

services/director-v2/src/simcore_service_director_v2/core/settings.py
services/director-v2/src/simcore_service_director_v2/models/comp_tasks.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_runs.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_core.py
services/director-v2/src/simcore_service_director_v2/utils/dask.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/conftest.py
services/director-v2/tests/unit/with_dbs/comp_scheduler/test_scheduler_dask.py

This PR changes the behavior of the dv-2 computational scheduler:
*BEFORE*:
- if the clusters-keeper is not reachable,
- if the dask scheduler is not reachable,
- if rabbitmq is not reachable,
- --> the pipeline would be directly set to FAILED state
*AFTER*:
- --> the pipeline will be set to WAITING_FOR_CLUSTER state
1. Since when we deploy or play around the clusters-keeper restarts wildly this will prevent failing pipelines straight away which were issues detected a while ago that should not be happening (see fixed issues).
2. Also, a new constant was defined `COMPUTATIONAL_BACKEND_MAX_WAITING_FOR_CLUSTER_TIMEOUT` that could be used in case we should change that value (currently defaulted to 10 minutes).
tests driving changes: `test_scheduler_dask.py`
- fixes …

🐛🎨Do not fail a pipeline when the clusters-keeper or the computational backend in general is not reachable for short time 🚨

---

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py

https://github.com/ITISFoundation/osparc-simcore/pull/8286 introduced an issue where a call to `max` could be made with an empty array:
This PR fixes it.

🐛Director-v2: fix empty arguments for `max` method

---

packages/notifications-library/src/notifications_library/templates/on_account_requested.email.content.html
packages/notifications-library/src/notifications_library/templates/on_account_requested.email.content.txt
services/web/server/src/simcore_service_webserver/templates/common/request_account.jinja2

Improves the formatting of account request emails by clearly highlighting the **target product and host**.
This change reduces the risk of manual errors when issuing invitations, such as sending them to the wrong host or product.
- Follow-up improvement to minimize invitation mistakes.
- 
- Fill up request form
- Support email list will receive new formatted email
None

🎨 Enhance account request emails to reduce invitation errors

---

tests/e2e-playwright/tests/conftest.py
tests/e2e-playwright/tests/metamodeling/test_response_surface_modeling.py

This PR brings:
- create a study with a Number Parameter --> Jsonifier --> Number Probe
- create a function out of it
- start mmux as a new project
- delete the projects and the function
Still needs:
- select in mmux the function
- run the function
- check for results
@alexpargon I would need some `osparc-test-id`  in the mmux frontend if possible
- relates to https://github.com/ITISFoundation/mmux_vite/issues/232

🎨E2E: add create study, create function, start mmux

---

services/api-server/src/simcore_service_api_server/core/application.py

- Since https://github.com/ITISFoundation/osparc-simcore/pull/8354 the `task_manager` is required inside the celery worker. (see here: https://github.com/ITISFoundation/osparc-simcore/blob/master/packages/celery-library/src/celery_library/task.py#L59). This PR adds the task_manager to the api-worker. 
- The latest merge request (https://github.com/ITISFoundation/osparc-simcore/pull/8352) concerning the api-worker was with this bug because the issue was introduced by merge conflicts. The unit tests which test the api-worker mock the task_manager so the issue was not detected. 
- It is not clear to me that it is advisable to have the `task_manager` dependency inside the celery-worker. Perhaps we can discuss today @giancarloromeo. But this PR adds to the api-worker anyway to make it …

🐛 Add `task_manager` to api-worker

---

packages/service-library/src/servicelib/rabbitmq/_client.py
packages/service-library/src/servicelib/rabbitmq/_client_base.py
packages/service-library/src/servicelib/redis/_constants.py
packages/service-library/src/servicelib/redis/_decorators.py
packages/service-library/src/servicelib/redis/_semaphore_decorator.py
packages/service-library/tests/rabbitmq/test_rabbitmq.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py

This pull request introduces improvements to logging and error handling in both the RabbitMQ and Redis modules.
* **Redis**: adds monitoring for lock and semaphore holding times. 
The changes aim to provide more actionable and structured logs for troubleshooting, and to help detect and warn about potential performance bottlenecks related to lock/semaphore usage. Minor test and logging adjustments are also included. It is expected to see some warnings appear when the expected time a lock is held is exceeded. Some further adjustments will be needed to silence the warnings that are unnecessary.
* **Rabbit**: use structured logs for connections/channel closing callbacks and unhandled exceptions in message handling. Also handle the ChannelClosed issue during a message similarly as in aio-pika …

🐛RabbitMQ client: prevent crashing consumer if channel is closed

---

.github/workflows/cleanup-caches-by-branches.yml

- upgrade the cache cleanup CI workflow

⬆️🔨 upgrade cache cleanup script

---

services/autoscaling/src/simcore_service_autoscaling/modules/cluster_scaling/_auto_scaling_core.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_dask.py
services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_pipelines.py

sometimes the `job_id` is None and that was not seen during latest refactoring actions.
This PR fixes this and improves logging in some specific locations.
This PR also ensure the `comp_pipeline` table is in sync when nodes are removed from the graph (revert https://github.com/ITISFoundation/osparc-simcore/pull/2702 in `comp_pipelines.py` discovered by @matusdrobuliak66 .

🐛Computational backend: fix issue where job_id is inexistent + logs improvements

---

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_base.py
services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/_scheduler_dask.py
services/director-v2/src/simcore_service_director_v2/modules/dask_client.py

- remove distributed Variable that can timeout after 30 seconds and bring us in a undefined state and send tasks to the underlying dask backend without writing it to the DB
- removes concurrent access to the dask-scheduler as this defeats the purpose of limiting its access via a semaphore (capacity is 20, with concurrent access set to 10, we get potentially 200 concurrent calls that the dask-scheduler does not handle)
- removes concurrent access to the DB as many warnings showing DB access approach maximum were spotted.
- relates to https://github.com/ITISFoundation/private-issues/issues/10

🎨Computational backend: improvements step 6

---

services/static-webserver/client/source/class/osparc/dashboard/TutorialBrowser.js
services/static-webserver/client/source/class/osparc/store/Groups.js

This PR fixes a bug where the support group's access rights were not being properly set. The issue occurred because the support group was added to the cache before its access rights were available, and these rights were only provided later when processing organization data.
Bonus:
- Tags filter always visible in the Tutorials tab, not only when they are grouped by tags
Buggy:
Fixed:

🐛 [Frontend] Fix: Support group accessRights

---

packages/service-library/src/servicelib/rabbitmq/rpc_interfaces/webserver/functions/functions_rpc_interface.py

- Increase the function rpc timeouts to 30sec. See the issue below for the motivation for doing so.
- closes #8439

🎨 Increase function rpc call timeouts to 30sec

---

services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_api_keys.py

Potential fix for [https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/95](https://github.com/ITISFoundation/osparc-simcore/security/code-scanning/95)
To fix this problem, we should ensure that no sensitive credential data (e.g., API keys, secrets, tokens) is directly logged. Instead, log only identifying but non-sensitive information about the expired/removed API keys, such as their database IDs, associated user IDs, display names, or generic counts. Specifically, in `services/web/server/src/simcore_service_webserver/garbage_collector/_tasks_api_keys.py`, line 25 currently logs the variable `api_key` in full. 
The fix involves:
- Editing line 25 to avoid logging the full API key value.
- Use available metadata if possible (such as a display name, if that's present in …

🔒️ Potential fix for code scanning alert no. 95: Clear-text logging of sensitive information

---

services/api-server/tests/unit/conftest.py
services/api-server/tests/unit/pact_broker/test_pact_checkout_release.py
services/api-server/tests/unit/pact_broker/test_pact_licensed_items.py

Follows up from  https://github.com/ITISFoundation/osparc-simcore/pull/8431  and fixes `pact_broker` tests
```
=========================== short test summary info ============================
ERROR tests/unit/pact_broker/test_pact_checkout_release.py::test_provider_against_pact - AttributeError: <module 'simcore_service_api_server.services_rpc.wb_api_server' from '/home/runner/work/osparc-simcore/osparc-simcore/.venv/lib/python3.11/site-packages/simcore_service_api_server/services_rpc/wb_api_server.py'> does not have the attribute '_checkout_licensed_item_for_wallet'
ERROR tests/unit/pact_broker/test_pact_licensed_items.py::test_provider_against_pact - AttributeError: <module 'simcore_service_api_server.services_rpc.wb_api_server' from …
```

🎨✅ [Maintenance] Add mock handler factory for LicensesRpcApi to fix pact tests

---

packages/service-library/src/servicelib/aiohttp/long_running_tasks/__init__.py
packages/service-library/src/servicelib/aiohttp/long_running_tasks/_constants.py
packages/service-library/src/servicelib/aiohttp/long_running_tasks/_manager.py
packages/service-library/src/servicelib/aiohttp/long_running_tasks/_request.py
packages/service-library/src/servicelib/aiohttp/long_running_tasks/_server.py
packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks_with_task_context.py
services/web/server/src/simcore_service_webserver/long_running_tasks/plugin.py
services/web/server/src/simcore_service_webserver/projects/_permalink_service.py
services/web/server/src/simcore_service_webserver/resource_manager/_constants.py
services/web/server/src/simcore_service_webserver/resource_manager/plugin.py
services/web/server/src/simcore_service_webserver/resource_manager/registry.py
services/web/server/src/simcore_service_webserver/socketio/_utils.py
services/web/server/src/simcore_service_webserver/socketio/server.py

Follows up refactoring webserver's `app` state keys from strings to `web.AppKey` (see #7734)
**Application state key refactoring:**
* Replaced string-based keys with `web.AppKey` objects in the long-running tasks module, introducing `APP_LONG_RUNNING_MANAGER_APPKEY` and `RQT_LONG_RUNNING_TASKS_CONTEXT_APPKEY` for safer access to manager and task context objects (`_manager.py`, `_request.py`, `_server.py`, `__init__.py`, tests, and plugins). [[1]](diffhunk://#diff-a52eb8db426355febdfd90a361ee6ece63d66f97b7ebd0a00b8aac871e99eaa4R1-L5) [[2]](diffhunk://#diff-a52eb8db426355febdfd90a361ee6ece63d66f97b7ebd0a00b8aac871e99eaa4R17-R23) [[3]](diffhunk://#diff-a1a9868662d09f21ea9224cd94a07cb1b351de281442f70e61450ced29036f99L1-R11) [[4]](diffhunk://#diff-7b7ff72ad4bf18c0db1d602c4e79cf83ac238f1555bd021 …

♻️ Refactor: migrate more `aiohttp` app keys to type-safe `web.AppKey` (follow up)

---

packages/postgres-database/src/simcore_postgres_database/utils_payments.py
packages/postgres-database/src/simcore_postgres_database/utils_payments_autorecharge.py
packages/postgres-database/tests/test_models_payments_transactions.py
packages/postgres-database/tests/test_utils_payments_autorecharge.py
packages/service-library/src/servicelib/aiohttp/db_asyncpg_engine.py
services/payments/src/simcore_service_payments/db/auto_recharge_repo.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_guests.py
services/web/server/src/simcore_service_webserver/garbage_collector/_core_utils.py
services/web/server/src/simcore_service_webserver/payments/_autorecharge_api.py
services/web/server/src/simcore_service_webserver/payments/_autorecharge_db.py
services/web/server/src/simcore_service_webserver/payments/_methods_api.py
services/web/server/src/simcore_service_webserver/payments/_methods_db.py
services/web/server/src/simcore_service_webserver/payments/_onetime_api.py
services/web/server/src/simcore_service_webserver/payments/_onetime_db.py
services/web/server/src/simcore_service_webserver/projects/models.py

This PR migrates database access from **`aiopg`** to **`asyncpg`** in the following components:
* The `payments` domain within the `webserver`
* The `simcore_postgres_database.utils_payments` module and its associated test suite
This pull request refactors the payments database utility and its usage across the codebase to fully adopt SQLAlchemy's async API, removing legacy `aiopg` types and error handling. It also updates test cases and web server modules to use the new async interfaces and corrects model naming for autorecharge logic. These changes modernize the codebase, improve compatibility with SQLAlchemy, and simplify transaction handling.
**Database API modernization:**
* Replaced all usage of `aiopg.sa.connection.SAConnection` and related types with …

♻️ [Maintenance] Refactor Payments Domain to Use asyncpg Instead of aiopg
