services/web/client/source/class/qxapp/components/form/Auto.js, services/web/client/source/class/qxapp/components/form/renderer/NoteForm.js, services/web/client/source/class/qxapp/components/form/renderer/PropForm.js, services/web/client/source/class/qxapp/components/workbench/NodeBase.js, services/web/client/source/class/qxapp/components/workbench/SettingsView.js, services/web/client/source/class/qxapp/data/Fake.js, services/web/client/source/class/qxapp/desktop/PrjEditor.js
The new infrastructure attaches a settings form to the node and shows it in the settings viewer. The form uses databinding to convert incoming values.
The data flow will probably have to be altered once the data model is available.
=> initial drop of new settings builder

services/web/client/source/class/qxapp/auth/core/BaseAuthPage.js, services/web/client/source/class/qxapp/auth/ui/LoginPage.js
If we want to have the browser save the content of a form (like the login form) we must provide some annotations as explained in in: https://www.chromium.org/developers/design-documents/create-amazing-password-forms
connected to #19 
=> Make login form password save friendly

services/dy-2Dgraph/use-cases/Makefile, services/dy-2Dgraph/use-cases/docker/boot.sh, services/web/server/src/simcore_service_webserver/reverse_proxy/__init__.py, services/web/server/src/simcore_service_webserver/reverse_proxy/handlers/jupyter.py
start the 2D visualizer using the reverse proxy base path
=> set notebook startup parameters to use the reverse proxy base path

services/web/server/requirements/base.txt
aio-libs aiohttp-session version 2.6.0 and earlier contains a Other/Unknown vulnerability in
EncryptedCookieStorage and NaClCookieStorage that can result in Non-expiring sessions / Infinite lifespan.
This attack appear to be exploitable via Recreation of a cookie post-expiry with the same value.
=> upgrades aiohttp-session to patch version 2.7.0

README.md, services/sidecar/tests/requirements.txt, services/storage/tests/requirements.txt
when no version specified in requirements.txt, pip installs the latest version __only__ if none was installed before
Bonus:
- added a badge for coveralls
closes #512 
=> added versions to requirements in storage and sidecar

Makefile
```
Step 19/47 : FROM build as cache
---> 13f975b73ae5
Step 20/47 : ENV SIMCORE_WEB_CONFIG production
---> Running in 74db9a46c7e2
Removing intermediate container 74db9a46c7e2
---> 9b9a02b12d6b
Step 21/47 : COPY --chown=scu:scu packages $HOME/packages
---> 675ad308834d
Step 22/47 : COPY --from=services_webclient:build --chown=scu:scu /home/scu/client/build-output $HOME/services/web/client
ERROR: Service 'webserver' failed to build: invalid from flag value services_webclient:build: pull access denied for services_webclient, repository does not exist or may require 'docker login'
make: *** [rebuild-devel] Error 1
```
- Temporary target builds a services_webclient:build image and avoids failure building webserver docker image
- Minor cleanup
=> Fixes ``make build-devel`` from scratch.

services/web/client/package-lock.json, services/web/client/package.json, services/web/server/tests/unit/test_rest.py
the qooxdoo bootloader (boot.js) tries to load files using double slashes in urls. like this
`root-dir//some/path/file.js` 
most webservers don't care. not so our aiohttp one ... this pr updates to the latest qooxdoo compiler which does not add double slashes anymore.
=> get up to new qxcompiler with fix for //

services/web/client/source/class/qxapp/component/widget/NodeView.js, services/web/client/source/class/qxapp/component/widget/PersistentIframe.js, services/web/client/source/class/qxapp/desktop/PrjEditor.js
Fixes the two empty NodeView cases:
- When an iFrame is maximized and the user selects a different node, an empty view is shown. To prevent that bug PrjEditor restores the iFrame before changing node.
- When selecting a file and closing the FilePicker an empty view may be shown. To prevent PrjDitor will show FilePicker's parent layout.
=> Fix: Avoid black/empty NodeViews

packages/simcore-sdk/src/simcore_sdk/node_ports/serialization.py, services/web/client/source/class/qxapp/desktop/PrjBrowser.js, services/web/server/src/simcore_service_webserver/projects/projects_models.py, services/web/server/tests/integration/projects/test_projects.py
Fixes the bug of opening two "Create new study" instances when double clicking the plus button. This was also causing an inconsistency in the DB having two projects with the same uuid.
Includes #687, that fixes the inconsistency in the DB
=> Check if a new study is already being created

services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/projects/__init__.py, services/web/server/src/simcore_service_webserver/projects/projects_access.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/src/simcore_service_webserver/studies_access.py, services/web/server/tests/integration/test_project_workflow.py
- Application does not load template projects via fakes
- Moves all calls to get fakes under project's db api (in mid term this should e completely removed)
Implements changes in #866
=> Disables fake-projects

api/specs/webserver/v0/openapi-projects.yaml, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/src/simcore_service_webserver/studies_access.py, services/web/server/tests/data/fake-project.json, services/web/server/tests/unit/test_template_projects.py, services/web/server/tests/unit/with_postgres/test_access_to_studies.py, services/web/server/tests/unit/with_postgres/test_projects.py
Cherry-picked squashed PR #870  to master
=> hotfix/get templates -> staging

api/specs/storage/v0/openapi.yaml, api/tests/conftest.py, services/storage/src/simcore_service_storage/application.py, services/storage/src/simcore_service_storage/cli.py, services/storage/src/simcore_service_storage/cli_config.py, services/storage/src/simcore_service_storage/dsm.py, services/storage/src/simcore_service_storage/handlers.py, services/storage/src/simcore_service_storage/models.py, services/storage/src/simcore_service_storage/resources.py, services/storage/src/simcore_service_storage/rest_routes.py, services/storage/src/simcore_service_storage/settings.py, services/storage/src/simcore_service_storage/utils.py, services/storage/tests/_test_rawdatcore.py, services/storage/tests/conftest.py, services/storage/tests/data/projects_with_data.json, services/storage/tests/docker-compose.yml, services/storage/tests/helpers/utils_assert.py, services/storage/tests/helpers/utils_project.py, services/storage/tests/test_configs.py, services/storage/tests/test_datcore.py, services/storage/tests/test_dsm.py, services/storage/tests/test_rest.py, services/storage/tests/utils.py, services/web/server/tests/unit/with_postgres/test_projects.py
Extension of storage api:
- Implements deep clone of a project on storage level (i.e. copying of all files related to a project into internal simcore.s3 storage and, if any, from datcore to simcore.s3)
- Implements deletion of files in internal simcore.s3 storage
=> Storage extension for deep copy of project files

services/storage/src/simcore_service_storage/db_tokens.py, services/web/server/src/simcore_service_webserver/users_handlers.py
Re-applies hotfix already added in staging by cherry-picking 5fd24212409f958bb7b3fb5c98e208a4d61f3260
* Applied retry policy to db query for /me endpoint
* fixes log: user w/o access tokens shall not log error
=> hot fix1229: fails db query (#1231)

api/specs/webserver/openapi-auth.yaml, services/web/client/source/class/osparc/auth/Manager.js, services/web/client/source/class/osparc/data/Resources.js, services/web/client/source/resource/api/openapi.yaml, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/director/handlers.py, services/web/server/src/simcore_service_webserver/login/handlers.py, services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py, services/web/server/src/simcore_service_webserver/socketio/handlers.py, services/web/server/tests/unit/with_dbs/test_change_email.py, services/web/server/tests/unit/with_dbs/test_change_password.py, services/web/server/tests/unit/with_dbs/test_logout.py, services/web/server/tests/unit/with_dbs/test_redis_registry.py, services/web/server/tests/unit/with_dbs/test_reset_password.py, services/web/server/tests/unit/with_dbs/test_resource_manager.py
**fix the issue arising from logout handler taking too much time**
**description of the problem**:
1. A user logs in and logs out
2. if the user logs in again in the next 5seconds then the websocket will be disconnected, thus it is not possible to use simcore
description of the log out procedure:
1. user opens several tabs on osparc
2. user logs out in one tab
3. the webserver receives the log out command, then sends a logout signal over the websockets to the other opened tabs (so they can properly log out)
4. the webserver waits 5sec so the frontends can react, then it disconnects all the user websockets
analysis:
1. the frontend does not wait for the logout response
2. the logout procedure is too long for the frontend, user cannot wait 5secs to be properly logged out
3. the backend also …
=> fix logging out, logging in failing

services/director/Makefile, services/director/src/simcore_service_director/producer.py, services/director/tests/test_producer.py
fix an issue where services provide other tags than x.x.x and the director raise an exception about it.
=> Fix: Director raise an exception when tags are not following X.X.X

packages/postgres-database/tests/docker-compose.yml, packages/service-library/tests/with_postgres/docker-compose.yml, packages/simcore-sdk/tests/unit/docker-compose.yml, services/docker-compose.yml, services/sidecar/tests/docker-compose.yml, services/storage/tests/docker-compose.yml, services/web/server/tests/unit/with_dbs/docker-compose.debug.yml, services/web/server/tests/unit/with_dbs/docker-compose.yml
The last fix, although valid from docker 19.03 is not compatible yet with portainer [see here](https://github.com/portainer/portainer/issues/3551).
Luckily there is an alternative to configure postgreSQL itself to override the system defaults.
fixes #1242
=> portainer compatible fix

services/web/server/src/simcore_service_webserver/computation_subscribe.py
re-adds a sleep time when webserver is processing messages coming from rabbitMQ.
Since an issue arose that production becomes unresponsive when the CC-Human template is running this could be the problem.
=> webserver does not respond when many logs are coming in from rabbitMQ

tests/e2e/tutorials/mattward.js, tests/e2e/tutorials/sleepers.js, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/auto.js
Puppeteer checks number of output files produced by a node.
So far we were only checking if some output was produced. Now we can check a specific number of outputs.
P.S. Since the node's logs file was hiding the lack of other outputs, this PR will make master red again.
closes #1341
=> e2e: Check number of output files

services/web/server/src/simcore_service_webserver/socketio/handlers.py
- prevent following assertion from happening in webserver and logs error instead as this should not be hapenning
```
message
ERROR:engineio.server:disconnect async handler error
File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 410, in _trigger_event
ret = await self.handlers[event](*args)
File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 518, in _handle_eio_disconnect
await self._handle_disconnect(sid, '/')
File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 423, in _handle_disconnect
await self._trigger_event('disconnect', '/', sid)
File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 466, in _trigger_event
ret = await …
```
=> [bugfix] prevent crash when no user id is found

ci/deploy/dockerhub-release.bash
=> Bugfix: Travis is still the one releasing to production

packages/postgres-database/scripts/remove_comp_tasks_duplicates.sql
- original table was not dropped after migration
-> was creating issue when deleting projects as the table constrained were still used.
=> fixes script to migrate comp_tasks table

services/web/server/src/simcore_service_webserver/socketio/handlers.py, services/web/server/src/simcore_service_webserver/socketio/handlers_utils.py
- catch exception arising in socket.io connection
=> catch exception on socketio connection

services/sidecar/src/simcore_service_sidecar/celery.py
=> fix issue when next_task_nodes is None

tests/e2e/tutorials/mattward.js, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/responsesQueue.js, tests/e2e/utils/utils.js
Instead of waiting a hardcoded amount of time for the service to be ready, a Node status listener was added. Now puppeteer waits until the service_state says running.
related to #1426
=> Fix e2e false positives

Makefile, services/web/Dockerfile, services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py
Fixes issues in master.
See commits
=> Fixes on webserver diagnostics submodule and setup in dev-mode

packages/pytest-simcore/src/pytest_simcore/minio_service.py
fix: minio fixture trying to find the published port when it is already the published port
=> fix env already shows published port

requirements.txt, services/api-gateway/requirements/dev.txt, services/catalog/requirements/dev.txt, services/director/requirements/dev.txt, services/sidecar/requirements/dev.txt, services/storage/requirements/dev.txt, services/web/server/requirements/dev.txt
Reference to common requirements.txt cannot be reached in devel containers
because the file is not mounted.
The most cost effective solution is to copy&past common requirements (they
do not change much) since COPYing the file in the Dockefile is more
disruptive
=> Fixes boot failure in devel mode

services/web/client/source/class/osparc/component/export/ExportDAG.js, services/web/client/source/class/osparc/component/widget/NodesTree.js, services/web/client/source/class/osparc/data/Permissions.js, services/web/client/source/class/osparc/desktop/StudyEditor.js, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/src/simcore_service_webserver/security_roles.py, services/web/server/tests/unit/with_dbs/test_projects.py
=> Fix "Save as template"

README.md, api/tests/Makefile, api/tests/requirements.in, api/tests/requirements.txt, packages/postgres-database/requirements/_migration.in, packages/postgres-database/requirements/_migration.txt, packages/postgres-database/requirements/_test.txt, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt, tests/swarm-deploy/requirements/requirements.in, tests/swarm-deploy/requirements/requirements.txt
- upgrade to latest ``Fake`` and ``redis`` packages (replaces faulty PR ##1501) both in ``packages`` and ``services/web/server``
- upgrades api/tests requirements and Makefile
- upgrades missing requirements from non-packages/services folders (e.g. ``coverage``, ``pytest``)
=> [maintenance] requirements upgrades

services/web/client/source/class/osparc/component/widget/NodesTree.js
The issue was not the opencor test itself, but this test is the first one that has to click on a NodesTree item. The problem is that some context checks are done when clicking an item and since the export button does not exist for GUEST users, the enable/disable operation on the button fails, not letting the item-clicking-routine go through.
=> Fix opencor e2e test

services/web/client/source/class/osparc/component/node/BaseNodeView.js, services/web/client/source/class/osparc/component/widget/CollapsibleView.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/dashboard/StudyBrowserButtonBase.js, services/web/client/source/class/osparc/desktop/ControlsBar.js, services/web/client/source/class/osparc/desktop/NavigationBar.js, services/web/client/source/class/osparc/desktop/PanelView.js, services/web/client/source/class/osparc/desktop/StudyEditor.js, services/web/client/source/class/osparc/utils/Utils.js
ITISFoundation/osparc-issues#168
Before:
After:
=> UI/UX Study Editor

services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py
There was an issue where GC would stop when trying to stop a service which was not found.
=> When the service is stopped errors are trapped

services/storage/src/simcore_service_storage/datcore.py, services/storage/src/simcore_service_storage/datcore_wrapper.py, services/storage/tests/test_datcore.py
If bf is down, storage handlers raise exceptions and stops working. 
This fix removes this hard dependency and catches exceptions raised by bf client when their service is unavailable
This fix does not totally solves the problems of storage that is designed to be very silent with bf operations, ie. nothing happens if there are errors in the interaction with bf. I think this needs a deeper refactoring that is outside the scope of this PR.
#1506
=> [bugfix] storage service fails when blackfynn API is not responsive

services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml, services/web/server/src/simcore_service_webserver/projects/projects_api.py
Minor fixes to overcome some e2e test failures
- Fixes output update in projects_api
- Sets max. size of psycopg2 pool to ~unlimited~ a large number at the webserver (want to check if it reduces ``CancelledError`` in aiopg). Asyngpg does not accept 0.
=> [bugfix] fixes projects_api and sets larger pool to webserver

packages/pytest-simcore/src/pytest_simcore/traefik_service.py, services/director/src/simcore_service_director/producer.py, services/docker-compose.local.yml, services/docker-compose.yml, tests/swarm-deploy/test_swarm_runs.py
- adds the entrypoint in the simcore stack
Port 10081 -> api-gateway currently impersonated by the amazing [mockserver](https://www.mock-server.com/#what-is-mockserver)
#1474
```bash
curl -X GET 127.0.0.1:10081/live
```
=> add traefik endpoint to api-gateway

packages/pytest-simcore/src/pytest_simcore/simcore_webserver_service.py, tests/swarm-deploy/conftest.py, tests/swarm-deploy/test_swarm_runs.py
ensure the database is filled up
- retry checking of root (http://127.0.0.1:9081) since it can take a small amount of time until traefik redirects and the webserver answers correctly
- ensure the database is correctly setup on start for the e2e testing preventing webserver to crash unexpectedly
=> [maintenance] improve stability of deploy tests

.travis.yml
Currently, e2e job was disabled in GitHub-actions (required) but NOT in travis (not required)
For that reason, the e2e job inn [travis runs](https://github.com/ITISFoundation/osparc-simcore/runs/831170681) on integration testing stage still failing. This prevents deployment stage from starting which might stop building images !
This PR completely excludes the e2e job in travis allowing the last step to run
=> Excludes e2e job from travis CI  until fixed

services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/dashboard/ExploreBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/data/Resources.js, services/web/client/source/class/osparc/data/model/Node.js, services/web/client/source/class/osparc/desktop/StudyEditor.js
This PR fixes a bug with the cached studies in the fronted by making sure the latest version is fetched before starting it.
- Do not allow negative node position values
=> [bugfix] Invalidate cache before starting a study

services/sidecar/src/simcore_service_sidecar/utils.py, services/sidecar/tests/unit/test_celery_configurator.py
executing ```docker node inspect self``` is not allowed on non-manager nodes in a swarm.
Therefore, alternative proposal is to try run a nvidia-smi container that will fail if the nvidia runtime is not set as default on the node.
@GitHK : please test on your GPU enabled machine.
fixes #1603 (after being tested by @GitHK )
=> fix testing if node has gpu support

services/director/src/simcore_service_director/producer.py, services/storage/src/simcore_service_storage/data/docker-prod-config.yaml, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py, services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml
- Fixes various issues found while manual exploratory testing
- Increases storage and webserver db connection pool
=> Fixes on publish studies handling

services/storage/src/simcore_service_storage/dsm.py, services/storage/src/simcore_service_storage/utils.py
The `list_files` function is now optimised to run with big datasets, and no longer depends on third party S3 calls when listing files in the storage service.
- database updates when retrieving the real file names (which might have been renamed) => responsible for 40% of the slowdown
- file metadata updates in the database after invoking an S3 call for each file when listing all the files => responsible for the majority of the reminding slowdown
- a `metadata_file_updater` launched before returning the upload link for each file to be uploaded. It will try to update the metadata for each file. It uses an exponential backoff retry to account for huge file uploads. It also has a maximum amount of possible retries. If it fails to update the metadata, an error message will be logged.
Changes …
=> Improving storage performance

services/sidecar/src/simcore_service_sidecar/executor.py
If an error occurs during a pull operation (registry sometimes times out), the sidecar will retry to fetch this image again.
=> Sidecar retries pull on error

services/sidecar/src/simcore_service_sidecar/executor.py, services/sidecar/src/simcore_service_sidecar/log_parser.py
- fixes an issue where retrieving logs from dead containers would cause the service scheduling to hang (a message will now be displayed in the service logs)
- before failing and stopping the service a message the error message will be posted to the service logs
Will help debugging https://github.com/ITISFoundation/osparc-simcore/issues/1479
=> Making services more debuggable

services/sidecar/src/simcore_service_sidecar/boot_mode.py, services/sidecar/src/simcore_service_sidecar/celery_configurator.py, services/sidecar/src/simcore_service_sidecar/cli.py, services/sidecar/src/simcore_service_sidecar/executor.py, services/sidecar/tests/integration/conftest.py, services/sidecar/tests/integration/test_sidecar.py
Some computational services support more then one type of boot mode, some of these require special resources.
These services can now check the env var `SC_COMP_SERVICES_SCHEDULED_AS` to determine the node they were booted on. See https://github.com/ITISFoundation/osparc-simcore/issues/1716 for details.
closes https://github.com/ITISFoundation/osparc-simcore/issues/1716
=> Computational services can determine on which queue they were scheduled

services/web/client/source/class/osparc/component/export/Permissions.js, services/web/client/source/class/osparc/data/Resources.js, services/web/client/source/class/osparc/store/Store.js, services/web/client/source/class/osparc/utils/Classifiers.js
Fixes replicated classifiers.
The problem we have is that the current frontend cache is not able to handle classifiers coming from different organizations. This PR fixes this specific issue but it would be nice to extend the caching system.
closes ITISFoundation/osparc-issues#279
=> Fixed cached classifiers

services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py
The last step of the GC, after removing everything is to also delete raining dynamic services.
Currently, some dynamic services (notebooks), require longer time than usual to be closed. This will be addressed in a separate PR.
Leaving this in place may cause users, which have big amounts of data to loose their data because partially saved.
=> Disabling GC service removal

services/web/client/source/class/osparc/component/sweeper/Iterations.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js
After going back to the Dashboard, frontend requests a fresh list (not cached) of studies.
closes ITISFoundation/osparc-issues#323
=> Bugfix: Disable cache when reloading studies

services/web/server/src/simcore_service_webserver/resource_manager/registry.py, services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py, services/web/server/tests/unit/with_dbs/fast/test_redis_registry.py
Resources will always have an alive key which will make them expire and get garbage collected by the system.
=> Fix resource manger alive keys always have a TTL

Makefile, scripts/install_nodejs_14.bash, services/docker-compose-ops.yml, tests/e2e/utils/wait_for_services.py
Fixes sudden CI failure in registry step during the e2e workflow.
The problem was that the latest release of ``flower`` was actually broken. The image tag was not frozen so the step ``wait_for_sercices.py`` would constantly fail. 
- Froze flower service in ops to latest working version
- Improved logging and checks reliability in ``tests/e2e/utils/wait_for_services.py``
- Small convenience improvements to help running in newly development machines
=> Fixes registry step in e2e-CI 

services/docker-compose.yml
fixed the redis version to the last digit.
if you want to fix to the SHA of all the versions. please feel free to create a PR.
=> fix redis version to version 5.0.9-alpine

api/specs/common/schemas/node-meta-v0.0.1-converted.yaml, api/specs/common/schemas/node-meta-v0.0.1.json, packages/models-library/src/models_library/services.py, services/catalog/src/simcore_service_catalog/services/frontend_services.py, services/director/src/simcore_service_director/api/v0/openapi.yaml, services/director/src/simcore_service_director/api/v0/schemas/node-meta-v0.0.1.json, services/storage/src/simcore_service_storage/api/v0/schemas/node-meta-v0.0.1.json, services/web/client/source/class/osparc/component/export/ExportDAG.js, services/web/client/source/class/osparc/component/node/GroupNodeView.js, services/web/client/source/class/osparc/component/node/NodeView.js, services/web/client/source/class/osparc/component/widget/BreadcrumbSplitter.js, services/web/client/source/class/osparc/component/widget/NodeSlideTreeItem.js, services/web/client/source/class/osparc/component/widget/NodesSlidesTree.js, services/web/client/source/class/osparc/data/model/Node.js, services/web/client/source/class/osparc/data/model/Study.js, services/web/client/source/class/osparc/data/model/StudyUI.js, services/web/client/source/class/osparc/desktop/ControlsBar.js, services/web/client/source/class/osparc/desktop/SlideShowView.js, services/web/client/source/class/osparc/desktop/WorkbenchView.js, services/web/client/source/class/osparc/store/Store.js, services/web/server/src/simcore_service_webserver/api/v0/schemas/node-meta-v0.0.1.json, tests/e2e/tutorials/tutorialBase.js
closes ITISFoundation/osparc-issues#361
closes #1903
=> Fix (un)grouping

.github/workflows/ci-testing-deploy.yml, tests/e2e/.gitignore, tests/e2e/package-lock.json, tests/e2e/package.json, tests/e2e/utils/startPuppe.js
In order to help debugging the e2e testing, this PR adds the option for dumping all logs coming from browser's console and also all the events/requests captured in the network.
The log file as uploaded as an artifact.
=> e2e: Dump console logs and network events to artifact file

services/director/src/simcore_service_director/producer.py, services/web/server/src/simcore_service_webserver/computation_api.py
A race condition occurs when updating the `comp_pipeline` and causes duplicate key errors. This will address the resolution of the race condition.
=> Fixing duplicate key error in comp_pipeline

services/director/requirements/_base.in, services/director/requirements/_base.txt, services/director/requirements/_test.txt, services/director/requirements/ci.txt, services/director/requirements/dev.txt, services/director/setup.py
Fixes versions errors due to missing unpinned versions in ``director/requirements/_base.txt`` 
Requirements in ``director`` ``_base.txt`` where not **deep frozen** since  the dependencies of ``servicelib`` (a package in the same repository) were not included (by mistake!)
Since the service will be replaced by ``director-v2`` we took this opportunity to **freeze the reqs** of this service to the latest working image (see procedure in ``_base.txt`` documentation). 
All reqs are frozen to match those of [itisfoundation/director:master-2020-11-05--14-45.c8669fb52659b684514fefa4f3b4599f57f276a0](https://hub.docker.com/layers/itisfoundation/director/master-2020-11-05--14-45.c8669fb52659b684514fefa4f3b4599f57f276a0/images/sha256-84ba999ca348bf9d56d9ef0af2e3494ede0cd06d357d289e2a09a4191e7a56d3?con …
=> Freezes director reqs

api/specs/common/schemas/project-v0.0.1-converted.yaml, api/specs/common/schemas/project-v0.0.1.json, services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json, services/storage/src/simcore_service_storage/api/v0/openapi.yaml, services/storage/src/simcore_service_storage/api/v0/schemas/project-v0.0.1.json, services/web/client/source/class/osparc/data/model/Workbench.js, services/web/client/source/class/osparc/desktop/WorkbenchView.js, services/web/client/source/class/osparc/file/FileDownloadLink.js, services/web/client/source/class/osparc/file/FilePicker.js, services/web/client/source/class/osparc/ui/basic/NodeStatusUI.js, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/api/v0/schemas/project-v0.0.1.json
related to ITISFoundation/osparc-issues#343
=> FilePicker supports download links

packages/models-library/requirements/_base.txt, packages/models-library/requirements/_test.txt, packages/postgres-database/requirements/_test.txt, packages/s3wrapper/requirements/_base.txt, packages/s3wrapper/requirements/_test.txt, packages/service-library/requirements/_base.in, packages/service-library/requirements/_base.txt, packages/service-library/requirements/_test.txt, packages/simcore-sdk/requirements/_base.txt, packages/simcore-sdk/requirements/_test.txt, scripts/requirements/Dockerfile, scripts/requirements/Makefile, services/api-server/requirements/_base.txt, services/api-server/requirements/_test.txt, services/catalog/requirements/_base.txt, services/catalog/requirements/_test.txt, services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director/requirements/Makefile, services/director/requirements/_test.in, services/sidecar/requirements/Makefile, services/sidecar/requirements/_base.txt, services/sidecar/requirements/_packages.txt, services/sidecar/requirements/_test.txt, services/storage/requirements/_base.txt, services/storage/requirements/_test.txt, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt, tests/environment-setup/requirements/requirements.txt, tests/swarm-deploy/requirements/requirements.txt
Weekly upgrade of python dependencies.
- Main library upgrades (see links to Bump PR below):
- pydantic (minor)
- attrs (patch)
- faker (patch)
- aiozipkin frozen to 0.7.1 due to incompatibilities
- Some test libraries and tools in packages as well (not in services)
- Tuning in Makefile recipes and Dockerfile (adds awk to display help)
=> Maintenance week 46

services/web/server/src/simcore_service_webserver/cli.py, services/web/server/src/simcore_service_webserver/log.py, services/web/server/src/simcore_service_webserver/resource_manager/config.py, services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py, services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py, services/web/server/src/simcore_service_webserver/studies_access.py, services/web/server/src/simcore_service_webserver/users_api.py, services/web/server/tests/unit/with_dbs/conftest.py, services/web/server/tests/unit/with_dbs/fast/test_access_to_studies.py, services/web/server/tests/unit/with_dbs/fast/test_redis.py
- It reimplements the fix using locks to protect construction and initialization of the GUEST user from an eager GC! :-)
- This PR replaces PR#1928  (bugfix for #1853: garbage collector deletes guest users  bug). This implementation avoid setting fictitious resources or anonymous users as in PR #1928. Those proved to be very error prone.
- EXTRA: resources are removed from registry when GC actually executes the clean. This way, the share-lock mechanism will prevent  a user from opening a resource that is being removed [upon request from @odeimaiz and @sanderegg]
Fixes #1853
```
make devenv
make test-dev-unit
```
=> BugFix: New fix for access_studies using redlocks

tests/e2e/tutorials/jupyters.js, tests/e2e/tutorials/mattward.js, tests/e2e/tutorials/sim4life.js, tests/e2e/tutorials/sleepers.js, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/auto.js
The last step in the e2e testing is to remove the created study. This PR splits that step into two different steps: closeStudy (back to Dashboard) and delete the study.
Sometimes the old merged function was running into troubles because an expected answer was received before starting to listen to it.
=> e2e: split remove study

services/web/client/source/class/osparc/file/FilePicker.js
This PR hides the DownloadLink section in the File Picker.
Once the node-ports support the download link @sanderegg will bring it back.
=> Hide DownloadLink in File Picker

packages/pytest-simcore/src/pytest_simcore/services_api_mocks_for_aiohttp_clients.py, services/director-v2/Makefile, services/director-v2/openapi.json, services/director-v2/src/simcore_service_director_v2/api/routes/computations.py, services/director-v2/src/simcore_service_director_v2/models/domains/comp_tasks.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_pipelines.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py, services/director-v2/tests/integration/test_computation_api.py, services/web/server/src/simcore_service_webserver/director_v2.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/tests/unit/with_dbs/fast/test_director_v2.py
With the director-v2 #1877 some things were too much simplified...
the dynamic services currently need the comp_tasks table to be filled continuously with something similar to the project (until the dynamic sidecar is available and this may become simpler)
**changes**
- director-v2: POST computations now has an additional parameter "start_pipeline" defaulted to False
- director-v2: POST/GET also return a stop_url for convenience
- director-v2: only start the pipeline if "start_pipeline" is set to True
- director-v2: return 422 on POST computations if there is no computational services in the pipeline only when start_pipeline is True
- webserver: brought back calls to update the pipeline when creating/replacing projects
**NOTE:** the outputs of the project are copied into comp_tasks. …
=> Bring back dynamic services retrieve/push

.env-devel, services/web/client/source/class/osparc/dashboard/ExploreBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowserButtonItem.js, services/web/client/source/class/osparc/data/model/Node.js
closes https://github.com/ITISFoundation/osparc-simcore/issues/1986
closes https://github.com/ITISFoundation/osparc-simcore/issues/1994
related to https://github.com/ITISFoundation/osparc-issues/issues/345
=> Fix text filter & Settings to read-only for guest users

services/web/client/source/class/osparc/file/FileDownloadLink.js, services/web/client/source/class/osparc/file/FilePicker.js
While trying to figure out what the filename behind a download link is, sometimes null was set. Making project's validation fail.
This PR makes sure that if the deduced value is null an empty string is set.
=> Fix: Avoid setting null on file File Picker's output label

services/director-v2/src/simcore_service_director_v2/api/routes/computations.py
- director-v2 returns a 500 because a container was not stopped properly.
=> bugfix director-v2 returns 500 when deleting pipeline that is in undefined state

tests/e2e/README.md, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/utils.js
After the informative presentation by @odeimaiz about end-to-end testing, I felt that during the testing there was little information about the backend state. Then, I thought it might be good to have a way to get a direct link to the backend logs at a give time. 
This implements a simple utility function to build links to graylog with a given time spam. Then, this function is used to build a log message next to every call to screenshot that will allow the tester to analyze the backend state corresponding to every front-end screenshot
Added some extra doc.
Following the instructions of the presentation, we can run a tutorial and see the ``Backend Snapshot:  ...`` link next to the screenshot
```cmd
$ cd tests/e2e
$ npm install --save
$ node tutorials/sleepers.js …
```
=> Adding snapshot link to graylog with every call to screenshots

services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py
Improves the workings of the GC to still continue cleaning if there are errors with some user and project data.
=> Report errors during user cleanup

services/sidecar/src/simcore_service_sidecar/celery_configurator.py, services/sidecar/src/simcore_service_sidecar/celery_task.py, services/sidecar/src/simcore_service_sidecar/cli.py, services/sidecar/src/simcore_service_sidecar/core.py, services/sidecar/src/simcore_service_sidecar/utils.py, services/web/server/src/simcore_service_webserver/computation_subscribe.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py
- When a computational task fails, the sidecar retries 2 times. setting the task back to PENDING so another sidecar might take it and run it.
- When the task fails 3 times, the task is set to FAILED
- Show the number of retries in the logs
- When a node fails, it then set the successors of that node to ABORTED
*see GIF below: The chip come from this [PR](https://github.com/ITISFoundation/osparc-simcore/pull/2057)
=> Partial pipelines: Handle retries in sidecar, and failures

packages/models-library/src/models_library/projects_nodes.py
Kember tutorial was failing because a wrong value of 0 is passed as deltaT to the kember service
=> bugfix: director-v2 is implicitely converting float values to int, preventing kember from running

ci/github/unit-testing/api-server.bash, packages/pytest-simcore/src/pytest_simcore/schemas.py, packages/service-library/tests/with_postgres/test_aiopg_utils.py, scripts/common.Makefile, services/docker-compose.yml, services/web/server/src/simcore_service_webserver/director/config.py, services/web/server/src/simcore_service_webserver/director/director_api.py, services/web/server/src/simcore_service_webserver/director/module_setup.py, services/web/server/tests/unit/conftest.py, services/web/server/tests/unit/isolated/test_director_api.py, services/web/server/tests/unit/with_dbs/slow/test_projects.py
Fixes an error in the implementation of ``stop_services`` in ``services/web/server/src/simcore_service_webserver/director/director_api.py`` prevents from stopping services.
- api-server: 
- FIX: typo in ``LOG_LEVEL`` environment variable prevented setting log level
- FIX: missing coverage argument in ci bash script
- FIX: missing namespace in ``test_projects``
- FIX: loop fixture missing in ``test_aiopg_utils`` would produce constant ``FileNotFoundError`` messages upon cleanup
Added a new test ``services/web/server/tests/unit/isolated/test_director_api.py`` that mocks director service API and
runs all functions in ``services/web/server/src/simcore_service_webserver/director/director_api.py`` in a workflow
```
cd osparc-simcore
make devenv …
```
=> bugfix:Fixes/stop services

services/sidecar/src/simcore_service_sidecar/executor.py
fixes the access to the port type by using the correct attribute name (pydantic side effect)
=> bugfix: access port type using proper attribute

services/director-v2/src/simcore_service_director_v2/api/routes/computations.py, services/director-v2/tests/integration/test_computation_api.py
Fixes issue where Mattward/Jupyters e2e was failing.
When there are no computational services in a pipeline, the entries shall still be made in comp_tasks table for the dynamic services to run correctly.
```console
make build-x up-prod
```
create a pipeline with just dynamic services... retrieve data is working as it should.
=> bugfix: pipeline without computational service is not created in comp_tasks table

api/specs/common/schemas/project-v0.0.1-converted.yaml, api/specs/common/schemas/project-v0.0.1.json, packages/models-library/src/models_library/projects_nodes.py, services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json, services/storage/src/simcore_service_storage/api/v0/openapi.yaml, services/storage/src/simcore_service_storage/api/v0/schemas/project-v0.0.1.json, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/api/v0/schemas/project-v0.0.1.json
runHash can be NULL, as defined in pydantic but not picked up by the test comparing the jsonschemas...
=> bugfix: correct project jsonschema regarding runHash field

services/web/client/source/class/osparc/component/filter/NodeTypeFilter.js, services/web/client/source/class/osparc/component/filter/group/ServiceFilterGroup.js, services/web/client/source/class/osparc/component/filter/group/StudyFilterGroup.js, services/web/client/source/class/osparc/component/node/BaseNodeView.js, services/web/client/source/class/osparc/component/service/ServiceJumbo.js, services/web/client/source/class/osparc/component/service/manager/ActivityManager.js, services/web/client/source/class/osparc/component/widget/Thumbnail.js, services/web/client/source/class/osparc/component/workbench/NodeUI.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/dashboard/ServiceBrowserListItem.js, services/web/client/source/class/osparc/dashboard/StudyBrowserButtonBase.js, services/web/client/source/class/osparc/desktop/ControlsBar.js, services/web/client/source/class/osparc/desktop/SlideShowToolbar.js, services/web/client/source/class/osparc/desktop/Toolbar.js, services/web/client/source/class/osparc/desktop/WorkbenchToolbar.js, services/web/client/source/class/osparc/desktop/WorkbenchView.js, services/web/client/source/class/osparc/utils/Services.js, tests/e2e/portal/2D_Plot.js, tests/e2e/portal/3D_Anatomical.js, tests/e2e/portal/3D_EM.js, tests/e2e/portal/Bornstein.js, tests/e2e/portal/CC_Human.js, tests/e2e/portal/CC_Rabbit.js, tests/e2e/portal/Kember.js, tests/e2e/portal/Mattward.js, tests/e2e/portal/opencor.js, tests/e2e/tutorials/tutorialBase.js
closes https://github.com/ITISFoundation/osparc-issues/issues/396
closes https://github.com/ITISFoundation/osparc-issues/issues/387
=> UI improvements

packages/models-library/src/models_library/service_settings.py, packages/models-library/tests/test_service_settings.py, services/sidecar/Dockerfile, services/sidecar/src/simcore_service_sidecar/config.py, services/sidecar/src/simcore_service_sidecar/executor.py
- set sidecar timeout for services to 0 --> no timeout
- allow to set the limits for CPUs and memory per service through the docker image labels (0 should be unlimited)
implements #2121 
1. 
```bash
make build-x up-prod
```
2. run a computational service with memory changes
=> Enhancement 2121: overwrite computational services limits

packages/postgres-database/tests/test_groups.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_assert.py, services/sidecar/src/simcore_service_sidecar/log_parser.py, services/web/server/src/simcore_service_webserver/groups_api.py, services/web/server/src/simcore_service_webserver/resource_manager/config.py, services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py, services/web/server/src/simcore_service_webserver/users_api.py, services/web/server/tests/sandbox/app.py, services/web/server/tests/unit/with_dbs/medium/test_resource_manager.py
Another group of fixes from PR #2079 associated with issues in the garbage collector.
- broad exceptions catches were suppressing ``CancelledError`` which avoided the gc. Since the gc is a periodic background task it could never be cancelled
- some extra fixes in garbage_collector.py
- some coroutines were not awaited
```cmd
make devenv
cd packages/postgres-database
make tests
cd ...
make test-dev-unit
```
cover this bugfix
=> BugFix: fixes awaitables and broad-exceptions in garbage-collector

packages/models-library/src/models_library/projects_pipeline.py, services/director-v2/src/simcore_service_director_v2/api/routes/computations.py, services/director-v2/src/simcore_service_director_v2/models/domains/comp_tasks.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py, services/director-v2/src/simcore_service_director_v2/utils/dags.py, services/director-v2/src/simcore_service_director_v2/utils/db.py, services/director-v2/tests/integration/test_computation_api.py, services/director-v2/tests/mocks/fake_workbench_computational_node_states.json, services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/tests/unit/isolated/test_projects_utils.py, services/web/server/tests/unit/with_dbs/slow/test_projects.py
- director-v2 was only retrieving the states of the running pipeline
- also notify frontend on possible state changes on nodes directly following the node which completed its run
=> getting states of all nodes

services/catalog/src/simcore_service_catalog/api/routes/services.py, services/catalog/src/simcore_service_catalog/core/background_tasks.py, services/catalog/src/simcore_service_catalog/services/director.py, services/catalog/src/simcore_service_catalog/services/frontend_services.py, services/catalog/tests/unit/test_services_frontend_services.py
- FIX: ``GET v0/catalog/services/simcore%2Fservices%2Ffrontend%2Ffile-picker/1.0.0`` for any front-end service failed
=> BugFix: Get service entrypoint also account for front-end

services/director-v2/src/simcore_service_director_v2/utils/dags.py
- to_node_class throws exception when regexp is not found
=> to_node_class throws exception if it does not find the value

scripts/demo/create_portal_markdown.py, services/catalog/src/simcore_service_catalog/services/director.py, services/web/server/src/simcore_service_webserver/catalog_client.py
FIX: While reviewing failures on e2e, I found that the catalog failed when requests had to return empty lists. 
CHANGED: added extra options to script to produce invitations
=> BugFix: handling empty list of services in catalog services and module-app

services/director-v2/src/simcore_service_director_v2/utils/dags.py
fixes in the director-v2 for retrieving states of all nodes prevent saving from control loops which are not acyclic graphs.
=> BugFix: re-allow for control loops

services/docker-compose.yml, tests/e2e/tutorials/jupyters.js, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/auto.js, tests/e2e/utils/utils.js
wait until jupyter notebook completed execution
Bonus:
- add some healthchecks for postgres/redis
=> wait for notebook to complete

services/docker-compose.yml, tests/e2e/tutorials/jupyters.js
- run all cells with menu command
- fix healthcheck on postgres
=> E2e wait for notebook2

packages/simcore-sdk/src/simcore_sdk/node_data/data_manager.py, packages/simcore-sdk/src/simcore_sdk/node_ports/filemanager.py, packages/simcore-sdk/tests/integration/test_filemanager.py, services/director/src/simcore_service_director/producer.py
- addresses the last issues with the state puller
- enhances error messages when containers are not attached to networks
=> Final bugs for state_puller

services/storage/src/simcore_service_storage/handlers.py
When requesting metadata for a file which dose not exist storage would be crashing. This is now avoided.
**Note:** without this fix deployed to staging and production the fixed jupyter-labs will not work.
=> if metadata file did not exist it would crash

services/web/server/src/simcore_service_webserver/director_v2.py
when some network glitch happens when webserver talks with director-v2 to get the pipeline status a 500 could come back to the frontend. Now this should be catched and an UNKNOWN status is returned.
partially fixes #2155
=> Webserver: handle 500s from director-v2 gracefully

services/docker-compose.yml
- add a retry middleware on the webserver: in case of 500 a retry will be done (3x) before returning 500 to the frontend
- add load balancer healthchecking of the webserver as traefik label so that traefik recognize when the webserver is not available anymore. NOTE: the webserver still need to issue a 503 when shutting down, with the header field Retry-After set to something reasonable. the webclient shall read this and retry then before failing.
- set the healthcheck for traefik 
(⚠️ devops) = simcore_traefik commands must be adapted @Surfict , @pcrespov , @GitHK :
```yaml
- "--ping=true"
- "--entryPoints.ping.address=:9082"
- "--ping.entryPoint=ping"
- - "--providers.docker.swarmModeRefreshSeconds=1"
```
Zero downtime: Connected users should be able to continue working with osparc when …
=> Zero time restart

services/docker-compose.yml, services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/director_v2.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/tests/integration/test_project_workflow.py
=> reduce traefik latency check, and remove unnecessary warnings when a pipeline does not exist

api/specs/webserver/openapi.yaml, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/tests/integration/test_exporter.py
after talking to @odeimaiz I changed export entrypoint to the original path. I thought it was a typo but apparently @GitHK had some reason to set it up that way. For the moment it is best to revert it so the front-end can export
@GitHK could you please add extra input on this issue?
=> Reverted :export to :xport 

ci/github/system-testing/e2e.bash, services/api-server/src/simcore_service_api_server/api/dependencies/database.py, services/api-server/src/simcore_service_api_server/db/repositories/_base.py, services/api-server/src/simcore_service_api_server/db/repositories/api_keys.py, services/api-server/src/simcore_service_api_server/db/repositories/users.py, services/api-server/tests/unit/_helpers.py, services/catalog/src/simcore_service_catalog/api/dependencies/database.py, services/catalog/src/simcore_service_catalog/core/background_tasks.py, services/catalog/src/simcore_service_catalog/db/repositories/_base.py, services/catalog/src/simcore_service_catalog/db/repositories/dags.py, services/catalog/src/simcore_service_catalog/db/repositories/groups.py, services/catalog/src/simcore_service_catalog/db/repositories/projects.py, services/catalog/src/simcore_service_catalog/db/repositories/services.py, services/director-v2/src/simcore_service_director_v2/api/dependencies/database.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/_base.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_pipelines.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/projects.py, services/docker-compose.yml, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py
=> FastAPI services: remove limitation of 1 connection per request

services/web/Dockerfile, services/web/server/src/simcore_service_webserver/exporter/formatters/sds/xlsx/templates/directory_manifest.py, tests/swarm-deploy/test_service_images.py
- fixes how libmagic is installed and the version which is installed
- adds a test to check that libmagic is present int he webserver
=> Fix libmagic install via Docker

packages/models-library/src/models_library/projects_nodes.py, packages/models-library/src/models_library/projects_nodes_io.py, packages/models-library/tests/test_project_nodes_io.py, services/api-server/src/simcore_service_api_server/utils/solver_job_models_converters.py, services/api-server/tests/unit/test_utils_solver_job_models_converters.py, services/web/server/tests/integration/test_exporter.py
- Fixes [test failure](https://github.com/ITISFoundation/osparc-simcore/pull/2220/checks?check_run_id=2244051004) of ``services/web/server/tests/integration/test_exporter.py::test_import_export_import_duplicate[export_version0]`` caused by a ``ValidationError`` after changes in the constraints of ``BaseFileLink`` models in ``packages/models-library/src/models_library/projects_nodes_io.py``
This issue detected that ``BaseFileLink`` had some inconsistencies when compared with ``api/specs/common/schemas/project-v0.0.1.json``, specifically in the ``dataset`` field. THIS NEEDS review when storage is refactored.
NOTE: This test was temporary disabled in [PR#2220](https://github.com/ITISFoundation/osparc-simcore/pull/2220) so it could be resolved separately for clarity.
```cmd
make devenv
source …
```
=> Fixes project validation of FileLinks

.env-devel, packages/models-library/src/models_library/settings/postgres.py, packages/postgres-database/tests/docker-compose.yml, packages/simcore-sdk/src/simcore_sdk/config/db.py, services/docker-compose.yml, services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py, services/web/server/src/simcore_service_webserver/config/server-defaults.yaml, services/web/server/src/simcore_service_webserver/config/server-docker-dev.yaml, services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml, services/web/server/src/simcore_service_webserver/db.py, services/web/server/tests/integration/conftest.py, services/web/server/tests/unit/with_dbs/config-devel.yml, services/web/server/tests/unit/with_dbs/config.yaml, tests/e2e/utils/wait_for_services.py
pgBouncer works best in Transaction pooling mode with our aiopg backend. BUT, this mode does not allow for listening to postgres notifications see [here](https://www.pgbouncer.org/features.html)
therefore, a direct connection to postgres is allowed for the webserver service ONLY to this end. everything else seems to work as expected until now.
- changed the docker container used for pgbouncer as it was deprecated... now using edoburu/pgbouncer:1.15.0@sha256:2f47bf272fa9fdf25c100d11f1972b23af61a351a136d3721bfa6bdb52630426
- increase max_client_conn to 10000 on pgbouncer to allow for err... 10000 clients... not the default 100...
- POSTGRES_LONG_RUNNING_SESSION_HOST env variable added to .env-devel for direct connections with postgres DB
-   (⚠️ devops) due to change of docker image …
=> Allow a direct connection to postgres from webserver for LISTEN/NOTIFY channel

services/storage/src/simcore_service_storage/dsm.py, services/storage/tests/conftest.py, services/storage/tests/docker-compose.yml, services/storage/tests/test_access_layer.py, services/storage/tests/test_rest.py
Theory:
- the pgBouncer is in transaction pooling mode: it allows a client to connect, the client makes a transaction, then the bouncer sets the connection back into the pool
- when storage is connected directly to the postgres DB nothing weird happen
- some of the calls storage does may need to keep the connection? some explicit transaction begin were added to try to fix this as I could not reproduce the issue locally.
=> Pg bouncer issue with storage

packages/service-library/src/servicelib/archiving_utils.py, packages/service-library/tests/test_archiving_utils.py, packages/service-library/tests/test_archiving_utils_extra.py, packages/simcore-sdk/src/simcore_sdk/node_ports/filemanager.py
- ``unarchive_dir`` returns set of paths extracted from archive 
- tests unarchive+prune algorithm will be used in the jupyter-commons library to fix #2256
- ADDS ``PrunableFolder`` class to gather capture+prune operations
NOTE: These changes will be imported into jupyter-common next.
- FIXES: Avoid empty state while updating work directory in dynamic services #2256 
- Might FIX: Jupyter displays "Directory not found" menu permanently ITISFoundation/osparc-issues#412
```
make devenv
make tests
```
=> Changes unarchive_dir and tests unarchive+prune algorithm

services/api-server/.env-devel, services/api-server/src/simcore_service_api_server/core/settings.py
``osparc-ops-environments`` repo defines host variable as ``DIRECTOR_V2_HOST`` in ``services/simcore/.env`` and api-server could not capture it so it could not communicate with the director-v2 service.
Fixes error ``service not found`` in api-server when queried solvers resources
``/v0/status`` should return all services healty
=> BugFix: Fixes env_prefix for director2 in api-server

services/web/server/src/simcore_service_webserver/diagnostics.py, services/web/server/src/simcore_service_webserver/diagnostics_config.py
Variable setting the time threshold for slow callbacks was wrong. This is set by ``AIODEBUG_SLOW_DURATION_SECS`` which defaults to 1 seconds. 
How does this work? If an async task in the loop blocks more than``AIODEBUG_SLOW_DURATION_SECS`` then a warning is logged in the console. This allows us to detect blocking of tasks by sync calls.
It should help to answer why traffik qualifies the webserver as unhealth on his 1secs periodic checks
=> Minor fix on diagnistics settings

services/web/client/source/class/osparc/dashboard/StudyBrowserButtonBase.js
2 lines for the title and text wrapping:
closes https://github.com/ITISFoundation/osparc-issues/issues/447
=> Two lines max for Study Title card

services/web/client/source/class/osparc/dashboard/ExploreBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, tests/e2e/utils/auto.js
e2e: Wait until all templates reach the frontend before starting one.
=> e2e: wait for all templates

services/docker-compose.yml, services/web/server/src/simcore_service_webserver/diagnostics_config.py
Fixes validation function for ``DiagnosticsSettings.max_task_delay``.  The variable failed when set using ``DIAGNOSTICS_MAX_TASK_DELAY`` environment variable. 
Now ``DIAGNOSTICS_MAX_TASK_DELAY=30`` secs
- Probably cause for frequent restart of web-server in production
- Currently production defaults ``DiagnosticsSettings.max_task_delay`` to 3 secs (after fixing #2288) which marks the webserver as un-healthy after a request takes more than 3 secs !!
- #2288
-  Frequent restart of web-server in production
=> Hotfix: Fix/validation diagnostics

tests/e2e/utils/auto.js
Fix: the first study puppeteer was trying to delete could be the "Loading studies card"
=> e2e: fix delete study

tests/e2e/utils/utils.js
Addresses the issue below:
```
Tutorial error: TypeError: Cannot use 'in' operator to search for 'state' in null
```
=> fixes and issue with e2e utils

Makefile, tests/performance/Dockerfile, tests/performance/Makefile, tests/performance/catalog_services.py, tests/performance/director_services.py, tests/performance/docker-compose.yml
Locust is a tool that allows to call entrypoints in parallel and get a nice graph from that.. it allows for testing our deployments.
replaces #2308
=> added locust facilities with more workers

services/web/server/src/simcore_service_webserver/catalog_client.py
PR [#2302](https://github.com/ITISFoundation/osparc-simcore/issues/2302) incorrectly set a super tight timeout for testing purpose and this went into the code by mistake.
This PR sets it back to defaults.
=> remove super tight timeout in calling catalog dags endpoints

services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py
aiopg has a bug when using the listen/notify pattern with postgres. In case postgres is restarted or unavailable the listening task is not reset see [aiopg issue](https://github.com/aio-libs/aiopg/pull/559#issuecomment-826813082).
Therefore the webserver listening task would stop working in such cases.
the listening pattern was slightly changed to first check if the connection is still open. if not the case then an exception is thrown and the listening task is restarted automatically.
fixes #2246
=> Bugfix: ensure services outputs are updated in frontend when database restarts

services/storage/src/simcore_service_storage/dsm.py
calling aiobotocore.list_objects_v2 method with a Prefix is several order of magnitudes faster when Prefix is ending with a /
e.g.:
looking for files in of project 0000802f-1e81-551f-8ab2-769c941aac66:
```python
client.list_objects_v2(Prefix="0000802f-1e81-551f-8ab2-769c941aac66") # this is SLOWWWWWWWWWW
client.list_objects_v2(Prefix="0000802f-1e81-551f-8ab2-769c941aac66/") # this is FASTTTTTTTTTT
```
for example on master, the first call takes 12 seconds to complete... while the second call takes a few ms...
=> Bugfix: make listing of S3 objects faster in storage

services/sidecar/src/simcore_service_sidecar/boot_mode.py, services/sidecar/src/simcore_service_sidecar/celery.py, services/sidecar/src/simcore_service_sidecar/celery_configurator.py, services/sidecar/src/simcore_service_sidecar/celery_task.py, services/sidecar/src/simcore_service_sidecar/cli.py, services/sidecar/src/simcore_service_sidecar/core.py, services/sidecar/src/simcore_service_sidecar/executor.py, services/sidecar/tests/integration/conftest.py, services/sidecar/tests/integration/test_sidecar.py
=> Bugfix: re-enable SC_COMP_SERVICES_SCHEDULED_AS passed to computational services

scripts/maintenance/clean_projects_of_user.py, scripts/maintenance/create_user.py, scripts/maintenance/import_projects_as_template.py, scripts/maintenance/requirements.txt
Example:
```console
for i in {01..20}; do ./create_user.py ENDPOINT puppeteer_$i@itis.testing PASSWORD; done
```
```console
./import_projects_as_template.py http://127.0.0.1:9081 iamauser@osparc.io PASSWORD /my/file/path/50b7\#SHA256=2538b018162c842fd1c67096a88ba2cb19366b39b8b93ec19a7afafeca7a7fdc.osparc --project-name "some funky name" --share-with-gid 2
```
=> added script to create new users, and import projects as template

packages/service-library/requirements/_base.in, packages/service-library/requirements/_base.txt, packages/service-library/src/servicelib/monitor_slow_callbacks.py, services/web/server/tests/unit/isolated/test_healthcheck.py
During the analysis of logs coming from production there were lots of entries similar to:
```bash
servicelib.monitor_slow_callbacks:instrumented(28) - Executing <Task finished coro=<Application._handle() done, defined at /home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_app.py:428> result=<Response OK not prepared>> took 7.647 seconds
```
Adding `pyinstrument.Profiler` will help  format the output of the slow callbacks. A full traceback of the call will be logged.
**WARNING:** there is a [slight performance hit](https://github.com/joerick/pyinstrument#how-is-it-different-to-profile-or-cprofile) for running the profiler. I think this is worth it in order to have more meaningful log messages which will help debugging the stack.
**Trivia**
While looking for the current solution, …
=> using pyinstrument to log traceback of slow callbacks

packages/models-library/tests/test_package.py, packages/pytest-simcore/src/pytest_simcore/websocket_client.py, packages/service-library/tests/conftest.py, packages/service-library/tests/test_package.py, packages/simcore-sdk/tests/unit/test_package.py, services/api-server/tests/unit/test__code_syntax.py, services/catalog/tests/unit/test__code_syntax.py, services/sidecar/tests/unit/test_code_syntax.py, services/storage/tests/conftest.py, services/storage/tests/test_package.py, services/web/server/requirements/_base.in, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt, services/web/server/requirements/_tools.txt, services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py, services/web/server/src/simcore_service_webserver/socketio/handlers_utils.py, services/web/server/tests/integration/01/test_exporter.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/integration/02/test_computation.py, services/web/server/tests/integration/02/test_rabbit.py, services/web/server/tests/unit/conftest.py, services/web/server/tests/unit/isolated/test_diagnostics.py, services/web/server/tests/unit/isolated/test_package.py, services/web/server/tests/unit/with_dbs/06/test_projects_02.py, services/web/server/tests/unit/with_dbs/09/test_projects_01.py, services/web/server/tests/unit/with_dbs/10/test_resource_manager.py, services/web/server/tests/unit/with_dbs/conftest.py
General maintenance of the ``webserver``
- CHANGES: makes ``metrics_handler``  implementation async by using a thread pool executor ot execute ``prometheos_client.generate_latest`` call
- CHANGES: general upgrade of webserver dependencies:
- ``aiohttp`` and ``python-socketio`` **cannot be upgraded** to the latest. Needs further refactoring (see #2008 and notes in requirement files)!
- FIXES: ``services/web/server/tests/integration/01/test_exporter.py`` **was de-activated**.  
-  Minor refactoring of fixtures
- CHANGES: unified pylint testing by reusing ``pytest-simcore`` utils
- CHANGES: moves socket-io fixtures to ``simcore-pytest``
- Remove trafaret dependency by pydantic-settings
- Remove constraints to aiohttp and python-socketio
- Replace openapi-core by pydantic (evaluate …
=> Refactoring webserver: async metrics handler, upgrades dependencies and fixes testing fixtures

api/specs/common/schemas/running_service.yaml, api/specs/director/openapi.yaml, services/director/requirements/_test.in, services/director/requirements/_test.txt, services/director/src/simcore_service_director/api/v0/openapi.yaml, services/director/src/simcore_service_director/producer.py, services/director/src/simcore_service_director/rest/generated_code/models/inline_response2003_data.py, services/director/src/simcore_service_director/rest/generated_code/models/simcore_node.py, services/director/src/simcore_service_director/rest/handlers.py, services/director/tests/test_handlers.py, services/director/tests/test_producer.py, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/director/director_api.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py, services/web/server/tests/unit/isolated/test_director_api.py, services/web/server/tests/unit/with_dbs/09/test_projects_01.py, services/web/server/tests/unit/with_dbs/10/test_resource_manager.py
- ```/running_interactive_services/{service_uuid}:``` DELETE has now an optional parameter to explicitly ask to save the service state when removing it from the swarm
- ```RunningServiceType``` now contains the user_id. This allows to know who started the service originally
- uses *aioresponses* mock library for testing (does not add any other dependency to the director frozen requirements)
-  re-generated the handlers code (minor changes, mostly some regexes that were missing)
- add necessary tests
- removed copy/pasted code in projects_api.py and use the director_api.py code instead
- when removing dynamic services, check if the user is a guest. If yes, then ask not to save the service state.
- improve tests to this end
```
make build
pytest -vvx …
```
=> Dynamic service: Do not save state for GUEST users

tests/performance/Makefile
allow overriding the maximum average response time (default to 200ms) when ping testing
=> Performance testing: allow setting maximum average response time

services/web/client/source/class/osparc/Error.js, services/web/client/source/class/osparc/data/Resources.js
- Error page:
- Show human friendly error code text
- More space for displaying entire error message
- Unresponsive backend:
- Improve error handling
- Add "Please, try again later" to 404 and 503 error messages
closes https://github.com/ITISFoundation/osparc-simcore/issues/2283
closes https://github.com/ITISFoundation/osparc-simcore/issues/2350
=> Better error handling

services/web/client/source/class/osparc/auth/Data.js, services/web/client/source/class/osparc/auth/Manager.js, services/web/client/source/class/osparc/component/metadata/QualityEditor.js, services/web/client/source/class/osparc/component/metadata/ServicesInStudy.js, services/web/client/source/class/osparc/component/permissions/Study.js, services/web/client/source/class/osparc/dashboard/StudyBrowserButtonItem.js, services/web/client/source/class/osparc/data/model/Study.js, services/web/client/source/class/osparc/desktop/StudyEditor.js, tests/e2e/portal-files/VTK_file.js
When sharing a study with an Organization, no matter Organization's role in the collaboration, its' members will only have ```viewer``` access to it.
This PR fixes that bug.
Before:
After:
closes https://github.com/ITISFoundation/osparc-simcore/issues/2272
=> Bugfix: Share study with Organization

services/web/server/requirements/_test.in, services/web/server/requirements/_test.txt, services/web/server/src/simcore_service_webserver/activity/celery_client.py, services/web/server/src/simcore_service_webserver/activity/config.py, services/web/server/src/simcore_service_webserver/activity/handlers.py, services/web/server/src/simcore_service_webserver/activity/module_setup.py, services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py, services/web/server/src/simcore_service_webserver/computation_utils.py, services/web/server/tests/unit/isolated/test_activity.py, services/web/server/tests/unit/with_dbs/04/test_computation_utils.py
=> Init celery application in app once + run call to blocking call in executor

packages/models-library/src/models_library/settings/celery.py, services/docker-compose-ops.yml, services/sidecar/src/simcore_service_sidecar/mpi_lock.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/src/simcore_service_webserver/resource_manager/config.py, services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py, services/web/server/src/simcore_service_webserver/resource_manager/redis.py, services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py, services/web/server/src/simcore_service_webserver/studies_access.py, services/web/server/src/simcore_service_webserver/studies_dispatcher/_users.py
When a project is opened in the backend (:open endpoint in webserver) a distributed redis lock for the whole resource registry is acquired to prevent multiple opening of the same project by different users. 
In case the lock acquisition fails, an exception is risen and the secure fallback is to report that the project is locked, which is fine.
The problem arise when on e2e when 20 users are creating a project at the same time, trying to lock the whole resource registry at the same time, which is a bottleneck. Why it suddenly appeared is an unknown, but might be due to computer power, or some changes in the docker swarm distribution of services.
as a reminder: to lock a redis distributed lock we use aioredlock library, which by default tries 3 times to lock and then raise an exception in …
=>   🐛 Project locked issue (e2e issue) (⚠️ devops)

packages/service-library/src/servicelib/archiving_utils.py
Currently, extracting zip files is done with a ProcessPool using all available cpu cores. This can be pretty heavy and, for instance on AWS, can make a cluster node completely unresponsive. I suggest to cap at 2. Once this is in, all dynamic services that consume that need to be updated.
=> 🏗️ Arbitrarily cap unarchiving to 2 workers

services/web/client/source/class/osparc/component/form/renderer/PropForm.js, services/web/server/src/simcore_service_webserver/catalog_api_handlers.py, services/web/server/tests/unit/isolated/test_catalog_api_handlers.py
We will allow matching ``data:*/* -> data:concrete`` types in a non-strict check mode. This will allow e.g. connecting a file picker (producing ``data:*/*``) with a sleeper (accepts ``data:text/plain``). 
There is obviously a chance that the file produced by the file-picker is not ``data:text/plain`` but this API is intended for a first check. Further plausibility checks will use strict mode and detect this failure. 
This strict/non-strict approach is convenient for UI/UX purposes.
- Fixes ITISFoundation/osparc-issues#442: cannot link files from File Picker to some cardiac model nodes
```command
make devenv
cd web/server
pytest tests/unit/isolated/test_catalog_api_handlers.py 
```
=> 🐛 Allows port matching from general to concrete data

services/web/client/source/class/osparc/component/task/Export.js, services/web/client/source/class/osparc/dashboard/StudyBrowserButtonItem.js
Implements the front end part for locked studies:
related to https://github.com/ITISFoundation/osparc-simcore/issues/1952: frontend part
=> Locked study icons

api/specs/director/openapi.yaml, services/director/src/simcore_service_director/api/v0/openapi.yaml, services/director/src/simcore_service_director/exceptions.py, services/director/src/simcore_service_director/producer.py, services/director/src/simcore_service_director/rest/handlers.py, services/director/tests/test_handlers.py
Moves changes relative to the `director-v0` from https://github.com/ITISFoundation/osparc-simcore/pull/1887
- Adds an API to recover service label. The labels are fetched form the docker image
=> 🔨adds new api endpoint for labels from PR1887

services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/socketio/handlers.py, services/web/server/tests/unit/with_dbs/10/test_resource_manager.py, services/web/server/tests/unit/with_dbs/docker-compose-devel.yml
if a user closes a tab opened on a study, and has another tab showing the dashboard, the project will not automatically unlock unless the user refreshes the remaining tab.
This PR shall solve this by sending a websocket event to all tabs a user has opened.
fixes [#431](https://github.com/ITISFoundation/osparc-issues/issues/431)
=> ✨Enhancement/detect user logged out

api/specs/storage/openapi.yaml, api/specs/webserver/components/schemas/locations.yaml, api/specs/webserver/openapi-storage.yaml, packages/postgres-database/src/simcore_postgres_database/migration/versions/c2d3acc313e1_adds_admin_to_userrole_enum.py, packages/postgres-database/src/simcore_postgres_database/models/users.py, services/storage/requirements/_base.in, services/storage/requirements/_test.in, services/storage/src/simcore_service_storage/api/v0/openapi.yaml, services/storage/src/simcore_service_storage/dsm.py, services/storage/src/simcore_service_storage/handlers.py, services/storage/src/simcore_service_storage/settings.py, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/security_roles.py, services/web/server/src/simcore_service_webserver/storage_handlers.py, services/web/server/tests/unit/with_dbs/04/test_storage.py
storage metadata table keeps track of the data in S3. We noticed that the information is out-of-sync in many deploys mostly due to data deleted in S3 but still remains annotated in the storage metadata table. Previous PR added a sync method to syncronize the metadata table but due to the large amount of objects in S3 the requests timed out and the operation could not be completed.
- 🩹 fix sync between storage's metadata table and s3 objects: 
- PROBLEM: current sync makes webserver handler time out when s3 holds a lot of data.
- SOLUTION: improves check speed in S3 and adds option to fire&forget in query
- ✨ adds new user role **ADMIN**. Resync operation can only be done by **ADMIN users**
- ✨  api data lifetime: all files created via API (e.g. uploads OR job results) have an expiration …
=> 🩹 Adds query option to avoid timeout for storage metadata sync

services/director-v2/src/simcore_service_director_v2/core/application.py, services/director-v2/src/simcore_service_director_v2/core/settings.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_services.py, services/director-v2/tests/conftest.py, services/director-v2/tests/unit/conftest.py, services/director-v2/tests/unit/test_core_settings.py, services/director-v2/tests/unit/test_modules_celery.py
Settings introduced in PR #2411 fail to initialize when deployed in master environment
```log
File "/home/scu/.venv/bin/uvicorn", line 8, in <module>
sys.exit(main())
File "/home/scu/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/scu/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/scu/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/scu/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/scu/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 362, in main
run(**kwargs)
File …
```
=> 🐛 Fixes dynamic-sidecar settings in director-v2

services/web/client/source/class/osparc/component/form/Auto.js
Frontend was expecting the enum options to be under widget.details.structure while the schema says it goes under widget.structure
=> Frontend SelectBox complies with schema

packages/models-library/src/models_library/services.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_api.py
The `SIMCORE_SERVICES_NETWORK_NAME` is prefixed with the stack name which contains dashes (`-`):
- added regression test
- dashes are now allowed for `SIMCORE_SERVICES_NETWORK_NAME`
=> 🐛 SIMCORE_SERVICES_NETWORK_NAME now allows dashes

tests/swarm-deploy/test_swarm_runs.py
- Disable test_swarm_runs test that is testing:
1. whether all services are up on the first trial
2. implicitely should show that the services are up in a specific amount of time
Currently the problem is that most of the services are depending on *postgres* service being up and migrated by the *migration* service. If the computer running the stack is a bit slow, then we might have director-v2 trying to access tables that are not existing yet and then failing -> failing the test cause the director-v2 will be restarted.
For now we decided to disable the test since, we already have others that test whether all the services EVENTUALLY finally started and it seems to be ok for now.
Let's see if we end up having services needing 10 trials to start up in the next weeks.
closes #2430
=> Disable test_swarm_runs failing 2/3 of the time

packages/settings-library/src/settings_library/celery.py, services/sidecar/src/simcore_service_sidecar/celery.py, services/sidecar/src/simcore_service_sidecar/celery_task.py, services/sidecar/src/simcore_service_sidecar/celery_task_utils.py, services/sidecar/src/simcore_service_sidecar/cli.py, services/sidecar/src/simcore_service_sidecar/rabbitmq.py, services/sidecar/src/simcore_service_sidecar/utils.py, services/sidecar/tests/unit/test_rabbitmq.py
Cancelling tasks seems to have been failing since a couple of PRs went in.
First, the python 3.8 PR changed how asyncio.loop.call_soon is to used.
Then, when the redis database was splitted in 3 separate DBs (one redis instance with 3 databases) instead of 1. the director-v2 celery client was not fixed accordingly.
This has lead to the following:
1. Cancelling a pipeline would cancel the tasks AFTER the one currently running correctly. BUT the currently running tasks would still run until completion instead of being stopped.
2. When a sidecar is shutdown, the currently running task would not be correctly cancelled.
Both of these issues are now fixed.
```
make build-devel up-devel
```
then start a pipeline with 1sleeper that lasts more than 2 seconds... cancel it. it should instantly be …
=> 🐛 aborting tasks fails

packages/service-library/src/servicelib/monitor_services.py, packages/service-library/src/servicelib/monitoring.py, services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py
After some googling on prometheus and the way metrics  are named and labelled some first conclusions:
1. a metrics shall only be generated if it is needed
2. each pair of metric-label equals a time series with an overhead of about 3kb
3. promeheus AND the application creating the metrics stores the metrics in the form of time series
Now we currently generate the following metrics in storage, director, webserver and any aiohttp-based service:
1. http_requests_total as a prometheus Counter
2. http_request_latency_seconds as a prometheus Histogram
3. http_requests_in_progress_total as a prometheus Gauge
We currently only need http_requests_total in the grafana dashboards. Therefore 2. and 3. are removed in this PR. Checking the prometheus GUI one can see that the Cardinality of the …
=> removing unused metrics that might be the culprit

.github/dependabot.yml, .github/workflows/ci-release.yml, .github/workflows/ci-staging.yml, .github/workflows/ci-testing-deploy.yml, ci/github/helpers/setup_docker_compose.bash, ci/github/helpers/setup_docker_experimental.bash, tests/environment-setup/test_used_docker_compose.py
Docker buildx v0.6.0 seems to have broken the docker bake application. the baked cookies are not getting the environment variables expanded as they used to in the version before.
Until this is clarified see [issue](https://github.com/docker/buildx/issues/703) the version of docker buildx will be set to 0.5.1.
Coming from the PR #2360, the github action to setup docker buildx with a specific version will be used.
bonus:
- dependabot on github actions added
- use github matrix to set versions on docker-compose and docker buildx
=> ♻️ Maintenance/fix docker buildx in CI

Makefile, ci/deploy/dockerhub-deploy.bash
`BUILD_TARGET` is now required by `docker-compose-build.yml` when using `make push`. 
The command will merge `docker-compose-build.yml` and `docker-compose-deploy.yml` and the `image` field will be overwritten with the values from `docker-compose-deploy.yml`. 
The value assigned to `BUILD_TARGET` is not important, it just needs to be present.
=>   🐛 fixing push to docker hub

services/web/client/source/class/osparc/Application.js, services/web/client/source/class/osparc/navigation/NavigationBar.js, services/web/client/source/class/osparc/ui/switch/ThemeSwitcher.js
This PR brings the Theme Switcher to the login page
osparc:
s4l:
closes https://github.com/ITISFoundation/osparc-simcore/issues/2482
=> Show the Theme Switcher also in the Login Page

services/web/server/src/simcore_service_webserver/projects/projects_api.py
Context:
the webserver starts the dynamic services by calling the director-v2.
When dynamic services that use the NEW dynamic sidecar are started, they set up a traefik proxy with some specific parameters regarding CORS. These needs to have the correct scheme (http/https).
In deployment cases the scheme is https and is given by the X-Forwarded-Proto header.
=> Dynamic sidecar isse: use X-Forwarded-Proto if available

services/web/client/source/class/osparc/navigation/BreadcrumbsSlideShowEdit.js
Since the plus buttons in the edition of the guided mode are able to modify the pipeline connections, in order to avoid issues with services that might have some work done and lose their input connections, for now, plus buttons will only be placed at the beginning and end. That way the intermediate connections will not be modified.
=> Guided Mode: Plus buttons only at the beginning and end

services/sidecar/src/simcore_service_sidecar/executor.py
While using the dask scheduler the job_id of each task has been modified to follow the pattern:
```job_id=SERVICEKEY_SERVICEVERSION__projectid_PROJECTID__nodeid_NODEID__UUID```
The sidecar binds this path inside the computational service in the following paths:
```bash
/input/job_id
/output/job_id
/log/job_id
```
The CC 0D services fails with a segfault and this seems to be related.
=>   🐛 Dask scheduler: set bound folders inside container without job id

scripts/maintenance/check_consistency_data.py, scripts/maintenance/consistency/docker-compose.yml, scripts/maintenance/requirements.txt
- adds a script for checking consistency between the file entries in the projects/file_meta_data tables in the database and what is available on S3
The scripts does the following:
pre-requisite:
- local docker volume containing a database from a deployment (see ```make import-db-from-docker-volume``` in /packages/postgres-database)
1. from the local DB parses the projects table for all the node UUIDs available used by some non-GUEST user
2. from the local DB parses the file_meta_data table for all file entries corresponding to the node UUIDs from 1.
3. from the corresponding S3 endpoint parses all the file corresponding to the node UUIDs from 1.
4. Compare files parsed in DB to the ones in S3
5. create a report as csv file containing
=> ✨ Maintenance/add consistency scripts

scripts/maintenance/check_consistency_data.py, scripts/maintenance/consistency/dump-restore.md
- also print out valid files CSV
- added some doc
=> ✨ Maintenance/enhance consistency checks

services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter.py, services/storage/src/simcore_service_storage/dsm.py, services/storage/src/simcore_service_storage/s3wrapper/s3_client.py, services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py, services/web/server/src/simcore_service_webserver/storage_api.py
Analyzed logs of ``webserver``, ``storage`` and ``datcoreadapter`` services.  Found and fix the folling issues:
- Increases *total timeout* from **20 secs to 5 mins** so it takes time to copy 
```log
ERROR: aiohttp.server:log_exception(393) - Error handling request
File "/home/scu/.venv/lib/python3.8/site-packages/simcore_service_webserver/diagnostics_monitoring.py", line 72, in _middleware_handler
resp = await handler(request)
File "/home/scu/.venv/lib/python3.8/site-packages/aiohttp_session/__init__.py", line 154, in factory
response = await handler(request)
File "/home/scu/.venv/lib/python3.8/site-packages/servicelib/rest_middlewares.py", line 67, in _middleware_handler
return await handler(request)
File …
```
=>   🐛 bugfix fails to copy studies with lots of data

services/web/client/source/class/osparc/data/Permissions.js, services/web/client/source/class/osparc/data/model/Study.js, services/web/client/source/class/osparc/utils/Study.js
Copy thumbnail only if exists
Bonus
Before:
After:
=> 🐛 bugfix: Copy thumbnail only if exists

services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/src/simcore_service_webserver/socketio/handlers.py
The following error was spotted while debugging issues with parallel testing of jupyters.
now a proper warning message is created and the error is not raising uncontrolled.
```console
021-09-23T06:59:52.764498729Z ERROR: /home/scu/.venv/lib/python3.8/site-packages/simcore_service_webserver/resource_manager/websocket_manager.py:managed_resource(180) - Error in web-socket for user:20159, session:328d7423-8413-467c-8cd1-d4474ff64c85
2021-09-23T06:59:52.764538763Z Traceback (most recent call last):
2021-09-23T06:59:52.764548797Z   File "/home/scu/.venv/lib/python3.8/site-packages/engineio/server.py", line 604, in _get_socket
2021-09-23T06:59:52.764557145Z     s = self.sockets[sid]
2021-09-23T06:59:52.764564040Z KeyError: '93b1c8c8939b4671b580b401d55a0511'
2021-09-23T06:59:52.764585166Z …
```
=> 🐛 Bugfix: handle error when webserver disconnects an already disconnected socket

services/web/client/source/class/osparc/component/workbench/BaseNodeUI.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/dashboard/CardBase.js, services/web/client/source/class/osparc/dashboard/ExploreBrowser.js
Bonus:
related to https://github.com/ITISFoundation/osparc-issues/issues/465
related to https://github.com/ITISFoundation/osparc-issues/issues/487
=> UI/UX: Workbench improvements

ci/github/system-testing/public-api.bash, packages/pytest-simcore/src/pytest_simcore/docker_compose.py, packages/pytest-simcore/src/pytest_simcore/docker_swarm.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_environs.py, packages/pytest-simcore/src/pytest_simcore/simcore_dask_service.py, packages/pytest-simcore/src/pytest_simcore/simcore_services.py, services/director-v2/src/simcore_service_director_v2/utils/logging_utils.py, services/director-v2/tests/conftest.py, services/director-v2/tests/integration/01/test_computation_api.py, services/director-v2/tests/integration/02/test__dynamic_sidecar_nodeports_integration.py, services/director-v2/tests/integration/02/test_dynamic_services_routes.py, services/director-v2/tests/integration/02/test_mixed_dynamic_sidecar_and_legacy_project.py, services/sidecar/tests/integration/test_mpi_lock.py, services/web/server/tests/integration/01/test_exporter.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/integration/01/test_project_workflow.py, services/web/server/tests/integration/02/test_computation.py, services/web/server/tests/integration/conftest.py, services/web/server/tests/integration/webserver_dev_config.yaml, tests/public-api/conftest.py, tests/public-api/requirements/_test.in, tests/public-api/requirements/_test.txt, tests/public-api/requirements/_tools.txt
- public-api CI job shall wait for simcore services to be ready before running tests
- ``simcore_services_ready`` is a module fixture that checks healthcheck entrypoints until all selected core services are ready
=> ♻️ Maintenance/improve public api ci job

packages/pytest-simcore/src/pytest_simcore/rabbit_service.py, packages/pytest-simcore/src/pytest_simcore/simcore_services.py, packages/pytest-simcore/src/pytest_simcore/websocket_client.py, services/web/server/src/simcore_service_webserver/groups_api.py, services/web/server/src/simcore_service_webserver/groups_utils.py, services/web/server/src/simcore_service_webserver/socketio/handlers_utils.py, services/web/server/src/simcore_service_webserver/socketio/module_setup.py, services/web/server/src/simcore_service_webserver/users_utils.py, services/web/server/tests/integration/02/test_rabbit.py, services/web/server/tests/integration/conftest.py
✅ This PR aims to fix the flaky ``services/web/server/tests/integration/02/test_rabbit.py`` test-suite and improve the CI stability.
- ♻️ split single ``test_rabbit_websocket_computation `` into smaller independent ``tests_`` cases
- ♻️ cleaned up pytest-simcore fixtures used in this test-suite
- ♻️ cleaned up some of the web-server's modules used in this test
Reviewing flaky integration tests in CI
```
make devenv
pytest -vv tests/integration/02/test_rabbit.py
```
=> ✅ Improving CI tests: web/server/tests/integration/02/test_rabbit.py

.github/workflows/ci-staging.yml, .github/workflows/ci-testing-deploy.yml, Makefile, docs/releasing-workflow-instructions.md
Adds the option to create a staging-hotfix release by following the same rules as for release-hotfixes:
- create a branch named such as staging_meerkat2
- wait for the CI to complete the normal build -> will generate images named such as webserver:hotfix-staging-github-latest and webserver:hotfix-staging-github-DATE-SHA
- if ok, then using ```make release-hotfix-staging``` creates a TAG that the github CI will pickup
- the CI will then rename the previously created images to staging-github-latest so that it gets deployed
=> ✨ Handling of staging hotfixes

.github/workflows/ci-staging.yml, Makefile
- fixes makefile recipe to create hotfixes in staging (added in PR #2649)
- fixes ``ci-staging.yml`` that would retag the hot-fixed images
Both these changes are already included in [🚑️ staging_Meerkat1 and 2 hotfixes](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Meerkat2)
=> 👷  fixes makefile recipe for hotfix-releases

api/specs/webserver/openapi-services.yaml, packages/models-library/src/models_library/projects.py, packages/models-library/src/models_library/projects_nodes.py, packages/models-library/src/models_library/projects_nodes_io.py, packages/models-library/src/models_library/projects_ui.py, packages/service-library/src/servicelib/aiohttp/application_setup.py, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/director_v2.py, services/web/server/src/simcore_service_webserver/director_v2_abc.py, services/web/server/src/simcore_service_webserver/director_v2_api.py, services/web/server/src/simcore_service_webserver/director_v2_core.py, services/web/server/src/simcore_service_webserver/director_v2_handlers.py
A key requirement to implement the meta modeling in PR #2556 is to avoid coupling high-level functionality, like meta-modeling implemented in its own plugin (an ``addon`` in this case), from low-level functionality like the ``director-v2`` plugin. For that reason, this PR refactors ``webserver.director_v2``'s *plugin*  introducing:
- ``director_v2_api``: new API module to reduce coupling with other plugins 
- ``director_v2_abc``: new abstract class to allow external consumers (e.g. metamodeling addon) to customize run policies (``AbstractProjectRunPolicy``)
It also adds some minor cleanup and doc: 
- improves type annotations
- Naming convention for constraint types: 
- It is an established practice to name constraint variants of builtin types appending suffix lik ``Str`` or ``Dict`` etc …
=> ♻️ New interfaces for webserver.director_v2 plugin

api/specs/webserver/openapi-projects.yaml, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/projects/project_lock.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/src/simcore_service_webserver/resource_manager/garbage_collector.py, services/web/server/src/simcore_service_webserver/users_api.py, services/web/server/tests/unit/isolated/test_studies_dispatcher_core.py, services/web/server/tests/unit/with_dbs/02/test_access_to_studies.py, services/web/server/tests/unit/with_dbs/09/conftest.py, services/web/server/tests/unit/with_dbs/09/test_projects_cancellations.py, services/web/server/tests/unit/with_dbs/09/test_projects_crud.py, services/web/server/tests/unit/with_dbs/09/test_projects_delete.py, services/web/server/tests/unit/with_dbs/10/test_resource_manager.py, services/web/server/tests/unit/with_dbs/_helpers.py, services/web/server/tests/unit/with_dbs/conftest.py
When creating a project FROM a TEMPLATE or AS a TEMPLATE FROM a Study, the webserver does the following:
1. copies the project skeleton in a new project (with new uuids for project, nodes)
2. copies the data by calling into the storage API
In case 2. fails or times-out (due to the webserver or more often due to the webbrowser timing out), the project is still listed for the user, although it is not valid and in an undefined state.
This PR aims to fix this issue by creating the new project as hidden by default UNTIL all the data was completely copied. In case of time out or of disconnection, the handler is cancelled and that cancellation is now handled. This will in turn delete the project, thus cleaning up.
As users still need something akin to copying only the skeleton an additional …
=> 🐛 Bugfix: properly handle timeout when copying project

services/web/client/source/class/osparc/component/study/SaveAsTemplate.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/data/Resources.js
This PR implements the frontend part for publishing a template with or without data.
=> Publish template with or without data

services/storage/docker/entrypoint.sh
As in PR #2667 , we need to add a call to `update-ca-certificates` to make the local deployment work with self-signed SSL certificates.
No issue, but related PR is #2667 
Merge and see, but as PR #2667 works this one-line code addition should as well. Tested locally manually calling `update-ca-certificates` , it worked.
=> 🐛Fix storage service in local deployment with self signed SSL certificates

tests/e2e/portal-files/VTK_file.js, tests/e2e/portal/2D_Plot.js, tests/e2e/portal/3D_Anatomical.js, tests/e2e/portal/3D_EM.js, tests/e2e/portal/Bornstein.js, tests/e2e/portal/CC_Human.js, tests/e2e/portal/CC_Rabbit.js, tests/e2e/portal/Kember.js, tests/e2e/portal/Mattward.js, tests/e2e/portal/Voila.js, tests/e2e/portal/opencor.js, tests/e2e/tutorials/isolve-gpu.js, tests/e2e/tutorials/isolve-mpi.js, tests/e2e/tutorials/jupyters.js, tests/e2e/tutorials/mattward.js, tests/e2e/tutorials/sim4life.js, tests/e2e/tutorials/sleepers.js, tests/e2e/utils/utils.js
In order to make service start timeouts more flexible, it will have to be provided with the cli arguments
=> e2e: get timeouts from cli arguments

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/io.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/task_shared_volume.py, services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py, services/dask-sidecar/tests/unit/test_tasks.py
Fixes running python-runner error due to missing folder when pulling inputs to the service. 
This bug is also found in production. Hotfix required.
1. create a ``main.py`` with
```python
print("hello world")
```
2. connect to a python runner and run as
This run would fail with the following log
since the routine ``pull_file_from_remote`` would raise ``FileNotFoundError`` because the folders for the destination path do not exist.
The design guarantees (by ``TaskSharedVolumes.__post_init__``) that the input/outputs and logs folders exist (although not that they are empty!). The problem is that  ``destination_path = task_volumes.inputs_folder / something_else`` and `something_else`` path might have some extra sub-folders.
This PR provides a temporary fix but IMO is not fully satisfactory …
=> 🐛 Fixes: python runner fails raising FileNotFoundError

services/dask-sidecar/docker/entrypoint.sh
For the local deployment of oSparc, we need to point the dask-sidecar to the self-signed certificate in order to connect to storage. While the certificates are handled in the docker-compose file for the local deployment in the ops-repo, we need to call 'update-ca-certificates' in order to read them (as root!, at the right place). If the deployment is non-local
(i.e. the regular docker-compose files from the ops-repo are used or simcore is built 'vanilla' without the ops repo) nothing will happen. These changes have been tested locally and it looks good from my side currently.
=> 🐛 add update certificates call to dask sidecar

services/web/client/source/class/osparc/component/form/renderer/PropForm.js, services/web/client/source/class/osparc/data/model/Node.js, services/web/client/source/class/osparc/data/model/Workbench.js
Fix: Connection to existing parameter not drawn bug
closes https://github.com/ITISFoundation/osparc-simcore/issues/2705
=> Bug fix: Draw connection to existing parameter

services/web/client/source/class/osparc/component/node/NodeView.js, services/web/client/source/class/osparc/desktop/SlideshowView.js, services/web/client/source/class/osparc/navigation/PrevNextButtons.js, tests/e2e/tutorials/tutorialBase.js
Depending on the state of the current node's outputs ("not-available", "out-of-date", "busy", "up-to-date"), the Next button shows:
- "not-available" or "out-of-date": "Run" (Computational) or "Select-file" (File Picker)
- "busy": "Running"
- "up-to-date": "Arrow"
Related to https://github.com/ITISFoundation/osparc-simcore/issues/2661
If the last node is a computational one it can still be run
=> App mode: Smarter Next button

services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js
=> Bugfix: Workbench issues

packages/settings-library/src/settings_library/comp_services.py, services/director/src/simcore_service_director/config.py
Changes the default (when no limit is set) on a computational service to use 1 CPU (and 2GB (unchanged))
=> ✨ Change default limit for computational services to 1 CPU

services/docker-compose.yml
Several issues were identified with the current configuration of traefik with regards to dynamic services (legacy ones).
- When the legacy service is removed (for example, if the service was forcefully removed, or the user disconnected for some reason and comes back later), the frontend of that service would try to reconnect with its backend (as for any socket.io based services).
In the current configuration, all the calls to /x/UUID were redirected to the webserver, which would rightfully answer with a 404 - NOT FOUND. This would trigger an infinite loop where the frontend tries to re-connect with its lost backend (and also triggers the Directory Not Found error in Jupyter lab).
- The new settings changes how the webserver traefik rules are set by changing it to take: Only ```/``` or …
=> ✨ Improve Traefik rules (⚠️ devops)

packages/service-library/requirements/_aiohttp.in, packages/service-library/requirements/_aiohttp.txt, packages/service-library/src/servicelib/aiohttp/application_setup.py, packages/service-library/src/servicelib/aiohttp/tracing.py, packages/service-library/tests/aiohttp/test_tracing.py, services/director-v2/src/simcore_service_director_v2/core/application.py, services/storage/requirements/_base.txt, services/web/server/docker/boot.sh, services/web/server/requirements/_base.in, services/web/server/requirements/_base.txt, services/web/server/requirements/_packages.txt, services/web/server/requirements/_tools.in, services/web/server/requirements/_tools.txt, services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/application_config.py, services/web/server/src/simcore_service_webserver/cli.py, services/web/server/src/simcore_service_webserver/director_v2_core.py, services/web/server/src/simcore_service_webserver/remote_debug.py, services/web/server/src/simcore_service_webserver/settings.py, tests/performance/Dockerfile, tests/performance/Makefile
Use [gunicorn](https://gunicorn.org/) to deploy aiohttp-based servers to boost response time and requests per seconds.
This is a proof that for the webserver application it is **NOT** the case.
Since the webserver handles a websocket, it is not possible to increase the number of worker processes gunicorn deploys.
For each request a worker process is assigned. Since the websocket is a kind of request that is kept it would need to be processed by the same worker. Gunicorn does not handle this case.
Nevertheless, using [gunicorn](https://docs.gunicorn.org/en/stable/index.html) is the recommended deployment of aiohttp (see [here](https://docs.aiohttp.org/en/stable/deployment.html)).
Integrating gunicorn implied some necessary changes:
- gunicorn handles reload without the need of watchdog …
=> Start aiohttp services using gunicorn

services/docker-compose.yml
⚠️ devops: remove the catchall from ```services/simcore/docker-compose.yml``` under treafik
A catch all service was introduced lately that would return a 503 for any invalid entrypoint.
This is too much.
Now a more selective catchall will return a 503 in case of accessing if it does not exists for any reason:
- /x/{UUID} this is the access of a legacy service backend
- uuid.services.OSPARC this is the access of a modern backend
Everything else will return a 404 which is traefik defaults behaviour.
This has the side effect of changing the ```Directory Not Found``` error of the jupyter lab service into the following much less agressive and more understandable:
- api-server is now also only served if the access is done with ```/``` or ```/v0```
=> ✨ Enhanced services catch all to only return 503 for services, 404 otherwise (⚠️ devops)

services/web/server/src/simcore_service_webserver/computation_subscribe.py
Problem:
- If for any reason the RabbitMQ communication fails and the consumer in the webserver raises exception, it tries right away to restart and if for some reason this not work it enters a loop, thus loading the webserver.
Fix:
- add a sleep interval of 2 seconds before restarting
=> 🐛 In case RabbitMQ has unexpected error, wait before restarting it

services/web/client/source/class/osparc/component/metadata/ServicesInStudy.js, services/web/client/source/class/osparc/data/Resources.js
closes https://github.com/ITISFoundation/osparc-issues/issues/572
=> Update All services with one click

packages/service-library/src/servicelib/aiohttp/monitor_services.py, packages/service-library/src/servicelib/aiohttp/monitoring.py, packages/service-library/src/servicelib/logging_utils.py, services/director/src/simcore_service_director/producer.py, services/storage/src/simcore_service_storage/application.py, services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py
- removed high cardinality metrics in storage and webserver by replacing all metrics that used endpoints with UUIDs inside with the "canonical" path. This translates into endpoint of the form
-```http_requests_total{app_name="simcore_service_webserver",endpoint="/v0/projects/{project_id}:open",http_status="200",method="POST"} 1.0```
as defined in their respective openapi.
Therefore the number of timeseries for an application can be calculated with: APP_NAMEs x ENDPOINTs x RESPONSE_STATUS x METHOD. ENDPOINT is constrained to the amount of entrypoints in the API. Before it was unconstrained since endpoints were created dynamically with UUIDs.
Also, storage and webserver use the same base module.
Additionally we have the following new metrics:
- platform metrics (defaults from the prometheus …
=> ♻️ Improve metrics generation

tests/performance/docker-compose.yml, tests/performance/locust_files/platform_ping_test.py
- allows the locust to send authenticated calls when going through some kind of authentication
```console
cd tests/performance
make build
export SC_USER_NAME=blahblah
export SC_PASSWORD=blahblahandblah
make up target=platform_ping_test.py host=OSPARC_HOST_TO_TEST
make down
=> ✨ Performance testing: allow for auth calls

services/docker-compose.yml
- The final missing rule that was missing so that tests for /view entrypoint is again functional
=> ♻️ Traefik rules: final Path needed for viewing files

services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUIPreview.js, services/web/client/source/class/osparc/desktop/WorkbenchView.js, services/web/client/source/class/osparc/theme/ColorDark.js, services/web/client/source/class/osparc/theme/ColorLight.js, services/web/client/source/class/osparc/theme/ColorLightBlue.js, services/web/client/source/class/osparc/theme/ColorPurple.js, services/web/client/source/class/osparc/theme/mixin/Color.js, services/web/client/source/class/osparc/wrapper/Svg.js
closes https://github.com/ITISFoundation/osparc-issues/issues/581
=> Delete link UI/UX

services/director/src/simcore_service_director/producer.py, services/director/tests/test_producer.py
- an issue arose where an image name used in a dynamic service was not following the conventions but of the type ```simcore/services/dynamic/jupyter-smash:2.5.8@sha256:lksdfjhlskfjsdlfksdjflgsdkjhgfsd123eu210```, this triggered a weird situation where the director-v0 was not able to stop the service, and letting a study as un-closed.
This PR fixes this problem.
=> 🐛 Retrieving service key/version from running service to use regex instead of split

requirements/constraints.txt, services/api-server/requirements/_base.txt, services/catalog/requirements/_base.txt, services/datcore-adapter/requirements/_base.txt, services/director-v2/requirements/_base.txt, services/dynamic-sidecar/requirements/_base.txt
Dependency upgrades `uvicorn == 0.17.0`. Also removes constraints.
- closes https://github.com/ITISFoundation/osparc-simcore/pull/2745
- https://github.com/ITISFoundation/osparc-issues/issues/428
=> ⬆️ uvicorn upgrade

services/web/client/source/class/osparc/component/form/Auto.js, services/web/client/source/class/osparc/component/widget/inputs/NodeOutputTreeItem.js, services/web/client/source/class/osparc/ui/form/ContentSchemaField.js
This PR brings a new widget (TextField like) that supports the Content Schema input port type that comes in https://github.com/ITISFoundation/osparc-simcore/pull/2756.
For now, only the ```array``` type is supported
=> Support ContentSchema (array) input/output port type

services/web/client/source/class/osparc/data/model/Node.js
This PR fixes the following scenario:
1. when a dynamic service starts, the frontend starts asking for the status of the service, until it says either Ready or Error
2. one of the responses is a 503 error (the service in the backend is actually in a good state, but the error response comes from a middle service)
3. the frontend stops asking because it thinks there is an Error in the dynamic service
Fixed:
=> Fix: Don't give up when a node status replies with 503

Makefile
Prevents pip to upgrade to version 22 until jazzband/pip-tools#1558 is resolved
``Dockerfile`` are all synced to  ``pip~=21.3`` (See ``tests/environment-setup/test_used_python.py``)
=> ⬆️ adds constraint to pip~=21.3 util pip-tools issue resolved

services/api-server/docker/boot.sh, services/catalog/docker/boot.sh, services/datcore-adapter/docker/boot.sh, services/director-v2/docker/boot.sh, services/dynamic-sidecar/docker/boot.sh
Fixes an annoying issue with uvicorn. If the working directory does not coincide with the directory from where the "app" is loaded, auto reload will not be working.
All uvicorn services will reload on changes applied to packages.
- https://github.com/encode/uvicorn/issues/1289
=> 🐛 Enabling auto reload for uvicorn in development mode

tests/e2e/utils/utils.js
Some e2e tests are failing because one request returns a 503.
This PR logs these 503 responses and makes the test not fail.
Next step: add a maximum of 503 responses.
=> e2e: log 503s

Makefile, services/docker-compose.local.yml, services/docker-compose.yml
This PR adds the sticky sessions to the webserver.
This means if a client connect with oSparc, Traefik will inject a cookie in the response, then recognize it on the next request from the same client and re-direct it to the very same instance of the webserver (in case they are scaled).
This is a pre-requisite to allow scaling of the webserver later. among others:
- handle the garbage collector (have only one instance do this - waiting for enhanced settings so that we have a garbage collector only service)
- add horizontal scaling using Redis or RabbitMQ
=> ✨ Enhancement/use sticky session

Makefile, services/web/server/src/simcore_service_webserver/computation_subscribe.py
This PR changes how RabbitMQ queues are declared.
Before PR: queue set as "exclusive" (e.g. (used by only one connection and the queue will be deleted when that connection closes)
After PR: queue is not exclusive
This has the following implication:
- when a webserver is restarted, for about 5-10 seconds it is a 2nd instance and it has issues accessing the queue (as explained [here](https://www.rabbitmq.com/queues.html) there can be a race condition and client side communication might ensure issues... that is what we are seeing)
- since the queue is not deleted now when the webserver goes down, it *could* generate issues but I don't see any at the moment since the messages have a TTL of 60000 seconds, so they will be deleted anyhow.
fixes #2758
=> 🐛 #2758 exclusive queue cannot be reacquired

services/director-v2/src/simcore_service_director_v2/core/errors.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/src/simcore_service_director_v2/modules/dask_clients_pool.py, services/director-v2/src/simcore_service_director_v2/utils/dask.py, services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py
The dask client automatically reconnects when a dask-scheduler restarts for whatever reason. That is nice, but it is NOT the case of all the Pub/Sub machinery used for:
- getting logs
- getting progress
- getting state changes
- cancelling tasks
This PR aims to detect when the original scheduler changed by checking its ID. If the ID changes, an exception is raised, catched and the dask-client is completely re-instantiated, guaranteeing that all the machinery is on par.
This should fix the issues **related to dask** where the logs are missing.
It is still an open question as if the dask-workers are correctly reconnecting. But this might come in another PR.
fixes #2787
=> 🐛 Check dask scheduler ID in cluster, if it changes raise an exception

services/web/client/source/class/osparc/component/widget/PersistentIframe.js, services/web/client/source/class/osparc/data/model/Node.js
This PR makes the frontend nodes connect to their dynamic service's iframes on demand.
When opening studies with many dynamic services, all the iframes were connected and opened right away, creating hundreds of parallel requests, overloading the backend and the frontend. With these changes, dynamic services will be started, the ```/retrieve``` endpoint called, BUT the iframe will not be loaded until the user opens it.
Before:
After:
related to https://github.com/ITISFoundation/osparc-simcore/issues/2785
=> Iframe lazy loading

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/background_task.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/src/simcore_service_director_v2/utils/dask.py
The Dask client internal heartbeat seems to lose the connection with the dask-scheduler after awhile. It is not clear why.
This check should allow detection of that fact.
Adds an yet an additional check when acquiring a client.
Not yet 100% foul proof but should already improve
=> 🐛 Check if connection with backend is still up

services/web/client/source/class/osparc/data/model/Node.js, services/web/client/source/class/osparc/ui/message/Loading.js
Demo showing the message in the 2D plot service:
=> Show "please wait" message when Nature services are starting

tests/e2e/portal/2D_Plot.js, tests/e2e/portal/Kember.js, tests/e2e/tutorials/tutorialBase.js
Since iframes are loaded on demand, to be on the safe side, wait 5 seconds after opening the node.
=> e2e fix: Wait for iframe after opening node

.env-devel, services/director/Makefile, services/director/src/simcore_service_director/exceptions.py, services/director/src/simcore_service_director/producer.py, services/director/src/simcore_service_director/rest/handlers.py, services/director/tests/test_handlers.py, services/director/tests/test_producer.py
When a dynamic service is stopped, it will save its state first by default. Up to now, this operation was not guaranteed which would lead to situations in which services were removed even if their state was not saved. This would in many cases result in serious data loss as reported in #2800 .
Here the stop request will fail if the save state operation fails which will avoid deleting services until its state save is guaranteed. To force stop w/o saving the state can still be achieved by passing ``save_state=False``. This is e.g. used in the GC.
We are aware that this modification partially solves the problem since there is still a chance that the GC might delete a service that failed a state save. Nonetheless, its gives a chance to the client to reconnect to an unstop service and therefore …
=> 🐛 Is2800/fix director0 lost connection

services/web/client/source/class/osparc/dashboard/CardBase.js, services/web/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/web/client/source/class/osparc/dashboard/SearchBarFilter.js, services/web/client/source/class/osparc/dashboard/ServiceBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/dashboard/TemplateBrowser.js, tests/e2e/tests/tags.test.js, tests/e2e/utils/auto.js
Issue: Study/Template/Service cards were interacting with the search filters that didn't belong to their tab. This PR fixes that bug:
=> Fix: Search filters

services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/tests/unit/isolated/test_projects_utils.py, services/web/server/tests/unit/isolated/test_template_projects.py
Fixes wrong signature in ``project_utils`` (somehow was not caught by our linter! Follow up in  #2811 )
This could have been prevented if I would have not missed (forgot) the tests in PR #2797
=> 🐛 Fixes wrong signature and adds tests

services/director/src/simcore_service_director/producer.py, services/director/tests/test_producer.py
This fix follows up from #2803 
After observing master, we noticed that the GC was failing to stop old services because they would not save their state. It happens that *some* old services do not add that functionality and threfore the new rule introduced in #2803 needs to introduce some exceptions to support this legacy.
NOTE1: that all this functionality will be taken over by the new side-car. 
NOTE2 (⚠️ devops):  #2803 must not be released alone but together with this PR. Otherwise, the GC will fail to close old services (mostly used in the e2e) and will collapse resources in the cluster (as observed in master)
#2803
=> 🐛 adds exception rules for legacy services (⚠️ devops)

services/web/client/source/class/osparc/dashboard/CardBase.js
closes https://github.com/ITISFoundation/osparc-simcore/issues/2810
=> Fix: service catalog search filter

services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/utils/DisabledPlugins.js
Following https://github.com/ITISFoundation/osparc-simcore/pull/2814
Check statics from webserver to enable/disable Export and Duplicate.
The animation was paused in order to add the ```WEBSERVER_EXPORT``` variable and restart the webserver:
=> Enable/disable Export and Duplicate

services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/application_settings_utils.py, services/web/server/src/simcore_service_webserver/clusters/module_setup.py, services/web/server/src/simcore_service_webserver/meta_modeling.py, services/web/server/src/simcore_service_webserver/version_control.py, services/web/server/tests/conftest.py, services/web/server/tests/unit/isolated/test_application_settings.py
Webserver plugins marked in the code as "under development" can be disabled via ``WEBSERVER_DEV_FEATURES_ENABLED=0`` and also get advertised in the front-end  statics under ``"pluginsDisabled"``.
Example of statics report sent to the front-end that shows four plugin disabled:
```json
{
"apiVersion": "0.7.0",
"appName": "simcore_service_webserver",
"buildDate": "2022-01-09T12:26:29Z",
"vcsRef": "dd536f998",
"vcsUrl": "git@github.com:ITISFoundation/osparc-simcore.git",
"stackName": "master-simcore",
"pluginsDisabled": [
"WEBSERVER_EXPORTER",
"WEBSERVER_SCICRUNCH",
"WEBSERVER_VERSION_CONTROL",
"WEBSERVER_META_MODELING"
]
```
which would correspond to the following env vars in eht web-server (@mrnicegyu11 )
```cmd
WEBSERVER_DEV_FEATURES_ENABLED=0
WEBSERVER_EXPORTER=null …
```
=> ✨ Enable/disable plugins marked as "under development" via env vars

packages/settings-library/src/settings_library/base.py, packages/settings-library/src/settings_library/utils_cli.py, packages/settings-library/tests/test_utils_cli.py
All services apps in the simcore-stack have now a CLI that allows displaying the app settings (associated to its env vars). This can help setup a reliable mechanism to catch up with changes in the configuration between the code and operations (⚠️ devops) 
- 🐛 Fixes problem with app's CLI  command ``settings --as-json-schema``
- ✨Adds flags to get different views (e.g. ``--exclude-unset``)
- Closes #2794 
- build image, prepare envs and compose specs:
```cmd
make build
make .env
make .stack-simcore-production.yml
```
- get webserver's config values as json
```cmd
docker-compose -f .stack-simcore-production.yml run webserver \
simcore-service-webserver settings --as-json  > webserver-settings.json
```
- get websercer's config **json-schema**
```cmd
docker-compose -f …
```
=> 🐛 fixes schema-json in settings-CLI

services/web/client/source/class/osparc/ui/markdown/Markdown.js
Initializes Mardown element's height to the minimum (1), and once it ```appear```s it will resize itself to whatever it takes.
Check bug issue to see the **before**
closes https://github.com/ITISFoundation/osparc-issues/issues/598
=> Bugfix: Initialize Mardown element's height to minimum

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/dask_clients_pool.py
- the dask clients pool was reporting invalid errors with a valid cause in the client, thus generating confusion
- the traceback of the error was missing making it difficult to narrow down the issue
This PR shall help in fixing this.
=> ♻️✨ Improve logging output in case of error when scheduling tasks

services/docker-compose-ops.yml, services/docker-compose.yml, services/web/server/tests/unit/with_dbs/docker-compose-devel.yml, services/web/server/tests/unit/with_dbs/docker-compose.yml
- Upgraded Redis to version 6.2.6 (latest 6 version) - [release notes of version 6](https://raw.githubusercontent.com/antirez/redis/6.0/00-RELEASENOTES)
- enable redis persistence (both RDB and AOF) see [redis persistence documentation for details](https://redis.io/topics/persistence). AOF is setup with the default settings which should ensure a maximum data loss of 1 second, which in our case should be more than enough
**⚠️ devops**: You need to ensure that the redis database ALWAYS end up on the node with the docker volume necessary for REDIS to regenerate its data. We should maybe also check redundancy (several mirrored redis databases).
bonus:
- clean up docker-compose-ops.yml of deprecated features in filestash and onlyoffice services.
=> ⬆️ upgrade redis to 6.2.6, added persistency ⚠️ devops

services/api-server/requirements/_base.in, services/api-server/requirements/_base.txt, services/api-server/requirements/_test.txt, services/api-server/requirements/_tools.txt, services/api-server/requirements/constraints.txt, services/api-server/src/simcore_service_api_server/modules/webserver.py
In preparation for new features, we upgrade api-server requirements.
- Removed local constraints
- Pruned dependencies
- full upgrade base.in, tests.in and tools.in
- #packages before: 44
- #packages after : 46
|#|name|before|after|upgrade| count|
|-|----|------|-----|-------|------|
|  1 | aiodebug                  | 1.1.2           | 2.3.0      | **MAJOR**  | 1 |
|  2 | aiofiles                  | 0.5.0           | 0.8.0      | *minor*    | 1 |
|  3 | aiohttp                   | 3.7.4.post0     | 3.8.1      | *minor*    | 1 |
|  4 | aiopg                     | 1.2.1           | 1.3.3      | *minor*    | 1 |
|  5 | alembic                   | 1.7.4           | 1.7.6      |            | 1 |
|  6 | asgiref                   | 3.4.1           | 3.5.0      | *minor*    | 1 |
|  7 | …
=> ⬆️ Upgrades api-server requirements

packages/settings-library/src/settings_library/postgres.py, services/catalog/src/simcore_service_catalog/api/routes/services.py
This PR follows #2869 and the idea is to provide caching of the request listing services from the catalog using for now a simple cache mechanism through [aiocache](https://github.com/aio-libs/aiocache) library.
This library could allow caching through Redis if need be. for now it caches in memory for a 30 seconds time.
The requests per seconds doubles using that mechanism, during the 30seconds the cache lives.
Without cache:
```
------------------------------------------------------------------------------------------------ benchmark: 2 tests ------------------------------------------------------------------------------------------------
Name (time in ms)                             Min                   Max                  Mean             StdDev                Median …
```
=> ✨ Cache list service request in catalog

services/director-v2/requirements/_test.in, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/director-v2/tests/unit/test_modules_dask_client.py, services/director/src/simcore_service_director/producer.py
@sanderegg detected in master deploy that many services were never stopped because the new save-state-first policy (that prevents stopping a service until the state data save is granted) would not allow it. 
```log
ERROR: simcore_service_webserver.director_v2_core:stop_service(145) - Exception: forwarded call failed with status 500, reason {'data': {'status': 500, 'message': 'Failed to save state of service 39af424f-803e-4cc9-89d2-11f1b07d8aeb: service sim4life_39af424f-803e-4cc9-89d2-11f1b07d8aeb:80/x/39af424f-803e-4cc9-89d2-11f1b07d8aeb unreachable [Cannot connect to host sim4life_39af424f-803e-4cc9-89d2-11f1b07d8aeb:80 ssl:None [Name or service not known]]'}}
ERROR: simcore_service_webserver.director_v2_core:stop_service(145) - Exception: forwarded call failed with status 500, reason …
```
=>  🐛Fix save state for non-responsive services

services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/tests/unit/with_dbs/05/test_project_db.py
This PR optimizes a call to the database used by the **G**arbage **C**ollector that is asking:
- for all running services, find the one that are not in the database
To this end it was calling a SQL that would return all the nodeID in all the projects in the table. In master alone this would return >7000 entries. Times the number of running services.
Then this would be passed into a python Set, which is a blocking call twice.
This PR adds a function ```node_id_exists``` that runs a pSQL call that checks in the workbench field whether a specific nodeID exists. The computation happens on the postgres server and returns a yes/no type entry.
```BEFORE: 4.5s to call on about >1000 projects with 23-1434 nodes each```
```AFTER: 0.87s```
Bonus: 2 new tests
fixes #2399
=> 🐛Fix blocking call in the garbage collector

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml, services/datcore-adapter/src/simcore_service_datcore_adapter/modules/pennsieve.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py, tests/environment-setup/test_used_docker_compose.py
- Activates cron job that analyzes repo code for vulnerabilities (every monday at 5:26am)
- Fixes two clear-text logging of sensitive info 
-  NOTE: as a good practice always use ``SecretStr`` in pydantic models for objects that are logged
More details:
- [codeQL]( https://codeql.github.com/docs/codeql-overview/)
- [GH-Action](https://github.com/github/codeql-action)
- [LGTM](https://lgtm.com/#explore)
- [codeql-config](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-a-custom-configuration-file)
To see some of the job runs, check the ["Actions" tab and select CodeQL workflow](https://github.com/ITISFoundation/osparc-simcore/actions/workflows/codeql-analysis.yml) 
- …
=> 🔒️ Adds codeql-analysis cron job

services/web/server/src/simcore_service_webserver/garbage_collector.py, services/web/server/src/simcore_service_webserver/login/plugin.py
Follows up fixes in #2901 to get GC working in master-deploy for the first time.
- #2757 
- Covered by CI
=> 🚑️ GC needs dependency to login storage

packages/models-library/src/models_library/clusters.py, packages/models-library/tests/test_clusters.py, packages/pytest-simcore/src/pytest_simcore/db_entries_mocks.py, services/director-v2/src/simcore_service_director_v2/api/routes/clusters.py, services/director-v2/src/simcore_service_director_v2/api/routes/computations.py, services/director-v2/src/simcore_service_director_v2/core/settings.py, services/director-v2/src/simcore_service_director_v2/models/schemas/clusters.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/factory.py, services/director-v2/src/simcore_service_director_v2/modules/dask_clients_pool.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_runs.py, services/director-v2/src/simcore_service_director_v2/utils/dask_client_utils.py, services/director-v2/tests/unit/test_modules_dask_clients_pool.py, services/director-v2/tests/unit/with_dbs/conftest.py, services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py, services/director-v2/tests/unit/with_dbs/test_route_clusters.py
This PR adds the following specific entrypoints:
- GET ```/clusters/default``` returns the default cluster
- GET ```/clusters``` now also returns the default cluster as the first element of the list
- - GET ```/clusters/default/details``` now also returns the default cluster details
- POST ```clusters/default:ping``` allows to ping the default cluster
As a summary, the default cluster is the cluster available to everyone, defined by the ENV ```COMPUTATIONAL_BACKEND_DEFAULT_CLUSTER_URL```. It can be either a dask-scheduler (as is usual at the moment) or a osparc-dask-gateway.
The default cluster is available to any user, albeit in USE mode only (one cannot change the parameters of the default cluster)
=> ✨ Enhancement/provide default cluster info

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py
- When the dynamic-sidecar is attaching containers to a project-network it tried to fetch the network fist. 
That project network may not exist on the host (especially if a swarm worker node).
This fix will use the low level aiodocker object instead to bypass the issue.
- The same network alias was being attached for all containers when the project was started. Now the correct alias is being attached 
- fixes https://github.com/ITISFoundation/osparc-simcore/pull/2633
See `How to test` section from https://github.com/ITISFoundation/osparc-simcore/pull/2633
=> 🐛 FIX issues with control networking

services/web/client/source/class/osparc/component/cluster/ClusterDetails.js, services/web/client/source/class/osparc/component/cluster/ClusterMiniView.js, services/web/client/source/class/osparc/component/cluster/ClustersDetails.js, services/web/client/source/class/osparc/component/form/Auto.js, services/web/client/source/class/osparc/component/permissions/Permissions.js, services/web/client/source/class/osparc/dashboard/ResourceMoreOptions.js, services/web/client/source/class/osparc/desktop/StartStopButtons.js, services/web/client/source/class/osparc/utils/Clusters.js
=> Cluster resource details II

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py
Fixes an issue where the director-v2 cannot find the node in the network aliases.
=> 🐛 Avoids locking the dynamic-sidecar in an error state

services/director-v2/tests/unit/test_modules_project_networks.py, services/web/server/src/simcore_service_webserver/login/plugin.py, services/web/server/src/simcore_service_webserver/login/settings.py, services/web/server/src/simcore_service_webserver/login/utils.py, services/web/server/tests/unit/isolated/test_login_plugin.py
The "From" field was not found during the sending of the email. Turns out the wrong parameter to parse the pedantic model was used.
This fixes the issue and allows for emails to get sent once again.
Extra:
- Fixes warnings with a test case in director-v2
- closes https://github.com/ITISFoundation/osparc-simcore/issues/2882
=> 🐛 Fix email sending issue missing "From" field

services/web/client/source/class/osparc/component/editor/AnnotationEditor.js, services/web/client/source/class/osparc/component/form/ColorPicker.js, services/web/client/source/class/osparc/component/workbench/Annotation.js, services/web/client/source/class/osparc/component/workbench/SvgWidget.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/desktop/WorkbenchView.js, services/web/client/source/class/osparc/ui/form/ContentSchemaHelper.js, services/web/client/source/class/osparc/utils/Clusters.js, services/web/client/source/class/osparc/wrapper/Svg.js
Fixed:
- Text annotation with font size
=> Fix: Range validation with prefix updated

services/dynamic-sidecar/openapi.json, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/directory_watcher.py, services/dynamic-sidecar/tests/unit/test_api_containers.py
Directory watcher is now disabled when starting the dynamic-sidecar.
=> 🐛 fixes concurrency issue with directory-watcher

.pylintrc, services/catalog/src/simcore_service_catalog/db/events.py, services/catalog/src/simcore_service_catalog/db/repositories/dags.py, services/catalog/src/simcore_service_catalog/db/repositories/services.py
The change in the catalog to async SQLAlchemy brought these:
- autocommit is disabled by default
- when modifying the database one need to use the explicit transaction context manager:
```python
with engine.begin() as conn:
conn.insert(...)
```
or
```python
with engine.connect() as conn:
conn.insert(...)
conn.commit()
```
a lot of information may be found [here](https://python-gino.org/docs/en/1.1b2/explanation/sa20.html)
fixes #2923
=> 🐛 #2923 - sharing not possible

services/director-v2/src/simcore_service_director_v2/api/routes/clusters.py, services/web/server/src/simcore_service_webserver/director_v2_core.py
creating a cluster or pinging it would use very nice password stars instead of the real password...
=> 🐛 Cluster credentials passed as *****

services/web/client/source/class/osparc/component/cluster/ClusterMiniView.js, services/web/client/source/class/osparc/desktop/StartStopButtons.js, services/web/client/source/class/osparc/desktop/StudyEditor.js
After closing the study, the Cluster Mini VIew has to stop asking for cluster details
=> Fix: Stop requesting cluster details

services/static-webserver/Dockerfile
when issuing ```make build-devel``` on a clean machine it would fail because the static-webserver tries to copy from qooxdoo-kit image that does not exist.
This image only exist in the **production** environment, e.g. after ```make build``` was called.
This fixes the issue.
```
docker system prune -a
make build-devel
```
=> ♻️🐛 Maintenance: removed devel-prod dependency on static-webserver

services/director-v2/src/simcore_service_director_v2/models/schemas/clusters.py, services/director-v2/tests/unit/test_models_clusters.py
The workers object is sometimes null.
=> 🐛 Sometimes the workers object is empty

scripts/common.Makefile, services/director/requirements/_base.in, services/director/requirements/_base.txt, services/director/requirements/_test.txt
upgrades urllib3==1.26.5 to fix CVE-2021-33503 . This fixes vulnerability in ``director`` services as reported in
https://github.com/ITISFoundation/osparc-simcore/security/dependabot/97
=> ⬆️  upgrades urllib3==1.26.5 to fix CVE-2021-33503

requirements/constraints.txt, services/datcore-adapter/requirements/_base.txt, services/datcore-adapter/requirements/_test.txt, services/datcore-adapter/requirements/_tools.txt
~~🔒️ Fixing vulnerabilities by upgrading ``rsa==4.7``~~  : Currently blocked until PR https://github.com/Pennsieve/pennsieve-python/pull/15 is merged and released
- [Access Restriction Bypass](https://github.com/ITISFoundation/osparc-simcore/security/dependabot/47): GHSA-xrx6-fmxq-rjj2
- [Timing attacks in python-rsa](https://github.com/ITISFoundation/osparc-simcore/security/dependabot/48): GHSA-537h-rv9q-vvph
⬆️ General upgrade of all service libraries (only updated libraries are included)
- #packages before: 45
- #packages after : 44
|#|name|before|after|upgrade| count|
|-|----|------|-----|-------|------|
|   1 | aiodebug                  | 1.1.2           | 2.3.0      | **MAJOR**  | 1 |
|   2 | anyio                     | 3.2.1           | 3.5.0      | *minor*    | 2 |
|   3 | asgiref …
=> ⬆️ udpates datcore-adapter service dependencies

packages/models-library/src/models_library/projects.py, packages/models-library/src/models_library/projects_access.py, packages/postgres-database/src/simcore_postgres_database/models/users.py, packages/postgres-database/tests/test_users.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_login.py, services/web/server/src/simcore_service_webserver/catalog_client.py, services/web/server/src/simcore_service_webserver/garbage_collector_core.py, services/web/server/src/simcore_service_webserver/garbage_collector_utils.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/security_api.py, services/web/server/src/simcore_service_webserver/users_api.py, services/web/server/tests/conftest.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/integration/conftest.py, services/web/server/tests/unit/isolated/test_security_access_model.py, services/web/server/tests/unit/with_dbs/01/test_studies_dispatcher_studies_access.py, services/web/server/tests/unit/with_dbs/03/meta_modeling/test_meta_modeling_iterations.py, services/web/server/tests/unit/with_dbs/03/version_control/conftest.py
- ✨ adds ``UserRole`` comparison operators
- 🔥 rm ``users_api.is_guest_user`` and creates instead ``users_api.get_user_role``
- ♻️ ``save_state`` flag logic: Using ``UserRole`` comparison instead of ``is_guest_user`` to check whether the state shall be saved or not.
- ♻️ cleanup ``pytest_simcore.helpers.utils_login`` by adding ``TypedDict`` to datastructures
- ♻️ splits gc-core module in two: codeclimate error ``garbage_collector_core.py has 508 lines of code (exceeds 500)``
- 🗑️  Updates to fix ``DeprecationWarning: the method passlib.handlers.sha2_crypt.sha256_crypt.encrypt() is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0, use .hash() instead.``
This PR is a part split from #2867 which will be closed w/o merge.
Refactoring supported by tests in web-server and …
=> ♻️ Maintenance: refactors guest user and save-state logic to improve flaky tests

.github/workflows/ci-release.yml, .github/workflows/ci-staging.yml
getting the branch name the commit was on is not so straightforward...
when the CI runs the current SHA is in GITHUB_SHA environement
When releasing to staging or production one creates a git TAG.
1. use-case is doing the tag on the master branch --> this should trigger a regular release to staging or production depending on the tag pattern
2. second use-case is doing the tag on a so-called hotfix branch, which triggers the same pattern but tags the resulting docker images differntly.
When the CI runs it checks-out the tag. Then one needs to find where the tag is on. to this end the following git call is run:
```bash
git name-rev --refs="refs/remotes/origin/master" --refs="refs/remotes/origin/hotfix_v*" --refs="refs/remotes/origin/hotfix_staging_*" --name-only ${GITHUB_SHA}
```
this …
=> 🐛 CI: properly get original git branch name

services/web/client/source/class/osparc/desktop/StartStopButtons.js, services/web/client/source/class/osparc/desktop/StudyEditor.js
[Now](https://github.com/ITISFoundation/osparc-simcore/pull/2922) that we know in which cluster a study/pipeline was run, when opening it, the cluster gets preselected.
=> Preselect cluster in Study Editor II

packages/pytest-simcore/src/pytest_simcore/redis_service.py, services/director-v2/requirements/_base.in, services/director-v2/requirements/_base.txt, services/director-v2/src/simcore_service_director_v2/api/routes/clusters.py, services/director-v2/src/simcore_service_director_v2/models/schemas/clusters.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/tests/unit/test_modules_dask_client.py, services/director-v2/tests/unit/test_modules_dask_clients_pool.py, services/web/server/src/simcore_service_webserver/redis.py, services/web/server/tests/integration/01/test_exporter.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/unit/with_dbs/01/clusters/test_clusters_handlers.py, services/web/server/tests/unit/with_dbs/conftest.py
For the user it is desirable that the available vs used resources in the cluster are shown.
```GET /clusters/{project_id}/details``` now additionally returns:
- used_resources: contains a dictionary with the currently used defined generic resources on each dask-worker e.g. ```{"CPU": 1.4, "RAM": 123442, "GPU": 1}```
- resources: contain the total amount of the generic resources that this worker provides
NOTE: resources are currently one of ```CPU, GPU, RAM, MPI``` and MPI might soon be deprecated.
Also this PR introduce a cache on the cluster details in the director-v2 of 3 seconds to reduce the calls towards the corresponding dask-scheduler coming from potentially any number of users.
@odeimaiz : for the frontend that means that the resources and used_resources are **absolute** numbers. …
=> ✨ retrieve dask available/used resources

services/director-v2/src/simcore_service_director_v2/models/schemas/clusters.py, services/director-v2/tests/unit/test_models_clusters.py
The dask scheduler counts the available resources. these are added and subtracted. We expect no negative values, therefore this is now corrected using a validator.
=> 🐛: ensure negative values are set to 0

services/web/client/source/class/osparc/component/widget/NodeTreeItem.js, services/web/client/source/class/osparc/component/workbench/BaseNodeUI.js, services/web/client/source/class/osparc/component/workbench/NodeUI.js, services/web/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/web/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/web/client/source/class/osparc/dashboard/ServiceBrowser.js, services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/dashboard/TemplateBrowser.js, services/web/client/source/class/osparc/data/model/Node.js, services/web/client/source/class/osparc/data/model/Workbench.js, services/web/client/source/class/osparc/wrapper/RadialMenu.js
- When right-clicking on the Workbench, the following actions show up:
- Add new service
- Draw rectangle
- Draw text
- When right-clicking on a Node, the following actions show up:
- Add/Remove Marker
- Delete node
- Connect to the input
- Connect to the output
- Study Browser: Only studies are part of the scroll area, search filter and selection will get anchored at the top
- Command shortcuts are shown on NodesTree's and NodeUI's menus
The smart wheel:
Scroll studies:
=> Context to the Wheel

packages/models-library/src/models_library/services_access.py, services/catalog/src/simcore_service_catalog/api/routes/services.py, services/catalog/src/simcore_service_catalog/utils/requests_decorators.py
The caching of the list of services from the director was filtered with a user-dependent list of services available in the database. This explains the various errors in the catalog.
fixes #3005
=> 🐛Separate caching director call from user dependent service listing

services/storage/src/simcore_service_storage/s3.py, services/storage/tests/unit/test_route_s3_access.py, services/storage/tests/unit/test_s3.py
Fixes issues with storage not being able to start when configured with an S3 url not containing a port
=> 🐛 Fix storage not starting with regular https addresses

requirements/tools/Dockerfile
pip-tools fails to compile with latest ``pip==22.1`` upgrade
- pins pip until https://github.com/jazzband/pip-tools/issues/1617 fixed
- this only affects ``pip-tools`` (i.e. to upgrade requirements)
=> ⬇️ pins pip==22.0.1 until pip-tools is fixed [skip CI]

packages/models-library/src/models_library/service_settings_labels.py, packages/service-integration/tests/test_osparc_config.py, requirements/tools/Dockerfile
e2e detected that the ``jupyters`` template project fail to open due to a validation error of some of its service labels
```log
ERROR: File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/director_v0.py", line 142, in get_service_labels return SimcoreServiceLabels.parse_obj(unenvelope_or_raise_error(resp)) File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for SimcoreServiceLabels simcore.service.settings -> __root__ -> 2 -> type unexpected value; permitted: 'string', 'int', 'integer', 'number', 'object', 'ContainerSpec', 'Resources' (type=value_error.const; given=resources; permitted=('string', 'int', …
```
=> 🐛 Fix/backwards compatibility on service annotation labels

packages/models-library/src/models_library/aiodocker_api.py, services/catalog/src/simcore_service_catalog/api/routes/services_resources.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/settings.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs.py
The Docker REST API requires a Singular form of Reservation, where it is actually the plural form...
🐛🐛🐛🐛
[https://github.com/docker/cli/issues/3611](https://github.com/docker/cli/issues/3611)
=> 🐛 Started dynamic services do not take the correct Reservation

tests/e2e/tutorials/sim4life.js
=> e2e: test sim4life-dy

packages/dask-task-models-library/setup.cfg, packages/models-library/setup.cfg, packages/postgres-database/setup.cfg, packages/pytest-simcore/setup.cfg, packages/service-integration/setup.cfg, packages/service-library/setup.cfg, packages/settings-library/setup.cfg, packages/simcore-sdk/setup.cfg, services/api-server/docker/boot.sh, services/api-server/setup.cfg, services/catalog/docker/boot.sh, services/catalog/setup.cfg, services/dask-sidecar/setup.cfg, services/datcore-adapter/docker/boot.sh, services/datcore-adapter/setup.cfg, services/datcore-adapter/src/simcore_service_datcore_adapter/core/application.py, services/datcore-adapter/src/simcore_service_datcore_adapter/core/settings.py, services/director-v2/docker/boot.sh, services/director-v2/setup.cfg, services/director/setup.cfg, services/dynamic-sidecar/docker/boot.sh, services/dynamic-sidecar/setup.cfg, services/storage/docker/boot.sh, services/storage/setup.cfg, services/web/server/docker/boot.sh, services/web/server/setup.cfg
Two very verbose but simple fixes:
- 🐛 ``boot.sh`` sets the same log-level to the app as to the server (i.e. ``uvicorn`` or ``gunicorn``). Up to now, they were not connected and portainer would always show INFO logs of the server regardless the log-level we set via env vars
- 🔨 ``bumpversion`` was failing to commit due to pre-commit-hook failing in modified README -> disabled pre-commit check on bumpversion changes.
Maintenance
=> 🐛🔨 Maintenance: fixes log-level of server in boot and bumpversion commit failure

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_scheduler.py, services/director-v2/tests/unit/test_routes_dynamic_services.py
After an `httpx` upgrade a test started failing due to timing timing/concurrency. Making sure all the pending requests finish before closing the client.
=> 🐛 Fixes failing test in master

.github/workflows/ci-testing-deploy.yml
disable manual caching for now.
=> 🚑️ CI: cache in setup-python failing

.github/workflows/ci-testing-deploy.yml, ci/github/integration-testing/director-v2.bash, ci/github/integration-testing/simcore-sdk.bash, ci/github/integration-testing/webserver.bash, ci/github/unit-testing/api-server.bash, ci/github/unit-testing/api.bash, ci/github/unit-testing/catalog.bash, ci/github/unit-testing/dask-sidecar.bash, ci/github/unit-testing/dask-task-models-library.bash, ci/github/unit-testing/datcore-adapter.bash, ci/github/unit-testing/director-v2.bash, ci/github/unit-testing/director.bash, ci/github/unit-testing/dynamic-sidecar.bash, ci/github/unit-testing/models-library.bash, ci/github/unit-testing/postgres-database.bash, ci/github/unit-testing/service-integration.bash, ci/github/unit-testing/service-library.bash, ci/github/unit-testing/settings-library.bash, ci/github/unit-testing/simcore-sdk.bash, ci/github/unit-testing/storage.bash, ci/github/unit-testing/webserver.bash
- sorted calls in bash scripts alphabetically
- renamed the marker "travis" (outdated) to "heavy_load"
- one can now create a test **that should not run in the CI because it is too heavy** (for example a test that moves around 10 GB of data which the CI does not like too much) one can do for example:
```python
@pytest.mark.parametrize(
"file_size",
[
_file_size("10Mib"),
_file_size("1003Mib"),
pytest.mark.heavy_load(_file_size("7Gib")),
],
)
```
It will skip the test if the marker "not heavy_load" is set
Additional Note:
- Since there is currently an issue in Github Actions with the setup-node/setup-python actions (caching is broken), the timeout for unit tests was expended by 3 minutes.
Note: pre-requisiste to #3021
=> ♻️ Maintenance: renamed travis tests to heavy load

packages/models-library/src/models_library/service_settings_labels.py, packages/models-library/tests/test_service_settings_labels.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/settings.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/validation.py
Some services like iSeg, which are composed of multiple containers, require the `boot options` to be present inside a different container than the one the option was defined on.
=> ♻️ boot options injected to all involved containers for the service

packages/models-library/src/models_library/projects_nodes_io.py, packages/models-library/tests/test__pydantic_models.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_port_validation.py, services/dynamic-sidecar/Dockerfile
*isolve-gpu* e2e test failed (see [incident](https://git.speag.com/oSparc/e2e-testing/-/issues/1)) because ``comp_task`` tables included some outputs with an old FileLink format. 
This PR adds a validator in FileLink that handles that legacy format.
A question remains, though: which service is still adding ``store="0"`` to the ``comp_task``?? 
- model_library tests adds example of data with legacy-format 
- simcore_sdk tests adds test with data taken from e2e test mentioned above
=> 🐛 Fixes FileLink validation legacy format

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs.py
This PR fixes the problem where the dy-sidecar services gets multiple ```Placement Constraints``` in the thousands.
=> 🐛 Fix dy-sidecar gets multiple same placement constraints

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py
Traefik labels on the dy-sidecar service are unnecessary, they create unwanted work for the traefik service, unnecessary routes, etc. thus they are removed.
=> ♻️ dy-sidecar: remove unnecessary traefik labels

services/web/client/source/class/osparc/data/model/Node.js
When opening the study bootOptions information was not deserialized and therefore, from that moment on, that user preference was lost.
=> 🐛 Bug Fix: de/serialize bootOptions when opening/closing the study

.github/workflows/ci-testing-deploy.yml, packages/dask-task-models-library/requirements/_base.txt, services/dask-sidecar/docker/boot.sh, services/dask-sidecar/requirements/_base.txt, services/dask-sidecar/requirements/_dask-complete.txt, services/dask-sidecar/requirements/_dask-distributed.txt, services/dask-sidecar/requirements/_packages.txt, services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/storage/requirements/_base.txt
- #packages before: 10
- #packages after : 10
|   1 | aiobotocore               | 2.2.0           | 2.3.3      | *minor*    | 2 | dask-sidecar⬆️</br>storage⬆️ |
|   2 | bokeh                     | 2.4.2           | 2.4.3      |            | 2 | dask-sidecar⬆️⬆️ |
|   3 | dask                      | 2022.4.0, 2022.5.0 | 2022.6.0   | *minor*    | 6 | dask-sidecar⬆️⬆️⬆️⬆️</br>dask-task-models-library🧪</br>director-v2⬆️ |
|   4 | dask-gateway              | 0.9.0           | 2022.6.1   | **MAJOR**  | 2 | dask-sidecar⬆️</br>director-v2⬆️ |
|   5 | dask-gateway-server       | 2022.4.0        | 2022.6.1   | *minor*    | 1 | director-v2🧪 |
|   6 | distributed               | 2022.4.0, 2022.5.0 | 2022.6.0   | …
=> ⬆️ Maintenance: upgrade dask libraries

packages/service-library/requirements/_fastapi.in, packages/service-library/requirements/_fastapi.txt, packages/service-library/requirements/_test.txt, packages/service-library/src/servicelib/fastapi/requests_decorators.py, packages/service-library/tests/fastapi/test_request_decorators.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/health.py
Implements from ITISFoundation/osparc-issues#638
> we need to have the fix that cancels tasks in the dy-sidecar when the REST client timesout (currently all these task are accumulating)
Specifically:
- ✨ adds ``servicelib.fastapi.request_decorators.cancellable_request`` helper (taken from datcore-adapter utils and modified)
- ``tests/fastapi/test_request_decorators.py``: Tried to test, but unable to emulate a client disconnect using ``TestClient``. ANY IDEAS WELCOME! :-)
- applies decorator to most of the ``/container``-base paths in dynamic-sidecar
NOTE: if ``servicelib.fastapi.request_decorators.cancellable_request`` is accepted, it will be reused in the other services (right now very similar copies in catalog and datcore-adapter).
- ITISFoundation/osparc-issues#638
```cmd
make devenv …
```
=> ✨ Is638/client cancellation

packages/service-library/src/servicelib/fastapi/requests_decorators.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py
Removes all ``@cancellable_requests`` decorators from dy-sidecar handlers. This feature malfunctions and currently prevents to start dynamic-services in master deploy. 
This PR reverts cancellable requests added in PR #3155 until we find a more reliable solution
- ITISFoundation/osparc-issues#638
=> 🚑️ Is638/tmp disable cancellation 

services/web/server/src/simcore_service_webserver/storage_handlers.py
The links returned by PUT upload_file are returning the request.scheme and did not check for the ```X-Forwarded-Proto``` header. therefore the links were using ```http``` instead of ```https``` in the deployments.
=> 🐛 Return correct scheme in storage links when uploading file

ci/github/unit-testing/service-library.bash, packages/pytest-simcore/src/pytest_simcore/helpers/utils_dict.py, packages/service-library/src/servicelib/archiving_utils.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs.py, services/storage/tests/unit/test_handlers_simcore_s3.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/tests/unit/with_dbs/02/test_project_db.py
Fixes regression.
added test to prevent this to happen again.
currently no test for the origin of the problem: https://github.com/ITISFoundation/osparc-simcore/pull/3058
closes #3137
=> 🐛 Regression fix: computational services always restarting

packages/service-library/src/servicelib/async_utils.py, packages/service-library/src/servicelib/fastapi/openapi.py, packages/service-library/tests/test_async_utils.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py, services/dynamic-sidecar/docker/boot.sh, services/dynamic-sidecar/openapi.json, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/settings.py, services/dynamic-sidecar/tests/conftest.py, services/dynamic-sidecar/tests/unit/conftest.py, services/dynamic-sidecar/tests/unit/test_api_containers.py, services/dynamic-sidecar/tests/unit/test_core_application.py, services/dynamic-sidecar/tests/unit/with_rabbit/test_core_rabbitmq.py
Some refactoring prior to PR #3157 so it does not clutter the review of changes there.
- OAS server definition adds a default server as well
- cleanup async_utils 
- small fix in logging format to display error codes (OEC). OECs will be displayed in graylog next to entire error stack
```cmd
ERROR Observation of service_name=dy-sidecar_012346 unexpectedly failed [OEC:123456789]
... # here long stack of error
```
- cleanup boot. NOTE: multiple forks in development mode are due to the directory watcher!!
- cleanup app startup and logs
- ITISFoundation/osparc-issues#638
=> ♻️ Is638/dy sidecar refactoring (round 6)

services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_nodes_handlers.py, services/web/server/tests/unit/with_dbs/02/test_projects_handlers__open_close.py, services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py, services/web/server/tests/unit/with_dbs/_helpers.py
Due to historic reasons adding nodes were created/added by the frontend. Later the backend took care of starting/stopping services but the saving of the updated project still relied on the frontend.
Since the dy-sidecar was made in such a way that it starts very fast, it would sometimes try to access the *comp_tasks* table before it was actually filled by the frontend saving the project.
This PR aims to improve that by ensuring the project is updated **by the backend** when adding a new node. This update is done before the service is started, so this will fix this problem once and for all.
fixes #3216
=> 🐛 Fix node not found on start of dy-sidecar

README.md, packages/simcore-sdk/src/simcore_sdk/node_data/data_manager.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py, packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py, packages/simcore-sdk/tests/unit/test_node_data_data_manager.py, services/api-server/README.md, services/api-server/src/simcore_service_api_server/api/routes/files.py, services/api-server/src/simcore_service_api_server/models/schemas/files.py, services/storage/src/simcore_service_storage/simcore_s3_dsm.py, services/storage/tests/unit/test_handlers_simcore_s3.py, services/web/server/src/simcore_service_webserver/exporter/formatters/formatter_v1.py
These change shall allow the upload of large files to osparc storage (>2Gb which seemed to be the current limit hit by @newton1985).
Nevertheless the API-server inner parts will still create some limitations as during an upload the following happens:
- an API client connects with the API-server
- the client starts uploading a file to osparc using ```PUT /v0/files/content``` entrypoint
- the ```api-server``` then receives the file as a [SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) which is nicely provided by the FastAPI library. e.g. This is a file that is partially in memory and on the disk to prevent exploding the RAM.
- the ```api-server``` then calls ```storage``` to generate multipart upload links
- the ```api-server``` then …
=> ✨ Api-server can upload >5Gb files

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_base.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_base.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_public.py
- when the director-v2 client unexpectedly fails it should log an error not an info message
=> ♻️ Dy-sidecar client unexpected error to be logged as an error

services/director-v2/src/simcore_service_director_v2/core/settings.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_logs.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py
Make sure `DYNAMIC_SIDECAR_LOG_LEVEL` is not set on the director-v2, if set put it to `INFO`.
Review log levels in dynamic-sidecar. Making its logs more helpful.
=> ♻️dynamic-sidecar log-level review  (⚠️ devops)

.env-devel, services/web/client/source/class/osparc/navigation/Manuals.js, services/web/client/source/class/osparc/navigation/NavigationBar.js, services/web/client/source/class/osparc/navigation/UserMenuButton.js, services/web/server/src/simcore_service_webserver/statics_constants.py, services/web/server/src/simcore_service_webserver/statics_settings.py
Now that we have a published TI manual (for now it's only the skeleton), we can link it to the manual button(s)
⚠️ devops: Set the correct link to the manual as an env-var, test if it works after deploying
=> ✨ 📝 TI manual link  (⚠️ devops)

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py
Since we do see strange behavior sometimes starting containers, this will help (in conjunction with setting the dy-sidecar log level to DEBUG)
=> ♻️ make call to docker-compose verbose to ease debugging

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/tests/unit/test_api_containers.py, services/dynamic-sidecar/tests/unit/test_core_docker_compose_utils.py
instead of calling ```docker-compose up --detach``` and directly ```docker-compose start``` which seems to not work in some cases.
Replaces the calls with:
```docker-compose up --no-start``` which only creates the containers and then ```docker-compose start``` which will start them.
Actually calling ```docker-compose --verbose up --detach``` shows that it returns right after creating the containers.
might fix #3247 
requires #3245
=> 🐛 Starts docker-compose services in 2 steps

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs.py
Inside the pydantic model `state_exclude` is a `set`, since it will not preserve the order. We sort result after it's being parsed.
=> 🐛 fixed flaky director-v2 test

requirements/tools/Makefile, services/datcore-adapter/requirements/_base.in, services/datcore-adapter/requirements/_base.txt
- Updates to latest pennsieve. This update unblocks the upgrade of rsa
- Remaining changes in requirement files suggest that changes in servicelib requirements were not propagated downstream. It will be corrected in a separate PR
- #packages before: 2
- #packages after : 5
|   1 | pennsieve                 | 6.1.2           | 6.2.0      | *minor*    | 1 | datcore-adapter⬆️ |
|   2 | rsa                       | 4.0             | 4.9        | *minor*    | 1 | datcore-adapter⬆️ |
*Legend*: 
=> ⬆️ maintenance/updates pennsieve library

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/cli.py, services/dynamic-sidecar/tests/unit/test_cli.py
Allows for people trying to save the state of the sidecar figure out where the data is present, without know where the underlying defined service has it's state directories.
- Check if the service has any data to save
```command
simcore-service-dynamic-sidecar state-list-dirs
```
- Save the data in the service
```command
simcore-service-dynamic-sidecar state-save
```
**NOTE: you also have autocomplete in the terminal**
=> ✨adds cli to list the content of state directories in dy-sidecar

packages/service-library/src/servicelib/aiohttp/long_running_tasks/_error_handlers.py, packages/service-library/src/servicelib/aiohttp/long_running_tasks/_routes.py, packages/service-library/src/servicelib/aiohttp/long_running_tasks/server.py, packages/service-library/src/servicelib/fastapi/long_running_tasks/_routes.py, packages/service-library/src/servicelib/long_running_tasks/_task.py, packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks.py, packages/service-library/tests/long_running_tasks/test_long_running_tasks_task.py
NOTE: currently only concerns REST long running tasks for AIOHTTP-based services (such as the webserver), PR is a pre-requisite for making copies of a project. FastAPI-based services are not concerned yet, since this would mean many more changes. But this should be changed ASAP.
A long running task in REST is handled like so in oSparc:
- client POST a request
- server returns a 202 (Accepted) with a ```{"task_id": TaskID, "status_href": LINK_TO_STATUS, "result_href": LINK_TO_RESULT}```
- client shall poll on ```GET status_href``` until status is *done*
- client shall then get the result by ```GET result_href```
This PR changes what the result is like from using a wrapper of result to **directly** returning the result. In essence this means for example when copying project:
```python
``` …
=> ♻️ Refactor long running tasks, result shall be directly returned

packages/simcore-sdk/src/simcore_sdk/node_ports_common/constants.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/settings.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/storage_client.py, packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py, swagger-cli
This PR adds retries in case of ConnectionError (see [aiohttp docs](https://docs.aiohttp.org/en/stable/client_reference.html#connection-errors))
It will retry using a default of 5 minutes, changeable via ENV variable
fixes https://github.com/ITISFoundation/osparc-simcore/issues/3242
=> ✨ added retries for upload and download in the node ports package

services/web/client/source/class/osparc/dashboard/StudyBrowser.js, services/web/client/source/class/osparc/utils/DisabledPlugins.js
removes isDuplicateDisabled check. it will always be enabled
=> remove isDuplicateDisabled

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/_routing.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/health.py, services/dynamic-sidecar/tests/unit/test_api_containers_long_running_tasks.py, services/web/server/src/simcore_service_webserver/computation_comp_tasks_listening_task.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_nodes_utils.py, services/web/server/tests/unit/with_dbs/02/test_projects_handlers__open_close.py
A user reports that inputs are pulled while a dynamic service is saving its state+outputs before closing. This might be caused by the mechanism that triggers to pull of inputs when outputs of the previous node are uploaded. This PR blocks this trigger when the project is locked. 
- ``web-server``
- Prevents ``post_trigger_connected_service_retrieve`` fire&forget task to retrieve inputs if project is locked
- ``dynamic-sidecar``
- ♻️ Minor cleanup of routes
- Fixes #3240
- ITISFoundation/osparc-issues#638
=> 🐛 Is3240/fix pull inputs sidecar

packages/service-library/src/servicelib/archiving_utils.py, packages/simcore-sdk/src/simcore_sdk/node_data/data_manager.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/__init__.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/nodeports_v2.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/port_utils.py, packages/simcore-sdk/src/simcore_sdk/node_ports_v2/serialization_v2.py, packages/simcore-sdk/tests/integration/conftest.py, packages/simcore-sdk/tests/integration/test_node_data_data_manager_.py, packages/simcore-sdk/tests/integration/test_node_ports_common_filemanager.py, packages/simcore-sdk/tests/integration/test_node_ports_v2_nodeports2.py, packages/simcore-sdk/tests/unit/test_node_data_data_manager.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_port.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_serialization_v2.py, services/api-server/src/simcore_service_api_server/api/routes/files.py, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/directory_watcher.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py, services/dynamic-sidecar/tests/unit/test_modules_directory_watcher.py, services/web/server/src/simcore_service_webserver/exporter/formatters/formatter_v1.py
Allow to redirect tqdm library progress logs to the frontend to show the user when:
- downloading workspace
- downloading/uploading ports
Bonus:
- use tqdm contrib functions to make logging behave better when a progress bar is displayed.
NOTE: no progress shown for archiving/unarchiving since async/sync code is proving difficult to circumvent.
[Screencast from 25. 08. 22 17:04:15.webm](https://user-images.githubusercontent.com/35365065/186707581-bf3db869-69d3-4b17-a988-33c92634903e.webm)
improves user experience https://github.com/ITISFoundation/osparc-issues/issues/638
=> ✨ Bring download/upload progress logs to the frontend

packages/service-library/src/servicelib/aiohttp/long_running_tasks/_server.py, packages/service-library/src/servicelib/aiohttp/long_running_tasks/client.py, packages/service-library/src/servicelib/aiohttp/long_running_tasks/server.py, packages/service-library/src/servicelib/long_running_tasks/_task.py, packages/service-library/tests/aiohttp/long_running_tasks/conftest.py, packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks.py, packages/service-library/tests/aiohttp/long_running_tasks/test_long_running_tasks_client.py, services/web/server/src/simcore_service_webserver/long_running_tasks.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers_crud.py
- brings a common client for aiohttp-based clients to query osparc long running task REST APIs
pre-requisite to simplify usage in #3287 
related to https://github.com/ITISFoundation/osparc-issues/issues/558
```bash
make "install-dev[all]"
make "test-dev[all]"
```
=> ✨ Aiohttp long running tasks client

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/validation.py, services/dynamic-sidecar/tests/unit/test_core_validation.py
covers more use cases where a partially complete docker-compose would fail adding the ```__backend__``` network.
still not sure why this would fail though
might help with ITISFoundation/osparc-simcore#3261
=> 🐛 iSeg sometimes stuck with invalid networks (maybe)

packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py
This PR properly uses aiohttp request call inside a context manager to ensure the request resources are properly closed.
This might be one of the reasons why uploading fails sometimes with large projects.
bonus: improves logging of errors.
related to https://github.com/ITISFoundation/osparc-issues/issues/663
=> 🐛 Nodeports filemanager incorrectly closes request

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_compose_specs.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_compose_specs.py
Services powered by the dynamic sidecar would not get the resource limits assigned to the corresponding containers. This PR fixes that.
All services spawned by the docker-compose spec should inject corresponding environment variables.
=>   🐛    Pass resource limits to dynamic services

packages/service-library/src/servicelib/archiving_utils.py, packages/service-library/src/servicelib/file_utils.py, packages/service-library/tests/test_archiving_utils.py
Bug reproduced by running ``test_archiving_utils::test_archiving_utils_against_sample`` against a sample ``workspace.zip`` provided by @GitHK. It revealed:
1. ``gather`` results ``extracted_paths`` included Exception instances (therefore it would fail ``p.is_file`` etc)
1. ``event_loop`` would get suddenly closed
This PR enhances error handling for archiving utils:
- cancels children tasks when ``asyncio.gather``-like raises
- Defines ``ArchiveError`` as a custom error for archive utils 
- Adds some guarantees to state upon failure (e.g. zip file/unzipped dst is deleted )
- ITISFoundation/osparc-issues#659
```cmd
make tests
```
=> 🐛 is659/decompressing-hangs

packages/simcore-sdk/src/simcore_sdk/node_data/data_manager.py, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/application.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py
The dynamic sidecar concurrently uploads the output port files and the workspace file.
An issue was identified inside the dynamic sidecar:
- the output port archiver was deleting the entire ```/tmp``` folder after the upload of the output ports
- since the upload of workspace is happening concurrently, and the ```workspace.zip``` file was located in this very ```/tmp``` folder it would be deleted, and the logs were correctly reporting that the file was not there!
This PR fixes the archiver of output ports by using the temporary directory context manager.
--> Always use context managers
fixes https://github.com/ITISFoundation/osparc-issues/issues/664
=> 🐛 workspace.zip disappears while uploading

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_api/_volume.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/nodeports.py
- This was failing since it is running in swarm mode. Removing the logs fetching since they bring no real benefit.
- computing folder size outside of directory cleanup context fails
=> 🐛 Various fixes

services/web/server/src/simcore_service_webserver/login/handlers.py, services/web/server/tests/unit/with_dbs/03/test_login_2fa.py
De-authorizes (``HTTPUnauthorized``) registering the same phone more than once on the system. If user tries, it returns a more concrete message: ``"Cannot register this phone number because it is already assigned to an active user"``
- Closes #3304
- Reproduce #3304, should get an error as ``"Cannot register this phone number because it is already assigned to an active user"``
- Automatically
```python
pytest -vv tests/unit/**/test_login_2fa.py
```
=> 🐛BugFix: Does not allow re-registering the same phone number

packages/settings-library/setup.cfg, packages/settings-library/src/settings_library/twilio.py, packages/settings-library/tests/test_twilio.py, services/web/server/src/simcore_service_webserver/login/_2fa.py
Some countries do not support [alphanumeric serder ID](https://support.twilio.com/hc/en-us/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS). Since the [list is pretty long and even some require pre-registration](https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID) the codes of the supported countries are passed in a list in ``TWILIO_COUNTRY_CODES_W_ALPHANUMERIC_SID_SUPPORT``
- New environ ``TWILIO_COUNTRY_CODES_W_ALPHANUMERIC_SID_SUPPORT``. Adjust with @odeimaiz
- SEE examples in https://github.com/ITISFoundation/osparc-simcore/blob/bf7e93e4451ec8e5b13ea44d581737a62c6705be/packages/settings-library/tests/test_twilio.py#L58
- ITISFoundation/osparc-issues#91
- @odeimaiz could you please do a little manual test when …
=> 🐛 Is91/fix alphanumeric sender  (⚠️ devops)

packages/service-library/src/servicelib/logging_utils.py, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/application_settings_utils.py, services/web/server/src/simcore_service_webserver/log.py, services/web/server/src/simcore_service_webserver/login/_2fa.py
Fixes typo that breaks ``send_sms``, which makes 2fa unusable
This should not happen anymore when we setup static-analysis in the CI (expected in PR #3321 )
**EXTRA**: guvicorn access-logger set to WEBSERVER_LOGLEVEL
=> 🐛 fixes 2fa typo in twilio function and guvicorn access-logger level

ci/github/unit-testing/models-library.bash, ci/github/unit-testing/postgres-database.bash, ci/github/unit-testing/service-integration.bash, packages/models-library/Makefile, packages/postgres-database/Makefile, packages/service-integration/Makefile, packages/service-library/src/servicelib/aiohttp/long_running_tasks/_server.py, packages/service-library/src/servicelib/long_running_tasks/_models.py, packages/service-library/src/servicelib/long_running_tasks/_task.py, packages/service-library/tests/long_running_tasks/test_long_running_tasks_task.py, packages/settings-library/Makefile, services/web/server/src/simcore_service_webserver/projects/projects_handlers_crud.py
This PR allows to disable the auto-cancellation mechanism when a client stops asking for the status of a long running task
The auto-cancel process is disabled for study copying.
Bonus:
- service integration lib, models lib and postgres-database lib CI now use Makefile recipes
```
make build up-prod
```
Create a large study, initiate a duplication, refresh the browser page (F5) --> the copy completes
=> ✨Do not auto-cancel study copy if the user disconnects

packages/pytest-simcore/src/pytest_simcore/docker_registry.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py, services/director-v2/tests/integration/02/utils.py, services/director-v2/tests/mocks/fake_dy_workbench_template.json
This PR introduces a retry mechanism when uploading to AWS according to the following official [AWS troubleshooting guide](https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/)
Retries of up to 5 times will be done on each presigned link in case of a 500 or 503 status code.
=> ✨Retry upon AWS 500s

docs/releasing-workflow-instructions.md
There are typos in the release instructions doc that prevented the hotfix-staging-release github action from running through. An underscore is missing.
Compare with `osparc-simcore/.github/workflows/ci-staging.yml:58ff`:
```
- if: contains(env.BRANCH_NAME, 'remotes/origin/hotfix_staging_')
env:
FROM_TAG_PREFIX: hotfix-staging-github
name: deploy from hotfix staging to staging
run: ./ci/deploy/dockerhub-tag-version.bash
```
=> 🐛 fix typos in release instruction for hotfix staging

packages/postgres-database/src/simcore_postgres_database/models/confirmations.py, services/web/server/src/simcore_service_webserver/login/_confirmation.py, services/web/server/src/simcore_service_webserver/login/handlers_confirmation.py, services/web/server/src/simcore_service_webserver/login/storage.py, services/web/server/tests/unit/with_dbs/03/test_login_registration.py
During manual tests today in TIP, found the following error
```log
ERROR: [2022-09-14 12:24:45,308/MainProcess] [servicelib.aiohttp.monitoring:middleware_handler(210)]  -  Unexpected server error "<class 'aiohttp.web_exceptions.HTTPInternalServerError'>" from access: 10.0.83.25 "GET /v0/auth/confirmation/1" done in 0.01 secs. Responding with status 500
File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/rest_middlewares.py", line 75, in _middleware_handler
response = await handler(request)
File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/rest_middlewares.py", line 203, in _middleware_handler
resp: _ResponseOrBodyData = await handler(request)
File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_webserver/pr …
```
=> 🐛 Fix/confirmation codes

packages/service-library/requirements/_fastapi.txt, requirements/constraints.txt, services/api-server/requirements/_base.txt, services/api-server/tests/unit/test__fastapi.py, services/autoscaling/requirements/_base.txt, services/catalog/requirements/_base.txt, services/datcore-adapter/requirements/_base.txt, services/datcore-adapter/src/simcore_service_datcore_adapter/modules/remote_debug.py, services/datcore-adapter/tests/unit/test_route_files.py, services/director-v2/requirements/_base.txt, services/dynamic-sidecar/openapi.json, services/dynamic-sidecar/requirements/_base.txt, services/storage/requirements/_base.txt, services/web/server/requirements/_base.txt
- 🔒️⬆️ Upgrades ``ujson`` to overcome vulnerabilities CVE-2021-45958, GHSA-fh56-85cw-5pq6
- ⬆️ Affected ``ujson`` dependencies were introduced  by``fastapi``.  By upgrading the latter, it pushed mainly the versions of ``starlette`` and ``ujson``.  The problem is that ``starlette`` broke parsing ``:`` in routes https://github.com/encode/starlette/pull/1675 (see failing tests in ``services/api-server/tests/unit/test__fastapi.py``). That issue was fixed in starlette and released in  [``starlette==0.20.2``](https://github.com/encode/starlette/releases/tag/0.20.2), BUT  fastapi still has ``starlette==0.19.1`` which should be resolved with https://github.com/tiangolo/fastapi/issues/4892.  
~~**ON HOLD**~~ -> recently released https://github.com/tiangolo/fastapi/releases/tag/0.85.0
- …
=> ⬆️🔒️ Maintenance/vulnerability upgrade for ujson, upgrade fastapi+starlette

packages/models-library/requirements/_test.txt, packages/postgres-database/requirements/_base.txt, packages/postgres-database/requirements/_migration.txt, packages/simcore-sdk/requirements/_base.txt, packages/simcore-sdk/requirements/_test.txt, requirements/constraints.txt, services/api-server/requirements/_base.txt, services/api-server/requirements/_test.txt, services/catalog/requirements/_base.txt, services/catalog/requirements/_test.txt, services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/dynamic-sidecar/requirements/_base.txt, services/storage/requirements/_base.txt, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt, tests/swarm-deploy/requirements/_test.txt
Upgrades ``mako`` (introduced by ``alembic``) to fix vulnerability https://github.com/advisories/GHSA-v973-fxgf-6xhp
- #packages before: 1
- #packages after : 1
|   1 | mako                      | 1.2.0, 1.1.5    | 1.2.2      |            | 10 | api-server⬆️🧪</br>catalog⬆️🧪</br>director-v2⬆️🧪</br>dynamic-sidecar⬆️</br>storage⬆️</br>web⬆️🧪 |
*Legend*: 
- #reqs files parsed: 60
|#|name|versions-base|versions-test|versions-tool|
|-|----|-------------|-------------|-------------|
|   1 | aio-pika                  | 6.8.0, 7.2.0              | 6.8.0, 8.2.0              |                           |
| …
=> 🔒️ ⬆️ Maintenance/fixes security vulnerabilities in mako

services/web/server/src/simcore_service_webserver/utils_rate_limiting.py, services/web/server/tests/unit/isolated/test_utils_rate_limiting.py
- 🐛 Fixes ``Retry-After`` header in global_rate_limit_route
- ``Retry-After`` is a relative time in secs, not absolute: see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 
- ♻️ cleanup tests and updated implementation
```cmd
pytest -vv tests/unit/isolated/test_utils_rate_limiting.py
```
=> 🐛 Fixes ``Retry-After`` header in global_rate_limit_route

services/static-webserver/client/source/class/osparc/component/node/FilePickerSSView.js, services/static-webserver/client/source/class/osparc/desktop/SlideshowView.js, services/static-webserver/client/source/class/osparc/file/FileDrop.js, services/static-webserver/client/source/class/osparc/file/FilePicker.js, services/static-webserver/client/source/class/osparc/file/FolderViewer.js, services/static-webserver/client/source/class/osparc/navigation/BreadcrumbsSlideshow.js, services/static-webserver/client/source/class/osparc/ui/basic/NodeStatusUI.js, services/static-webserver/client/source/class/osparc/ui/form/FileInput.js, services/static-webserver/client/source/class/osparc/utils/StatusUI.js
File Picker was redesigned to support file uploading in both App and Workbench mode. Requested by @newton1985.
File Picker in App mode:
File Picker in Workbench mode:
related to https://github.com/ITISFoundation/osparc-issues/issues/670
=> ✨ App Mode: Allow uploading file to File Picker

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/auth/Data.js, services/static-webserver/client/source/class/osparc/auth/Manager.js, services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ProfilePage.js, services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js, services/static-webserver/client/source/class/osparc/utils/Utils.js
- More human readable Flash Message
- Show hourglass with tooltip in Navigation bar. Tapping it brings you to the preferences
https://github.com/ITISFoundation/osparc-simcore/pull/3352
=> ✨Expiration Date: FE 2nd iteration

packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py
Apparently the 500 errors were not handled causing failures from `S3TransferErrors` on AWS prod.
`web.HTTPServerError` has an internal status of `-1` the correct exception would be `web.HTTPInternalServerError` which is a `500`.
=> 🐛 Correctly retry AWS 500 Internal error when uploading file

packages/service-library/src/servicelib/aiohttp/monitoring.py, packages/service-library/tests/aiohttp/test_monitoring.py
This enhance the labels created by the **webserver** with the *simcore-user-agent* header added in #3410 
therefore http_requests_total now provide a lable **simcore_user_agent** which may be used in prometheus to filter out e2e/p2p tests, where the header is set to "puppeteer". The default is set to "undefined".
Important NOTE: This is currently only for metrics created by the **webserver**, i.e. not for number of service created/stopped.
=> ✨Metrics: Webserver provides a label for Simcore-User-Agent

tests/e2e/utils/startPuppe.js
PR #3410 brought usage of setExtraHTTPHeaders in order to make all puppeteer requests to add some additional headers to make these requests detectable for metrics.
It seems puppeteer has an issue when this is enabled, that makes it fail in some way with CORS error see [this](https://github.com/puppeteer/puppeteer/issues/4889)
Therefore, and following that thread, the flag to disable security in the puppet was added.
=> 🐛 fixes CORS issue in puppeteer while testing with X-Simcore-User-Agent header

tests/e2e/portal/Kember.js, tests/e2e/tutorials/jupyterlabs.js, tests/e2e/tutorials/sleepers.js, tests/e2e/tutorials/ti-plan.js, tests/e2e/tutorials/tutorialBase.js
There are some e2e and p2e tests that fail checking output files and the tests still pass. This PR tries to fix those false positives. 
Funny enough, I don't see why these error show up in the first place. Therefore, I also print the expected vs received.
=> e2e: More reliable output files check

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/volume_remover.py, services/director-v2/tests/unit/conftest.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_docker_service_specs_volume_remover.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_api.py
Addresses issues with the bash script responsible for removing dyv-volumes
- Added tests covering all use cases for the bash script.
- If a volume is missing no error should be raised.
- Enhances runtime of the volume removal service. It will no longer wait if the volume is not present.
=> 🐛 dy-volume removal service fixes and improvements

.github/workflows/ci-release.yml, .github/workflows/ci-staging.yml, .github/workflows/ci-testing-deploy.yml, ci/deploy/dockerhub-deploy.bash
This PR adds the ```concurrency``` field in the CI workflows that will automatically cancel jobs when:
- github workflow name is the same, and
- github ref is the same (see GITHUB_REF environment (example ref/heads/master or ref/pulls/3434/merge for this very PR)
In effect, this should auto-cancel the previous CI job when a developer pushes several commits to github and therefore reduce the time other developers must wait
- github workflow name is the same
In effect only one staging workflow can run at the same time
- github workflow name is the same
In effect only one release workflow can run at the same time
Bonus:
- fixes #3435
=> ✨ CI: auto-cancel job with same name

services/web/server/src/simcore_service_webserver/login/_confirmation.py, services/web/server/src/simcore_service_webserver/login/_registration.py, services/web/server/src/simcore_service_webserver/login/settings.py
During a demo today, an invitation link did not work and was reported as "expired". At first glance, we did not understand why this happened and took us some time to recall that actually **all** confirmation tokens are time-limited. The problem was that the invitations that we were using were already expired but it was not obvious from the info available (no logs, no indication in the database, etc)  
This PR aims to avoid this problem in the future by:
- logging as WARNING when a given confirmation token in use is expired and therefore removed from the database
- INVITATION tokens are now unlimited (i.e. they do not expire)
Some actions in a login require some sort of confirmation/validation step. For those we create confirmation tokens that, due to security reasons, have a limited …
=> ♻️ Expired confirmation tokens are logged and INVITATION tokens do not expire

packages/service-library/src/servicelib/exceptions.py, services/web/server/src/simcore_service_webserver/products_events.py
After the experience with releases, when a ``product`` config is wrong, the webserver will fail startup and stop. Up to know we logged but it produced a chain effect that was more difficult to debug. Now, if products validation fail upon startup, the web-server stops with error.
Quoting [Willet ](https://www.willett.io/posts/precepts/)
> If your service can’t load the config on startup for any reason, it should just crash – that’s much easier to diagnose than the result of one broked instance going down an ancient code path
- closes #3453
=> ✨ is3453/fail boot if invalid product setup

.github/workflows/ci-testing-deploy.yml, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/cli.py
Cannot use ``alias`` with ``BaseSettings``. Created instead a helper in ``webserver``'s ``ApplicationSettings`` **just** for the special export functions.
EXTRA: improved a bit speed of web-server's CLI ``simcore-service-webserver --help`` by reducing explicit imports
- closes ITISFoundation/osparc-simcore#3372
```cmd
pytest -vv --pdb  tests/**/test_application*.py
```
=> 🐛 is3372/fixes warning of alias in BaseSettings

.gitignore, services/datcore-adapter/requirements/_base.txt, services/datcore-adapter/requirements/_test.txt, services/datcore-adapter/requirements/_tools.txt
general requirements upgrade of datcore-adapter micro-service
- #packages before: 38
- #packages after : 37
|   1 | aiofiles                  | 0.8.0           | 22.1.0     | **MAJOR**  | 1 | datcore-adapter⬆️ |
|   2 | anyio                     | 3.5.0           | 3.6.2      | *minor*    | 2 | datcore-adapter⬆️🧪 |
|   3 | asgiref                   | 3.5.0           | 🗑️ removed |  | 1 | datcore-adapter⬆️ |
|   4 | astroid                   | 2.12.11         | 2.12.12    |            | 1 | datcore-adapter🧪 |
|   5 | boto3                     | 1.21.33         | 1.24.95    | *minor*    | 1 | datcore-adapter⬆️ |
|   6 | botocore                  | 1.24.33         | 1.27.95    | *minor*    | 1 | …
=> ⬆️ Update datcore-adapter requirements

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py, services/director-v2/tests/unit/test_api_route_dynamic_scheduler.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py
The dy-sidecar was accidentally expoed to the user services instead of only exposing the proxy.
It is no longer possible to contact the dy-sidecar from a user service (like from a jupyter-notebook).
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3390
=> ♻️ user services can no longer contact the dynamic sidecar

services/datcore-adapter/src/simcore_service_datcore_adapter/utils/client_base.py, services/docker-compose.devel.yml
This PR disable http/2 on the httpx client used in the datcore-adapter.
It seems we are impacted by this: [https://github.com/encode/httpx/discussions/2112](https://github.com/encode/httpx/discussions/2112) in httpx
current workaround is to disable http/2 protocol. sad.
should fix #3464
=> 🐛 Bugfix#2: datcore-adapter stops calling into pennsieve after too many requests are done?

services/migration/Dockerfile, services/migration/docker/entrypoint.sh, services/migration/docker/healthcheck.sh, services/web/Dockerfile
New healthcheck function for the migration service with low CPU footprint.
Previous healthcheck has been producing **an almost constant**  (~13 %) CPU usage.  See  @mrnicegyu11's [promQL request](https://monitoring.osparc.speag.com/prometheus/graph?g0.expr=sum(irate(container_cpu_usage_seconds_total%7Bid%3D~%22%2Fdocker%2F.*%22%2Ccontainer_label_com_docker_swarm_service_name%3D%22staging-simcore_staging_migration%22%7D%5B1m%5D))%20by%20(container_label_com_docker_swarm_service_name)%20*%20100%20&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2w)
After a couple of days, that ended up consuming all CPU credit in AWS.  See outcome from @Surfict's research:
This is probably what caused the instabilities we have been experiencing in the last days in the e2e. 
🚑️ This should be …
=> 🐛 fix/low-CPU-load healthcheck for migration service

services/storage/src/simcore_service_storage/simcore_s3_dsm.py, services/storage/tests/fixtures/data_models.py, services/storage/tests/unit/test_handlers_simcore_s3.py
fixes https://github.com/ITISFoundation/osparc-issues/issues/754#issuecomment-1295083982
```bash
make devenv
cd services/storage
make test-unit-dev
```
=> 🐛 Storage: crash when not a file in the project

.codecov.yml, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_db.py, services/web/server/tests/unit/with_dbs/02/test_project_db.py, services/web/server/tests/unit/with_dbs/02/test_projects_nodes_handler.py, services/web/server/tests/unit/with_dbs/_helpers.py, services/web/server/tests/unit/with_dbs/conftest.py
- some findings from #3449 were splited in here:
- adding nodes concurrently would fail to be correctly saved into the databsae, leading to inconsistencies (e.g. creating hundreds of new nodes in a project would only save some tens of them) --> this is fixed by patching the workbench instead of replacing the whole project with an outdated project (the process of patching is **locking** the project in the database while being updated, preventing any other reads.
- deleting node was not updating the database, which was relying on the frontend to save the project. This is now done 100% in the backend and also by patching the workbench
This goes along the lines needed for https://github.com/ITISFoundation/osparc-issues/issues/756
Next steps will be to:
- change links
- change node names …
=> 🐛✨ Ensure adding/deleting node is thread safe

Makefile, services/director-v2/docker-compose-extra.yml, services/docker-compose.yml, tests/swarm-deploy/conftest.py
- uses latest itisfoundation/rabbitmq:3.11.2-management image
⚠️ devops: In case this is set somewhere, you will need to change the version accordingly
=> ⬆️ Use latest rabbit MQ service

services/web/server/src/simcore_service_webserver/groups_models.py, services/web/server/tests/unit/isolated/test_groups_models.py
The ``thumbnail`` column in the ``groups`` table contains old data that does not validate as an url. I have found empty strings, or embedded images. From now on, any invalid thumbnail (i.e. a valud that does not match ``Optional[AnyUrl]``) is automatically nullified. 
This error happens while ``get_profile``: The database has an old thumbnail that when parsed into ``ProfileGet`` a ``ValidationError`` is raised which is converted by the middle-ware into 500. Since ``WEBSERVER_DIAGNOSTICS=`` the error is logged in the backend:
**why?**: The problem is that ``groups`` resources are NOT validated (handlers are pretty old) when created but the ``Profile`` resource IS validated when read. That lead to a paradoxical situation in which you could write "invalid" group data but could not read it …
=> 🐛 Fix/sanitize old data for usergroups.thumbnail

.vscode/extensions.json, .vscode/settings.template.json, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/models.py, services/dask-sidecar/tests/unit/test_docker_utils.py, services/dask-sidecar/tests/unit/test_models.py
ensure memory-swap is set to the same value as memory limit if not set.
-1 disables it and any other value is equal to memory
MemorySwap = memory + swap
The PR effectively disables swapping for computational services.
Also @mrnicegyu11 concerning this [https://github.com/ITISFoundation/osparc-simcore/issues/3506](https://github.com/ITISFoundation/osparc-simcore/issues/3506), this can to the best of my knowledge not happen in the dask-sidecar as it validates through pydantic and the 3 parameters in the use-case are not part of the pydantic model.
see [https://github.com/itisfoundation/osparc-simcore/blob/59c34d86136ad0d4a2f584f2afc013ae32921ab7/services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py](https://github.com/itisfoundation/osparc-simcore/blob/ …
=> ✨ Ensure memory swap for computational services is same as memory (⚠️ devops)

services/storage/src/simcore_service_storage/simcore_s3_dsm.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers_crud.py, services/web/server/src/simcore_service_webserver/storage_api.py, services/web/server/tests/unit/with_dbs/02/test_projects_cancellations.py, services/web/server/tests/unit/with_dbs/_helpers.py, services/web/server/tests/unit/with_dbs/conftest.py
This PR changes the call to compute the project size.
BEFORE: would check every storage location to get the total size of the project
AFTER: only computes the project total size reported by the internal Simcore S3 storage location
Rationale: in the way this is currently implemented we cannot ask the Pennsieve to give us this information (missing API, and others)
This problem prevents copying any project or opening templates.
@pcrespov this will need to be hotfixed to production
=> 🐛 Project copy failing when pennsieve token is active

api/tests/requirements.in, api/tests/requirements.txt, packages/dask-task-models-library/requirements/_test.in, packages/dask-task-models-library/requirements/_test.txt, packages/models-library/requirements/_test.in, packages/models-library/requirements/_test.txt, packages/service-integration/requirements/_test.in, packages/service-integration/requirements/_test.txt, packages/service-library/requirements/_test.in, packages/service-library/requirements/_test.txt, packages/settings-library/requirements/_test.in, packages/settings-library/requirements/_test.txt, packages/simcore-sdk/requirements/_test.in, packages/simcore-sdk/requirements/_test.txt, services/dask-sidecar/requirements/_test.in, services/dask-sidecar/requirements/_test.txt, services/datcore-adapter/requirements/_test.in, services/datcore-adapter/requirements/_test.txt, services/director/requirements/_test.in, services/storage/requirements/_test.in, services/storage/requirements/_test.txt, services/web/server/requirements/_test.in, services/web/server/requirements/_test.txt, tests/environment-setup/requirements/requirements.in, tests/environment-setup/requirements/requirements.txt, tests/swarm-deploy/requirements/_test.in, tests/swarm-deploy/requirements/_test.txt
``pytest-sugar`` fails with  ``pytest==7.2.0`` as reported in https://github.com/Teemu/pytest-sugar/issues/243 .
Until it is resolved, this workaround will add ``py>=1.11.0`` in the requirements (as deduced from https://github.com/Teemu/pytest-sugar/issues/243#issuecomment-1298658807).
Maintenance
=> ⬆️ 🔨 Workaround to avoid test failures due to pytest-sugar

services/static-webserver/client/source/class/osparc/component/widget/NodeTreeItem.js, services/static-webserver/client/source/class/osparc/data/Converters.js, services/static-webserver/client/source/class/osparc/data/model/Slideshow.js, services/static-webserver/client/source/class/osparc/desktop/SlideshowView.js, services/static-webserver/client/source/class/osparc/file/FilesTree.js
- Studies/Datasets
- Nodes
- Files
closes https://github.com/ITISFoundation/osparc-simcore/issues/3226
closes https://github.com/ITISFoundation/osparc-simcore/issues/3518
closes https://github.com/ITISFoundation/osparc-simcore/issues/3520
=> ✨ Sort files and NodeTreeItem menu's bgColor

.github/workflows/ci-testing-deploy.yml
This PR will ensure Github does not allow PRs with issues to be merged.
The aggregate jobs that are ```unit-tests```, ```integration-tests``` and ```system-tests``` were getting green even though some of their dependencies failed.
This PR fixes this and will make using the ```auto-merge``` feature safe.
=> 🐛 CI integration tests not run when they should

services/director-v2/requirements/_test.in, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py
PR #3524 got merged into master with some failures that we correct here. 
- Fixes``[int] director-v2 02`` : all dependencies to ``py`` were removed
```cmd
_ ERROR collecting tests/integration/02/test_dynamic_sidecar_nodeports_integration.py _
ImportError while importing test module '/home/runner/work/osparc-simcore/osparc-simcore/services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/02/test_dynamic_sidecar_nodeports_integration.py:37: in <module>
from py._path.local import LocalPath
E …
```
=> 🐛 Fixes CI test issues introduced by faulty #3524

services/director-v2/tests/integration/01/test_computation_api.py, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py, services/director-v2/tests/integration/conftest.py, services/director-v2/tests/integration/shared_comp_utils.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py, services/web/server/tests/unit/isolated/test_diagnostics_healthcheck.py
fix flakyness in:
- tests/unit/isolated/test_diagnostics_healthcheck.py::test_diagnose_on_response_delays
- services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py::test_merge_dynamic_sidecar_specs_with_user_specific_specs
- tests/integration/01/test_computation_api.py::test_burst_create_computations
related to https://github.com/ITISFoundation/osparc-simcore/issues/3421
=> 🐛 CI: reduce test flakyness

packages/pytest-simcore/src/pytest_simcore/aws_services.py, packages/simcore-sdk/requirements/_base.in, packages/simcore-sdk/requirements/_test.in, packages/simcore-sdk/requirements/_test.txt, packages/simcore-sdk/requirements/_tools.txt, packages/simcore-sdk/requirements/constraints.txt, packages/simcore-sdk/tests/conftest.py, packages/simcore-sdk/tests/unit/test_node_data_data_manager.py, packages/simcore-sdk/tests/unit/test_node_ports_common_file_io_utils.py, services/storage/tests/unit/test_handlers_files.py, services/storage/tests/unit/test_s3_utils.py
These are the results of some testing with regard to https://github.com/ITISFoundation/osparc-simcore/issues/3531
Currently this cannot be reproduced but a test is now ready to be able to assess whether the chunk upload might be at fault.
also some additional information were added to the error log such as exact file size in bytes, number of upload links and chunk size so that in case this happens again we should have everything to test whether this is really the issue or not.
Another option would be maybe to remove the Content-Length header as found in some forums, but this does not look very solid.
=> ⚗️🐛 Add a test for reproducing potential 400 issue with upload to AWS

services/docker-compose.yml
This PR revises docket networks given in the `docker-compose.yml` file.
The computational_services_subnet was made less custom and now uses a default attachable docker network.
The interactive services subnet is left pretty much as-is for legacy services backwards compatability
The default network is explicitly added where it is present by default for notional clarity.
These changes should ideally not change or impact simcore microservice communication.
=> ♻️ Refactoring: Revise docker networks

.github/workflows/ci-testing-deploy.yml, services/docker-compose-ops.yml, services/docker-compose.yml
#3543
Bonus: ensure CI triggers on all tests if docker-compose files are changed.
=> ♻️ Rerevise docker networks dk (bis)  (⚠️ devops)

services/agent/Dockerfile
`rclone` was installed in the wrong docker image layer and was not available when running in production mode.
=> 🐛 agent running in production now has access to rclone

tests/e2e/tutorials/isolve-gpu.js, tests/e2e/tutorials/isolve-mpi.js, tests/e2e/tutorials/jupyterlabs.js, tests/e2e/tutorials/mattward.js, tests/e2e/tutorials/sim4life-light.js, tests/e2e/tutorials/sim4life.js, tests/e2e/tutorials/sleepers.js, tests/e2e/tutorials/ti-plan.js, tests/e2e/tutorials/tutorialBase.js
The splash screen can stay there for just a bit longer than the hardcoded 15" (increased to 20").
=> e2e: Increase S4L startup time

packages/settings-library/src/settings_library/catalog.py, packages/settings-library/src/settings_library/r_clone.py, packages/settings-library/src/settings_library/utils_r_clone.py, packages/settings-library/tests/test_utils_r_clone.py, services/agent/src/simcore_service_agent/modules/volumes_cleanup/_s3.py, services/agent/tests/unit/test_modules_volumes_cleanup_s3.py
Agent clone configuration appears not to be correct in master, which runs with a CEPH backend.
- ♻️ rlcone output afet sync command is more helpful (states what files it synced)
- 🐛 Fiexed issues with `MINIO` and `CEPH` in `S3Provider` enum that caused warnings in the logs. (unsure if these also blocked transfers)
=> 🐛 agent rclone configuration fixes

services/static-webserver/client/source/class/osparc/data/model/Node.js, services/static-webserver/client/source/class/osparc/ui/message/Loading.js
Once the backend tells the frontend that a dynamic service is ready and provides the service url, the frontend pings it to really make sure that it is responsive.
In some cases this is not enough, this PR adds one more check after the successful ping.
The process is the following
- The backend set the service state to ready
- The backend provides the service url
- The frontend pings the service url until it receives a successful response
- **New**: In order to make sure that everything is set, the frontend requests (and retries) the service website.
- The iframe is loaded and it requests the service website
While the service is loading, show service's thumbnail instead of vendor's logo
=> Request service frontend after successful ping

services/autoscaling/requirements/_test.in, services/autoscaling/requirements/_test.txt, services/autoscaling/requirements/_tools.txt, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/utils_docker.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_utils_docker.py
This PR removes the "Down" monitored nodes from the docker node list on the manager, to keep things tidy.
Bonus: better wait for services to go down (should remove flakyness in autoscaling tests)
=> ✨Autoscaling: automatically cleanup nodes from the docker swarm

services/web/server/requirements/_base.in, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt, services/web/server/requirements/_tools.txt, services/web/server/src/simcore_service_webserver/socketio/server.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/integration/02/test_rabbit.py, services/web/server/tests/unit/with_dbs/03/garbage_collector/test_resource_manager.py
This reverts commit db03a28713d14aa64698ba6deffa339e95ed2803.
Reason: Frontend needs an update before that can go in
=> Revert "⬆️ Maintenance: Upgrade python-socketio + flakyness (#3622)"

tests/e2e/tutorials/ti-plan.js
In order not to accumulate too many TIP studies in puppeteer's account, if TIP e2e test fails because the optimizer times out, close the "Preparing Inputs" view before going back to the dashboard
=> e2e: close Preparing Inputs window

services/static-webserver/client/source/class/osparc/component/permissions/ShareWith.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/GroupedToggleButtonContainer.js, services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js, services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js, services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js, services/static-webserver/client/source/class/osparc/store/Store.js
We can now group Templates by "Shared with"
The grouping functionality is also available for Services!
Group by "Shared with"
Group Services
=> ✨ Groups Templates (and Services!) by Shared with

services/agent/src/simcore_service_agent/modules/volumes_cleanup/_s3.py
Helps with debugging since the application is running at warning log level. Currently on master I've just realised there is an issue but the log level is too high (which is correct) and the error is not logged. Including it where it makes sense.
=> 🐛 agent rclone error is also included when logged

services/director-v2/tests/unit/with_dbs/test_api_route_dynamic_services.py
How this test passed the CI is a complete mystery to me! @sanderegg or @pcrespov any ideas?
Not sure why the CI passed on this test.
=> 🐛fixed test blocking CI in director-v2 unittests

packages/service-library/src/servicelib/background_task.py, packages/service-library/tests/test_background_task.py, services/web/server/src/simcore_service_webserver/projects/project_lock.py, services/web/server/tests/unit/with_dbs/03/test_redis.py
Previously we were using aioredlock to lock projects. When we migrated to redis-py, we lost the automatic timeout extension of distributed locks. This probably led to the following issues:
https://github.com/ITISFoundation/osparc-issues/issues/724
https://github.com/ITISFoundation/osparc-simcore/issues/3145
in case of a crash in the webserver, these locks would never timeout.
This PR aims to fix this by mimicking the behavior of aioredlock (default timeout of 10 seconds, with auto-extension every 6 seconds). In case the webserver would restart/crash without having the time to release the lock, this would ensure the lock is released at some point.
This PR just fixes the ProjectLock, all the other locks are not concerned with this change.
just looking at master's redis-commander shows how …
=> 🐛Introduce timeout in project lock (a la aioredlock)

packages/service-library/src/servicelib/rabbitmq.py, services/web/server/src/simcore_service_webserver/computation_subscribe.py
Since @mrnicegyu11 fixed how prometheus scrapes instances of the webserver, the metrics coming out of it were multiplied by the number of instances. The bugfix was correct, but then the metrics were wrong.
The final issue was identified as being a flaw in how the webserver gets the metrics out of RabbitMQ.
It was using ```exclusive``` queues (1 per instance of the webserver), thus replicating the metrics in all instances.
Now it uses a non-exclusive queue to this end.
fixes https://github.com/ITISFoundation/osparc-simcore/issues/3472
=> 🐛 Metrics: ensure instrumentation messages are treated only once

services/autoscaling/src/simcore_service_autoscaling/core/errors.py, services/autoscaling/src/simcore_service_autoscaling/core/settings.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/models.py, services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_core_settings.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_models.py, services/autoscaling/tests/unit/test_modules_ec2.py, services/autoscaling/tests/unit/test_utils_docker.py, services/autoscaling/tests/unit/test_utils_rabbitmq.py
This PR brings a mechanism to scale down the nodes created by the autoscaling application. (concerns only AWS deployments).
The following concepts were already known:
- A monitored node is a node with labels defined as in ```NODES_MONITORING_NODE_LABELS```
- An observed service is a service with labels defined as in ```NODES_MONITORING_SERVICE_LABELS``` (also its tasks are labeled the same)
- The autoscaling service scales up the cluster with fitting machines when it detects observed services that are pending resources (one at a time for now)
- The new EC2 instances are connected to the swarm in ```drain``` mode, labelled accordingly  and then made ```active``` so that the swarm can schedule the services on them
The following concepts are new:
- When a node is not running any observed …
=> ✨ Autoscaling: scale down nodes

services/docker-compose.local.yml, services/docker-compose.yml
Long running tasks in the webserver are NOT distributed.
Therefore copies are failing when not in sticky connection.
=> 🐛 Maintenance: revert disabling of sticky connection

packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py
Give more information when the 400 bad request issue arises. see https://github.com/ITISFoundation/osparc-simcore/issues/3531
https://github.com/ITISFoundation/osparc-simcore/issues/3531
=> ♻️ File Upload issue in AWS: add more informative logs

services/web/server/src/simcore_service_webserver/projects/projects_api.py
Ensure the lock state is passed to the frontend when listing projects.
=> 🐛 Edit templates: missing lock when opening dashboard

services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js
=> 🐛 Bugfixes Lock on Study card & Update card

services/static-webserver/client/source/class/osparc/CookiePolicy.js, services/static-webserver/client/source/class/osparc/component/form/ColorPicker.js, services/static-webserver/client/source/class/osparc/component/form/tag/TagItem.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonLoadMore.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/dashboard/ToggleButtonContainer.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/ui/basic/Tag.js
Before (tags and edit template):
After (tags and edit template):
Before (Load More):
After (Load More):
closes https://github.com/ITISFoundation/osparc-issues/issues/817
closes https://github.com/ITISFoundation/osparc-issues/issues/818
=> 🐛 Fixes: Load More card, Cookie text, Text on Tag and Edit template

services/storage/src/simcore_service_storage/db_projects.py, services/storage/src/simcore_service_storage/simcore_s3_dsm.py
@drniiken could not copy a template project that he owned. This was a side effect of having corrupted data in both ``projects`` and ``meta_data`` tables. The copy routine was failing because a validation error on some data owned by the same user.  The corrupt data had nothing to do with this operation but the error was not handled properly which resulted in a confusing 400 error with ``message=Invalid header token`` 
Running the same request from storage i.e. ``GET http://storage:8080/v0/locations/0/files/metadata?user_id=5&uuid_filter=b7...`` revealed the validation error.
Two actions were taken:
1.  fixed corrupted data in staging
2. create this PR that skips corrupted data in the database
This should prevent for the moment this error but does not completely solves the problem. Follow …
=> 🐛 Fix/storage skip invalid projects while listing

packages/simcore-sdk/src/simcore_sdk/node_ports_common/client_session_manager.py, packages/simcore-sdk/tests/unit/test_node_ports_common_file_io_utils.py
force aiohttp client to not keep connections alive. This might help when trying to re-upload a part.
might help with https://github.com/ITISFoundation/osparc-simcore/issues/3531
=> 🐛⚗️ Bugfix/is3531/try disabling keep alive when uploading

tests/e2e/portal/2D_Plot.js, tests/e2e/portal/3D_Anatomical.js, tests/e2e/portal/3D_EM.js, tests/e2e/portal/Bornstein.js, tests/e2e/portal/CC_Human.js, tests/e2e/portal/CC_Rabbit.js, tests/e2e/portal/Kember.js, tests/e2e/portal/Mattward.js, tests/e2e/portal/opencor.js, tests/e2e/publications/Voila.js, tests/e2e/s4l/sim4life-dipole.js, tests/e2e/s4l/sim4life-lite.js, tests/e2e/s4l/sim4life.js, tests/e2e/tutorials/isolve-gpu.js, tests/e2e/tutorials/isolve-mpi.js, tests/e2e/tutorials/jupyterlabs.js, tests/e2e/tutorials/sleepers.js, tests/e2e/tutorials/ti-plan.js, tests/e2e/tutorials/tutorialBase.js, tests/e2e/utils/utils.js
This PR enables the puppeteer to run against `testing.osparc.io` routes with basic-authentication. The usecase for this is to check that oSparc is running correctly after a scheduled maintenance. Using the `testing.osparc.io` route, the maintenance page can be bypassed. E2E tests can then be run (manually from a console) against a deployment which is still showing a maintenance page.
*How to run against testing route:*
```
cd osparc-simcore
sudo apt-get install libxss1 #at least on wsl2 this is necessary
npm i tests/e2e
cd tests/e2e
for i in $(ls tutorials/ | grep -e '\.js$'); 
do 
echo $i && node --trace-warnings tutorials/$i https://testing.osparc-master.speag.com --user XXXXXXX@example.org --pass XXXXXXXXX --start_timeout 12000 --basicauth_user XXXXXXXXX --basicauth_pass XXXXXXXXX > …
```
=> ✨ Add capability to use basicauth flags to e2e puppeteer

services/static-webserver/client/source/class/osparc/component/metadata/ServicesInStudyUpdate.js, services/static-webserver/client/source/class/osparc/component/service/ServiceButtonList.js, services/static-webserver/client/source/class/osparc/dashboard/CardBase.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js, services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js, services/static-webserver/client/source/class/osparc/store/Support.js
As requested by @habz-bs, this PR makes possible to Update all Templates with one click.
=> ✨Frontend: Update all templates

services/static-webserver/client/source/class/osparc/component/form/tag/TagItem.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/ui/list/MemberListItem.js, services/static-webserver/client/source/class/osparc/ui/list/OrganizationListItem.js, services/static-webserver/client/source/class/osparc/utils/Study.js
Bugfixes:
After (tags and manager bugfixes, unique name):
Before (tags and manager bugs):
=> 🐛 Bugfixes Frontend: Support null Tag description & Managers can Edit organization details

services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/utils/Clusters.js
The startup sequence of the frontend was buggy when it had to load a given studyId. This was the case for anonymous users.
Fixed:
=> 🐛 Bugfix: Anonymous start

services/autoscaling/src/simcore_service_autoscaling/core/errors.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_modules_ec2.py, services/autoscaling/tests/unit/test_utils_docker.py
This PR changes the way autoscaling app treats services with pending tasks.
BEFORE:
- runs every X seconds
- if there are pending tasks needing resources, it would create a number of machines to accommodate them
- **waits for the launched machine to appear (e.g. about 3 minutes)**
--> If there new tasks needing resources in the meantime they have to wait that additional time+X
AFTER:
- runs every X seconds
- if there are pending tasks needing resources, it would create a number of machines to accommodate them
- **only waits until the new EC2 instances exist (e.g. a few seconds)**
--> If there are new tasks needing resources in the meantime, they only wait a few seconds+X
Also fix the problem that dy-sidecar are pinned down to a node with specific ID and become pending with resources again …
=> ✨🐛 Autoscaling: async creation of machines

services/web/server/src/simcore_service_webserver/_constants.py, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/login/plugin.py, services/web/server/src/simcore_service_webserver/rest_handlers.py, services/web/server/tests/unit/isolated/test_application_settings.py, services/web/server/tests/unit/isolated/test_rest.py
Fixes value of ``invitation_required``  in ``/config``. This configuration depends on the product now and it was returned the app-level config instead.
=> 🐛 Fixes invitation_required value in /config 

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_scheduler.py, services/director-v2/tests/conftest.py
Adding cancellation of observation cycle. Allows for resources to be freed and services to close faster.
NOTE: by design, the legacy dynamic sidecar scheduler, never supported this. The observation cycle will raise some unexpected errors when cancelled. :hammer::hammer:
NOTE: upcoming, new version of the scheduler, already comes with proper cancellation and will avoid all this mess.
- fixes https://github.com/ITISFoundation/osparc-issues/issues/827
=> 🐛 observation cycle cancellation

packages/models-library/src/models_library/basic_regex.py, packages/models-library/src/models_library/docker.py, packages/models-library/tests/test_docker.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/tests/unit/test_core_docker_compose_utils.py, services/dynamic-sidecar/tests/unit/test_core_docker_utils.py
use aiodocker and its integrated progress context to pull container service images
fixes #3229
=> ✨ Enhancement/dynamic sidecar/add progress pulling services

services/static-webserver/client/source/class/osparc/component/message/FlashMessenger.js, services/static-webserver/client/source/class/osparc/component/notification/NotificationUI.js, services/static-webserver/client/source/class/osparc/component/notification/Notifications.js, services/static-webserver/client/source/class/osparc/data/MaintenanceTracker.js
Keep asking every 20' in case there are updates:
related to https://github.com/ITISFoundation/osparc-simcore/issues/3784: UI: force logout users only between the time span (begin, end] of maintenance
=> ✨ Maintenance Tracker II

packages/models-library/src/models_library/basic_regex.py, packages/models-library/src/models_library/rabbitmq_messages.py, packages/models-library/src/models_library/utils/enums.py, packages/models-library/tests/test_utils_enums.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/file_io_utils.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py, services/autoscaling/tests/unit/test_utils_rabbitmq.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/projects_networks.py, services/dynamic-sidecar/Dockerfile, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/mounted_fs.py, services/web/server/src/simcore_service_webserver/computation_subscribe.py, services/web/server/src/simcore_service_webserver/socketio/events.py
Brings more progress messages to the frontend:
- cluster up-scaling
- ~~sidecar image pulling~~ (might come later)
- state push/pull
- inputs pull
- outputs pull
- service image pulling
- comp. service running
This PR enables a new exchange in RabbitMQ for progress information.
This progress are forwarded to the webclient with the ```nodeProgress``` event that contains:
```python
{
"user_id": int,
"project_id": uuid,
"node_id": uuid,
"progress_type": str,
"progress": 0-1.0
}
```
progress type can be of the following:
```
"COMPUTATION_RUNNING"
"CLUSTER_UP_SCALING"
"SIDECAR_PULLING"
"SERVICE_INPUTS_PULLING"
"SERVICE_OUTPUTS_PULLING"
"SERVICE_STATE_PULLING"
"SERVICE_IMAGES_PULLING"
"SERVICE_STATE_PUSHING"
"SERVICE_OUTPUTS_PUSHING"
```
NOTE:
for the SERVICE_IMAGES_PULLING as well as for …
=> ✨ Enhancement/improve progress messages

Makefile, README.md, services/api-server/src/simcore_service_api_server/utils/client_base.py, services/invitations/Makefile, services/invitations/README.md, services/invitations/src/simcore_service_invitations/cli.py, services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/invitations.py, services/web/server/src/simcore_service_webserver/invitations_client.py, services/web/server/src/simcore_service_webserver/invitations_core.py, services/web/server/src/simcore_service_webserver/invitations_settings.py, services/web/server/src/simcore_service_webserver/login/_registration.py, services/web/server/src/simcore_service_webserver/login/handlers_registration.py, services/web/server/src/simcore_service_webserver/login/plugin.py, services/web/server/tests/unit/with_dbs/03/test_invitations.py
Implements new invitations check on the web-server
- ✨ New ``web/server/invitations`` plugin to interact with the ``invitations`` service
- ``invitations_settings.py``: plugin settings
- ``invitations_client.py``: SDK to interact with the service http API. 
- setup/tear-down client session
- exposes service API
- ``invitations.py``: exposes plugin API (free functions and exceptions) and ``setup_*`` function
- ✨ Adds new invitations check in ``web/server/login`` plugin
- 🔨 Cleanup scripts in ``invitations`` service
- 📝 Cleanup badges in README
- ITISFoundation/osparc-simcore#3683: webserver side of the invitations
- unit tested with coverage >85%
- manually
1. set  ``WEBSERVER_LOGIN_REGISTRATION_CONFIRMATION_REQUIRED=1`` and ``WEBSERVER_LOGIN_REGISTRATION_INVITATION_REQUIRED=1`` in …
=> ✨ Is3683/invitations webserver check

services/static-webserver/client/source/class/osparc/component/node/BaseNodeView.js, services/static-webserver/client/source/class/osparc/component/permissions/Permissions.js, services/static-webserver/client/source/class/osparc/component/permissions/Service.js, services/static-webserver/client/source/class/osparc/component/permissions/Study.js, services/static-webserver/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/static-webserver/client/source/class/osparc/desktop/preferences/pages/OrganizationsPage.js, services/static-webserver/client/source/class/osparc/ui/list/CollaboratorListItem.js, services/static-webserver/client/source/class/osparc/ui/list/ListItem.js, services/static-webserver/client/source/class/osparc/ui/list/MemberListItem.js
Expose to the frontend more member access rights operations:
- Owners (read, write, delete) can:
- Promote Collaborators to Owners
- Demote other Owners to Collaborators
- Remove others
- Collaborators (read, write) can:
- Promote Collaborators to Collaborators
- Demote other Collaborators to Viewers
- Remove others
- Viewers (read) can:
- No operations
- Organizations: Promote to Admin and Demote to Member
closes https://github.com/ITISFoundation/osparc-issues/issues/843
closes https://github.com/ITISFoundation/osparc-issues/issues/837
=> ✨ Study/Template/Service permissions

services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js, services/static-webserver/client/source/class/osparc/store/Store.js
We would like to sort Tags by popularity (EM-FDTD, EM-QS, Neuron, Thermal), but since we don't have such a feature, sorting them by name also does the trick.
**Bonus**:  Do not allow selecting locked cards
Sorted Tags:
Locked cards:
closes https://github.com/ITISFoundation/osparc-issues/issues/846
closes https://github.com/ITISFoundation/osparc-issues/issues/842
closes https://github.com/ITISFoundation/osparc-issues/issues/845
=> ✨ Sort Tags alphabetically

packages/service-library/src/servicelib/long_running_tasks/_task.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_port.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_manager.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_event_filter.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_manager.py
Out ports are currently not working. An interface changed that was not tested.
- ♻️ better error formatting for simpler tracking of issues
- ✨ added regression test to avoid changes to logging callback breaking the outputs again
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3794
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3800
=> 🐛 Fix broken output ports

.vscode/extensions.json, packages/service-library/src/servicelib/long_running_tasks/_errors.py, services/dynamic-sidecar/setup.cfg, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py, services/dynamic-sidecar/tests/unit/test_core_docker_utils.py, services/web/server/src/simcore_service_webserver/session_access.py
The error message reported in #3793: ``[...] 784 finished with exception: ''93dac263047b''``  is due to a ``KeyError``. And the trace shows the location:
```log
[... ]
/simcore_service_dynamic_sidecar/core/docker_utils.py", line 129, in _parse_docker_pull_progress
_, layer_total_size = all_image_pulling_data[image_name][layer_id]
[... ]
```
Since a ``KeyError `` converted to a string is directly the erroneous key 
```python
x = {}
try:
y = x["93dac263047b"]
except KeyError as err:
print(f"The error is {err}")
```
will print
```cmd
The error is 93dac263047b
```
- 🐛Essentially initializing the item as ``all_image_pulling_data[image_name].setdefault(layer_id, (0,0))``. The former version of the algorithm expected a particular sequence of states that write and read from that container and …
=> 🐛 Fixes is3793: error while pulling images 

services/autoscaling/src/simcore_service_autoscaling/api/health.py, services/autoscaling/src/simcore_service_autoscaling/core/settings.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/models.py, services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py, services/autoscaling/src/simcore_service_autoscaling/utils/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_modules_ec2.py, services/autoscaling/tests/unit/test_utils_docker.py, services/autoscaling/tests/unit/test_utils_dynamic_scaling.py
- some refactoring
- some bugfixes (issues with timezones, never use utcnow() anymore but now(timezone.utc), getting EC2 instances AND vs OR operation, sending of progress when upscaling)
- adds Name tag on EC2 instances such that lucky people with UI access can see machine names ;) @Surfict 
-  (⚠️ devops) introduces new ENV ```EC2_INSTANCES_MACHINES_BUFFER```, defaults to 0 when **undefined** Please currently define to 0
This PR teaches the autoscaling to keep a buffer of machines when upscaling and downscaling **BUT** not usable until episode II as this will indeed create more machines than necessary in case of load and keep always that number of buffer machines when scaling down but not ensure that EC2_INSTANCES_MACHINES_BUFFER is always present.
=> ✨Autoscaling: have a buffer of machines always ready (episode I)  (⚠️ devops)

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/auth/LoginPage.js, services/static-webserver/client/source/class/osparc/auth/ui/Login2FAValidationCodeView.js, services/static-webserver/client/source/class/osparc/auth/ui/VerifyPhoneNumberView.js, services/static-webserver/client/source/class/osparc/component/task/TaskUI.js, services/static-webserver/client/source/class/osparc/component/task/TasksButton.js, services/static-webserver/client/source/class/osparc/dashboard/ServiceBrowser.js, services/static-webserver/client/source/class/osparc/data/model/Node.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/store/StaticInfo.js, services/static-webserver/client/source/class/osparc/ui/basic/LogoWPlatform.js, services/static-webserver/client/source/class/osparc/utils/LibVersions.js, services/static-webserver/client/source/class/osparc/utils/Utils.js
Thanks to the feedback coming from @pcrespov 
In order to give a better feedback to the user:
related to https://github.com/ITISFoundation/osparc-issues/issues/765
=> ✨Frontend UX: Enhance registration/login process

Makefile, services/autoscaling/src/simcore_service_autoscaling/core/settings.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/models.py, services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py, services/autoscaling/src/simcore_service_autoscaling/utils/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/rabbitmq.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_utils_docker.py, services/autoscaling/tests/unit/test_utils_dynamic_scaling.py, services/autoscaling/tests/unit/test_utils_ec2.py, services/autoscaling/tests/unit/test_utils_rabbitmq.py
continues from #3790 
This PR reworked the machine buffering enhancement. After this PR the autoscaling service can keep a constant number of so-called "reserve machines" that are in docker swarm *drain* mode. Therefore these machines are ready for running services in a few seconds (max 20 seconds which is the time the autoscaling background task interval + possibly starting other instances).
1. no load: the reserved drain machines are kept forever
2. under load: when machines in the reserve are used for services, then new machines are pre-created and added to the reserve again
- implement some heuristic to have *smart reserve*. Why keep unneeded resources forever if there is a long time of innactivity?
-  (⚠️ devops) ```EC2_INSTANCES_MACHINES_BUFFER``` is now usable and shall be defined …
=> ✨ Autoscaling: buffer machines Episode II (⚠️ devops)

services/static-webserver/client/source/class/osparc/component/node/BaseNodeView.js, services/static-webserver/client/source/class/osparc/component/notification/Notification.js, services/static-webserver/client/source/class/osparc/component/notification/NotificationsRibbon.js, services/static-webserver/client/source/class/osparc/component/permissions/PublishTemplateWith.js, services/static-webserver/client/source/class/osparc/component/permissions/Service.js, services/static-webserver/client/source/class/osparc/component/permissions/Study.js, services/static-webserver/client/source/class/osparc/component/task/TasksButton.js, services/static-webserver/client/source/class/osparc/component/widget/SlideBar.js, services/static-webserver/client/source/class/osparc/data/MaintenanceTracker.js, services/static-webserver/client/source/class/osparc/data/model/NodeProgressSequence.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/navigation/BreadcrumbsSlideshow.js, services/static-webserver/client/source/class/osparc/ui/basic/NodeStatusUI.js, services/static-webserver/client/source/class/osparc/ui/message/Loading.js, services/static-webserver/client/source/class/osparc/utils/StatusUI.js, services/static-webserver/client/source/class/osparc/viewer/MainPage.js
Maintenance Notifications, instead of being shown as Flash Messages, they now go to the Ribbon.
A closable Notification is added 12h in advance and a permanent one will replace it/will be shown 30' in advance.
ITISFoundation/osparc-issues#765
=> ✨ Feature: Maintenance Notification on ribbon

services/static-webserver/client/source/class/osparc/component/form/tag/TagItem.js, services/static-webserver/client/source/class/osparc/theme/Appearance.js, services/static-webserver/client/source/class/osparc/theme/zmt/ColorLight.js, services/static-webserver/client/source/class/osparc/ui/basic/Tag.js, services/static-webserver/client/source/class/osparc/utils/Utils.js
As reported by @eofli, the light theme needs some love and also contrast in its basic color palette. This PR only brings the contrast thing.
Notice the buttons and strong button's text color.
Before:
After:
=> ✨ Frontend: Increase light theme's contrast

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_compose_egress_config.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/validation.py, services/dynamic-sidecar/tests/unit/test_api_containers.py, services/dynamic-sidecar/tests/unit/test_api_containers_long_running_tasks.py
_The art of copy and pasting is something very few manage to master. I am really bad at it.🤦_ 
PR https://github.com/ITISFoundation/osparc-simcore/pull/3606 broke the sidecars not running on manager nodes.
Removed `overlay` driver from the service docker-compose spec. The node needs to be a swarm manager in order to use it. It is also not necessary in this case.
- fixes issue introduced by https://github.com/ITISFoundation/osparc-simcore/pull/3606
=> 🐛 Removing overlay from docker-compose spec

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/auth/ui/LoginView.js, services/static-webserver/client/source/class/osparc/component/task/TaskUI.js, services/static-webserver/client/source/class/osparc/data/Roles.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/ui/window/Confirmation.js, services/static-webserver/client/source/class/osparc/ui/window/Window.js
=> 📝 Frontend: wording and center windows

services/static-webserver/client/source/class/osparc/data/model/Node.js, services/static-webserver/client/source/class/osparc/data/model/NodeProgressSequence.js, services/static-webserver/client/source/class/osparc/data/model/NodeStatus.js
Reset Node's start up sequence when:
- it fails
- it gets restarted
- it gets stopped
=> ✨ Reset Node's start up sequence

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py
- increase the ```COMPOSE_HTTP_TIMEOUT``` env variable when calling docker-compose from the dynamic sidecar on a freshly created node. NOTE: this will be deprecated with docker-compose V2
- fixes the issue with starting s4l-lite on a fresh node
references: 
- https://github.com/AzuraCast/AzuraCast/issues/3258
- https://github.com/docker/compose/issues/3927
=> 🐛 Dynamic sidecar: failing service on freshly started node

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/MaintenanceTracker.js, services/static-webserver/client/source/class/osparc/WindowSizeTracker.js, services/static-webserver/client/source/class/osparc/component/notification/Notification.js, services/static-webserver/client/source/class/osparc/component/notification/NotificationsRibbon.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/desktop/preferences/Preferences.js, services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ConfirmationsPage.js, services/static-webserver/client/source/class/osparc/navigation/UserMenuButton.js, services/static-webserver/client/source/class/osparc/viewer/MainPage.js, tests/e2e/tutorials/ti-plan.js
This PR changes the notification system for small screens.
We used to have a (too annoying) pop up message in the center of the window. This PR will replace it with a message on the ribbon.
=> ✨ Frontend: Window too small message to ribbon

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_base.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_thin.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_base.py
Apparently the dynamic-schedueler is eating up all connections in the http client used to talk to the dy-sidecars. This causes the director to stop talking to them. 
This tries to add more details about what is happening to the connection pool.
- using correct instance of the client (no longer creating a new one)
- better pool usage details
=> ♻️ director-v2 api client enhancements

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py, services/director-v2/src/simcore_service_director_v2/utils/client_decorators.py, services/director-v2/tests/unit/test_utils_client_decorators.py
Some log messages are not helpful. Refactoring logs to make them more useful.
=> ♻️ Cleaning up logs

services/web/server/src/simcore_service_webserver/email_core.py, services/web/server/src/simcore_service_webserver/email_handlers.py, services/web/server/src/simcore_service_webserver/email_settings.py, services/web/server/src/simcore_service_webserver/login/_2fa.py, services/web/server/src/simcore_service_webserver/login/handlers_change.py, services/web/server/src/simcore_service_webserver/login/handlers_registration.py, services/web/server/src/simcore_service_webserver/login/utils_email.py, services/web/server/src/simcore_service_webserver/publication_handlers.py, services/web/server/tests/unit/with_dbs/03/login/test_login_utils_emails.py, services/web/server/tests/unit/with_dbs/03/test_email.py, services/web/server/tests/unit/with_dbs/conftest.py
- 🐛 Sets more fields in header reducing the changes that get rejected or marked as spam
- ♻️ returns email-headers in  ``POST /emails:test`` entrypoint
- ♻️ cleanup naming
- some registration emails got into spam folder
- Manual test using ``POST /emails:test``
=> 🐛 Adds message-id and date to email headers

services/static-webserver/client/source/class/osparc/AboutProduct.js, services/static-webserver/client/source/class/osparc/auth/ui/LoginView.js, services/static-webserver/client/source/class/osparc/auth/ui/RegistrationView.js, services/static-webserver/client/source/class/osparc/auth/ui/ResetPassView.js, services/static-webserver/client/source/class/osparc/component/editor/ClusterEditor.js, services/static-webserver/client/source/class/osparc/component/form/Auto.js, services/static-webserver/client/source/class/osparc/desktop/preferences/pages/SecurityPage.js, services/static-webserver/client/source/class/osparc/ui/form/PasswordField.js, services/static-webserver/client/source/class/osparc/utils/LibVersions.js
This PR implements a new passwordField widget that is able to show/hide the password
requested by @sfarcito
=> ✨ Frontend: show password

services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js
This PR excludes from the shared-with grouping the organizations that are actually single users.
Before:
After:
=> 🐛 Frontend: cleanup shared-with grouping

services/static-webserver/client/source/class/osparc/auth/LoginPage.js, services/static-webserver/client/source/class/osparc/component/metadata/ServicesInStudy.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/product/AboutProduct.js, services/static-webserver/client/source/class/osparc/product/tutorial/s4llite/Dashboard.js, services/static-webserver/client/source/class/osparc/product/tutorial/s4llite/S4LLiteSpecs.js, services/static-webserver/client/source/class/osparc/product/tutorial/s4llite/S4LLiteUI.js, services/static-webserver/client/source/class/osparc/product/tutorial/s4llite/Welcome.js, services/static-webserver/client/source/class/osparc/store/Support.js
The last re-rebranding implies that S4L lite is now written as <i>S4L<sup>lite</sup></i>.
Some labels in the frontend couldn't support html text. This PR brings that feature.
closes https://github.com/ITISFoundation/osparc-issues/issues/864
=> 🐛✨ Frontend: Make labels html compatible

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_base.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_abc.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_task.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_base.py, services/director-v2/tests/unit/test_modules_dynamic_sidecar_observer.py
- ♻️ adds extra logs for the connection pool in the dynamic_sidecar_client
- 🐛 fixes an edge case where dynamic sidecars scheduler would end up in a loop calling `_apply_observation_cycle` and `mark_service_for_removal`. This was introduced when https://github.com/ITISFoundation/osparc-simcore/pull/3771 was added
=> 🐛 Fix edge case when cancelling observation

services/static-webserver/client/source/class/osparc/data/model/NodeProgressSequence.js
The Dynamic service start up sequence was wrong: SIDECARS_PULLING comes before CLUSTER_UP_SCALING.
ITISFoundation/osparc-issues#765
=> ✨🐛 Frontend: Node Progress update sequence

services/static-webserver/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/static-webserver/client/source/class/osparc/theme/ColorDark.js, services/static-webserver/client/source/class/osparc/theme/ColorLight.js, services/static-webserver/client/source/class/osparc/theme/zmt/ColorDark.js, services/static-webserver/client/source/class/osparc/theme/zmt/ColorLight.js, services/static-webserver/client/source/class/osparc/ui/message/Loading.js
The issue for rendering Edges (node connections) in the Workbench is that the Nodes need to be printed before printing the Edges (these depend on the position of the in/out ports). This PR changes the mechanism for rendering them.
Before, we had a while loop with a 4 seconds timeout that would wait for all Nodes to be visible. We now listen to the ```appear``` event on the Node and once all nodes are printed we proceed to render the Edges.
Reported by Fariba Karimi.
=> 🐛 Bugfix: Workbench: render Edges after making sure all Nodes were rendered

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_public.py
If the user services were not started already, the project_network attach fails. It should be interrupted without an error.
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3866
=> 🐛 Avoid project_networks_attach failing

services/autoscaling/src/simcore_service_autoscaling/core/settings.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_utils_dynamic_scaling.py
For S4l-lite we do use [g4dn.8xlarge EC2 instance type](https://aws.amazon.com/ec2/instance-types/).
These provide a 900GB SSD with NVME connection that is usable directly and provides with ~16kIOPS. About 5 times more than the usual gp3 EBS backed drive.
This PR brings a new ENV ```EC2_INSTANCES_CUSTOM_BOOT_SCRIPTS``` that allows to pass custom boot scripts to the EC2 instance when booting.
One usage of this is the following:
```
EC2_INSTANCES_CUSTOM_BOOT_SCRIPTS=["mkfs --type xfs -f -n ftype=1 /dev/nvme2n1","mkdir --parents /mnt/docker","mount /dev/nvme2n1 /mnt/docker","jq '.\"data-root\"=\"/mnt/docker/data\", .\"exec-root\"=\"/mnt/docker/exec\"' /etc/docker/daemon.json  > /tmp/daemon.json","mv /tmp/daemon.json /etc/docker/daemon.json","systemctl restart docker"]
```
On each booted EC2 …
=> ✨ Autoscaling: Use EC2 Instance Storage drive (⚠️ devops)

services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/autoscaling/src/simcore_service_autoscaling/modules/ec2.py, services/autoscaling/src/simcore_service_autoscaling/utils/dynamic_scaling.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/autoscaling/tests/unit/test_modules_ec2.py
This PR allows to run several Autoscaling services with different purposes:
- 1 Autoscaling that takes care for example of scaling EC2 instances for a specific service (i.e. jupyter-math)
- 1 Autoscaling that takes care for example of scaling EC2 instances for another service (i.e. s4l)
The PR allows both Autoscaling application to not trample each other feet by stealing each other machines.
Each Autoscaling is made unique through the ENV ```NODES_MONITORING_NODE_LABELS``` and ```NODES_MONITORING_SERVICE_LABELS```
NOTE: the moto library has an issue, see https://github.com/getmoto/moto/issues/5966. This implied that a patch had to be applied in the unit tests. Real testing with AWS showed that the system is functional.
bonus:
fixes …
=> ✨Autoscaling: allow multiple autoscaling services

services/static-webserver/client/source/class/osparc/dashboard/CardBase.js, services/static-webserver/client/source/class/osparc/dashboard/Dashboard.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonBase.js, services/static-webserver/client/source/class/osparc/dashboard/GridButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ListButtonItem.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/static-webserver/client/source/class/osparc/dashboard/ResourceContainerManager.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/dashboard/TemplateBrowser.js, services/static-webserver/client/source/class/osparc/data/Permissions.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js, services/static-webserver/client/source/class/osparc/ui/window/Dialog.js, services/static-webserver/client/source/class/osparc/ui/window/Window.js
=> ✨ Frontend Dashboard: Convert tab labels into icons for small screens

services/static-webserver/client/source/class/osparc/desktop/preferences/pages/ProfilePage.js, services/static-webserver/client/source/class/osparc/desktop/preferences/pages/SecurityPage.js, services/static-webserver/client/source/class/osparc/theme/Appearance.js, services/static-webserver/client/source/class/osparc/theme/products/osparc/Appearance.js, services/static-webserver/client/source/class/osparc/theme/products/s4l/Appearance.js, services/static-webserver/client/source/class/osparc/theme/products/tis/Appearance.js, services/static-webserver/client/source/class/osparc/ui/form/PasswordField.js
As requested by @GitHK, this PR makes it easier to navigate through the login/registration forms (the tab sequence was broken when the show-password-eye was introduced).
=> ✨ Frontend: Navigate through login forms

tests/e2e/tutorials/tutorialBase.js
Instead of waiting fixed 20" for the s4l iframe to appear and the splash screen to disappear, we now wait fixed 10" for the s4l iframe to appear and a maximum of 60" for the splash screen to disappear.
=> ✨ S4L e2e: wait for S4L Splash Screen to disappear

services/static-webserver/client/source/class/osparc/auth/Manager.js, services/static-webserver/client/source/class/osparc/auth/ui/RegistrationView.js, services/static-webserver/client/source/class/osparc/data/Resources.js
This PR implements the frontend part of https://github.com/ITISFoundation/osparc-simcore/pull/3856
During the registration process, if the user made it to the registration view using an invitation token, this invitation, that can contain the user's email address encrypted, is checked with the backend. If the backend responds with an associated email to that token, the frontend will fill up and disable the email textfield.
=> ✨Frontend User registration: Check Invitation email from token

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/DownloadLinkTracker.js, services/static-webserver/client/source/class/osparc/dashboard/StudyBrowser.js, services/static-webserver/client/source/class/osparc/file/FileLabelWithActions.js, services/static-webserver/client/source/class/osparc/file/FilePicker.js, services/static-webserver/client/source/class/osparc/utils/Utils.js, tests/e2e/utils/auto.js
This PR changes the way files are downloaded in the File Browser window.
Until now, we were downloading files using XMLHttpRequest and the given (presigned) URL. This meant that first the response had to be loaded, then convert it into the file blob and finally download it.
Now, we simply create a virtual HTML ```<a>``` tag, make it point to the given (presigned) URL and virtually click it, which directly starts the download process.
closes https://github.com/ITISFoundation/osparc-issues/issues/899
=> 🎨 Frontend: Improve UX for "Download of Study Data"

services/autoscaling/src/simcore_service_autoscaling/core/settings.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py
as explained there:
https://aws.amazon.com/ec2/pricing/on-demand/
The price of EC2 instances is billed by the second. therefore the default for terminating a node is changed from 55 minutes to 1 minute.
=> ♻️Autoscaling: set default termination time of EC2 instance to 1 minute

services/static-webserver/client/source/class/osparc/MaintenanceTracker.js, services/static-webserver/client/source/class/osparc/component/metadata/ServicesInStudy.js, services/static-webserver/client/source/class/osparc/component/node/BaseNodeView.js, services/static-webserver/client/source/class/osparc/component/widget/NodesTree.js, services/static-webserver/client/source/class/osparc/component/widget/StudyTitleOnlyTree.js, services/static-webserver/client/source/class/osparc/component/workbench/ServiceCatalog.js, services/static-webserver/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/static-webserver/client/source/class/osparc/desktop/SlideshowToolbar.js, services/static-webserver/client/source/class/osparc/info/CardLarge.js, services/static-webserver/client/source/class/osparc/info/MergedLarge.js, services/static-webserver/client/source/class/osparc/info/ServiceLarge.js, services/static-webserver/client/source/class/osparc/info/StudyLarge.js, services/static-webserver/client/source/class/osparc/info/StudyMedium.js, services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js
If the the aspect ratio of a thumbnail was too wide, it could trigger an infinite re-render of the entire Large Card (triggering also some unnecessary calls to the backend) and an annoying scrollbar that could hide key buttons.
This zusammenzuführen standardizes all the Large Cards (Study, Service and Merged) and limits the max width of the thumbnail.
Before:
After:
=> 🐛 Fix: Thumbnail width on Large Card

packages/service-library/tests/test_docker_utils.py, services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/test_utils_docker.py
Fixes unhandled exception in the sort predicate when autoscaling services is sorting tasks. This issue was found in production AWS [logs](https://monitoring.osparc.io/graylog/search?rangetype=absolute&from=2023-03-15T10%3A52%3A04.734Z&to=2023-03-15T10%3A52%3A06.734Z&q=source%3A%22manager1%22+AND+gl2_source_input%3A%2261b8724b5311605a9cb391d3%22&highlightMessage=6ceedf7f-c31f-11ed-bcdd-0242ac120009)
```logs
File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/background_task.py", line 33, in _periodic_scheduled_task
await task(**task_kwargs)
File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/redis_utils.py", line 30, in wrapper
return await func(*args, **kwargs)
File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/dynamic_scaling_core.py", line …
```
=> 🐛 Bug/autoscaling datetime failure

.github/ISSUE_TEMPLATE/1_bug_report.yml, README.md, scripts/docker/docker-compose-config.bash
- Badges that monitors the status of the status.osparc.io and https://s4llite.statuspage.io and redirect to them upon click.
- @odeimaiz something similar could be added to notify "incidents" in the front-end (see https://status.osparc.io/api for more info )
- add option in bug template form
- 🔨 Patch by @sanderegg that fixes ``make up-prod`` and ``make up-devel``
=> 📝 Maintenance: adds status badges and adds new fields in template forms for bug issues

services/docker-compose.yml
Agent requires slightly more RAM to properly work when rlcone is syncing. Setting the limit to a save 1GB to avoid future issues.
=> 🐛 raising agent limit to 1G

.github/workflows/ci-release.yml, .github/workflows/ci-staging.yml, .github/workflows/ci-testing-deploy.yml, ci/github/helpers/install_rclone_docker_volume_plugin.bash, scripts/install_rclone.bash, services/docker-compose.yml
Upgrades CI dependencies:
ubuntu 20.04 --> 22.04, but for director-v0 tests that require python 3.6, hence ubuntu 20.04 required.
buildx 0.8.2 --> 0.10.2
RClone 1.58.1 and 1.57 --> 1.62.1
=> ⬆️ CI: upgrade ubuntu/buildx

services/web/server/src/simcore_service_webserver/garbage_collector_core.py, services/web/server/tests/unit/isolated/test_garbage_collector_core.py
GC was wrongly fetching the `project_id`, it is now recovered from the intended data structure. I have no idea why I did that 🤷‍♂️
```
ERROR: [2023-03-17 08:34:35,601/MainProcess] [simcore_service_webserver.garbage_collector_core:_remove_single_orphaned_service(166)]  -  Exception: '6c2bca80-75f6-56bd-b169-7386e6e0ce21'
File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/logging_utils.py", line 160, in log_decorator_wrapper
value = await func(*args, **kwargs)
File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_webserver/garbage_collector_core.py", line 365, in _remove_single_orphaned_service
project_uuid = currently_opened_projects_node_ids[service_uuid]
KeyError: '6c2bca80-75f6-56bd-b169-7386e6e0ce21'
```
- fixes …
=> 🚑️ Fix GC error while trying to close service

services/static-webserver/client/source/class/osparc/component/workbench/WorkbenchUI.js, services/static-webserver/client/source/class/osparc/data/model/Node.js
4000! 🥳 
Request start service when double clicking on it if it's idle or failed.
4 different ways to start a service:
closes https://github.com/ITISFoundation/osparc-simcore/issues/3521
=> 🎨 Frontend: auto-start service when double clicking in service

services/static-webserver/client/source/class/osparc/component/share/NewCollaboratorsManager.js, services/static-webserver/client/source/class/osparc/store/Store.js
Since the last organization/members refactoring in the frontend, services can't be shared with Everyone. This PR enables again the feature.
=> 🐛 Bugfix: Let users make Services Public

packages/postgres-database/src/simcore_postgres_database/errors.py, packages/postgres-database/src/simcore_postgres_database/migration/versions/9014ae5fd6e5_checkconstraint_filetype.py, packages/postgres-database/src/simcore_postgres_database/models/services_consume_filetypes.py, packages/postgres-database/tests/test_services__meta_data.py, packages/postgres-database/tests/test_services_consume_filetypes.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_services.py, services/web/server/src/simcore_service_webserver/studies_dispatcher/handlers_redirects.py, services/web/server/tests/unit/with_dbs/01/studies_dispatcher/test_studies_dispatcher_handlers.py
Searching for ``filetype`` values in the API is now case insensitive. To achieve that we enforce the values in the db (currently inserted by hand) to be uppercase and the search/comparison is done that way. Highlights:
- Adds  a check constraint to ``services_consume_filetypes.filetype`` to ensure uppercase
- API parses and formats ``filetype`` as uppercase
- ♻️ Update tests
Based on the feedback from @ignapas after testing interaction with nih-portal
- related to ITISFoundation/osparc-issues#683
- add some extension with lower characters  to ``services_consume_filetypes.filetype`` wil raise a "CheckViolation" exception
=> 🐛 filetypes in webserver API are case insensitive

services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py, services/api-server/src/simcore_service_api_server/modules/webserver.py
Increase job creation speed by 30%, removing unnecessary call to director-v2
relates to https://github.com/ITISFoundation/osparc-issues/issues/675
relates to https://github.com/ITISFoundation/osparc-issues/issues/885
=> ♻️ Api server: improve job creation speed

services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.in, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/tests/unit/test_modules_dask_client.py
During heavy testing, it was observed that some errors are arising due to the fact that workers are disappearing from the gateway due to auto-adaptation of the number of workers.
This should fix this problem.
- relates to https://github.com/ITISFoundation/osparc-issues/issues/885
=> 🐛Dask: fix issue with disappearing workers

tests/e2e/tutorials/tutorialBase.js
Fixes ti-plan e2e test:
The PostPro step (s4l-lite-postpro) must have the smash file preloaded. We used to have only one pipeline in the algorithm tree (TI Field + Surface viewer) and one week ago we added a second pipeline (HF Field + Surface viewer), that's why the test started failing. With this change we make sure that there is at least one pipeline in the algorithm tree.
=> 🐛 fix e2e: ti-plan test

.github/workflows/ci-testing-deploy.yml, packages/pytest-simcore/requirements/coverage.txt, services/agent/requirements/_test.in, services/agent/requirements/_test.txt, services/api-server/requirements/_test.in, services/api-server/requirements/_test.txt, services/autoscaling/requirements/_test.in, services/autoscaling/requirements/_test.txt, services/catalog/requirements/_test.in, services/catalog/requirements/_test.txt, services/datcore-adapter/requirements/_test.in, services/datcore-adapter/requirements/_test.txt, services/director-v2/requirements/_test.in, services/director-v2/requirements/_test.txt, services/director/requirements/_test.in, services/director/requirements/_test.txt, services/invitations/requirements/_test.in, services/invitations/requirements/_test.txt, services/osparc-gateway-server/tests/system/requirements/_test.in, services/osparc-gateway-server/tests/system/requirements/_test.txt, services/storage/requirements/_test.in, services/storage/requirements/_test.txt, services/web/server/requirements/_test.in, services/web/server/requirements/_test.txt
After last [PyPI Object Storage Migration](https://status.python.org/incidents/y52td1f7pyy1) the python library ``codecov`` was removed from the PyPI index producing the following error after ``pip install``-ing:
```log
ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: none)
ERROR: No matching distribution found for codecov==2.1.12
```
- #packages before: 1
- #packages after : 0
|   1 | codecov                   | 2.1.12          | 🗑️ removed |  | 10 | agent🧪</br>api-server🧪</br>autoscaling🧪</br>catalog🧪</br>datcore-adapter🧪</br>director-v2🧪</br>invitations🧪</br>osparc-gateway-server🧪</br>storage🧪</br>web🧪 |
*Legend*: 
- ⬆️ base dependency (only services …
=> 🗑️  Removes deprecated ``codecov``

.github/workflows/ci-testing-deploy.yml, services/storage/src/simcore_service_storage/_meta.py, services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter.py, services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter_settings.py, services/storage/src/simcore_service_storage/db.py, services/storage/src/simcore_service_storage/db_file_meta_data.py, services/storage/src/simcore_service_storage/db_projects.py, services/storage/src/simcore_service_storage/handlers_datasets.py, services/storage/src/simcore_service_storage/handlers_files.py, services/storage/src/simcore_service_storage/handlers_health.py, services/storage/src/simcore_service_storage/handlers_locations.py, services/storage/src/simcore_service_storage/handlers_simcore_s3.py, services/storage/src/simcore_service_storage/s3.py, services/storage/src/simcore_service_storage/s3_client.py, services/storage/src/simcore_service_storage/settings.py, services/storage/src/simcore_service_storage/simcore_s3_dsm.py, services/storage/src/simcore_service_storage/utils.py
relates to https://github.com/ITISFoundation/osparc-simcore/issues/4071
```cmd
cd services/storage
make mypy
```
=> ✨Maintenance: enable mypy in storage

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/events.py, services/autoscaling/src/simcore_service_autoscaling/dynamic_scaling_core.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/projects_networks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_logs.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_manager.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_manager.py
The log level is already properly passed to the frontend with a default of INFO message (python log level of 20).
new: ensure the log level is passed all the way from the computational backend.
For now, not many changes.
relates to https://github.com/ITISFoundation/osparc-simcore/issues/4075
=> ♻️ Ensure log level is passed to the frontend

api/specs/webserver/openapi-projects.yaml, services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/projects/projects_handlers.py, services/web/server/tests/unit/with_dbs/02/test_projects_handlers__open_close.py
```/projects/{project_id}:open?disable_service_auto_start=true``` will prevent any dynamic service to start
@odeimaiz 
fixes https://github.com/ITISFoundation/osparc-simcore/issues/4074
=> ✨Webserver: Allow to disable auto-start of dynamic services

.github/workflows/ci-testing-deploy.yml, mypy.ini, packages/postgres-database/src/simcore_postgres_database/migration/versions/53e095260441_add_projects_access_rights_and_.py, packages/postgres-database/src/simcore_postgres_database/migration/versions/da8abd0d8e42_add_comp_runs_table.py, packages/postgres-database/src/simcore_postgres_database/utils_aiopg_orm.py, packages/postgres-database/src/simcore_postgres_database/utils_aiosqlalchemy.py, scripts/mypy.bash, scripts/mypy/Dockerfile, scripts/mypy/requirements.txt, services/api-server/src/simcore_service_api_server/models/schemas/jobs.py, services/api-server/src/simcore_service_api_server/models/schemas/meta.py, services/catalog/src/simcore_service_catalog/api/dependencies/database.py, services/catalog/src/simcore_service_catalog/models/domain/dag.py
After the upgrade of ``mypy`` in PR https://github.com/ITISFoundation/osparc-simcore/pull/4108 I noticed that many of the packages started to fail the ``mypy`` type-check step. 
- ``sqlalchemy-stub`` does not seem sufficient to support ``mypy``. Extended to ``sqlalchemy[mypy]``. See [details here](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html#installation).
- Follows up from https://github.com/ITISFoundation/osparc-simcore/pull/4108
- Related to https://github.com/ITISFoundation/osparc-simcore/issues/4071
- all ``typecheck`` steps in CI pass
- locally: ``make mypy``
=> 🔨♻️ Fixes mypy  issue after upgrade

services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/tests/unit/isolated/test_application_settings.py, services/web/server/tests/unit/with_dbs/01/clusters/conftest.py, services/web/server/tests/unit/with_dbs/01/clusters/test_clusters_handlers.py, services/web/server/tests/unit/with_dbs/01/clusters/test_clusters_plugin_setup.py, services/web/server/tests/unit/with_dbs/01/studies_dispatcher/conftest.py, services/web/server/tests/unit/with_dbs/03/invitations/test_invitations.py, services/web/server/tests/unit/with_dbs/03/login/conftest.py, services/web/server/tests/unit/with_dbs/03/test_email.py, services/web/server/tests/unit/with_dbs/conftest.py
Since the WEBSERVER_DEV_ENABLED env seems to bring some issues, this PR brings ```WEBSERVER_CLUTERS``` out of it.
By default it is disabled, and must be explicitly enabled.
⚠️: nothing to be done.
- relates to https://github.com/ITISFoundation/osparc-issues/issues/885
=> ♻️Clusters: make non dev feature, disabled by default (⚠️)

services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/factory.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/src/simcore_service_director_v2/utils/dask.py, services/director-v2/src/simcore_service_director_v2/utils/dask_client_utils.py, services/director-v2/src/simcore_service_director_v2/utils/scheduler.py, services/director-v2/tests/unit/conftest.py
Since cluster adaptive scaling seems to generate a lot of issues when running thousands of jobs this is now disabled.
Therefore the cluster is scaled to a hard-coded huge number (10'000 workers), which should be enough for the time being.
Bonus: some mypy fixes
- relates to https://github.com/ITISFoundation/osparc-simcore/issues/3991
- depends on https://github.com/ITISFoundation/osparc-simcore/pull/4133
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4107
=> ✨🐛Dask-gateway: disable adaptive cluster

services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director-v2/tests/unit/test_modules_dynamic_sidecar_client_api_thin.py
Apparently `httpx` or `anyio` (dependency) may have issues in resolving hostnames with docker. Trying to update to latest version to see if issue persists.
- trying to address https://github.com/ITISFoundation/osparc-simcore/issues/4161
=> ⬆️ upgrading httpx for director-v2

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_api/_core.py
Making logs in director-v2 more readable. The message was wrongly logged at `warning` log level. Dropping to `info` as it makes more sense.
- https://github.com/ITISFoundation/osparc-issues/issues/675
=> ♻️ Drop log priority

services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/test_utils_docker.py
Shall massively reduce the occurrence of the out of sequence error in the autoscaling logs. Which is nonetheless not a problem. mostly cosmetics as the draining is repeated in the next iteration.
- fixes #3860
=> 🐛Autoscaling: fix out of sequence error

packages/pytest-simcore/src/pytest_simcore/helpers/utils_postgres.py
Since the `migration` is updated (containers restart). We need to consider the current running task in order to properly assert that the migration passed.
- https://github.com/ITISFoundation/osparc-simcore/pull/4175
- https://github.com/ITISFoundation/osparc-issues/issues/675
=> 🐛 Fixes broken migrated_pg_tables_context

.pre-commit-config.yaml, Makefile, packages/dask-task-models-library/src/dask_task_models_library/container_tasks/io.py, packages/models-library/src/models_library/rest_pagination.py, packages/models-library/src/models_library/services.py, scripts/demo-meta/osparc_webapi.py, scripts/demo/create_portal_markdown.py, services/catalog/src/simcore_service_catalog/core/settings.py, services/director-v2/src/simcore_service_director_v2/cli/_client.py, services/director-v2/src/simcore_service_director_v2/models/schemas/dynamic_services/service.py, services/director/src/simcore_service_director/config.py, services/director/src/simcore_service_director/producer.py, services/invitations/src/simcore_service_invitations/cli.py, services/web/server/src/simcore_service_webserver/projects/projects_utils.py, services/web/server/src/simcore_service_webserver/statics_settings.py
Fixes the following bugs detected by sonar cloud:
- `director`'s `producer`: [Introduce a new variable or use its initial value before reassigning 'tasks'](https://sonarcloud.io/project/issues?open=AYBvvM9h_8r2OU53wDLi&id=ITISFoundation_osparc-simcore)
- `webserver`'s `project_utils`:  [Remove or correct this useless self-assignment](https://sonarcloud.io/project/issues?open=AYBvvMUr_8r2OU53wCth&id=ITISFoundation_osparc-simcore)
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4120
In place
=> 🐛 Fix minor bugs in project plugin and director

packages/service-library/src/servicelib/docker_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py, services/dask-sidecar/tests/unit/test_docker_utils.py
=> 🐛Computational backend: correct parsing of log lines

.vscode/settings.template.json, packages/pytest-simcore/src/pytest_simcore/docker_registry.py, packages/pytest-simcore/src/pytest_simcore/docker_swarm.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_public_api.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py, services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py, tests/public-api/conftest.py, tests/public-api/test_files_api.py, tests/public-api/test_it.py, tests/public-api/test_meta_api.py, tests/public-api/test_solvers_api.py, tests/public-api/test_solvers_jobs_api.py, tests/public-api/test_users_api.py
-  ✅ ♻️ cleanup ``test/public-api``
- 🐛 fixes failing docker log dumps issue that avoided producing container log artifacts.
- Temporary **disables failing test** until logs policy in the director-v2 is clarified 
- In the public-api tests, I run a sleeper that will exit with failure (there is a flag to force it). 
- Then I try to download the logsfile for the failing sleeper but it does not exits
- Tracing the issue i noticed that the directorv2 actually is deleting the logsfile (and the outputs) because the job failed https://github.com/ITISFoundation/osparc-simcore/blob/04af546b173d7a1c4201367f46d82657ab896d7a/services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py#LL176C40-L176C40
-  @sanderegg: Why would you delete the logs of a failing run? Am I …
=> ✅ Fixes flaky test api-server #3569

.flake8, packages/postgres-database/src/simcore_postgres_database/migration/versions/10b293fdcd56_alters_product_login_settings.py, packages/postgres-database/src/simcore_postgres_database/migration/versions/ff33dcf20b44_adding_column_product_name_to_groups_.py, packages/postgres-database/src/simcore_postgres_database/utils_products.py, packages/postgres-database/src/simcore_postgres_database/utils_tags.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_login.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/volume_remover.py, services/director-v2/tests/unit/conftest.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_api.py, services/web/server/src/simcore_service_webserver/groups_api.py, services/web/server/src/simcore_service_webserver/products/_db.py, services/web/server/src/simcore_service_webserver/projects/projects_db_utils.py, services/web/server/src/simcore_service_webserver/security/_authorization.py, services/web/server/src/simcore_service_webserver/users_api.py, services/web/server/tests/unit/with_dbs/01/studies_dispatcher/test_studies_dispatcher_handlers.py, services/web/server/tests/unit/with_dbs/01/test_groups.py, services/web/server/tests/unit/with_dbs/02/test_projects_handlers__delete.py, services/web/server/tests/unit/with_dbs/02/test_projects_handlers_crud.py, services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py, services/web/server/tests/unit/with_dbs/03/login/test_login_2fa_resend.py, services/web/server/tests/unit/with_dbs/03/login/test_login_registration.py, services/web/server/tests/unit/with_dbs/03/tags/test_tags.py, services/web/server/tests/unit/with_dbs/03/test_project_db.py, services/web/server/tests/unit/with_dbs/03/test_users.py, services/web/server/tests/unit/with_dbs/conftest.py
- among others now: sa.select() takes positional arguments, not a list anymore!
BEFORE:
[unit]webserver-01
[unit]webserver-02
[unit]webserver-03
AFTER:
[unit]webserver-01 - **2 minutes gain**
[unit]webserver-02 -  **9 minutes gain**
[unit]webserver-03 - **4 minutes gain**
=> ⚗️ Maintenance: make upgrade/downgrade a module fixture

api/specs/webserver/scripts/openapi_tags.py, packages/service-library/src/servicelib/request_keys.py, services/web/server/src/simcore_service_webserver/application.py, services/web/server/src/simcore_service_webserver/projects/projects_tags_handlers.py, services/web/server/src/simcore_service_webserver/tags/_handlers.py, services/web/server/src/simcore_service_webserver/tags/plugin.py, services/web/server/tests/unit/with_dbs/03/tags/conftest.py, services/web/server/tests/unit/with_dbs/03/tags/test_tags.py
- ♻️ refactors ``tags`` plugin in webserver
- plugin under ``tags `` folder
- protected internal modules
- uses envelpe reposnses
- general code cleanup (e.g. `_logger`,  TODO, ...)
- part of https://github.com/ITISFoundation/osparc-simcore/issues/4071
```cmd
make mypy | grep tags
```
=> ♻️  `webserver`: fixes mypy issues in `tags` plugin

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/events.py, packages/dask-task-models-library/tests/container_tasks/test_events.py, packages/models-library/src/models_library/rabbitmq_messages.py, packages/service-library/src/servicelib/logging_utils.py, packages/service-library/tests/test_logging_utils.py, packages/settings-library/src/settings_library/docker_registry.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/constants.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py, services/dask-sidecar/tests/unit/test_dask_utils.py, services/dask-sidecar/tests/unit/test_docker_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_logs.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_utils.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/rabbitmq.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/tests/unit/test_core_docker_utils.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_manager.py
- relates to https://github.com/ITISFoundation/osparc-issues/issues/747
=> ♻️Sidecars: Image pulling is now a debug log, try to guess log level of services

packages/service-library/src/servicelib/logging_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/core.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/docker_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/computational_sidecar/task_shared_volume.py, services/dask-sidecar/src/simcore_service_dask_sidecar/dask_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/file_utils.py, services/dask-sidecar/src/simcore_service_dask_sidecar/tasks.py, services/dask-sidecar/tests/unit/conftest.py, services/dask-sidecar/tests/unit/test_tasks.py, tests/public-api/test_solvers_jobs_api.py
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3569
- resolves https://github.com/ITISFoundation/osparc-simcore/issues/4234
=> 🐛service logs file not uploaded when service failing

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_service_specs.py
The dynamic-sidecar service will also contain the user service's `key` and `version`. For the case of multi container services only the key and version of the container started in the GUI will be displayed.
=> ✨Propagate key and version to dy-sidecar service labels

services/web/server/src/simcore_service_webserver/catalog/_handlers.py, services/web/server/tests/unit/with_dbs/01/test_catalog_api.py
- @elisabettai found out that it was not possible to connect 2 services together anymore. the /inputs:match endpoint of the webserver returns 422 (e.g. 2 sleepers could not be connected anymore)
This PR fixes this problem
=> 🐛 passing data from a service to another fails

tests/e2e/s4l/sim4life-lite.js, tests/e2e/tutorials/jupyterlabs.js
The e2e pipelines would fail to fail for jupyterlab and sim4life.  This fixes this bug by adding the missing `await`.
=> 🐛 Fix false passes on some e2e tests

packages/models-library/src/models_library/projects_nodes.py, packages/models-library/src/models_library/rabbitmq_messages.py, packages/service-library/src/servicelib/rabbitmq.py, packages/service-library/tests/long_running_tasks/test_long_running_tasks_task.py, services/autoscaling/tests/unit/test_utils_rabbitmq.py, services/dask-sidecar/docker/boot.sh, services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_consumers.py, services/web/server/src/simcore_service_webserver/notifications/project_logs.py, services/web/server/src/simcore_service_webserver/projects/projects_api.py, services/web/server/src/simcore_service_webserver/socketio/messages.py, services/web/server/tests/integration/01/test_exporter.py, services/web/server/tests/integration/02/notifications/test_rabbitmq_consumers.py
=> ✨Comp backend: disconnect progress update in webserver

services/web/server/src/simcore_service_webserver/projects/projects_api.py
fixes issue brought in by https://github.com/ITISFoundation/osparc-simcore/pull/4273
=> 🐛Fix node progress value when the service did not run yet

services/docker-compose.yml
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4279
=> ✨RabbitMQ: add persistency on rabbitmq service

docs/coding-conventions.md, services/web/server/src/simcore_service_webserver/activity/handlers.py, services/web/server/src/simcore_service_webserver/application_settings.py, services/web/server/src/simcore_service_webserver/application_settings_utils.py, services/web/server/src/simcore_service_webserver/login/handlers_confirmation.py, services/web/server/src/simcore_service_webserver/long_running_tasks.py, services/web/server/src/simcore_service_webserver/rabbitmq_settings.py, services/web/server/src/simcore_service_webserver/resource_manager/plugin.py, services/web/server/src/simcore_service_webserver/resource_manager/registry.py, services/web/server/src/simcore_service_webserver/resource_manager/websocket_manager.py, services/web/server/src/simcore_service_webserver/studies_dispatcher/_projects_permalinks.py, services/web/server/src/simcore_service_webserver/studies_dispatcher/_redirects_handlers.py, services/web/server/src/simcore_service_webserver/studies_dispatcher/_studies_access.py, services/web/server/src/simcore_service_webserver/utils_aiohttp.py, services/web/server/src/simcore_service_webserver/utils_rate_limiting.py
- ♻️ fixes mypy issues in ``webserver`` plugin ``resource_manager``
- ♻️ fixes all mypy issues in `webserver` except for
```cmd
make mypy | grep -v -E "exporter|projects|rest_"
```
- @matusdrobuliak66 can you please take care of `projects` after this PR is in?
- @GitHK  can you please take care of `exporter` after this PR is in?
- @pcrespov will take care of `rest` as soon as https://github.com/ITISFoundation/osparc-simcore/pull/4316 merges.
- part of https://github.com/ITISFoundation/osparc-simcore/issues/4071
```cmd
make mypy | grep -v -E "exporter|projects|rest_"
```
=> ♻️  `webserver`: fixes mypy issues in `resource-manager` plugin

packages/postgres-database/tests/docker-compose.yml, packages/service-library/tests/aiohttp/with_postgres/docker-compose.yml, scripts/maintenance/consistency/docker-compose.yml, services/director/tests/test_producer.py, services/docker-compose.yml, services/web/server/tests/unit/with_dbs/docker-compose-devel.yml, services/web/server/tests/unit/with_dbs/docker-compose.yml
Bumps PostgresSQL Minor Version from 14.5 to 14.8
There are no DB migrations necessary, postgres claims that the update can be done on-the-fly.
See: https://www.postgresql.org/docs/release/14.8/
=> ⬆️ Bump Postgres minor version

services/autoscaling/src/simcore_service_autoscaling/utils/utils_docker.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_utils_docker.py, services/autoscaling/tests/unit/test_utils_dynamic_scaling.py
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4344
```
make devenv
cd services/autoscaling
make test-dev
```
=> 🐛Autoscaling: fix listing of nodes with common prefix

.github/ISSUE_TEMPLATE/6_hotfix.yml, requirements/base.Makefile, services/api-server/requirements/_base.in, services/api-server/requirements/_base.txt, services/api-server/requirements/_test.txt, services/api-server/requirements/_tools.txt
- ⬆️ full upgrade of `api-server` requirements
- ⬆️ adds ``fastapi-pagination``
- 📝 Updated hotfix template forms `PULL_REQUEST_TEMPLATE.md`
- Prerequisite to https://github.com/ITISFoundation/osparc-simcore/pull/4407
- #packages before: 61
- #packages after : 66
|   1 | aio-pika                  | 9.1.2           | 9.1.3      |            | 1 | api-server⬆️ |
|   2 | aiocache                  | 0.11.1          | 0.12.1     | *minor*    | 1 | api-server⬆️ |
|   3 | aiofiles                  | 0.8.0           | 23.1.0     | **MAJOR**  | 1 | api-server⬆️ |
|   4 | aiohttp                   | 3.8.3           | 3.8.4      |            | 1 | api-server⬆️ |
|   5 | aiosignal                 | 1.2.0 …
=> ⬆️ Upgrade api-server requirements and includes pagination library

services/web/server/src/simcore_service_webserver/users/_db.py, services/web/server/tests/unit/with_dbs/03/test_users.py
Fixes the exception raised when there is no product defined for a user. Instead of 500 error, a default permission (in this case a False) is returned.
=> 🐛Personalized-resource-limits: return default value when no product is defined

.github/ISSUE_TEMPLATE/4_pre_release.yml, packages/models-library/tests/test_utils_service_io.py, services/web/server/src/simcore_service_webserver/login/_2fa.py, services/web/server/src/simcore_service_webserver/login/_constants.py, services/web/server/src/simcore_service_webserver/login/handlers_auth.py, services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py
Various improvements:
- ♻️ Adds user_id (in extras) and masked phone number for sms failures @odeimaiz @sanderegg 
- addresses the issue with failing sms in US 
- ♻️ Adds more validation checks for image-labels in registry, e.g. version in metadata vs image tag @mguidon 
- addresses issue with wrong version of s4l
- 🔨 Minor improvement in release form
- maintenance
- test_2fa_sms_failure_during_login
```cmd
pytest -vv tests/unit/**/test_*_login.py
```
None
=> ♻️ Maintenance: Enhanced logs on sms service errors and tests image labels

services/dask-sidecar/src/simcore_service_dask_sidecar/utils.py
nvidia/cuda:10.0-base has been removed from Dockerhub.
upgraded to latest version which is ```nvidia/cuda:12.2.0-base-ubuntu22.04```
=> 🐛upgrade dask-sidecar cuda version to properly detect GPU nodes

packages/service-library/src/servicelib/aiohttp/incidents.py, services/web/server/src/simcore_service_webserver/diagnostics/_healthcheck.py, services/web/server/src/simcore_service_webserver/projects/_handlers_crud.py
Various errors detected in master
- Temporary fix of `PUT projects` error (until proper validation of body is in place)
```log
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/projects/_handlers_crud.py", line 463, in replace_project
Project.parse_obj(new_project)  # validate
File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Project
permalink
extra fields not permitted (type=value_error.extra)
```
- Fixes healthcheck 
```log
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/diagnostics/plugin.py", line 51, in _on_healthcheck_async_adapter
assert_healthy_app(app)
File …
```
=> 🐛 Fixes replace operation in projects and uninitialized variable in health-check 

services/director-v2/src/simcore_service_director_v2/models/schemas/dynamic_services/scheduler.py, services/director-v2/tests/mocks/fake_scheduler_data.json, services/director-v2/tests/mocks/fake_scheduler_data_compose_spec.json, services/director-v2/tests/mocks/legacy_scheduler_data_format.json, services/director-v2/tests/unit/test_modules_dynamic_sidecar_observer.py
Field `can_save`, can no longer be `None`, removing all relative tests and validation code.
- closes https://github.com/ITISFoundation/osparc-simcore/issues/4204
=> ♻️ removing code that is no longer required

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/store/Support.js, services/static-webserver/client/source/class/osparc/ui/message/FlashMessage.js, services/static-webserver/client/source/class/osparc/ui/window/Dialog.js, services/static-webserver/client/source/class/osparc/utils/Utils.js
Update the Create account dialog and Warning message guests will see when account is required or when opening a published link:
"To use all [``productName``] (``productManual``) features, please send us an e-mail to create an account: ``supportEmail``"
Create account dialog:
Warning flash message:
=> 🎨 Guest users warning message

services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/director-v2/requirements/constraints.txt, services/director-v2/tests/integration/01/test_computation_api.py, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py, services/director-v2/tests/integration/02/test_mixed_dynamic_sidecar_and_legacy_project.py, services/director-v2/tests/integration/conftest.py, services/director-v2/tests/unit/with_dbs/test_api_route_dynamic_services.py
- #packages before: 74
- #packages after : 73
|   1 | aio-pika                  | 9.1.2           | 9.1.4      |            | 2 | director-v2⬆️🧪 |
|   2 | aiocache                  | 0.11.1          | 0.12.1     | *minor*    | 1 | director-v2⬆️ |
|   3 | aiodocker                 | 0.19.1          | 0.21.0     | *minor*    | 1 | director-v2⬆️ |
|   4 | aiofiles                  | 0.8.0           | 23.1.0     | **MAJOR**  | 1 | director-v2⬆️ |
|   5 | aiohttp                   | 3.8.3           | 3.8.4      |            | 2 | director-v2⬆️🧪 |
|   6 | aioredis                  | 2.0.1           | 🗑️ removed |  | 1 | director-v2⬆️ |
|   7 | aiosignal                 | 1.2.0           | 1.3.1      | …
=> ⬆️ Complete upgrade of director v2 dependencies

ci/github/helpers/install_rclone_docker_volume_plugin.bash, packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone.py, packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_r_clone.py, scripts/install_rclone.bash
The error we are getting in the CI, does not provide any context. Trying to upgrade rclone in the hopes that this will fix the issues. I see two releases with fixes for deadlocks due to progress being logged.
https://rclone.org/changelog/#v1-63-1-2023-07-17
=> ⬆️ rclone to 1.63.1

packages/service-library/src/servicelib/long_running_tasks/_task.py, packages/service-library/tests/long_running_tasks/test_long_running_tasks_task.py
Very pesky edge case
`FAILED tests/long_running_tasks/test_long_running_tasks_task.py::test_checked_once_task_is_auto_removed - Failed: DID NOT RAISE <class 'servicelib.long_running_tasks._errors.TaskNotFoundError'>`
Pytest raises a BaseException that is not caught and retried by tenacity.
Also the test logic was not 100% accurate
- closes https://github.com/ITISFoundation/osparc-simcore/issues/3671
=> 🐛 fixing flaky test test_checked_once_task_is_auto_removed

packages/dask-task-models-library/requirements/_base.txt, packages/dask-task-models-library/requirements/_test.txt, packages/dask-task-models-library/requirements/_tools.txt, services/dask-sidecar/requirements/_base.txt, services/dask-sidecar/requirements/_dask-distributed.txt, services/dask-sidecar/requirements/_test.txt, services/dask-sidecar/requirements/_tools.txt, services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/osparc-gateway-server/requirements/_base.txt, services/osparc-gateway-server/requirements/_test.txt, services/osparc-gateway-server/requirements/_tools.txt
- #packages before: 40
- #packages after : 50
|   1 | aio-pika                  | 9.1.4           | 9.1.2      | 🔥 downgrade | 2 | director-v2⬆️🧪 |
|   2 | aiobotocore               | 2.5.0           | 2.5.2      |            | 1 | dask-sidecar⬆️ |
|   3 | aiohttp                   | 3.8.4           | 3.8.5      |            | 6 | dask-sidecar⬆️🧪</br>director-v2⬆️🧪</br>osparc-gateway-server⬆️🧪 |
|   4 | attrs                     | 21.4.0          | 23.1.0     | **MAJOR**  | 2 | dask-sidecar⬆️🧪 |
|   5 | boto3                     | 1.26.76         | 1.26.161   |            | 1 | dask-sidecar🧪 |
|   6 | botocore                  | 1.29.76         | 1.29.161   |            | 2 | dask-sidecar⬆️🧪 |
|   7 …
=> ⬆️Upgrade dask-based services

services/agent/requirements/_base.txt, services/agent/requirements/_test.txt, services/api-server/requirements/_base.txt, services/autoscaling/requirements/_base.txt, services/catalog/requirements/_base.txt, services/catalog/requirements/_test.txt, services/datcore-adapter/requirements/_base.txt, services/invitations/requirements/_base.txt, services/osparc-gateway-server/tests/system/requirements/_test.txt, services/osparc-gateway-server/tests/system/requirements/_tools.txt, services/resource-usage-tracker/requirements/_base.txt, services/storage/requirements/_base.txt, services/storage/requirements/_test.txt, services/web/server/requirements/_base.txt, services/web/server/requirements/_test.txt
Master deploy presents sporadic errors in the `web-server` logged as
```cmd
Task exception was never retrieved
future: <Task finished name='Task-262869' coro=<RequestHandler.start() done, defined at /home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_protocol.py:462> exception=AttributeError("'NoneType' object has no attribute 'get_extra_info'")>
File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 505, in start
request = self._request_factory(message, payload, self, writer, handler)
File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 446, in _make_request
return _cls(
File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_request.py", line 811, in __init__
super().__init__(*args, …
```
=> ⬆️  repo-wide upgrade to aiohttp==3.8.5

ci/deploy/dockerhub-tag-version.bash, ci/helpers/show_system_versions.bash
Currently, we push two docker image tags to each docker image (identified by its digest) that we upload to dockerhub. One is "short" and one is "verbose" (including built date and git sha), like so:
- [master-github-2023-07-26--11-57.f6fa3ed338fa4875c76f02c37c22883bb660060d](https://hub.docker.com/layers/itisfoundation/webserver/master-github-2023-07-26--11-57.f6fa3ed338fa4875c76f02c37c22883bb660060d/images/sha256-6d297d6d54fe5d9eb9a930ab521556d7cc152dd2f8d4d46e088e7d97bc16e2c7?context=explore) (this is only for archiving purposes, it is not used anywhere)
- [master-github-latest](https://hub.docker.com/layers/itisfoundation/webserver/master-github-latest/images/sha256-6d297d6d54fe5d9eb9a930ab521556d7cc152dd2f8d4d46e088e7d97bc16e2c7?context=explore) (we use this actually)
This is …
=> ✨⚗️ Add additional docker image tag to simcore github actions (⚠️ DEVOPS)

services/static-webserver/client/source/class/osparc/component/study/ResourceSelector.js
Puppeteers have no wallet yet. This PR allows opening projects without selecting a wallet.
=> 🐛 e2e fix: enable the open project button

services/web/server/src/simcore_service_webserver/projects/db.py
ensure permission checks are done prior to adding/removing project nodes
NOTE: @matusdrobuliak66  this should go in the hotfix to staging as well
=> 🐛Check permissions before modifying project nodes

packages/simcore-sdk/src/simcore_sdk/node_ports_common/r_clone.py, packages/simcore-sdk/tests/integration/test_node_ports_common_r_clone.py, packages/simcore-sdk/tests/unit/test_node_ports_v2_r_clone.py
Unfortunately `rclone` was configured to copy the content pointed by the symlink. This caused `rclone` to fail if the symlink was broken (the pointed file did not exists).
- ✨ adds regression test
- 🐛 rclone copies symlinks as they are without following them
- https://github.com/ITISFoundation/osparc-issues/issues/675
=> 🐛 `rclone` preserves symlinks even if broken

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/api/containers_extension.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_context.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_event_handler.py, services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/outputs/_watcher.py, services/dynamic-sidecar/tests/unit/test_api_containers.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_manager.py, services/dynamic-sidecar/tests/unit/test_modules_outputs_watcher.py
The `otuputs-watcher` inside the dynamic-sidecar was generating events even when disabled.
- ♻️ by default the `dynamic-sidecar` will not trigger on any input folder changes
- ♻️ the disabling mechanism, it is now done at a very low level, will no longer push all FS events to the upper layer (better performance)
- 🐛 `test_outputs_watcher_disabling` was horribly broken, test was adusted
- should avoid https://github.com/ITISFoundation/osparc-simcore/issues/4595
=> 🐛 fix `dynamic-sidecar` outputs watcher

services/web/server/src/simcore_service_webserver/projects/db.py
This PR fixes the issue with synchronization between the *projects* table *workbench* column and the *projects_nodes* table.
The problem arises due to the following issues:
On node creation the frontend does:
1. ```POST /projects/{project_id}/nodes``` and does not wait for an answer
2. ```PUT /projects/{project_id}``` arrives soon after with the new node in the workbench --> works since 1. call is fast
On node deletion the frontend does:
1. ```DELETE /projects/{project_id}/nodes/{node_id}``` and does not wait for an answer although that call is slow when a dynamic service needs to be removed (typically from .5s to several seconds).
2. ```PUT /projects/{project_id}``` arrives soon after with the node already removed from the workbench. the call is fast an changes *projects/workbench*.
3. …
=> 🐛 Hot-fix: Ensure synchronization between projects/workbench and projects_nodes

services/api-server/src/simcore_service_api_server/api/routes/files.py, services/api-server/src/simcore_service_api_server/models/schemas/files.py, services/api-server/src/simcore_service_api_server/services/storage.py, services/api-server/tests/unit/test_api_files.py
Make sure `file_id` is a path parameter according to openapi. I found an openapi validator which complained because FastApi does not add a path parameter to the openapi specification unless the parameter is specified as an input to the given function.
=> 🐛 Make sure openapi is happy about abort endpoint

services/dask-sidecar/requirements/_base.txt, services/dask-sidecar/requirements/_dask-distributed.in, services/dask-sidecar/requirements/_dask-distributed.txt, services/dask-sidecar/requirements/_test.txt, services/dask-sidecar/requirements/_tools.txt, services/director-v2/requirements/_base.txt, services/director-v2/requirements/_test.txt, services/director-v2/requirements/_tools.txt, services/osparc-gateway-server/requirements/_test.txt, services/osparc-gateway-server/requirements/_tools.txt, services/osparc-gateway-server/tests/system/requirements/_test.txt, services/osparc-gateway-server/tests/system/requirements/_tools.txt
- #packages before: 26
- #packages after : 22
|   1 | aio-pika                  | 9.1.2           | 9.2.2      | *minor*    | 1 | dask-sidecar⬆️ |
|   2 | aiobotocore               | 2.5.2           | 2.5.4      |            | 1 | dask-sidecar⬆️ |
|   3 | aiofiles                  | 23.1.0          | 23.2.1     | *minor*    | 1 | dask-sidecar⬆️ |
|   4 | aiormq                    | 6.7.6           | 6.7.7      |            | 1 | dask-sidecar⬆️ |
|   5 | anyio                     | 3.7.1           | 🗑️ removed |  | 1 | dask-sidecar⬆️ |
|   6 | async-timeout             | 4.0.2           | 4.0.3      |            | 2 | dask-sidecar⬆️🧪 |
|   7 | boto3                     | 1.26.161        | 1.28.17    | …
=> ⬆️Comp backend: ensure numpy installed in client

packages/pytest-simcore/src/pytest_simcore/docker_compose.py, packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker.py, packages/pytest-simcore/src/pytest_simcore/monkeypatch_extra.py, packages/pytest-simcore/src/pytest_simcore/simcore_services.py, packages/service-library/tests/conftest.py, services/autoscaling/tests/unit/conftest.py, services/autoscaling/tests/unit/test_dynamic_scaling_core.py, services/catalog/tests/unit/conftest.py, services/clusters-keeper/tests/unit/conftest.py, services/migration/tests/conftest.py, services/resource-usage-tracker/tests/unit/conftest.py, services/storage/tests/conftest.py, services/web/server/tests/conftest.py, services/web/server/tests/integration/01/test_garbage_collection.py, services/web/server/tests/unit/with_dbs/conftest.py, test.bash, tests/public-api/conftest.py
In an attempt to reduce the warnings and making tests outcome clearer, this shall reduce the warnings generated by the monkeypatch_extra module. The ```monkypatch_extra.py``` module was removed everywhere possible in a train ride. the last ones are still in and concern director-v2, dynamic-sidecar and simcore-sdk. Also some system tests are affected.
To all backend developers: Please do not use any fixture of monkeypatch_extra.py module
The bellow image show an example of tests passing without warnings (green outcome) and with warnings (yellow outcome). If we want to tackle all the SQLAlchemy2.0 warnings for instance. we need to go for warnings free tests.
=> ♻️Maintenance: attempt at fixing monkeypatch warnings

services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_api/_core.py, services/director-v2/tests/unit/with_dbs/test_modules_dynamic_sidecar_docker_api.py
since [release 1.56.0](https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.56.0), the code from #4453 for backward compatibility can be safely removed, thus cleaning the logs.
=> ♻️Maintenance: remove backward compatibility code

packages/service-library/src/servicelib/long_running_tasks/_models.py, packages/service-library/src/servicelib/long_running_tasks/_task.py, services/api-server/openapi.json, services/api-server/src/simcore_service_api_server/api/errors/httpx_client_error.py, services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py, services/api-server/src/simcore_service_api_server/api/routes/studies.py, services/api-server/src/simcore_service_api_server/api/routes/studies_jobs.py, services/api-server/src/simcore_service_api_server/models/types.py, services/api-server/src/simcore_service_api_server/services/webserver.py, services/api-server/tests/unit/api_solvers/conftest.py, services/api-server/tests/unit/api_solvers/test_api_routers_solvers_jobs.py, services/api-server/tests/unit/api_solvers/test_api_routers_solvers_jobs_delete.py, services/api-server/tests/unit/api_solvers/test_api_routers_solvers_jobs_metadata.py, services/api-server/tests/unit/api_studies/conftest.py, services/api-server/tests/unit/api_studies/test_api_routes_studies.py, services/api-server/tests/unit/api_studies/test_api_routes_studies_jobs.py, services/api-server/tests/unit/api_studies/test_api_studies_mocks.py, services/api-server/tests/unit/conftest.py, services/web/server/tests/unit/with_dbs/02/test_projects_crud_handlers__clone.py, services/web/server/tests/unit/with_dbs/03/meta_modeling/test_meta_modeling_iterations.py
- ✨ NEW `clone_study` as `POST   /v0/studies/{study_id}:clone`
- 🐛 `create_*` and `clone_*` operations respond with `201 Created`
- 🔨 New generic fixture for long-running-tasks 
@bisgaard-itis we can now use this feature to clone templates for the tutorial?
- follows up from PR 
- resolves #4651
Driving tests are  `test_clone_study*` in 
```cmd
pytest -vv tests/unit/api_studies/test_api_routes_studies.py
```
None
=> ✨ new `clone_study` in api-server

.github/workflows/ci-testing-deploy.yml, packages/service-library/setup.cfg, packages/service-library/src/servicelib/background_task.py, packages/service-library/src/servicelib/logging_utils.py, packages/service-library/src/servicelib/rabbitmq.py, packages/service-library/src/servicelib/rabbitmq_rpc_router.py, packages/service-library/tests/rabbitmq/conftest.py, packages/service-library/tests/rabbitmq/test_rabbitmq.py, packages/service-library/tests/rabbitmq/test_rabbitmq_connection.py, packages/service-library/tests/rabbitmq/test_rabbitmq_rpc_router.py
NOTE: this provides a convenient way to expose RPC functions. NOT yet a convenient way to provide the client side. this might come later. baby steps as someone much smarter than me said.
This PR allows to reduce the complexity of https://github.com/ITISFoundation/osparc-simcore/pull/4602
- pre-requisite of https://github.com/ITISFoundation/osparc-simcore/pull/4602
=> ✨RabbitMQ: Add RPC decorator for server side

packages/service-library/src/servicelib/sequences_utils.py, packages/service-library/tests/test_sequences_utils.py, packages/service-library/tests/test_utils.py, services/director-v2/tests/integration/02/test_dynamic_sidecar_nodeports_integration.py, services/storage/src/simcore_service_storage/simcore_s3_dsm.py
- ✨ added `partition_gen` and `pairwise` sequence dividers
- ⚗️ I have a hunch something is wrong with `logged_gather` when providing the max_concurrency flag, using a different approach to achieve the same result.
Why am I trying this? We have a locking mechanism inside `logged_gather` (the `AsyncSemaphore`) and I think it could be the culprit why the copy of very large studies hangs. I have no explanation to why this happens.
This PR archives the same result without using blocking.
NOTE: if this is the issue I will refactor `logged_gather`'s internals to use `partition_gen` instead of an `AsyncSemaphore`
=> ⚗️ `storage` remove task concurrency locking while duplicating a project

services/storage/requirements/_base.txt, services/storage/requirements/_test.txt, services/storage/requirements/_tools.txt, services/storage/src/simcore_service_storage/application.py, services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter.py, services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter_exceptions.py, services/storage/src/simcore_service_storage/datcore_adapter/datcore_adapter_settings.py, services/storage/src/simcore_service_storage/db_access_layer.py, services/storage/src/simcore_service_storage/db_projects.py, services/storage/src/simcore_service_storage/db_tokens.py, services/storage/src/simcore_service_storage/dsm_cleaner.py, services/storage/src/simcore_service_storage/dsm_factory.py, services/storage/src/simcore_service_storage/handlers_health.py, services/storage/src/simcore_service_storage/handlers_locations.py, services/storage/src/simcore_service_storage/handlers_simcore_s3.py, services/storage/src/simcore_service_storage/s3_client.py, services/storage/src/simcore_service_storage/simcore_s3_dsm.py, services/storage/src/simcore_service_storage/utils_handlers.py, services/storage/tests/unit/conftest.py, services/storage/tests/unit/test__openapi_specs.py, services/storage/tests/unit/test_aiobotocore.py, services/storage/tests/unit/test_cli.py, services/storage/tests/unit/test_utils_handlers.py
- #packages before: 68
- #packages after : 84
|   1 | aio-pika                  | 9.1.2           | 9.2.2      | *minor*    | 1 | storage⬆️ |
|   2 | aioboto3                  | 9.6.0           | 11.3.0     | **MAJOR**  | 1 | storage⬆️ |
|   3 | aiobotocore               | 2.3.0           | 2.6.0      | *minor*    | 1 | storage⬆️ |
|   4 | aiofiles                  | 0.8.0           | 23.2.1     | **MAJOR**  | 1 | storage⬆️ |
|   5 | aioitertools              | 0.10.0          | 0.11.0     | *minor*    | 1 | storage⬆️ |
|   6 | aiormq                    | 6.7.6           | 6.7.7      |            | 1 | storage⬆️ |
|   7 | aiosignal                 | 1.2.0           | 1.3.1      | *minor*    | 2 | …
=> ⬆️Storage: dependencies upgrade

.coveragerc, .ruff.toml, packages/service-library/src/servicelib/rabbitmq/_errors.py, packages/service-library/src/servicelib/rabbitmq/_rpc_router.py, packages/service-library/tests/rabbitmq/test_rabbitmq_rpc_router.py, scripts/common.Makefile, services/clusters-keeper/Makefile, services/clusters-keeper/tests/unit/test_rpc_clusters.py
The concept is to have a common/shared interface module that defines the types of whatever is returned through RPC
pre-requisite of https://github.com/ITISFoundation/osparc-simcore/pull/4703
=> ♻️Rabbitmq rpc: response shall not be jsonized

packages/models-library/src/models_library/rpc_schemas_clusters_keeper/clusters.py, services/clusters-keeper/src/simcore_service_clusters_keeper/modules/clusters.py, services/clusters-keeper/src/simcore_service_clusters_keeper/rpc/clusters.py, services/clusters-keeper/src/simcore_service_clusters_keeper/utils/clusters.py, services/clusters-keeper/src/simcore_service_clusters_keeper/utils/ec2.py, services/clusters-keeper/tests/unit/test_rpc_clusters.py, services/director-v2/src/simcore_service_director_v2/modules/clusters_keeper.py
allows an EC2 instance created by clusters-keeper to have a walletID set to None
=> ✨Comp backend: Clusters-keeper can create a cluster with no wallet ID defined

packages/postgres-database/src/simcore_postgres_database/migration/versions/c4245e9e0f72_payment_transactions_states.py, packages/service-library/src/servicelib/rabbitmq/_rpc_router.py, services/director-v2/src/simcore_service_director_v2/api/routes/computations.py, services/director-v2/src/simcore_service_director_v2/core/errors.py, services/director-v2/src/simcore_service_director_v2/models/dask_subsystem.py, services/director-v2/src/simcore_service_director_v2/modules/clusters_keeper.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py, services/director-v2/src/simcore_service_director_v2/utils/comp_scheduler.py, services/director-v2/tests/integration/01/test_computation_api.py, services/director-v2/tests/mocks/fake_workbench_computational_node_states.json, services/director-v2/tests/unit/test_modules_dask_client.py, services/director-v2/tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py, services/payments/tests/unit/test_rpc_payments.py
This PR shall fix the issues where the *Running* state of a task was shown although the task is not computing, but is taken by a dask-sidecar (Dask scheduler states make no difference between a task being processed or taken by a worker and queued on the worker memory).
Therefore this shall fix:
- when multiple computational services where shown as *Running*
- and also the *Running* state is now shown as soon as the computational service signaled it started progressing, therefore linked directly to the worker activity and not only from the dask-scheduler processing fct
- *pending* <-> *waiting_for_cluster* state now stable
This was achieved by:
Bonus:
- ensure that RPC calls do not return internal exceptions
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4517
- fixes …
=> ♻️✨ Comp backend task state reporting fixed

services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks.py
=> 🐛Ensure the progress is set to None

services/api-server/src/simcore_service_api_server/api/dependencies/authentication.py, services/api-server/src/simcore_service_api_server/api/routes/solvers_jobs.py, services/api-server/src/simcore_service_api_server/db/repositories/api_keys.py, services/api-server/src/simcore_service_api_server/db/repositories/groups_extra_properties.py, services/api-server/src/simcore_service_api_server/db/repositories/users.py, services/api-server/src/simcore_service_api_server/services/director_v2.py, services/api-server/tests/unit/api_solvers/test_api_routers_solvers_jobs.py, services/api-server/tests/unit/conftest.py
This PR permits PublicAPI users that have the right permissions to access on-demand clusters to use them.
Bonus: some cleanup so some people get more %!!
=> ✨Api-server: allow usage of on-demand clusters if defined in groups_extra_properties

.github/CODEOWNERS, services/web/server/src/simcore_service_webserver/login/_confirmation.py, services/web/server/src/simcore_service_webserver/login/handlers_confirmation.py, services/web/server/src/simcore_service_webserver/login/handlers_registration.py, services/web/server/src/simcore_service_webserver/login/utils.py, services/web/server/src/simcore_service_webserver/notifications/_rabbitmq_consumers.py, services/web/server/src/simcore_service_webserver/wallets/_api.py, services/web/server/src/simcore_service_webserver/wallets/_db.py, services/web/server/src/simcore_service_webserver/wallets/_events.py, services/web/server/src/simcore_service_webserver/wallets/_groups_api.py, services/web/server/src/simcore_service_webserver/wallets/_handlers.py, services/web/server/src/simcore_service_webserver/wallets/plugin.py, services/web/server/tests/unit/with_dbs/03/invitations/test_invitations.py, services/web/server/tests/unit/with_dbs/03/login/conftest.py, services/web/server/tests/unit/with_dbs/03/login/test_login_2fa.py, services/web/server/tests/unit/with_dbs/03/login/test_login_registration.py, services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py
A user's default wallet is auto created **when the account registration is completed** (i.e. user clicks confirmation link)
- ✨ `login` triggers `SIGNAL_ON_USER_CONFIRMATION` when user clicks confirmation link (i.e. final step in registration)
- ✨ `wallets` plugin observers `SIGNAL_ON_USER_CONFIRMATION` and executes `_auto_add_default_wallet` that **ensures** that user **owns** one wallet.
- ♻️ `POST /v0/wallets` to create wallets restricted to `WEBSERVER_DEV_FEATURES_ENABLED=1`
- Implements `a user's default wallet (on account creation)` in https://github.com/ITISFoundation/osparc-issues/issues/1027
Driving test are
- all `services/web/server/tests/unit/with_dbs/03/login/test_login_registration.py`
- `services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py:test_auto_wallet_on_u …
=> ✨ Auto-create wallet for new user in product

services/static-webserver/client/source/class/osparc/dashboard/ResourceBrowserBase.js, services/static-webserver/client/source/class/osparc/data/Resources.js, services/static-webserver/client/source/class/osparc/study/ResourceSelector.js, services/static-webserver/client/source/class/osparc/study/StudyOptions.js, services/static-webserver/client/source/class/osparc/study/TierButton.js, services/static-webserver/client/source/class/osparc/study/TierButtons.js
This PR implements the frontend part for https://github.com/ITISFoundation/osparc-simcore/pull/4812
The frontend elements stay more or the same (some extra information about the plan itself is required), but the names and the costs per unit are provided by the backend.
related to https://github.com/ITISFoundation/osparc-issues/issues/922
=> ✨ Expose pricing plans

services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/attribute_monitor/_logging_event_handler.py, services/dynamic-sidecar/tests/unit/test_modules_attribute_monitor.py
Fixes the following issue where the attribute monitor will fail if the file would be removed immediately after being created.
```python
File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/logging_utils.py", line 225, in log_catch
yield
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/attribute_monitor/_watchdog_extensions.py", line 70, in on_any_event
self.event_handler(event)
File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/attribute_monitor/_logging_event_handler.py", line 33, in event_handler
file_stat = file_path.stat()
File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
return self._accessor.stat(self, follow_symlinks=follow_symlinks) …
```
=> 🐛 Fix issue with paths not found in attribute monitor

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/desktop/MainPage.js, services/static-webserver/client/source/class/osparc/desktop/SlideshowToolbar.js, services/static-webserver/client/source/class/osparc/desktop/SlideshowView.js, services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js, services/static-webserver/client/source/class/osparc/desktop/WorkbenchView.js, services/static-webserver/client/source/class/osparc/navigation/NavigationBar.js, services/static-webserver/client/source/class/osparc/navigation/StudyTitleWOptions.js, services/static-webserver/client/source/class/osparc/ui/form/EditLabel.js
This feature was only enabled in ``s4l-lite``. Now ~~every time an iframe gets maximized,~~ the study title will be visible on the navigation bar. Request from @cosfor1 so that it also applies to use cases in ``s4l``.
=> ✨ Show editable Study title on Navigation Bar

services/web/server/src/simcore_service_webserver/catalog/_api_units.py, services/web/server/tests/unit/isolated/test_catalog_api_units.py
json-schema does not require `type` field with `enum` since the values of the enumeration can have different types. This PR prevents that this case breaks matching.
Nonetheless, since we mostly use "pure-string" enums it is recommended to add `"type": "string"`. For instance, in this case modify the json-schema such that makes the enum strictly of `strings` by adding a  `type` field:
```json
{
"title": "Solution method",
"description": "An enumeration",
"enum": [ "Iterative (GMRES)",  "FMM-LU"],
"type": "string"  # <-- NOTE THIS
}
```
This is legal in json-schema and you are basically saying that the values of the enum are strings. For more insight on the enum schemas you can look at https://github.com/pcrespov/sandbox-python/blob/98fb613a41e9c6a5a54f52be321cb652bfe047da/json-schemas/test_ …
=> 🐛 Fixes `enum`-ports breaks compatibility matching

services/agent/Dockerfile, services/api-server/Dockerfile, services/autoscaling/Dockerfile, services/catalog/Dockerfile, services/clusters-keeper/Dockerfile, services/dask-sidecar/Dockerfile, services/datcore-adapter/Dockerfile, services/director-v2/Dockerfile, services/invitations/Dockerfile, services/osparc-gateway-server/Dockerfile, services/payments/Dockerfile, services/resource-usage-tracker/Dockerfile, services/storage/Dockerfile, services/web/Dockerfile
Running ```make build-devel``` from scratch shows issues that are connected with the buildx caches.
In order to fix this the cache mode was set to ```sharing=private``` see [https://docs.docker.com/engine/reference/builder/#run---mounttypecache](https://docs.docker.com/engine/reference/builder/#run---mounttypecache) for details.
This seems to fix the issue.
```
docker system prune -a
docker buildx prune
make build-devel
```
=> ♻️🐛Fix build cache issue in devel mode

services/web/server/src/simcore_service_webserver/payments/_autorecharge_api.py, services/web/server/src/simcore_service_webserver/payments/_methods_api.py, services/web/server/src/simcore_service_webserver/payments/_onetime_api.py, services/web/server/tests/unit/with_dbs/03/wallets/payments/test_payments.py
Payments can only be done to **owned wallets** . We can share this wallet with other users in read-mode. This allows them to consume credits from the wallet but cannot perform any kind of payment to it.  For that reason **we cannot allow users with read-only access to see any payment information associated to this wallet** (e.g. auto-recharge settings or payment methods). 
This PR reviews and fixes permissions required for sub resources as `/wallets/{wallet_id}/*` related to payments
- Reviewed checks on read operations for wallets
- Renamed check as `raise_for_...()`  (named analogous to `response.raise_for_status()`) that will be transformed into a [Forbidden 403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) 
In the **front-end**, when a **shared read-only wallet** is …
=> 🎨 Read-only permissions to wallets do not give access to wallet-payment info

services/autoscaling/Dockerfile, services/autoscaling/docker/entrypoint.sh, services/clusters-keeper/Dockerfile, services/clusters-keeper/docker/entrypoint.sh
ensure update-ca-certificates is called upon startup
since the ```ca-certificate``` package was removed after installing the docker engine the rabbitMQ client was unable to resolve SSL certificates, thus not able to connect to a secure rabbitMQ server.
This PR solves this.
- relates to https://github.com/ITISFoundation/osparc-issues/issues/1108
=> 🐛 Autoscaling/Clusters-keeper unable to resolve SSL certificates

services/dask-sidecar/docker/boot.sh, tests/swarm-deploy/conftest.py
This PR changes the way the dask-sidecar starts by retrieving on which EC2 instance it runs if available.
see [https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) for details.
=> ✨ Dask sidecar: find out on start on which EC2 instance it runs if available

services/director-v2/src/simcore_service_director_v2/modules/clusters_keeper.py, services/director-v2/src/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py
enable passing of wallet ID to the clusters-keeper which is used to name the primary machine in AWS
=> ✨Director-v2 passes the wallet ID to clusters-keeper

packages/dask-task-models-library/src/dask_task_models_library/container_tasks/protocol.py, packages/simcore-sdk/src/simcore_sdk/node_ports_common/filemanager.py, services/dask-sidecar/src/simcore_service_dask_sidecar/tasks.py, services/director-v2/src/simcore_service_director_v2/modules/dask_client.py, services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_compose_specs.py, services/director-v2/src/simcore_service_director_v2/utils/rabbitmq.py, services/storage/src/simcore_service_storage/simcore_s3_dsm_utils.py, services/web/server/src/simcore_service_webserver/director_v2/_core_dynamic_services.py, services/web/server/src/simcore_service_webserver/session/access_policies.py
Opsie, this is an embarrassing one.
Fixed the preview for nodes with state stored as directories.
And also deeply nested directories are supported
Bonus: pylint fixes after tooling update
- https://github.com/ITISFoundation/osparc-issues/issues/1108
- fixes: https://github.com/ITISFoundation/osparc-issues/issues/1150
=> 🐛 if node has it's state stored a directory it will now display the content in the preview

services/static-webserver/client/source/class/osparc/Application.js, services/static-webserver/client/source/class/osparc/desktop/credits/CreditsIndicator.js, services/static-webserver/client/source/class/osparc/navigation/CreditsMenuButton.js, services/static-webserver/client/source/class/osparc/navigation/UserMenuButton.js, services/static-webserver/client/source/class/osparc/store/Store.js
The tear down of the App's Store (cache) after logging out was not optimal. This was visible on the Credits Indicator after logging out and logging back in (but it was also the case for some other resources).
=> 🐛 Bugfix: Reset Store after logging out

services/director-v2/src/simcore_service_director_v2/api/routes/dynamic_scheduler.py, services/director-v2/src/simcore_service_director_v2/cli/__init__.py, services/director-v2/src/simcore_service_director_v2/cli/_client.py, services/director-v2/src/simcore_service_director_v2/cli/_core.py, services/director-v2/tests/unit/with_dbs/test_cli.py
This allows to peak into the memory of director-v2 to see what it's actually tracking. There is an issue on production which is not allowing us to debug what is happening. This will help.
=> ✨Adding new cli option to debug internal status of `director-v2`

services/director-v2/src/simcore_service_director_v2/modules/db/repositories/comp_tasks/_utils.py
disable override of resources with hardware info, as this fails with dynamic services
Following issues were discovered:
- in non-AWS billable (master): there is no clusters-keeper available and this prevents starting any service
- in AWS billable: there is currently an issue when starting a dynamic service
=> 🐛TEMP: disable override resources

tests/e2e/utils/auto.js, tests/e2e/utils/utils.js
- https://github.com/ITISFoundation/osparc-issues/issues/1108
=> ♻️ E2E: adds milliseconds to screenshot prefix + wait before checking the logs
